--[[

@author Kurki
@copyright (c)2026 Profession Master. All Rights Reserved.

--]]

-- Quest name lookup for vanilla (english fallback; the client resolves localized titles at runtime)
local questNames = {
    [22] = "Goretusk Liver Pie",
    [38] = "Westfall Stew",
    [90] = "Seasoned Wolf Kabobs",
    [92] = "Redridge Goulash",
    [93] = "Dusky Crab Cakes",
    [127] = "Selling Fish",
    [296] = "Ormer's Revenge",
    [384] = "Beer Basted Boar Ribs",
    [385] = "Crocolisk Hunting",
    [418] = "Thelsamar Blood Sausages",
    [429] = "Wild Hearts",
    [471] = "Apprentice's Duties",
    [498] = "The Rescue",
    [501] = "Elixir of Pain",
    [555] = "Soothing Turtle Bisque",
    [564] = "Costly Menace",
    [703] = "Barbecued Buzzard Wings",
    [715] = "Liquid Stone",
    [769] = "Kodo Hide Bag",
    [862] = "Dig Rat Stew",
    [1487] = "Deviate Eradication",
    [1559] = "Flash Bomb Recipe",
    [1578] = "Supplying the Front",
    [1582] = "Moonglow Vest",
    [1618] = "Gearing Redridge",
    [2178] = "Easy Strider Living",
    [2203] = "Badlands Reagent Run II",
    [2359] = "Klaven's Tower",
    [2478] = "Mission: Possible But Not Probable",
    [2501] = "Badlands Reagent Run II",
    [2751] = "Barbaric Battlements",
    [2752] = "On Iron Pauldrons",
    [2753] = "Trampled Under Foot",
    [2754] = "Horns of Frenzy",
    [2755] = "Joys of Omosh",
    [2756] = "The Old Ways",
    [2758] = "The Origins of Smithing",
    [2761] = "Smelt On, Smelt Off",
    [2762] = "The Great Silver Deceiver",
    [2763] = "The Art of the Imbue",
    [2771] = "A Good Head On Your Shoulders",
    [2772] = "The World At Your Feet",
    [2773] = "The Mithril Kid",
    [2848] = "Wild Leather Shoulders",
    [2849] = "Wild Leather Vest",
    [2850] = "Wild Leather Helmet",
    [2851] = "Wild Leather Boots",
    [2852] = "Wild Leather Leggings",
    [2853] = "Master of the Wild Leather",
    [2855] = "Wild Leather Shoulders",
    [2856] = "Wild Leather Vest",
    [2857] = "Wild Leather Helmet",
    [2858] = "Wild Leather Boots",
    [2859] = "Wild Leather Leggings",
    [2860] = "Master of the Wild Leather",
    [3402] = "The Undermarket",
    [4083] = "The Spectral Chalice",
    [4161] = "Recipe of the Kaldorei",
    [5124] = "Fiery Plate Gauntlets",
    [5127] = "The Demon Forge",
    [5305] = "Sweet Serenity",
    [5306] = "Snakestone of the Shadow Huntress",
    [5307] = "Corruption",
    [6032] = "Sacred Cloth",
    [7321] = "Soothing Turtle Bisque",
    [7493] = "The Journey Has Just Begun",
    [7497] = "The Journey Has Just Begun",
    [7604] = "A Binding Contract",
    [7649] = "Enchanted Thorium Platemail: Volume I",
    [7650] = "Enchanted Thorium Platemail: Volume II",
    [7651] = "Enchanted Thorium Platemail: Volume III",
    [7653] = "Imperial Plate Belt",
    [7654] = "Imperial Plate Boots",
    [7655] = "Imperial Plate Bracer",
    [7656] = "Imperial Plate Chest",
    [7657] = "Imperial Plate Helm",
    [7658] = "Imperial Plate Leggings",
    [7659] = "Imperial Plate Shoulders",
    [8313] = "Sharing the Knowledge",
    [8586] = "Dirge's Kickin' Chimaerok Chops",
    [8798] = "A Yeti of Your Own",
    [8869] = "Sweet Serenity",
    [8877] = "Firework Launcher",
    [8878] = "Festive Recipes",
    [8882] = "Cluster Launcher",
};

_G.professionMaster:CreateModel("quest-names-vanilla", questNames);
