-- LibProfessionDB names — WoW Vanilla, esMX, Firstaid
-- Auto-generated by ProfessionDB tools/build_authoritative_data.py. Do not hand-edit.
-- 16 recipes

if GetLocale() ~= "esMX" then return end
local lib = LibStub and LibStub("LibProfessionDB-1.0", true)
if not lib or not lib:IsGameVersion("Vanilla") then return end

lib:LoadNames(129, {
		[3275] = {
			["name"] = "Venda de lino",
		},
		[3276] = {
			["name"] = "Venda de lino gruesa",
		},
		[3277] = {
			["name"] = "Venda de lana",
		},
		[3278] = {
			["name"] = "Venda de lana gruesa",
		},
		[7924] = {
			["name"] = "Primeros auxilios",
		},
		[7928] = {
			["name"] = "Venda de seda",
		},
		[7929] = {
			["name"] = "Venda de seda gruesa",
		},
		[7934] = {
			["name"] = "Contraveneno",
		},
		[7935] = {
			["name"] = "Contraveneno fuerte",
		},
		[10840] = {
			["name"] = "Venda de tejido mágico",
		},
		[10841] = {
			["name"] = "Venda de tejido mágico gruesa",
		},
		[10846] = {
			["name"] = "Primeros auxilios",
		},
		[18629] = {
			["name"] = "Venda de paño rúnico",
		},
		[18630] = {
			["name"] = "Venda de paño rúnico gruesa",
		},
		[23787] = {
			["name"] = "Contraveneno potente",
		},
		[470349] = {
			["name"] = "Venda de paño rúnico denso",
		},
	})
