-- LibProfessionDB names — WoW Mists, koKR, Fishing
-- Auto-generated by ProfessionDB tools/build_authoritative_data.py. Do not hand-edit.
-- 1 recipes

if GetLocale() ~= "koKR" then return end
local lib = LibStub and LibStub("LibProfessionDB-1.0", true)
if not lib or not lib:IsGameVersion("Mists") then return end

lib:LoadNames(356, {
		[43308] = {
			["name"] = "물고기 찾기",
		},
	})
