-- LibProfessionDB names — WoW TBC, frFR, Fishing
-- Auto-generated by ProfessionDB tools/build_authoritative_data.py. Do not hand-edit.
-- 4 recipes

if GetLocale() ~= "frFR" then return end
local lib = LibStub and LibStub("LibProfessionDB-1.0", true)
if not lib or not lib:IsGameVersion("TBC") then return end

lib:LoadNames(356, {
		[7732] = {
			["name"] = "Pêche",
		},
		[18248] = {
			["name"] = "Pêche",
		},
		[33095] = {
			["name"] = "Pêche",
		},
		[43308] = {
			["name"] = "Découverte de poisson",
		},
	})
