-- LibProfessionDB recipe-scroll prefixes - WoW Vanilla, zhCN
-- Auto-generated by tools/build-recipe-items.py from wago.tools DB2. Do not hand-edit.
-- [skillLineID] = localized scroll prefix, DERIVED from real scroll names in this
-- locale (item name minus the craft spell's name), never transcribed by hand.
-- 9 professions

if GetLocale() ~= "zhCN" then return end
local lib = LibStub and LibStub("LibProfessionDB-1.0", true)
if not lib then return end

lib:LoadRecipeScrollPrefixes({
[129]="手册：",
[164]="设计图：",
[165]="图样：",
[171]="配方：",
[185]="食谱：",
[186]="手册：",
[197]="图样：",
[202]="结构图：",
[333]="公式：",
})

-- [skillLineID] = how many REAL scrolls voted for the prefix above.
-- Mining's is 1: one smelting scroll decides the header for 22 synthetic
-- descriptors. Shipped so a consumer can see the sample size and draw its
-- own header if it would rather -- the builder does not decide that here.
lib:LoadRecipeScrollPrefixSamples({
[129]=5,
[164]=210,
[165]=215,
[171]=76,
[185]=73,
[186]=1,
[197]=185,
[202]=123,
[333]=111,
})

-- [skillLineID] = Use: sentence, %s = the craft's name. The ARTICLE is the
-- profession's majority and is NOT per-recipe correct -- see the builder.
lib:LoadRecipeScrollUseText({
[129]="教你学会制作%s。",
[164]="教你学会制作%s。",
[165]="教你学会制作%s。",
[171]="教你学会配制%s。",
[185]="教你学会烹制%s。",
[186]="教你学会%s。",
[197]="教你学会制作%s。",
[202]="教你学会制作%s。",
[333]="教你学会制作%s。",
})
