-- Generated by tools/build_content.py from content/frFR/eastern-kingdoms/stormwind-city.md. Do not edit.
local _, ns = ...
local Translate = ns.Lore.Translate

Translate("frFR", "stormwind-city", {
	title = "Cité de Stormwind",
	aliases = { "Stormwind" },
	sections = {
		{
			title = "Résumé",
			text = [=[La Cité de Stormwind est la capitale du {link:kingdom-of-stormwind}royaume de Stormwind{/link} et la plus grande cité de l'{link:humans}humanité{/link} encore debout dans le sud. Ses murs blancs s'élèvent à la lisière ouest de la {link:elwynn-forest}forêt d'Elwynn{/link}, et des canaux bleus courent entre ses quartiers. Les marchands se pressent dans le quartier commerçant. Les pèlerins gravissent les marches de la cathédrale de la Lumière. Au-dessus de tout se dresse le donjon de Stormwind, où les rois du royaume règnent depuis des générations. La cité est fière, riche et populeuse. C'est aussi une cité privée de son roi.]=],
		},
		{
			title = "Origines",
			text = [=[Aucune chronique ne rapporte l'année de la fondation de Stormwind. Ses racines remontent aux familles d'{link:arathor}Arathor{/link} qui partirent vers le sud il y a longtemps et fondèrent un royaume qu'elles nommèrent {link:azeroth}Azeroth{/link}. Stormwind en était le cœur. Pendant des siècles, la cité grandit dans la paix, et l'Église de la {link:holy-light}Lumière sacrée{/link} en fit l'un des grands sièges de sa foi. Puis vint la {link:first-war}Première Guerre{/link}. La {link:horde}Horde{/link} orque incendia le royaume et mit la capitale à sac, et le roi {link:llane-wrynn}Llane Wrynn{/link} mourut dans son propre donjon. Les survivants s'enfuirent vers le nord avec sire {link:anduin-lothar}Anduin Lothar{/link}, jusqu'en {link:lordaeron}Lordaeron{/link}.]=],
		},
		{
			title = "Aujourd'hui",
			text = [=[Stormwind fut relevée après la {link:second-war}Deuxième Guerre{/link}, pierre par pierre, par la {link:stonemasons-guild}guilde des Tailleurs de pierre{/link}. Quand la {link:house-of-nobles}Chambre des nobles{/link} refusa de payer ce labeur, les maçons se révoltèrent, la reine {link:tiffin-wrynn}Tiffin Wrynn{/link} fut tuée et les maçons furent chassés. Ils devinrent la {link:defias-brotherhood}Confrérie défias{/link}.

Aujourd'hui, le roi {link:varian-wrynn}Varian Wrynn{/link} a disparu au cours d'un voyage diplomatique, et nul à la cour ne peut dire où il se trouve. Son jeune fils {link:anduin-wrynn}Anduin{/link} porte le titre de roi. Le généralissime {link:bolvar-fordragon}Bolvar Fordragon{/link} gouverne en son nom comme régent, et la noble dame {link:katrana-prestor}Katrana Prestor{/link} se tient souvent à ses côtés. L'armée est loin. Les Défias rançonnent les routes hors des murs. À l'intérieur des murs, les prisonniers de la {link:the-stockade}Prison{/link} se sont soulevés contre leurs gardes. Les agents du {link:si-7}SI:7{/link} soupçonnent que quelqu'un à la cour aide la Confrérie.]=],
		},
		{
			title = "Habitants",
			text = [=[• {b}Le peuple de Stormwind.{/b} Marchands, artisans, marins, clercs et réfugiés des guerres.
• {b}La cour et les nobles.{/b} Le régent, ses conseillers et les seigneurs de la {link:house-of-nobles}Chambre des nobles{/link} se réunissent au donjon de Stormwind.
• {b}Le clergé.{/b} Les prêtres et les paladins de la cathédrale de la Lumière servent sous l'autorité de l'archevêque {link:archbishop-benedictus}Benedictus{/link}.
• {b}Les nains d'Ironforge.{/b} Ils ont leur propre quartier près des murs de la cité, avec ses forges et le tunnel vers {link:ironforge}Ironforge{/link}.
• {b}Les mages.{/b} Les magiciens du quartier des mages étudient et enseignent en vue du donjon.
• {b}Les gens de l'ombre.{/b} Le {link:si-7}SI:7{/link} œuvre depuis les ombres de la vieille ville. Des démonistes se réunissent dans la cave d'une taverne, et peu de gens demandent ce qu'ils y font.]=],
		},
		{
			title = "Histoire",
			text = [=[• {b}L'ancien royaume.{/b} Pendant des siècles, Stormwind fut la capitale d'un royaume paisible, gouverné par la maison Wrynn.
• {b}La chute.{/b} Pendant la {link:first-war}Première Guerre{/link}, la {link:horde}Horde{/link} força la cité. {link:llane-wrynn}Llane{/link} fut tué et son fils {link:varian-wrynn}Varian{/link} emmené en exil.
• {b}La reconstruction.{/b} Après la {link:second-war}Deuxième Guerre{/link}, les exilés rentrèrent chez eux, et les maçons rebâtirent la cité sur ses anciennes fondations.
• {b}L'émeute.{/b} Les nobles refusèrent de payer les maçons. La querelle finit dans le sang, et par la mort de la reine.
• {b}Aujourd'hui.{/b} Le roi a disparu. Un enfant est sur le trône, un régent gouverne, et les ennemis du royaume s'enhardissent sur ses propres terres.]=],
		},
		{
			title = "Légendes de la cité",
			text = [=[• La nouvelle Stormwind fut bâtie sur les ruines de l'ancienne. Beaucoup des hommes qui élevèrent ses murs se cachent aujourd'hui parmi les {link:defias-brotherhood}Défias{/link}.
• Un fromager du quartier commerçant n'est pas seulement fromager. Ceux qui savent quelle porte emprunter disent que le {link:si-7}SI:7{/link} garde un œil sur la cité depuis sa boutique.
• Des navires partent désormais d'un nouveau port, sur la rive ouest de la cité, et traversent la mer jusqu'à {link:auberdine}Auberdine{/link}, en {link:darkshore}Sombrivage{/link}.]=],
		},
	},
})

Translate("frFR", "trade-district", {
	title = "Quartier commerçant",
	sections = {
		{
			title = "Résumé",
			text = [=[Le quartier commerçant est le quartier le plus animé de {link:stormwind-city}Stormwind{/link}. Ses rues abritent la banque, l'hôtel des ventes, l'auberge appelée la Gilded Rose et des boutiques de tous les métiers. {link:morgan-pestle}Morgan Pestle{/link} y vend ses potions, et la famille {link:elling-trias}Trias{/link} y vend du fromage. Des griffons se posent à la lisière du quartier, porteurs de lettres et de voyageurs venus de tout le royaume. Sous tous les marchandages court le plus ancien commerce de la cité, celui des rumeurs. Ce qui s'entend à midi dans le quartier commerçant est connu au donjon le soir même.]=],
		},
	},
})

Translate("frFR", "cathedral-square", {
	title = "Place de la Cathédrale",
	sections = {
		{
			title = "Résumé",
			text = [=[La place de la Cathédrale est la grande esplanade au cœur de {link:stormwind-city}Stormwind{/link}. À son extrémité nord s'élève la {link:cathedral-of-light}cathédrale de la Lumière{/link}, la plus grande maison de la {link:holy-light}Lumière sacrée{/link} du sud. Autour de la place se dressent l'hôtel de ville, où l'architecte {link:baros-alexston}Baros Alexston{/link} a son bureau, et les salles où s'exercent le clergé et les paladins de la cité. Des soldats font l'exercice sur les dalles. Des pèlerins viennent prier. La place est l'endroit où Stormwind se montre telle qu'elle veut être vue : fidèle, ordonnée et forte.]=],
		},
	},
})

Translate("frFR", "old-town", {
	title = "Vieille ville",
	sections = {
		{
			title = "Résumé",
			text = [=[La vieille ville s'étend à l'est de {link:stormwind-city}Stormwind{/link}, là où les rues sont étroites et les bâtiments plus anciens qu'ailleurs. Elle abrite la caserne de la cité et une boutique d'armures pour les soldats. C'est aussi le foyer du {link:si-7}SI:7{/link}. {link:master-mathias-shaw}Maître Mathias Shaw{/link} travaille depuis la caserne, et ses agents vont et viennent par des portes que la plupart des citoyens ne remarquent jamais. Dans les ruelles, chacun s'occupe de ses affaires et pose peu de questions. Les soldats fraîchement arrivés dans la capitale viennent d'abord ici pour être armés, logés et envoyés là où le royaume a besoin d'eux.]=],
		},
	},
})

Translate("frFR", "dwarven-district", {
	title = "Quartier des nains",
	sections = {
		{
			title = "Résumé",
			text = [=[Le quartier des nains se dresse au nord de {link:stormwind-city}Stormwind{/link}, près des murs de la cité. Les nains d'{link:ironforge}Ironforge{/link} qui vivent à Stormwind en ont fait leur quartier. On y trouve les forges les plus bruyantes de la cité, une salle de la {link:explorers-league}Ligue des explorateurs{/link} et l'entrée du {red:deeprun-tram}Tram des profondeurs{/red}, qui file sous les montagnes jusqu'à Ironforge. Le quartier est le signe de la vieille amitié entre les deux royaumes. Ses forgerons disent, et pas à voix basse, que le meilleur acier de Stormwind se forge dans leur rue.]=],
		},
	},
})

Translate("frFR", "mage-quarter", {
	title = "Quartier des mages",
	sections = {
		{
			title = "Résumé",
			text = [=[Le quartier des mages s'étend au sud-ouest de {link:stormwind-city}Stormwind{/link}, là où des toits violets s'élèvent au-dessus des canaux. Le sanctum des magiciens se dresse en son cœur, et c'est là que les mages de la cité forment leurs élèves aux {link:arcane-magic}arcanes{/link}. Toute la magie pratiquée ici n'est pas légale. Sous la taverne appelée le Slaughtered Lamb, des démonistes se réunissent dans une cave et étudient des puissances que l'Église condamne. Près du quartier, au bord des canaux, se dresse la sinistre porte de {link:the-stockade}la Prison{/link}, où les gardes ont été repoussés jusqu'au seuil par leurs propres prisonniers.]=],
		},
	},
})

Translate("frFR", "the-park", {
	title = "Le parc",
	sections = {
		{
			title = "Résumé",
			text = [=[Le parc est un quartier verdoyant au nord-ouest de {link:stormwind-city}Stormwind{/link}. De vieux arbres se dressent entre des allées tranquilles. C'est l'endroit le plus calme d'une cité populeuse, et il s'étend juste sous les murs du donjon de Stormwind. Les habitants viennent ici se reposer, se promener et bavarder. Roy Lewells tient un cercle de lecture non loin. Ses membres se retrouvent dans une cave après les heures de travail pour débattre d'histoire et d'idées, avec des livres empruntés à la {link:royal-library}Bibliothèque royale{/link}, et avec des rafraîchissements que Roy partage volontiers avec ceux qui l'aident.]=],
		},
	},
})

Translate("frFR", "stormwind-keep", {
	title = "Donjon de Stormwind",
	aliases = { "Château de Stormwind" },
	sections = {
		{
			title = "Résumé",
			text = [=[Le donjon de {link:stormwind-city}Stormwind{/link} se dresse à l'extrémité nord de la cité, siège des rois de la maison Wrynn. Sa salle du trône est gardée jour et nuit. Là, le jeune {link:anduin-wrynn}roi Anduin{/link} se tient aux côtés du {link:bolvar-fordragon}généralissime Bolvar Fordragon{/link}, et {link:katrana-prestor}dame Katrana Prestor{/link} les assiste tous deux. Le donjon abrite aussi la {link:royal-library}Bibliothèque royale{/link}, les bureaux de la garde de la cité et un jardin clos où se promènent les seigneurs de la cour. Toutes les conversations de ce jardin ne sont pas destinées à des oreilles loyales.]=],
		},
	},
})

Translate("frFR", "stormwind-harbor", {
	title = "Port de Stormwind",
	aliases = { "port de Stormwind" },
	sections = {
		{
			title = "Résumé",
			text = [=[Le port de Stormwind a retrouvé son animation. Un nouveau navire traverse désormais la mer depuis son quai sud jusqu'à {link:auberdine}Auberdine{/link}, sur les rives de {link:darkshore}Sombrivage{/link}, et il transporte vivres, lettres et voyageurs entre le royaume et les terres des {link:night-elves}elfes de la nuit{/link}. Des commis comptent la cargaison caisse par caisse, et il n'y a jamais assez de dockers. Gardes et canonniers surveillent les eaux. Des marchands de la cité ont déjà envoyé des parents de l'autre côté de la mer pour commercer à Auberdine, et des lettres reviennent en sens inverse pour demander de l'aide. Pour la première fois depuis des années, la cité regarde au-delà de la mer.]=],
		},
	},
})

Translate("frFR", "valley-of-heroes", {
	title = "Vallée des héros",
	sections = {
		{
			title = "Résumé",
			text = [=[La Vallée des héros est la grande entrée de {link:stormwind-city}Stormwind{/link}. La route qui vient de la forêt d'{link:elwynn-forest}Elwynn{/link} franchit un long pont et passe entre de hautes statues avant d'atteindre la porte principale de la cité. Chaque voyageur qui vient à Stormwind par la terre passe sous elles. La garde de la cité veille de près ici, car la porte est la première défense de la capitale et la première chose que voient ses visiteurs. Les messagers des maréchaux lointains du royaume arrivent ici, et des écuyers portent leurs nouvelles de la porte jusqu'à la salle du trône.]=],
		},
	},
})

Translate("frFR", "cathedral-of-light", {
	title = "Cathédrale de la Lumière",
	aliases = { "Cathédrale de la Lumière sacrée" },
	sections = {
		{
			title = "Résumé",
			text = [=[La cathédrale de la Lumière est la plus grande maison de la {link:holy-light}Lumière sacrée{/link} du royaume de {link:stormwind-city}Stormwind{/link}. Elle s'élève au-dessus de la place de la Cathédrale, au cœur de la cité. L'archevêque {link:archbishop-benedictus}Benedictus{/link} dirige l'Église depuis ses salles. Des prêtres y instruisent les fidèles, et dans ses chambres latérales, le seigneur {link:grayson-shadowbreaker}Grayson Shadowbreaker{/link} forme les paladins du royaume.]=],
		},
		{
			title = "Gardienne des reliques",
			text = [=[La cathédrale ne se contente pas de prier. On y apporte des objets saints pour qu'ils soient gardés en sûreté, et des objets maudits pour qu'ils soient purifiés. Quand l'Œil de Paleth maudit fut retrouvé, on le porta à l'archevêque. Quand une petite statue du roi {link:terenas-menethil}Terenas Menethil{/link} fut découverte dans les {link:wetlands}Paluns{/link}, la Lumière sembla se rassembler autour d'elle, et elle aussi fut envoyée à la cathédrale pour y être gardée. Les fidèles de {link:stormwind-city}Stormwind{/link} ont foi que ce qui entre dans la cathédrale sera bien gardé.]=],
		},
		{
			title = "Les serviteurs de la cathédrale",
			text = [=[La cathédrale abrite bien plus que son archevêque. Évêques, frères et acolytes servent dans ses salles. Frère Kristoff y prépare ses sermons avec des livres de la {link:royal-library}Bibliothèque royale{/link}, et les paladins du seigneur {link:captain-grayson}Grayson{/link} s'exercent entre ses murs. La parole de l'Église part d'ici vers l'abbaye de {link:northshire-abbey}Northshire{/link} et vers chaque chapelle du royaume.]=],
		},
	},
})

Translate("frFR", "royal-library", {
	title = "Bibliothèque royale",
	aliases = { "Bibliothèque de Stormwind", "bibliothèque de Stormwind" },
	sections = {
		{
			title = "Résumé",
			text = [=[La Bibliothèque royale se trouve dans le donjon de {link:stormwind-city}Stormwind{/link}. Elle conserve la mémoire écrite du royaume : histoires, traités et registres de la cour. Son gardien, {link:milton-sheaf}Milton Sheaf{/link}, fait rechercher les livres perdus partout où la rumeur les place, du {link:duskwood}Bois de la Pénombre{/link} aux bibliothèques perdues de l'{link:alterac-mountains}Alterac{/link} déchu.]=],
		},
		{
			title = "Le prêt des livres",
			text = [=[La bibliothèque ne garde pas ses rayonnages pour les seuls seigneurs. Elle prête des livres aux érudits et au clergé, et ces temps-ci, elle échange aussi des volumes avec un petit cercle de lecture de la cité. Les titres que demande ce cercle disent ce qui préoccupe désormais le petit peuple : des récits des raids de la {link:horde}Horde{/link}, les conquêtes des rois Trollbane, et des titres plus étranges encore.]=],
		},
		{
			title = "Les bibliothécaires",
			text = [=[{link:milton-sheaf}Milton Sheaf{/link} tient la bibliothèque, et Donyal Tovald veille sur ses rayonnages et ses prêts. Ce sont des hommes rigoureux. Un livre qui quitte la bibliothèque doit revenir dans le même état, et un emprunteur qui traite un volume avec respect peut revenir en emprunter, si provocants qu'en soient les mots.]=],
		},
	},
})

Translate("frFR", "varian-wrynn", {
	title = "Varian Wrynn",
	subtitle = "Le roi disparu de Stormwind",
	found = "Nulle part ; le roi a disparu",
	hint = "Découvrez le roi que Stormwind a perdu.",
	allegiance = "Royaume de Stormwind · Maison Wrynn",
	aliases = { "Varian", "roi Varian", "roi Varian Wrynn" },
	sections = {
		{
			title = "Résumé",
			text = [=[Varian Wrynn est le roi de {link:stormwind-city}Stormwind{/link}, fils du roi {link:llane-wrynn}Llane Wrynn{/link} et père du jeune Anduin. Enfant, il vit brûler le royaume de son père, devint un homme en exil, et rentra chez lui pour régner sur une cité rebâtie sur ses cendres. Aujourd'hui, il n'est plus là. Il partit pour un voyage diplomatique et ne revint jamais, et aucune nouvelle de lui n'est parvenue à sa cour.]=],
		},
		{
			title = "Importance",
			text = [=[L'absence de Varian pèse sur tout {link:stormwind-city}Stormwind{/link}. Un enfant porte son titre. Un régent gouverne en son nom. Son armée est loin, ses routes ne sont pas sûres, et ses nobles se querellent dans les salles du donjon. Chaque sujet loyal du royaume pose la même question, et nul à la cour ne peut y répondre : où est le roi ? Jusqu'à son retour, Stormwind doit être tenue par ceux qui se tenaient aux côtés de son trône.]=],
		},
		{
			title = "Hauts faits",
			text = [=[• Enfant, il survécut à la chute de {link:stormwind-city}Stormwind{/link} pendant la {link:first-war}Première Guerre{/link}, quand son père fut tué.
• Il fut emmené vers le nord, en {link:lordaeron}Lordaeron{/link}, par sire {link:anduin-lothar}Anduin Lothar{/link} et grandit en exil.
• Après la {link:second-war}Deuxième Guerre{/link}, il revint prendre le trône d'une Stormwind rebâtie.
• Il épousa {link:tiffin-wrynn}Tiffin Wrynn{/link} et la perdit dans l'émeute des tailleurs de pierre.
• Il partit pour une mission diplomatique et disparut.]=],
		},
		{
			title = "Non consigné",
			text = [=[Aucune chronique ne rapporte l'année de la disparition de Varian, ni l'endroit où il fut vu pour la dernière fois. Ce qu'il est devenu, on l'ignore à {link:stormwind-city}Stormwind{/link}.]=],
		},
	},
	chapters = {
		{
			title = "Le retour de l'exilé",
			hint = "Découvrez comment Stormwind fut rebâtie.",
			text = [=[L'enfant qui avait fui la cité en flammes revint homme. {link:stormwind-city}Stormwind{/link} avait été rebâtie par les maçons, et Varian fut couronné dans les salles de son père. Il prit une reine, {link:tiffin-wrynn}Tiffin{/link}, et elle lui donna un fils, qu'il nomma d'après le héros qui lui avait sauvé la vie. Un temps, il sembla que la maison Wrynn avait traversé le feu.]=],
		},
		{
			title = "La mort de la reine",
			hint = "Découvrez ce que l'émeute des maçons coûta au roi.",
			text = [=[Quand la {link:house-of-nobles}Chambre des nobles{/link} refusa de payer la {link:stonemasons-guild}guilde des Tailleurs de pierre{/link}, les maçons se soulevèrent avec colère. Dans le chaos de cette émeute, la {link:tiffin-wrynn}reine Tiffin{/link} fut tuée. Les maçons furent chassés de la cité, et le roi resta seul pour élever son fils. De l'exil des maçons naquit la {link:defias-brotherhood}Confrérie défias{/link}.]=],
		},
		{
			title = "Le trône vide",
			hint = "Portez au roi un rapport sur la Confrérie défias.",
			text = [=[Le rapport était destiné aux mains du roi lui-même. Il parlait de la confrérie de {link:edwin-vancleef}VanCleef{/link} et de la trahison découverte à la cour. Mais le roi n'était pas là pour le lire. Dame Prestor le reçut à sa place, et elle dit seulement que Varian était parti en mission diplomatique. Elle ne dit pas où il était allé.]=],
		},
	},
	mentions = {
		{ text = "An Audience with the King, un rapport qui lui est adressé" },
	},
	bonds = {
		{ id = "anduin-wrynn", name = "Anduin Wrynn", note = "son fils" },
		{ id = "llane-wrynn", name = "Llane Wrynn", note = "son père" },
		{ id = "tiffin-wrynn", name = "Tiffin Wrynn", note = "sa reine, perdue dans l'émeute" },
		{ id = "anduin-lothar", name = "Anduin Lothar", note = "l'emmena en exil" },
		{ id = "bolvar-fordragon", name = "Bolvar Fordragon", note = "gouverne en son nom" },
		{ id = "katrana-prestor", name = "Katrana Prestor", note = "parle pour la cour en son absence" },
	},
})

Translate("frFR", "anduin-wrynn", {
	title = "Anduin Wrynn",
	subtitle = "L'enfant roi de Stormwind",
	found = "La salle du trône du donjon de Stormwind",
	hint = [=[Demandez audience dans la salle du trône du donjon de Stormwind.]=],
	allegiance = "Royaume de Stormwind · Maison Wrynn",
	aliases = { "roi Anduin", "prince Anduin" },
	sections = {
		{
			title = "Résumé",
			text = [=[Anduin Wrynn est le fils unique du {link:varian-wrynn}roi Varian{/link} et de la {link:tiffin-wrynn}reine Tiffin{/link}. Ce n'est encore qu'un enfant, et pourtant, en l'absence de son père, il porte le titre de roi de {link:stormwind-city}Stormwind{/link}. Il se tient dans la salle du trône du donjon parmi des hommes faits en armure et des dames de la cour, tandis que le {link:bolvar-fordragon}généralissime Bolvar Fordragon{/link} gouverne en son nom.]=],
		},
		{
			title = "Importance",
			text = [=[Anduin est l'avenir de la maison Wrynn et l'espoir vivant de son royaume. Tant qu'il se tient dans la salle du trône, le peuple de {link:stormwind-city}Stormwind{/link} peut croire que sa lignée de rois n'est pas rompue. Il fut nommé d'après sire {link:anduin-lothar}Anduin Lothar{/link}, le champion qui sauva son père enfant et l'emporta hors de la cité en flammes.

La place de l'enfant est étrange. Il porte le plus haut titre du royaume, et pourtant les décisions du royaume sont prises par d'autres. Chaque solliciteur qui entre dans la salle du trône s'incline devant lui. Peu lui adressent la parole. Ils parlent au régent à ses côtés, et à la dame de la cour qui se tient près d'eux deux. Anduin voit et entend tout cela.]=],
		},
		{
			title = "Hauts faits",
			text = [=[• Il perdit sa mère dans l'émeute des maçons quand il était tout petit.
• Il porte le titre de son père tant que le roi est porté disparu.
• Il tient sa cour aux côtés du régent et des seigneurs du royaume.
• Il attend dans la salle du trône de son père des nouvelles de celui-ci.]=],
		},
		{
			title = "Non consigné",
			text = [=[Aucune chronique ne rapporte l'année de la naissance d'Anduin, ni son âge exact en ces jours. Les registres de la cour disent peu de ses propres pensées.]=],
		},
	},
	chapters = {
		{
			title = "Un enfant sur le trône",
			hint = "Parlez au jeune roi dans le donjon de Stormwind.",
			text = [=[L'enfant a appris à rester immobile pendant de longues audiences. Il écoute maréchaux et nobles, les suppliques des fermes et les rapports des frontières. Il a perdu une mère et, peut-être, un père. La cour l'appelle roi. Ceux qui regardent de près voient qu'il est aussi un enfant qui attend des nouvelles qui ne viennent jamais.]=],
		},
		{
			title = "L'héritier de deux maisons",
			hint = "Découvrez l'histoire de la maison Wrynn.",
			text = [=[Le grand-père d'Anduin, le roi {link:llane-wrynn}Llane Wrynn{/link}, mourut lors de la chute de l'ancienne {link:stormwind-city}Stormwind{/link}. Son père grandit en exil à la cour du {link:terenas-menethil}roi Terenas{/link}, en {link:lordaeron}Lordaeron{/link}, et revint bâtir une nouvelle cité. Sa mère, la reine {link:tiffin-wrynn}Tiffin{/link}, mourut dans ses rues. Anduin a hérité à la fois de la couronne et de ses blessures.]=],
		},
	},
	bonds = {
		{ id = "varian-wrynn", name = "Varian Wrynn", note = "son père, disparu" },
		{ id = "tiffin-wrynn", name = "Tiffin Wrynn", note = "sa mère" },
		{ id = "bolvar-fordragon", name = "Bolvar Fordragon", note = "son régent et protecteur" },
		{ id = "katrana-prestor", name = "Katrana Prestor", note = "une dame de sa cour" },
		{ id = "anduin-lothar", name = "Anduin Lothar", note = "le héros dont il porte le nom" },
	},
})

Translate("frFR", "bolvar-fordragon", {
	title = "Bolvar Fordragon",
	subtitle = "Régent de Stormwind",
	found = "La salle du trône du donjon de Stormwind",
	hint = [=[Allez trouver le généralissime qui gouverne depuis la salle du trône.]=],
	allegiance = "Royaume de Stormwind · Lumière sacrée",
	aliases = { "Bolvar", "généralissime Bolvar Fordragon", "généralissime Fordragon", "Fordragon" },
	sections = {
		{
			title = "Résumé",
			text = [=[Le généralissime Bolvar Fordragon est un champion de la {link:holy-light}Lumière sacrée{/link} et le régent de {link:stormwind-city}Stormwind{/link}. Le {link:varian-wrynn}roi Varian{/link} ayant disparu et son fils n'étant encore qu'un enfant, Bolvar gouverne le royaume depuis la salle du trône du donjon. Il se tient aux côtés du jeune Anduin dans une armure étincelante, et chaque ordre qui quitte le donjon de Stormwind le quitte sous son sceau.]=],
		},
		{
			title = "Importance",
			text = [=[Bolvar maintient l'unité du royaume à l'heure la plus incertaine. Il doit répondre aux appels de chaque frontière en difficulté, des {link:redridge-mountains}Carmines{/link} aux {link:wetlands}Paluns{/link}, avec une armée déjà trop dispersée. Il s'appuie sur les conseils de son entourage. Parmi eux, nulle voix n'est plus souvent entendue que celle de {link:katrana-prestor}dame Katrana Prestor{/link}.]=],
		},
		{
			title = "Hauts faits",
			text = [=[• Il gouverne {link:stormwind-city}Stormwind{/link} comme régent au nom de l'enfant roi.
• Il garde Anduin en personne, dans la salle du trône du donjon.
• Il reçoit les suppliques des villes et des maréchaux du royaume.
• Il envoie des champions affronter les menaces que l'armée ne peut atteindre.]=],
		},
	},
	chapters = {
		{
			title = "La supplique de Lakeshire",
			hint = "Portez au régent la supplique du magistrat de Lakeshire.",
			text = [=[Le magistrat {link:magistrate-solomon}Solomon{/link}, de {link:lakeshire}Lakeshire{/link}, écrivit au régent au sujet des dangers qui se refermaient sur {link:redridge-mountains}les Carmines{/link}, et il supplia la couronne de l'aider. Bolvar ne voulut pas décider seul. Il envoya d'abord le messager parler à {link:katrana-prestor}dame Prestor{/link}, et ce n'est qu'après ses conseils qu'il rédigea son décret pour Lakeshire.]=],
		},
		{
			title = "Une statue du vieux roi",
			hint = [=[Apportez au régent une relique du roi Terenas depuis les Paluns.]=],
			text = [=[De {link:menethil-harbor}Port de Menethil{/link}, dans les {link:wetlands}Paluns{/link}, arriva une petite statue du roi {link:terenas-menethil}Terenas Menethil{/link}, retrouvée après une longue recherche. Les gardiens du port craignaient de la garder dans une terre assaillie d'ennemis. Ils l'envoyèrent directement à Bolvar, confiants qu'il saurait où garder un tel souvenir du roi de {link:lordaeron}Lordaeron{/link}.]=],
		},
		{
			title = "Le seigneur forestier",
			hint = "Apportez au régent des nouvelles de Nathanos Marris.",
			text = [=[La nouvelle parvint au donjon au sujet de {link:nathanos-blightcaller}Nathanos Marris{/link}, jadis seigneur forestier, qui sert aujourd'hui les {link:forsaken}Réprouvés{/link} sous le nom de Nathanos Blightcaller. Bolvar ne la prit pas à la légère. Il appela une armée à marcher sur les {link:eastern-plaguelands}Maleterres de l'est{/link} pour en finir avec le Blightcaller, et il avertit que la {link:horde}Horde{/link} défendrait le seigneur forestier au prix de sa vie.]=],
		},
		{
			title = "La grande mascarade",
			hint = [=[Tenez-vous aux côtés du généralissime quand la vérité éclatera dans sa propre salle du trône.]=],
			text = [=[Le maréchal {red:reginald-windsor}Reginald Windsor{/red} vint à la salle du trône avec la preuve d'un complot au cœur de la cour. Quand il parla, la femme qui conseillait Bolvar depuis si longtemps montra sa vraie forme. C'était {link:onyxia}Onyxia{/link}, fille d'{link:deathwing}Aile-de-mort{/link}. Bolvar avait été sa marionnette, et elle le lui dit en face. Windsor tomba, et le dragon s'enfuit. Elle laissa derrière elle un régent ébranlé et une cour qui ne pouvait plus se fier aux siens.]=],
		},
	},
	mentions = {
		{ text = "The True Masters" },
		{ text = "The True Masters" },
		{ text = "A Friend of the Family" },
		{ text = "The First and the Last" },
		{ text = "The {link:nathanos-blightcaller}Blightcaller{/link} Cometh" },
		{ text = "Order Must Be Restored" },
		{ text = "The Great Masquerade" },
		{ text = "The Dragon's Eye" },
	},
	bonds = {
		{ id = "anduin-wrynn", name = "Anduin Wrynn", note = "l'enfant roi qu'il protège" },
		{ id = "varian-wrynn", name = "Varian Wrynn", note = "le roi qu'il sert" },
		{ id = "katrana-prestor", name = "Katrana Prestor", note = "sa conseillère la plus écoutée" },
		{ id = "master-mathias-shaw", name = "Maître Mathias Shaw", note = "son maître espion" },
		{ id = "major-samuelson", name = "Major Samuelson", note = "un officier de sa garde" },
	},
})

Translate("frFR", "katrana-prestor", {
	title = "Katrana Prestor",
	subtitle = "Dame de la cour de Stormwind",
	found = "La salle du trône du donjon de Stormwind",
	hint = [=[Allez trouver la noble dame qui se tient aux côtés du régent.]=],
	allegiance = "Royaume de Stormwind · La cour",
	aliases = { "Katrana", "dame Katrana Prestor", "dame Prestor" },
	sections = {
		{
			title = "Résumé",
			text = [=[Dame Katrana Prestor est une noble dame d'une grande influence. Elle se tient dans la salle du trône du donjon de {link:stormwind-city}Stormwind{/link} aux côtés du {link:bolvar-fordragon}généralissime Bolvar Fordragon{/link}, et elle parle pour la cour quand la cour doit parler. Les solliciteurs qui viennent au donjon constatent souvent que leurs paroles n'atteignent le régent qu'après l'avoir atteinte, elle.]=],
		},
		{
			title = "Importance",
			text = [=[Dans une cour sans roi, les conseils d'une conseillère de confiance ont le poids de la loi. La voix de dame Prestor se fait entendre sur chaque grande question du royaume : ce que le royaume peut épargner, qui il doit croire, et lesquels de ses troubles peuvent être ignorés sans danger. Certains dans le royaume admirent sa sagesse. D'autres, loin de la capitale, commencent à se demander pourquoi leurs suppliques trouvent si rarement une réponse.

Elle est toujours présente. Quand le régent reçoit une supplique, elle est à ses côtés. Quand un rapport arrive pour le roi absent, c'est elle qui le prend. Quand le régent doit décider, il lui demande d'abord conseil. Aucun seigneur de la {link:house-of-nobles}Chambre des nobles{/link} n'occupe une place aussi proche du cœur du royaume.]=],
		},
		{
			title = "Hauts faits",
			text = [=[• Elle conseille le régent sur les affaires du royaume.
• Elle reçoit les rapports adressés au roi absent.
• Elle dit à ceux qui le demandent que le roi est parti en mission diplomatique.]=],
		},
		{
			title = "Non consigné",
			text = [=[Aucun registre de la cour ne dit d'où venait dame Prestor, ni quand elle arriva pour la première fois au donjon de {link:stormwind-city}Stormwind{/link}.]=],
		},
	},
	chapters = {
		{
			title = "Le rapport pour le roi",
			hint = "Portez au roi un rapport sur la Confrérie défias.",
			text = [=[Le rapport était adressé au {link:varian-wrynn}roi Varian{/link}. Il parlait des {link:defias-brotherhood}Défias{/link}, de la trahison du seigneur {link:gregor-lescovar}Gregor Lescovar{/link} et de l'assassin du jardin royal. Dame Prestor le reçut elle-même. Elle remercia son porteur et expliqua que le roi était parti en mission diplomatique.]=],
		},
		{
			title = "Conseil au régent",
			hint = "Portez la supplique de Lakeshire au donjon de Stormwind.",
			text = [=[Quand {link:lakeshire}Lakeshire{/link} supplia la couronne de l'aider dans {link:redridge-mountains}les Carmines{/link}, le régent refusa de répondre avant que dame Prestor n'ait parlé. Elle entendit la supplique et donna son conseil. Alors seulement {link:bolvar-fordragon}Bolvar{/link} rédigea son décret.]=],
		},
		{
			title = "La grande mascarade",
			hint = "Voyez la cour de Stormwind telle qu'elle est vraiment.",
			text = [=[Quand le maréchal {red:reginald-windsor}Reginald Windsor{/red} vint à la salle du trône avec sa preuve, dame Prestor se moqua de lui et ordonna son arrestation. Puis elle rejeta son déguisement. Dame Katrana Prestor n'avait jamais été une noble dame. C'était {link:onyxia}Onyxia{/link}, fille d'{link:deathwing}Aile-de-mort{/link}, un dragon noir qui avait porté un visage humain à la cour de {link:stormwind-city}Stormwind{/link}. Aussi longtemps qu'elle s'était tenue aux côtés du régent, le Vol noir avait eu l'oreille du royaume. Windsor mourut dans la salle du trône. Onyxia s'enfuit, et elle laissa {link:bolvar-fordragon}Bolvar{/link} découvrir depuis combien de temps il était sa marionnette.]=],
		},
	},
	mentions = {
		{ text = "An Audience with the King" },
		{ text = "The True Masters" },
		{ text = "The Great Masquerade" },
	},
	bonds = {
		{ id = "bolvar-fordragon", name = "Bolvar Fordragon", note = "le régent qu'elle conseille" },
		{ id = "anduin-wrynn", name = "Anduin Wrynn", note = "l'enfant roi de sa cour" },
		{ id = "varian-wrynn", name = "Varian Wrynn", note = "le roi qu'elle dit absent" },
	},
})

Translate("frFR", "archbishop-benedictus", {
	title = "Archevêque Benedictus",
	subtitle = "Archevêque de l'Église de la Lumière sacrée",
	found = "La cathédrale de la Lumière, place de la Cathédrale",
	hint = [=[Cherchez le chef des fidèles dans la cathédrale de la Lumière.]=],
	allegiance = "Église de la Lumière sacrée · Cathédrale de la Lumière",
	aliases = { "Benedictus" },
	sections = {
		{
			title = "Résumé",
			text = [=[L'archevêque Benedictus dirige l'Église de la {link:holy-light}Lumière sacrée{/link} depuis la cathédrale de la Lumière, à {link:stormwind-city}Stormwind{/link}. Il est le chef spirituel des prêtres du royaume et la voix de sa foi. Le clergé de {link:northshire-abbey}Northshire{/link}, les paladins de la cathédrale et les évêques du royaume se tournent tous vers lui.]=],
		},
		{
			title = "Importance",
			text = [=[Benedictus occupe la charge jadis tenue par {link:alonsus-faol}Alonsus Faol{/link}, l'archevêque qui fonda l'ordre des paladins après la {link:first-war}Première Guerre{/link}. En un âge de peste, de guerre et de magie noire, l'archevêque doit défendre la foi de {link:stormwind-city}Stormwind{/link} comme les terres au-delà. Il ne se contente pas de prier contre le mal. Il envoie des champions pour le détruire.]=],
		},
		{
			title = "Hauts faits",
			text = [=[• Il dirige le clergé de la cathédrale de la Lumière.
• Il recueille les reliques maudites pour que la Lumière les purifie.
• Il envoie des champions contre les serviteurs de la mort au-delà des frontières du royaume.]=],
		},
		{
			title = "Non consigné",
			text = [=[On a peu écrit sur la vie de Benedictus avant qu'il ne coiffe la mitre d'archevêque.]=],
		},
	},
	chapters = {
		{
			title = "L'œil maudit",
			hint = "Apportez à l'archevêque une relique qui doit être purifiée.",
			text = [=[Des {link:wetlands}Paluns{/link} arriva l'Œil de Paleth, une relique pervertie par une malédiction. Il ne fut pas détruit là où on l'avait trouvé. On le porta à {link:stormwind-city}Stormwind{/link} et on le remit entre les mains de l'archevêque, car rares sont ceux dans le royaume qui pourraient purifier une telle chose.]=],
		},
		{
			title = "Celui qui apporte le froid",
			hint = [=[Répondez à l'appel de l'archevêque contre la liche des Souilles de Tranchebauge.]=],
			text = [=[Loin au sud, en {link:kalimdor}Kalimdor{/link}, dans les salles épineuses des {link:quilboar}huranes{/link}, une créature de la non-mort appelée {link:amnennar-the-coldbringer}Amnennar{/link} the Coldbringer a élu domicile. Benedictus n'attend pas qu'un tel mal traverse la mer. Il demande des champions pour aller trouver le Coldbringer et en finir avec lui au nom de la Lumière.]=],
		},
	},
	mentions = {
		{ text = "Cleansing the Eye" },
		{ text = "Bring the Light" },
	},
	bonds = {
		{ id = "grayson-shadowbreaker", name = "Grayson Shadowbreaker", note = "dirige les paladins de sa cathédrale" },
		{ id = "alonsus-faol", name = "Alonsus Faol", note = "occupa la charge avant lui" },
		{ id = "bolvar-fordragon", name = "Bolvar Fordragon", note = "le régent de son royaume" },
	},
})

Translate("frFR", "master-mathias-shaw", {
	title = "Maître Mathias Shaw",
	subtitle = "Maître du SI:7",
	found = "La caserne de la vieille ville",
	hint = [=[Trouvez le maître du SI:7 dans la caserne de la vieille ville.]=],
	allegiance = "Royaume de Stormwind · SI:7",
	aliases = { "Mathias Shaw", "Shaw" },
	sections = {
		{
			title = "Résumé",
			text = [=[Maître Mathias Shaw dirige le {link:si-7}SI:7{/link}, le service secret de {link:stormwind-city}Stormwind{/link}. Depuis la caserne de la vieille ville, il recueille des rapports de tout le royaume, forme des agents aux arts de la discrétion et les envoie là où les soldats ne peuvent aller. La plupart des citoyens de Stormwind ne connaissent pas son nom. La plupart de ses ennemis aimeraient ne pas le connaître.]=],
		},
		{
			title = "Importance",
			text = [=[Avec l'armée au loin, les agents de Shaw sont les yeux du royaume. Ils surveillent la {link:defias-brotherhood}Confrérie défias{/link} en {link:westfall}Marche de l'Ouest{/link} et au {link:duskwood}Bois de la Pénombre{/link}, et ils surveillent la cour au donjon de {link:stormwind-city}Stormwind{/link}. C'est Shaw qui découvre que le bras de la Confrérie s'étend au-delà des champs et des mines, jusque dans les salles de la noblesse du royaume.]=],
		},
		{
			title = "Hauts faits",
			text = [=[• Il dirige les agents du {link:si-7}SI:7{/link} contre les {link:defias-brotherhood}Défias{/link} en {link:westfall}Marche de l'Ouest{/link} et au {link:duskwood}Bois de la Pénombre{/link}.
• Il forme les voleurs de {link:stormwind-city}Stormwind{/link}.
• Il démasque le traître, le seigneur {link:gregor-lescovar}Gregor Lescovar{/link}.]=],
		},
	},
	chapters = {
		{
			title = "L'ombre du passé",
			hint = [=[Apportez au maître du SI:7 la description du visiteur de Bazil Thredd.]=],
			text = [=[Avant l'émeute de la {link:the-stockade}Prison{/link}, {link:bazil-thredd}Bazil Thredd{/link} avait reçu un visiteur. Le gardien consigna ce qu'il avait vu de ce visiteur et scella le document. La description passa entre les mains de {link:baros-alexston}Baros Alexston{/link} et parvint à Shaw. Il la lut, et il sut que la piste ramenait à {link:stormwind-city}Stormwind{/link} même. Il fit prévenir un vieil ami qui surveille la cité.]=],
		},
		{
			title = "La tête de la bête",
			hint = "Aidez le SI:7 à démasquer le traître de la cour.",
			text = [=[Quand le traître, le seigneur {link:gregor-lescovar}Lescovar{/link}, et son contact défias gisaient morts dans le jardin royal, la nouvelle parvint à Shaw. C'était une victoire, mais pas une fin. Un seigneur de la {link:house-of-nobles}Chambre des nobles{/link} avait travaillé avec la confrérie de {link:edwin-vancleef}VanCleef{/link}, et Shaw envoya tout le récit à l'architecte de la cité, pour qu'il parvienne au roi.]=],
		},
	},
	mentions = {
		{ text = "La {link:defias-brotherhood}Confrérie défias{/link}" },
		{ text = "La {link:defias-brotherhood}Confrérie défias{/link}" },
		{ text = "Shadow of the Past" },
		{ text = "Look to an Old Friend" },
		{ text = "The Head of the Beast" },
		{ text = "Brotherhood's End" },
		{ text = "Seek out SI: 7" },
		{ text = "The First and the Last" },
		{ text = "Honor the Dead" },
	},
	bonds = {
		{ id = "elling-trias", name = "Elling Trias", note = "son agent dans le quartier commerçant" },
		{ id = "baros-alexston", name = "Baros Alexston", note = "partage sa lutte contre les Défias" },
		{ id = "gregor-lescovar", name = "Gregor Lescovar", note = "le traître qu'il démasqua" },
		{ id = "bolvar-fordragon", name = "Bolvar Fordragon", note = "le régent qu'il sert" },
	},
})

Translate("frFR", "baros-alexston", {
	title = "Baros Alexston",
	subtitle = "Architecte de la cité de Stormwind",
	found = "L'hôtel de ville, place de la Cathédrale",
	hint = [=[Trouvez l'architecte de la cité à l'hôtel de ville, sur la place de la Cathédrale.]=],
	allegiance = "Royaume de Stormwind · Hôtel de ville",
	aliases = { "Baros", "Alexston" },
	sections = {
		{
			title = "Résumé",
			text = [=[Baros Alexston est l'architecte de la cité de {link:stormwind-city}Stormwind{/link}. Depuis l'hôtel de ville, sur la place de la Cathédrale, il supervise la construction et l'entretien de la capitale. Il connaît les pierres de Stormwind mieux que n'importe quel seigneur de la cour, et il connaît le prix qui fut payé pour les élever.]=],
		},
		{
			title = "Importance",
			text = [=[Baros se tient au carrefour de la plus vieille blessure de {link:stormwind-city}Stormwind{/link}. La cité qu'il entretient fut rebâtie par les maçons qui devinrent la {link:defias-brotherhood}Confrérie défias{/link}. Quand {link:edwin-vancleef}Edwin VanCleef{/link} écrivit une lettre qu'il n'envoya jamais, elle était adressée à Baros. Par l'architecte, l'histoire de la Confrérie passe des {link:the-deadmines}Mortemines{/link} à la {link:the-stockade}Prison{/link}, du {link:si-7}SI:7{/link} à la salle du trône.]=],
		},
		{
			title = "Hauts faits",
			text = [=[• Il maintient les bâtiments de {link:stormwind-city}Stormwind{/link} en bon état.
• Il donne suite à la lettre de {link:edwin-vancleef}VanCleef{/link} et fait prévenir le gardien de la {link:the-stockade}Prison{/link}.
• Il porte la lutte contre la Confrérie jusqu'au {link:si-7}SI:7{/link} et à la cour.
• Il répond, du mieux qu'il peut, aux suppliques qui parviennent à la cité depuis des rivages lointains.]=],
		},
	},
	chapters = {
		{
			title = "Des débuts modestes",
			hint = [=[Récupérez le vieux compas de l'architecte dans sa maison de Marche de l'Ouest.]=],
			text = [=[Baros avait autrefois une maison en {link:westfall}Marche de l'Ouest{/link}. Il y laissa quelque chose : un vieux compas, l'outil de son premier métier. La Marche de l'Ouest est dangereuse aujourd'hui, et ses fermes sont tombées aux mains des voleurs et de la ruine. Mais un bâtisseur n'oublie pas l'instrument qui lui apprit à tracer sa première ligne droite.]=],
		},
		{
			title = "La lettre jamais envoyée",
			hint = [=[Apportez à l'architecte la lettre trouvée parmi les affaires de VanCleef.]=],
			text = [=[{link:edwin-vancleef}Edwin VanCleef{/link} avait écrit une lettre à Baros et l'avait scellée, mais elle ne quitta jamais les {link:the-deadmines}Mortemines{/link}. Quand elle parvint enfin entre les mains de l'architecte, il la lut avec soin. Ses mots tournèrent ses pensées vers la {link:the-stockade}Prison{/link}, où l'un des lieutenants de VanCleef, {link:bazil-thredd}Bazil Thredd{/link}, était détenu.]=],
		},
		{
			title = "Une lettre d'Auberdine",
			hint = [=[Portez la lettre de l'ancien d'Auberdine de l'autre côté de la mer, jusqu'à Stormwind.]=],
			text = [=[L'ancien {link:thundris-windweaver}Thundris Windweaver{/link}, d'{link:auberdine}Auberdine{/link}, écrivit à Baros pour demander qu'on se souvienne de sa petite ville. Baros rit quand le porteur de la lettre arriva, et son sourire s'effaça à mesure qu'il lisait. Sa réponse fut honnête. Les coffres de {link:stormwind-city}Stormwind{/link} ne sont plus ce qu'ils étaient, et ce qu'il en reste est dispersé. Il n'avait rien à envoyer que ses regrets.]=],
		},
	},
	mentions = {
		{ text = "Humble Beginnings" },
		{ text = "The Unsent Letter" },
		{ text = "{link:bazil-thredd}Bazil Thredd{/link}" },
		{ text = "The Curious Visitor" },
		{ text = "Shadow of the Past" },
		{ text = "Brotherhood's End" },
		{ text = "An Audience with the King" },
		{ text = "Expanding Horizons" },
		{ text = "Making Do" },
	},
	bonds = {
		{ id = "edwin-vancleef", name = "Edwin VanCleef", note = "lui écrivit une lettre jamais envoyée" },
		{ id = "warden-thelwater", name = "Gardien Thelwater", note = "garde la Prison" },
		{ id = "master-mathias-shaw", name = "Maître Mathias Shaw", note = "maître du SI:7" },
		{ id = "katrana-prestor", name = "Katrana Prestor", note = "reçut son rapport pour le roi" },
	},
})

Translate("frFR", "elling-trias", {
	title = "Elling Trias",
	subtitle = "Maître fromager",
	found = "Fromages Trias, dans le quartier commerçant",
	hint = [=[Rendez visite à la fromagerie du quartier commerçant et parlez à son maître.]=],
	allegiance = "Fromages Trias · SI:7",
	aliases = { "Trias" },
	sections = {
		{
			title = "Résumé",
			text = [=[Elling Trias vend du fromage dans le quartier commerçant, et il le vend bien. C'est aussi un agent du {link:si-7}SI:7{/link}. Depuis sa boutique, il surveille les rues les plus animées de la cité, et des messages pour {link:master-mathias-shaw}Mathias Shaw{/link} passent sur son comptoir avec les meules et les pointes. Quand un diplomate disparaît ou qu'un traître doit être surveillé, Shaw fait appel à son vieil ami.]=],
		},
		{
			title = "Importance",
			text = [=[Elling prouve que les yeux du {link:si-7}SI:7{/link} sont partout dans la cité, même derrière un comptoir de fromages.]=],
		},
		{
			title = "Hauts faits",
			text = [=[• Il guide la recherche d'un diplomate de {link:stormwind-city}Stormwind{/link} disparu sur la route.
• Il organise la surveillance du jardin du seigneur {link:gregor-lescovar}Lescovar{/link}.]=],
		},
	},
	chapters = {
		{
			title = "Un vieil ami",
			hint = "Parlez au fromager à la demande de maître Shaw.",
			text = [=[Le message de {link:master-mathias-shaw}Shaw{/link} envoya un inconnu dans une fromagerie. Elling écouta, pesa l'affaire et envoya l'inconnu au donjon, où un certain {link:tyrion}Tyrion{/link} surveille le jardin royal.]=],
		},
	},
	mentions = {
		{ text = "Look to an Old Friend" },
		{ text = "Infiltrating the Castle" },
		{ text = "The Attack!" },
		{ text = "The Missing Diplomat" },
		{ text = "Philmor's Favor" },
	},
	bonds = {
		{ id = "master-mathias-shaw", name = "Maître Mathias Shaw", note = "son maître au SI:7" },
		{ id = "tyrion", name = "Tyrion", note = "son contact au donjon" },
	},
})

Translate("frFR", "grayson-shadowbreaker", {
	title = "Grayson Shadowbreaker",
	subtitle = "Seigneur des paladins de la cathédrale",
	found = "La cathédrale de la Lumière, place de la Cathédrale",
	hint = [=[Cherchez le seigneur qui forme les paladins dans la cathédrale de la Lumière.]=],
	allegiance = "Église de la Lumière sacrée · Paladins de Stormwind",
	aliases = { "Seigneur Grayson Shadowbreaker", "Shadowbreaker" },
	sections = {
		{
			title = "Résumé",
			text = [=[Le seigneur Grayson Shadowbreaker forme les paladins de {link:stormwind-city}Stormwind{/link} dans les salles de la cathédrale de la Lumière. C'est un chevalier et un maître, et ses élèves apprennent de lui que la {link:holy-light}Lumière sacrée{/link} demande le sacrifice avant d'accorder la force. Les jeunes paladins du royaume passent entre ses mains, et les anciens aussi, quand ils cherchent une voie plus rude.]=],
		},
		{
			title = "Importance",
			text = [=[{link:captain-grayson}Grayson{/link} maintient vivante l'union de la foi et de l'acier que l'Église de la {link:holy-light}Lumière sacrée{/link} forgea après la {link:first-war}Première Guerre{/link}. Ses conseils portent au-delà de {link:stormwind-city}Stormwind{/link}. Il envoie les jeunes paladins nains auprès de leurs propres maîtres à {link:ironforge}Ironforge{/link}, et on lui confie des objets saints que le royaume souhaite garder en sûreté.]=],
		},
		{
			title = "Hauts faits",
			text = [=[• Il forme les paladins de la cathédrale.
• Il envoie les paladins nains auprès de Tiza Battleforge, à {link:ironforge}Ironforge{/link}.
• Il engage les paladins aguerris du royaume sur une longue route d'épreuves et de sacrifice.
• Il reçoit la statuette de Menethil pour qu'elle soit gardée dans la cathédrale.]=],
		},
		{
			title = "Non consigné",
			text = [=[On a peu écrit sur la vie de {link:captain-grayson}Grayson{/link} avant la cathédrale, ni sur les actes qui lui valurent son titre.]=],
		},
	},
	chapters = {
		{
			title = "Une relique de Terenas",
			hint = [=[Apportez à la cathédrale une petite statue de l'ancien roi de Lordaeron.]=],
			text = [=[Le roi {link:terenas-menethil}Terenas Menethil{/link} était un homme humble qui n'aimait pas les monuments, et peu de ses effigies survécurent à la chute de son royaume. Quand une petite statue de lui sortit des {link:wetlands}Paluns{/link}, la Lumière sembla reposer en elle. On la porta à {link:stormwind-city}Stormwind{/link} et on la confia au seigneur {link:captain-grayson}Grayson{/link}, pour qu'elle soit gardée dans la cathédrale de la Lumière.]=],
		},
		{
			title = "La route du sacrifice",
			hint = [=[Parcourez la longue route que le seigneur Grayson impose aux paladins du royaume.]=],
			text = [=[{link:captain-grayson}Grayson{/link} n'accorde pas à la légère les honneurs d'un paladin. La première épreuve qu'il impose est celle du sacrifice : un don coûteux à l'église d'{link:ironforge}Ironforge{/link}, en échange d'un encensoir sacré gardé par son grand prêtre.]=],
		},
	},
	mentions = {
		{ text = "Tome of Divinity" },
		{ text = "Emphasis on Sacrifice" },
		{ text = "Lord Grayson Shadowbreaker" },
		{ text = "A Friend of the Family" },
	},
	bonds = {
		{ id = "archbishop-benedictus", name = "Archevêque Benedictus", note = "dirige l'Église qu'il sert" },
		{ id = "bolvar-fordragon", name = "Bolvar Fordragon", note = "un autre champion de la Lumière" },
	},
})

Translate("frFR", "major-samuelson", {
	title = "Major Samuelson",
	subtitle = "Major de la garde de la Cité de Stormwind",
	found = "Donjon de Stormwind",
	hint = [=[Trouvez le major de la garde de la cité dans le donjon de Stormwind.]=],
	allegiance = "Royaume de Stormwind · Garde de la Cité de Stormwind",
	aliases = { "Samuelson" },
	sections = {
		{
			title = "Résumé",
			text = [=[Le major Samuelson commande au sein de la garde de la cité de {link:stormwind-city}Stormwind{/link} depuis les salles du donjon. Sa charge est l'ordre de la capitale et l'affectation de ses soldats. Les rapports des postes lointains de la garde passent sur son bureau, tout comme les plaintes des officiers qui les tiennent.]=],
		},
		{
			title = "Importance",
			text = [=[Samuelson est le visage de la garde qui protège la capitale elle-même. Tous les officiers ne se réjouissent pas des postes qu'il attribue, et tous les rapports qu'il reçoit ne sont pas heureux.]=],
		},
		{
			title = "Hauts faits",
			text = [=[• Il supervise les officiers de la garde de la cité.
• Il reçoit le rapport du lieutenant {link:lieutenant-farren-orinelle}Farren Orinelle{/link}, posté au loin, à {link:southshore}Southshore{/link}.]=],
		},
	},
	mentions = {
		{ text = "Reassignment" },
	},
	bonds = {
		{ id = "bolvar-fordragon", name = "Bolvar Fordragon", note = "le régent qu'il sert" },
	},
})

Translate("frFR", "gregor-lescovar", {
	title = "Gregor Lescovar",
	subtitle = "Un seigneur de la cour",
	found = "Le jardin du donjon de Stormwind",
	hint = [=[Surveillez le seigneur qui se promène dans le jardin du donjon de Stormwind.]=],
	allegiance = "Chambre des nobles · Confrérie défias",
	aliases = { "Seigneur Gregor Lescovar", "Lescovar" },
	sections = {
		{
			title = "Résumé",
			text = [=[Le seigneur Gregor Lescovar est un noble de la {link:house-of-nobles}Chambre des nobles{/link} qui circule librement dans les salles et les jardins du donjon de {link:stormwind-city}Stormwind{/link}. C'est aussi un traître. En secret, il rencontre Marzon la Lame silencieuse, un agent de la {link:defias-brotherhood}Confrérie défias{/link}, parmi les haies du jardin royal.]=],
		},
		{
			title = "Importance",
			text = [=[Lescovar prouve que la Confrérie étend son bras jusque dans la cour. Les nobles qui refusèrent jadis de payer les maçons comptent désormais parmi eux un membre qui travaille avec eux.]=],
		},
	},
	chapters = {
		{
			title = "Le jardin",
			hint = [=[Montez la garde dans le jardin royal pendant que le traître rencontre son contact.]=],
			text = [=[Le {link:si-7}SI:7{/link} avait posté sa surveillance. Quand Lescovar vint au jardin rencontrer Marzon, chaque mot fut entendu. Ni le seigneur ni l'assassin ne quittèrent le jardin vivants.]=],
		},
	},
	mentions = {
		{ text = "Infiltrating the Castle" },
		{ text = "The Attack!" },
	},
	bonds = {
		{ id = "master-mathias-shaw", name = "Maître Mathias Shaw", note = "le démasqua" },
		{ id = "tyrion", name = "Tyrion", note = "surveillait son jardin" },
	},
})

Translate("frFR", "milton-sheaf", {
	title = "Milton Sheaf",
	subtitle = "Bibliothécaire de la Bibliothèque royale",
	found = "La Bibliothèque royale, donjon de Stormwind",
	hint = "Parlez au bibliothécaire du donjon de Stormwind.",
	allegiance = "Royaume de Stormwind · Bibliothèque royale",
	aliases = { "Milton" },
	sections = {
		{
			title = "Résumé",
			text = [=[Milton Sheaf tient la {link:royal-library}Bibliothèque royale{/link} du donjon de {link:stormwind-city}Stormwind{/link}. C'est un homme patient et rigoureux, pour qui chaque volume manquant est une blessure. Il fait rechercher les livres perdus partout où la rumeur les place, et il sait quel érudit, dans quelle ville lointaine, pourrait l'aider à les retrouver.]=],
		},
		{
			title = "Importance",
			text = [=[Par le travail patient de Milton, le royaume retrouve sa propre mémoire, un volume à la fois.]=],
		},
		{
			title = "Hauts faits",
			text = [=[• Il recherche l'Histoire de {link:stormwind-city}Stormwind{/link} perdue, retrouvée au loin, au {link:duskwood}Bois de la Pénombre{/link}.
• Il travaille avec le maître des traditions {link:loremaster-dibbs}Dibbs{/link}, de {link:southshore}Southshore{/link}, pour retrouver les Tomes d'{link:alterac-mountains}Alterac{/link}.
• Il trouve des livres pour le clergé de Stormwind, avec l'aide de frère {link:brother-paxton}Paxton{/link}, de {link:northshire-abbey}Northshire{/link}.]=],
		},
	},
	mentions = {
		{ text = "An Old History Book" },
		{ text = "{link:southshore}Southshore{/link}" },
		{ text = "Return to Milton" },
		{ text = "Speaking of Fortitude" },
		{ text = "Brother {link:brother-paxton}Paxton{/link}" },
	},
	bonds = {
		{ id = "donyal-tovald", name = "Donyal Tovald", note = "autre bibliothécaire" },
	},
})

Translate("frFR", "morgan-pestle", {
	title = "Morgan Pestle",
	subtitle = "Apothicaire du quartier commerçant",
	found = "L'apothicairerie Pestle, dans le quartier commerçant",
	hint = "Trouvez l'apothicaire du quartier commerçant.",
	allegiance = "Apothicairerie Pestle",
	sections = {
		{
			title = "Résumé",
			text = [=[Morgan Pestle tient l'apothicairerie familiale dans le quartier commerçant de {link:stormwind-city}Stormwind{/link}. Son frère William travaille à Comté-de-l'Or, et à eux deux, les frères achètent et vendent herbes, potions et choses plus étranges. Quand William achète des bougies de {link:kobolds}kobold{/link} aux mineurs d'{link:elwynn-forest}Elwynn{/link}, c'est à {link:morgan-stern}Morgan{/link} que va la livraison.]=],
		},
		{
			title = "Importance",
			text = [=[Les frères {link:william-pestle}Pestle{/link} lient la capitale à sa forêt. Ce qui est récolté dans les terres sauvages d'{link:elwynn-forest}Elwynn{/link} se vend sur les marchés de {link:stormwind-city}Stormwind{/link}.]=],
		},
		{
			title = "Hauts faits",
			text = [=[• Il reçoit les livraisons de son frère depuis Comté-de-l'Or.
• Il vend composants et potions aux gens de la cité.]=],
		},
	},
	mentions = {
		{ text = "Shipment to {link:stormwind-city}Stormwind{/link}" },
	},
	bonds = {
		{ id = "william-pestle", name = "William Pestle", note = "son frère à Comté-de-l'Or" },
	},
})

Translate("frFR", "innkeeper-allison", {
	title = "Aubergiste Allison",
	subtitle = "Aubergiste de la Gilded Rose",
	found = "La Gilded Rose, dans le quartier commerçant",
	hint = "Prenez une chambre à l'auberge du quartier commerçant.",
	allegiance = "La Gilded Rose",
	aliases = { "Allison" },
	sections = {
		{
			title = "Résumé",
			text = [=[L'aubergiste Allison tient la Gilded Rose, la grande auberge du quartier commerçant. Des voyageurs de tous les coins du royaume dorment sous son toit, et elle entend leurs nouvelles avant n'importe qui d'autre dans la cité. Bien des demandes d'aide venues de terres lointaines passent par sa salle commune.]=],
		},
		{
			title = "Importance",
			text = [=[La Gilded Rose est l'endroit où les nouvelles du royaume viennent passer la nuit, et Allison est parmi les premières à les entendre.]=],
		},
		{
			title = "Hauts faits",
			text = [=[• Elle tient la Gilded Rose.
• Elle transmet des demandes d'aide venues de lieux lointains, même des druides de {link:darnassus}Darnassus{/link}.]=],
		},
	},
	mentions = {
		{ text = "Assisting Arch Druid Staghelm" },
	},
	bonds = {
		{ id = "morgan-pestle", name = "Morgan Pestle", note = "un voisin du quartier commerçant" },
	},
})

Translate("frFR", "tyrion", {
	title = "Tyrion",
	subtitle = "Guetteur du jardin royal",
	found = "Donjon de Stormwind, près du jardin royal",
	hint = [=[Trouvez le guetteur du donjon de Stormwind à qui Elling Trias se fie.]=],
	allegiance = "Royaume de Stormwind · SI:7",
	sections = {
		{
			title = "Résumé",
			text = [=[Tyrion monte la garde près du jardin royal du donjon de {link:stormwind-city}Stormwind{/link}, où se promène le seigneur {link:gregor-lescovar}Gregor Lescovar{/link}. Quand le {link:si-7}SI:7{/link} eut besoin d'yeux dans ce jardin, {link:elling-trias}Elling Trias{/link} lui envoya de l'aide. Pour s'approcher assez près pour écouter, il lui fallait une diversion habile, et il en construisit une de ses propres mains.]=],
		},
		{
			title = "Importance",
			text = [=[Sans la surveillance de Tyrion, la rencontre du jardin n'aurait jamais été entendue, et le traître de la cour circulerait toujours librement.]=],
		},
		{
			title = "Hauts faits",
			text = [=[• Il rassemble de la soie et des pommes fraîches pour préparer une diversion destinée au garde du jardin.
• Il fait prévenir quand {link:gregor-lescovar}Lescovar{/link} et son contact se rencontrent enfin.]=],
		},
	},
	mentions = {
		{ text = "Infiltrating the Castle" },
		{ text = "Items of Some Consequence" },
		{ text = "The Attack!" },
	},
	bonds = {
		{ id = "elling-trias", name = "Elling Trias", note = "lui envoie de l'aide" },
		{ id = "gregor-lescovar", name = "Gregor Lescovar", note = "le seigneur qu'il surveille" },
	},
})

Translate("frFR", "brohann-caskbelly", {
	title = "Brohann Caskbelly",
	subtitle = "Explorateur de la Ligue",
	found = "La salle de la Ligue des explorateurs, quartier des nains",
	hint = "Cherchez l'explorateur dans le quartier des nains.",
	allegiance = "Ligue des explorateurs · Royaume d'Ironforge",
	aliases = { "Brohann" },
	sections = {
		{
			title = "Résumé",
			text = [=[Brohann Caskbelly représente la {link:explorers-league}Ligue des explorateurs{/link} d'{link:ironforge}Ironforge{/link} dans le quartier des nains de {link:stormwind-city}Stormwind{/link}. Il collectionne cartes, rumeurs et ruines, et sa passion du moment est un temple englouti des trolls. On le dit noyé dans {link:swamp-of-sorrows}le Marais des Chagrins{/link}, et Brohann compte bien le trouver.]=],
		},
		{
			title = "Importance",
			text = [=[Brohann montre que le bras de la Ligue s'étend bien au-delà des montagnes d'{link:ironforge}Ironforge{/link}. Même dans une cité humaine, un {link:dwarves}nain{/link} peut garder l'esprit tourné vers des ruines à l'autre bout du monde.]=],
		},
		{
			title = "Hauts faits",
			text = [=[• Il recherche le temple perdu d'{link:temple-of-atal-hakkar}Atal'Hakkar{/link}.
• Il envoie des explorateurs dans les {link:the-hinterlands}Hinterlands{/link} en quête de ce dont se souviennent les trolls.]=],
		},
	},
	mentions = {
		{ text = "In Search of The Temple" },
		{ text = "Vers les {link:the-hinterlands}Hinterlands{/link}" },
		{
			text = [=[Dans le temple d'{link:temple-of-atal-hakkar}Atal'Hakkar{/link}]=],
		},
	},
})
