-- Generated by tools/build_content.py from content/ptBR/kalimdor/darkshore.md. Do not edit.
local _, ns = ...
local Translate = ns.Lore.Translate

Translate("ptBR", "darkshore", {
	title = "Costa Negra",
	sections = {
		{
			title = "Resumo",
			text = [=[A Costa Negra é um longo litoral cinzento no noroeste de {link:kalimdor}Kalimdor{/link}, do outro lado de um estreito da grande árvore {link:teldrassil}Teldrassil{/link}. Suas florestas são sombrias mesmo ao meio-dia, suas praias são frias, e suas colinas estão cheias de ruínas mais antigas que qualquer reino dos homens. Os {link:night-elves}elfos noturnos{/link} a mantêm a partir da pequena cidade portuária de {link:auberdine}Auberdine{/link}. Fizeram dela um portão entre seu novo lar e o mundo mais amplo. Mas a terra que guardam está doente. Seus rios correm imundos, suas feras enlouqueceram, e velhos inimigos voltaram às ruínas do próprio passado dos elfos.]=],
		},
		{
			title = "Origens",
			text = [=[Muito antes da {link:great-sundering}Grande Cisão{/link}, estas colinas davam para as margens do {link:well-of-eternity}Poço da Eternidade{/link}. Aqui a {link:queen-azshara}Rainha Azshara{/link} ergueu as cidades gêmeas de {link:ameth-aran}Ameth'Aran{/link} e {link:bashal-aran}Bashal'Aran{/link} para seus Bem-nascidos favoritos, e pôs o lorde {link:athrikus-narassin}Athrikus Narassin{/link} para governá-las de sua {link:tower-of-althalaxx}Torre de Althalaxx{/link}. Quando a {link:war-of-the-ancients}Guerra dos Antigos{/link} terminou e o Poço foi destruído, as cidades caíram e a terra foi rasgada. O que restou tornou-se uma costa do novo mar. As ruínas de {link:ruins-of-mathystra}Mathistra{/link}, outrora um grande bastião dos elfos, desmoronaram no norte. Depois da {link:battle-of-mount-hyjal}Batalha do Monte Hyjal{/link}, os elfos noturnos ergueram {link:teldrassil}Teldrassil{/link} ao largo desta costa. Nenhuma crônica registra o ano em que {link:auberdine}Auberdine{/link} foi construída.]=],
		},
		{
			title = "Os Dias Atuais",
			text = [=[{link:auberdine}Auberdine{/link} é uma cidade modesta, mas movimentada. Navios levam viajantes a {link:teldrassil}Teldrassil{/link} e, através do mar, às terras dos humanos. Um novo navio a liga agora ao {link:stormwind-harbor}Porto de Ventobravo{/link}, e outro navega por {link:southshore}Costa Sul{/link} até o {link:menethil-harbor}Porto de Menethil{/link}. A cidade precisa de cada amigo que esses navios possam trazer. Os {link:furbolgs}pelursos{/link} {link:blackwood-furbolgs}Bosqueneros{/link} se voltaram contra os elfos. Uma doença se espalha pelos ursos-cardo e pelos cervos, e parece fluir da {link:felwood}Selva Maleva{/link}, a leste. {link:naga}Nagas{/link} ocupam as ruínas de {link:ruins-of-mathystra}Mathistra{/link}. O {link:twilight-s-hammer}Martelo do Crepúsculo{/link} escava no {link:the-master-s-glaive}Glaive do Mestre{/link}, e um culto de bruxos se reúne na {link:tower-of-althalaxx}Torre de Althalaxx{/link}. Quando o ancião de Auberdine pediu ajuda a {link:stormwind-city}Ventobravo{/link}, Ventobravo não tinha nenhuma para dar. {link:darnassus}Darnassus{/link} enviou pouco mais.]=],
		},
		{
			title = "Habitantes",
			text = [=[• {b}Os elfos noturnos de {link:auberdine}Auberdine{/link}.{/b} {link:sentinels}Sentinelas{/link}, druidas e estudiosos que mantêm a cidade e estudam a corrupção que a cerca.
• {b}Os anões.{/b} Mineiros, ferreiros e mercadores de {link:ironforge}Altaforja{/link}, e os estudiosos da {link:explorers-league}Liga dos Exploradores{/link}, que escavam no sul.
• {b}Os pelursos {link:blackwood-furbolgs}Bosqueneros{/link}.{/b} Outrora amigos dos elfos, agora enlouquecidos e hostis em seus acampamentos.
• {b}Os nagas.{/b} Os nagas Stormscale assombram {link:ruins-of-mathystra}Mathistra{/link} e a caverna atrás das {link:cliffspring-falls}Quedas de Fontescarpa{/link}.
• {b}Os murlocs Greymist.{/b} Apinham-se na costa e atacam navios e pescadores.
• {b}Os mortos inquietos.{/b} Os espíritos dos Bem-nascidos ainda vagueiam pelas ruínas de {link:ameth-aran}Ameth'Aran{/link}.
• {b}Os luniscos.{/b} Percorrem as colinas do leste, e ficam mais hostis a cada estação.]=],
		},
		{
			title = "História",
			text = [=[• {b}As Cidades Gêmeas.{/b} Na era de {link:azshara}Azshara{/link}, {link:ameth-aran}Ameth'Aran{/link} e {link:bashal-aran}Bashal'Aran{/link} prosperaram junto ao {link:well-of-eternity}Poço da Eternidade{/link}, enquanto o mundo abaixo delas deslizava para a loucura.
• {b}A {link:great-sundering}Cisão{/link}.{/b} No caos da guerra, {link:athrikus-narassin}Athrikus Narassin{/link} prometeu ao povo de Ameth'Aran a vida eterna por meio de sua magia. Seus espíritos nunca encontraram descanso.
• {b}O Longo Sono.{/b} Muitos druidas seguiram {link:malfurion-stormrage}Malfurion Stormrage{/link} no sono do {link:emerald-dream}Sonho Esmeralda{/link}. Alguns dos que dormiam despertaram há pouco, e encontram seus antigos lares em ruínas.
• {b}O Novo Lar.{/b} Depois da guerra contra a {link:burning-legion}Legião Ardente{/link}, os elfos noturnos fizeram de {link:teldrassil}Teldrassil{/link} seu lar, e {link:auberdine}Auberdine{/link} tornou-se sua porta para o mundo.]=],
		},
		{
			title = "Saber da Costa",
			text = [=[• Grandes criaturas marinhas vêm se lançando nas praias da Costa Negra em número cada vez maior. As sacerdotisas do {link:temple-of-the-moon}Templo da Lua{/link} descobriram que são os nagas que as expulsam.
• Um cristal vermelho ergue-se nas colinas do leste. Dentro dele há fragmentos de osso e metade de uma mandíbula. Os luniscos se reúnem em torno dele, e ninguém sabe por quê.
• Os pescadores de {link:auberdine}Auberdine{/link} já não saem com seus barcos. Dizem que os murlocs comeram todas as garoupas.]=],
		},
	},
})

Translate("ptBR", "auberdine", {
	title = "Auberdine",
	sections = {
		{
			title = "Resumo",
			text = [=[Auberdine é a cidade portuária da {link:darkshore}Costa Negra{/link}, construída na costa voltada para {link:teldrassil}Teldrassil{/link}. Seu ancião, {link:thundris-windweaver}Thundris Windweaver{/link}, e seu conselho da vila a governam. {link:sentinels}Sentinelas{/link} a guardam, e um poço lunar em seu coração dá a água pura de que seus druidas e sacerdotisas precisam. Elfos noturnos e anões dividem sua estalagem, suas forjas e suas docas. De seus píeres, um navio atravessa até a {link:rut-theran-village}Vila de Rut'theran{/link}, ao pé de Teldrassil, e outro navega até o {link:menethil-harbor}Porto de Menethil{/link}. Agora vieram duas novas rotas: uma para o {link:stormwind-harbor}Porto de Ventobravo{/link}, e uma para Menethil passando por {link:southshore}Costa Sul{/link}, no {link:hillsbrad-foothills}Contraforte de Eira dos Montes{/link}. A cidade espera que os navios tragam ajuda. Até agora trouxeram apenas viajantes.]=],
		},
	},
})

Translate("ptBR", "ruins-of-mathystra", {
	title = "Ruínas de Mathistra",
	aliases = { "Mathistra" },
	sections = {
		{
			title = "Resumo",
			text = [=[As Ruínas de Mathistra ficam no extremo nordeste da {link:darkshore}Costa Negra{/link}. Mathistra foi outrora um grande bastião dos elfos, e fragmentos de sua magia ainda jazem entre a relva e as pedras partidas. Os {link:naga}nagas{/link} Stormscale a ocupam agora, e estão saqueando o lugar que seus próprios ancestrais um dia chamaram de lar. Suas mestras das feras dobram as grandes feras do mar à sua vontade. Nos últimos tempos, algo mais antigo foi encontrado sob as ruínas. Um guardião elemental vigiava uma escadaria que desce para a escuridão, e nem os Ancientes sabem ainda o que há lá embaixo.]=],
		},
	},
})

Translate("ptBR", "bashal-aran", {
	title = "Bashal'Aran",
	sections = {
		{
			title = "Resumo",
			text = [=[Bashal'Aran foi uma das cidades gêmeas que a {link:queen-azshara}Rainha Azshara{/link} ergueu para seus Bem-nascidos. Suas ruínas ficam a leste de {link:auberdine}Auberdine{/link}. Duendes demoníacos, capetas e sátiros do bando Deth'ryll fizeram delas o seu covil, e se fortalecem alimentando-se da magia que ainda se agarra às pedras. Há, porém, um santuário num penhasco no oeste das ruínas do qual eles não se aproximam. Uma luz azul paira em torno dele. Dentro dele espera o espírito de {link:asterion}Asterion{/link}, preso ali por seu próprio senhor há mais tempo do que qualquer elfo vivo consegue lembrar.]=],
		},
	},
})

Translate("ptBR", "ameth-aran", {
	title = "Ameth'Aran",
	sections = {
		{
			title = "Resumo",
			text = [=[Ameth'Aran era a gêmea de {link:bashal-aran}Bashal'Aran{/link}, uma cidade dos Bem-nascidos junto ao {link:well-of-eternity}Poço da Eternidade{/link}. Foi arruinada na guerra que partiu o mundo. Seu povo não morreu de verdade. Agarrou-se à promessa de {link:athrikus-narassin}Athrikus Narassin{/link}, e agora vagueia pelas ruínas como espíritos amaldiçoados e lamentosos, ainda carregando as ferramentas mágicas de seu antigo ofício. Duas grandes tabuletas entre as pedras contam a história da cidade e de sua queda. Uma antiga chama azul ainda arde aqui. É quente o bastante para destruir coisas que nenhum outro fogo consegue tocar.]=],
		},
	},
})

Translate("ptBR", "tower-of-althalaxx", {
	title = "Torre de Althalaxx",
	sections = {
		{
			title = "Resumo",
			text = [=[A Torre de Althalaxx ergue-se no nordeste da {link:darkshore}Costa Negra{/link}. Foi a sede de {link:athrikus-narassin}Athrikus Narassin{/link}, o lorde Bem-nascido que governava {link:ameth-aran}Ameth'Aran{/link} e {link:bashal-aran}Bashal'Aran{/link} para a {link:queen-azshara}Rainha Azshara{/link} e passava a maior parte de seus dias aqui, longe delas. Depois de dez mil anos, a torre tem de novo um senhor. Um grupo de bruxos que se chama {link:cult-of-the-dark-strand}Cult of the Dark Strand{/link} a tomou, e os mais fortes deles ficam nos aposentos superiores. Um vigia de {link:auberdine}Auberdine{/link}, {link:balthule-shadowstrike}Balthule Shadowstrike{/link}, mantém seu acampamento por perto. Ele viu clarões de luz no alto da torre, e ouviu gritos.]=],
		},
	},
})

Translate("ptBR", "grove-of-the-ancients", {
	title = "Bosque dos Ancientes",
	sections = {
		{
			title = "Resumo",
			text = [=[O Bosque dos Ancientes fica no sul da {link:darkshore}Costa Negra{/link}, abrigado pelas montanhas. Aqui habitam os Ancientes, grandes espíritos da floresta que estão ao lado dos elfos noturnos desde os dias mais antigos. {link:onu}Onu{/link}, um Anciente do Saber, reúne notícias de toda ameaça na terra, e os druidas de {link:auberdine}Auberdine{/link} dão ouvidos a seus avisos. A seu lado está {link:arbal}Arbal{/link}, um Anciente da Guerra. O bosque é paciente, como todos os Ancientes, mas não está ocioso. Daqui se planeja em silêncio a luta contra os nagas e o {link:twilight-s-hammer}Martelo do Crepúsculo{/link}.]=],
		},
	},
})

Translate("ptBR", "twilight-vale", {
	title = "Vale do Crepúsculo",
	sections = {
		{
			title = "Resumo",
			text = [=[Vale do Crepúsculo é o nome dado aos bosques do sul da {link:darkshore}Costa Negra{/link}, das ruínas de {link:ameth-aran}Ameth'Aran{/link} até as fronteiras do {link:ashenvale}Vale Gris{/link}. Suas estradas ligam {link:auberdine}Auberdine{/link} ao {link:maestra-s-post}Entreposto de Maestra{/link} e a {link:astranaar}Astranaar{/link}, e os mensageiros passam por elas por sua conta e risco. {link:blackwood-furbolgs}Pelursos Bosqueneros{/link} emboscam viajantes, espreitadores da lua rondam as árvores, e os ursos doentes da floresta atacam qualquer um que se aproxime. O {link:grove-of-the-ancients}Bosque dos Ancientes{/link}, {link:the-master-s-glaive}o Glaive do Mestre{/link} e a escavação da {link:explorers-league}Liga dos Exploradores{/link} ficam todos dentro do vale. Quem viaja por ele não sai da estrada.]=],
		},
	},
})

Translate("ptBR", "mist-s-edge", {
	title = "Beira das Névoas",
	sections = {
		{
			title = "Resumo",
			text = [=[A Beira das Névoas é a longa água cinzenta ao longo da costa da {link:darkshore}Costa Negra{/link}, onde o {link:cliffspring-river}Rio Fontescarpa{/link} deságua no mar. Suas praias estão cobertas de carcaças de grandes criaturas marinhas e de destroços de navios. Dois desses navios, o Silver Dawning e o Mist Veil, jazem no fundo ao norte de {link:auberdine}Auberdine{/link}, afundados por murlocs quando entravam no porto. Caranguejos correm por toda a extensão de areia. Os murlocs Greymist erguem suas cabanas ao longo da praia, e seus chefes caçam tanto pescadores quanto {link:sentinels}Sentinelas{/link}.]=],
		},
	},
})

Translate("ptBR", "cliffspring-river", {
	title = "Rio Fontescarpa",
	sections = {
		{
			title = "Resumo",
			text = [=[O Rio Fontescarpa desce das montanhas do leste e corre até o mar ao norte de {link:auberdine}Auberdine{/link}. Uma ponte o atravessa acima de sua primeira cachoeira. Sua água já foi limpa. Agora está ficando imunda, e o ancião de Auberdine teme que a mácula chegue à própria cidade. Os acampamentos do norte dos pelursos {link:blackwood-furbolgs}Bosqueneros{/link} ficam ao longo de suas margens, e suas fogueiras ardem junto à água. {link:thundris-windweaver}Thundris Windweaver{/link} acredita que os pelursos sujam o rio, mas que a verdadeira raiz do veneno está mais a leste, na {link:felwood}Selva Maleva{/link}.]=],
		},
	},
})

Translate("ptBR", "cliffspring-falls", {
	title = "Quedas de Fontescarpa",
	sections = {
		{
			title = "Resumo",
			text = [=[As Quedas de Fontescarpa despencam das montanhas a leste de {link:auberdine}Auberdine{/link}. A maior parte da região bebe delas, e agora um veneno corre em suas águas e adoece os cervos da {link:darkshore}Costa Negra{/link}. Atrás das quedas fica uma caverna onde crescem cogumelos raros. Os Ancientes avisaram o povo de Auberdine para se manter longe dela, pois sentiram que um novo mal fizera ali o seu lar. Tinham razão. Os nagas tomaram a caverna, e um lorde {link:naga}naga{/link} chamado {link:lord-sinslayer}Sinslayer{/link} os lidera.]=],
		},
	},
})

Translate("ptBR", "blackwood-den", {
	title = "Antro dos Bosqueneros",
	sections = {
		{
			title = "Resumo",
			text = [=[O Antro dos Bosqueneros fica no extremo sul da {link:darkshore}Costa Negra{/link}, perto da fronteira do {link:ashenvale}Vale Gris{/link}. É um aglomerado de acampamentos de pelursos em torno de uma pequena caverna, e pertence à {link:blackwood-furbolgs}tribo Bosquenera{/link}. Um {link:night-elves}elfo noturno{/link} chamado {link:volcor}Volcor{/link} foi ferido aqui pelos pelursos e refugiou-se no fundo da caverna. Seu fiel companheiro, {link:grimclaw}Grimclaw{/link}, foi sozinho para o norte buscar ajuda. O antro é um sinal sombrio de quão baixo os pelursos caíram. Eles já viveram em paz com os elfos. Agora atacam qualquer elfo que se aproxime de suas fogueiras.]=],
		},
	},
})

Translate("ptBR", "remtravel-s-excavation", {
	title = "Escavação de Trilheiro",
	aliases = { "a escavação de Remtravel" },
	sections = {
		{
			title = "Resumo",
			text = [=[A Escavação de Trilheiro é a escavação da {link:explorers-league}Liga dos Exploradores{/link} no sudoeste da {link:darkshore}Costa Negra{/link}. Aqui o {link:prospector-remtravel}Prospector Remtravel{/link} e sua equipe descobriram sinais de uma grande e antiga sociedade. Então a própria terra se voltou contra eles. Golens de pedra se ergueram do chão e tomaram o local, e os {link:troggs}troggs{/link} Gravelflint vieram com eles. A equipe fugiu para {link:auberdine}Auberdine{/link}. O prospector não. Ele ainda está em algum lugar da escavação, procurando um misterioso fóssil que já perdeu uma vez. O que a Liga fará com o fóssil, ninguém em Auberdine sabe dizer.]=],
		},
	},
})

Translate("ptBR", "the-master-s-glaive", {
	title = "Glaive do Mestre",
	aliases = { "o Glaive do Mestre" },
	sections = {
		{
			title = "Resumo",
			text = [=[O Glaive do Mestre ergue-se no sul da {link:darkshore}Costa Negra{/link}: uma lâmina enorme cravada no crânio de um gigante caído. {link:onu}Onu{/link} ensina que um dos antigos senhores da terra morreu aqui em eras passadas, empalado pelo glaive. O senhor está morto há muito, mas lascas de seu poder podem restar em seus ossos. O {link:twilight-s-hammer}Martelo do Crepúsculo{/link} veio procurá-las. Seus cultistas acampam sob a lâmina, e seus livros guardam páginas de antiga magia élfica distorcida para chamar seus antigos senhores de volta ao mundo.]=],
		},
	},
})

Translate("ptBR", "thundris-windweaver", {
	title = "Thundris Windweaver",
	subtitle = "Ancião de Auberdine",
	found = "Auberdine, no andar de cima da prefeitura",
	hint = [=[Procure o ancião que governa os assuntos diários de Auberdine.]=],
	allegiance = "Auberdine · Elfos noturnos",
	aliases = { "Thundris" },
	sections = {
		{
			title = "Resumo",
			text = [=[Thundris Windweaver é o ancião de {link:auberdine}Auberdine{/link}. Conduz os assuntos do dia a dia da cidade com mão justa e firme. É também o mais atento estudioso da corrupção da cidade. Já viu esta doença antes, em tempos muito passados, e sabe que ela não para nas fronteiras de uma floresta.]=],
		},
		{
			title = "Importância",
			text = [=[Thundris vê a forma inteira dos problemas da {link:darkshore}Costa Negra{/link}. A fúria dos pelursos, o rio imundo e as ferramentas dos antigos Bem-nascidos são, para ele, partes de uma só guerra. Ele também quer que {link:auberdine}Auberdine{/link} seja conhecida. As grandes cidades lembram apenas o que a {link:great-sundering}Grande Cisão{/link} tirou dos elfos noturnos. Ele quer que lembrem a cidade que ainda está de pé.]=],
		},
		{
			title = "Feitos",
			text = [=[• Seguiu o envenenamento do {link:cliffspring-river}Rio Fontescarpa{/link} até {link:stranglethorn-vale}a Selva{/link} Maleva.
• Descobriu que os sátiros corrompem os pelursos {link:blackwood-furbolgs}Bosqueneros{/link} por meio de talismãs.
• Manda reunir e destruir as relíquias mágicas dos Bem-nascidos de {link:ameth-aran}Ameth'Aran{/link}.
• Purifica gemas Kor tomadas dos nagas para aqueles que trilham um caminho sagrado.
• Escreveu a {link:stormwind-city}Ventobravo{/link} pedindo ajuda.]=],
		},
	},
	chapters = {
		{
			title = "Os Bosqueneros Corrompidos",
			hint = [=[Atraia para fora o sátiro que atormenta os pelursos do norte.]=],
			text = [=[Thundris misturou água do poço lunar com a própria comida dos pelursos e mandou colocá-la junto à fogueira deles. Os que comeram ficaram purificados por um momento. Nesse momento, o {link:satyrs}sátiro{/link} que os mantinha escravizados saiu para ver o que dera errado. Seu talismã foi levado a {link:auberdine}Auberdine{/link}. Thundris chamou isso de uma batalha vencida numa longa guerra.]=],
		},
		{
			title = "Ferramentas dos Bem-nascidos",
			hint = [=[Tome as relíquias dos antigos Bem-nascidos dos espíritos de Ameth'Aran.]=],
			text = [=[Os espíritos de {link:ameth-aran}Ameth'Aran{/link} ainda carregam os instrumentos de sua magia. Thundris desejaria que eles tivessem perecido no cataclismo que acabou com o mundo deles. Como não pereceram, ele mesmo os destruirá.]=],
		},
		{
			title = "Uma Carta Através do Mar",
			hint = [=[Leve a carta do ancião a Ventobravo e traga de volta a resposta.]=],
			text = [=[Thundris enviou uma carta a {link:baros-alexston}Baros Alexston{/link}, de {link:stormwind-city}Ventobravo{/link}, a bordo do novo navio. A resposta foi gentil, e foi vazia. Ventobravo não tinha nada de sobra. Thundris aceitou-a em silêncio. Se nem Ventobravo nem {link:darnassus}Darnassus{/link} vierem, disse ele, então {link:auberdine}Auberdine{/link} decidirá seu próprio destino.]=],
		},
	},
	mentions = {
		{
			text = [=[Thundris Windweaver, enviado por {link:terenthis}Terenthis{/link}]=],
		},
		{ text = "{link:bashal-aran}Bashal'Aran{/link}" },
		{ text = "O {link:cliffspring-river}Rio Fontescarpa{/link}" },
		{ text = "Em Busca da Gema Kor" },
		{ text = "Horizontes em Expansão" },
		{ text = "É Tudo Diversão e Brincadeira Até..., um olho de antigo mal" },
	},
	bonds = {
		{ id = "terenthis", name = "Terenthis", note = "envia-lhe notícias dos pelursos" },
		{ id = "asterion", name = "Asterion", note = "o espírito que ele mandou estranhos encontrar" },
		{ id = "baros-alexston", name = "Baros Alexston", note = "respondeu à sua carta" },
		{ id = "sentinel-glynda-nal-shea", name = "Sentinela Glynda Nal'Shea", note = "mantém a paz de sua cidade" },
	},
})

Translate("ptBR", "terenthis", {
	title = "Terenthis",
	subtitle = "Vigia dos Bosqueneros",
	found = "Auberdine, perto do posto das Sentinelas",
	hint = [=[Fale com o elfo noturno de Auberdine que caça os sinais da corrupção.]=],
	allegiance = "Auberdine · Elfos noturnos",
	sections = {
		{
			title = "Resumo",
			text = [=[Terenthis é um {link:night-elves}elfo noturno{/link} de {link:auberdine}Auberdine{/link} que jurou encontrar a corrupção em sua origem. Alguns de seus parentes foram salvos de um {link:furbolgs}pelurso{/link} corrompido em {link:teldrassil}Teldrassil{/link}. Desde aquele dia, ele jurou que nenhum outro de seu povo sofreria do mesmo modo, e vigia de perto os pelursos da {link:darkshore}Costa Negra{/link}.]=],
		},
		{
			title = "Importância",
			text = [=[Terenthis foi um dos primeiros a mostrar o quanto o perigo se aproximara. Seus batedores encontraram os acampamentos {link:blackwood-furbolgs}Bosqueneros{/link} corrompidos à vista de {link:auberdine}Auberdine{/link}. Ele é também amigo dos que vivem sozinhos nos ermos, e um amigo em apuros o encontra pronto.]=],
		},
		{
			title = "Feitos",
			text = [=[• Enviou batedores para encontrar um acampamento de pelursos corrompidos, e combatentes para rarear suas fileiras.
• Confeccionou um manto encantado de peles de espreitador da lua que permitia a quem o vestisse andar sem ser visto pelas feras da {link:darkshore}Costa Negra{/link}.
• Trouxe {link:volcor}Volcor{/link} para casa do {link:blackwood-den}Antro dos Bosqueneros{/link}.
• Envia suas descobertas ao ancião, {link:thundris-windweaver}Thundris Windweaver{/link}.]=],
		},
	},
	chapters = {
		{
			title = "Quão Grande É a Ameaça?",
			hint = [=[Encontre um acampamento de pelursos corrompidos perto de Auberdine.]=],
			text = [=[O acampamento ao sul de {link:auberdine}Auberdine{/link} era pior do que Terenthis temera. Os {link:blackwood-furbolgs}Bosqueneros{/link} estavam corrompidos, e estavam perto. Ele disse a Auberdine que se preparasse para o que estava por vir. Disse também aos que tinham lutado ali que não se lamentassem. Tinham diminuído a ameaça, ainda que o musgo vil continuasse a envenenar a terra.]=],
		},
		{
			title = "Um Mestre Perdido",
			hint = "Atenda ao chamado da fera que veio sozinha a Auberdine.",
			text = [=[{link:grimclaw}Grimclaw{/link} chegou a {link:auberdine}Auberdine{/link} sem seu mestre. Terenthis entendeu de imediato. {link:volcor}Volcor{/link} estava ferido, em algum lugar ao sul, entre os pelursos. Ele costurou um manto que esconderia seu portador das feras, e avisou que sua magia falharia se quem o vestisse fizesse mais do que falar.]=],
		},
	},
	mentions = {
		{ text = "Um Mestre Perdido" },
		{ text = "Fuga pela Força" },
		{ text = "Fuga pela Furtividade" },
		{ text = "{link:thundris-windweaver}Thundris Windweaver{/link}" },
		{
			text = [=[Jornada ao {link:ashenvale}Vale Gris{/link}, um chamado da Sentinela Selarin]=],
		},
	},
	bonds = {
		{ id = "volcor", name = "Volcor", note = "seu amigo" },
		{ id = "grimclaw", name = "Grimclaw", note = "o companheiro de Volcor" },
		{ id = "thundris-windweaver", name = "Thundris Windweaver", note = "o ancião a quem ele se reporta" },
		{ id = "blackwood-furbolgs", name = "Pelursos Bosqueneros", note = "a corrupção que ele vigia" },
	},
})

Translate("ptBR", "onu", {
	title = "Onu",
	subtitle = "Anciente do Saber",
	found = "O Bosque dos Ancientes, no sul da Costa Negra",
	hint = [=[Procure o Anciente do Saber no bosque perto das montanhas do sul.]=],
	allegiance = "Os Ancientes · Bosque dos Ancientes",
	sections = {
		{
			title = "Resumo",
			text = [=[Onu é um Anciente do Saber, um dos grandes espíritos da floresta, e guarda o {link:grove-of-the-ancients}Bosque dos Ancientes{/link} no sul da {link:darkshore}Costa Negra{/link}. Fala devagar e com longas pausas, e não se apressa. Sabe que todas as coisas acontecem em seu devido tempo.]=],
		},
		{
			title = "Importância",
			text = [=[Onu é a memória da {link:darkshore}Costa Negra{/link}. Sabe o que os cultistas do {link:twilight-s-hammer}Martelo do Crepúsculo{/link} adoram, e sabe onde caiu um de seus antigos senhores. Os druidas e estudiosos de {link:auberdine}Auberdine{/link} levam a ele suas perguntas mais graves, e o Arquidruida {link:fandral-staghelm}Fandral Staghelm{/link} lhe envia mensagens de {link:darnassus}Darnassus{/link}.]=],
		},
		{
			title = "Feitos",
			text = [=[• Enviou vigias ao {link:the-master-s-glaive}Glaive do Mestre{/link} e soube que o {link:twilight-s-hammer}Martelo do Crepúsculo{/link} estava lá.
• Estudou uma página arrancada do tomo do culto e sentiu nela a magia dos antigos.
• Reuniu relíquias de {link:ruins-of-mathystra}Mathistra{/link} para aprender como o culto usa a magia élfica.
• Fala de {link:malfurion-stormrage}Shan'do Stormrage{/link} como alguém que compreendia a paciência da floresta.]=],
		},
	},
	chapters = {
		{
			title = "O Glaive do Mestre",
			hint = "Vá ao Glaive do Mestre a pedido do Anciente.",
			text = [=[Onu achou estranho que os nagas tivessem vindo à {link:darkshore}Costa Negra{/link}. Achou mais estranho ainda que o {link:twilight-s-hammer}Martelo do Crepúsculo{/link} tivesse vindo. Quando seus temores se confirmaram, falou do antigo senhor empalado no Glaive. Esse senhor está morto. Seu poder, talvez, não esteja.]=],
		},
		{
			title = "Páginas dos Antigos",
			hint = "Traga ao Anciente o que foi tomado do acampamento do culto.",
			text = [=[Os rabiscos arrancados do Tomo do Crepúsculo continham uma magia caótica, e por baixo dela havia a escrita dos elfos. O culto estava usando antiga feitiçaria élfica para trazer seus antigos senhores de volta ao mundo. Onu pôs-se a descobrir como, antes que seus inimigos pudessem terminar o que tinham começado.]=],
		},
		{
			title = "A Escadaria sob Mathistra",
			hint = "Traga ao Anciente o que restou do guardião de Mathistra.",
			text = [=[Quando o globo de água turva foi posto diante dele, Onu mostrou algo próximo da surpresa. Havia uma escadaria sob {link:ruins-of-mathystra}Mathistra{/link}, e um guardião a vigiava. Disse apenas que precisava falar com os outros Ancientes, e que era bom que a escadaria tivesse sido encontrada antes que os nagas ou o culto a encontrassem.]=],
		},
	},
	mentions = {
		{
			text = [=[Onu, convocado por {link:barithras-moonshade}Barithras Moonshade{/link}]=],
		},
		{ text = "O {link:twilight-base-camp}Acampamento do Crepúsculo{/link}" },
		{
			text = [=[{link:grove-of-the-ancients}Bosque dos Ancientes{/link}, uma mensagem de {link:fandral-staghelm}Fandral Staghelm{/link}]=],
		},
	},
	bonds = {
		{ id = "arbal", name = "Arbal", note = "está com ele no bosque" },
		{ id = "barithras-moonshade", name = "Barithras Moonshade", note = "dá ouvidos a seus avisos" },
		{ id = "fandral-staghelm", name = "Fandral Staghelm", note = "envia-lhe notícias" },
		{ id = "baron-marinous", name = "Barão Marinous", note = "o guardião de Mathistra" },
	},
})

Translate("ptBR", "sentinel-glynda-nal-shea", {
	title = "Sentinela Glynda Nal'Shea",
	subtitle = "Sentinela de Auberdine",
	found = "Auberdine",
	hint = "Fale com a Sentinela que paga as recompensas de Auberdine.",
	allegiance = "Sentinelas · Auberdine",
	aliases = { "Glynda Nal'Shea" },
	sections = {
		{
			title = "Resumo",
			text = [=[A Sentinela Glynda Nal'Shea zela pela segurança de {link:auberdine}Auberdine{/link}, e tem uma visão dura dessa tarefa. Onde outros ainda reverenciam os luniscos, ela vê apenas seu número crescente e sua raiva. Paga as recompensas anunciadas pelo conselho da vila, e quer respostas sobre o cristal vermelho nas colinas do leste.]=],
		},
		{
			title = "Feitos",
			text = [=[• Mandou encontrar o cristal vermelho e testá-lo com água do poço lunar. Ele guardava ossos e metade de uma mandíbula.
• Pagou a recompensa pelo {link:murlocs}murloc{/link} {link:murkdeep}Murkdeep{/link}.
• Pagou a recompensa pela coruja negra {link:jai-vhanel}Jai'vhanel{/link}, e lamentou que não se tivesse encontrado outro caminho.]=],
		},
	},
	mentions = {
		{ text = "O Cristal Vermelho" },
		{ text = "Como Cascatas de Água" },
		{ text = "Os Fragmentos Interiores" },
		{ text = "PROCURADO: {link:murkdeep}Murkdeep{/link}!" },
		{ text = "PROCURADO: {link:jai-vhanel}Jai'vhanel{/link}" },
	},
	bonds = {
		{ id = "murkdeep", name = "Murkdeep", note = "o murloc que ela queria morto" },
		{ id = "jai-vhanel", name = "Jai'vhanel", note = "um guardião que enlouqueceu" },
	},
})

Translate("ptBR", "tharnariun-treetender", {
	title = "Tharnariun Treetender",
	subtitle = "Curandeiro das Feras",
	found = "Auberdine",
	hint = [=[Fale com o elfo noturno que busca uma cura para os ursos doentes da floresta.]=],
	allegiance = "Auberdine · Elfos noturnos",
	aliases = { "Tharnariun" },
	sections = {
		{
			title = "Resumo",
			text = [=[Tharnariun Treetender tentou curar a praga que domina os ursos-cardo da {link:darkshore}Costa Negra{/link}. As feras, outrora nobres, ficaram raivosas. Ele construiu uma armadilha de luz para acalmá-las, esperando curar uma delas. A cura falhou. Agora precisa ordenar a morte das criaturas que queria salvar, e isso o entristece.]=],
		},
		{
			title = "Feitos",
			text = [=[• Testou uma cura num urso raivoso capturado.
• Ordenou que os ursos doentes fossem rareados para retardar a praga.
• Ordenou a morte da Mãe da Toca, numa caverna perto de {link:bashal-aran}Bashal'Aran{/link}.
• Advertiu que muitos elfos fugiriam para terras mais seguras da {link:alliance}Aliança{/link} em vez de enfrentar a vida em seu novo lar.]=],
		},
	},
	mentions = {
		{ text = "Terras Empestadas" },
		{ text = "A Purificação dos Infectados" },
		{ text = "A Esperança de Tharnariun" },
	},
	bonds = {
		{ id = "alanndarian-nightsong", name = "Alanndarian Nightsong", note = "cuida dos cervos doentes" },
	},
})

Translate("ptBR", "gwennyth-bly-leggonde", {
	title = "Gwennyth Bly'Leggonde",
	subtitle = "Enviada do Templo da Lua",
	found = "Auberdine, perto do ninho dos hipogrifos",
	hint = "Fale com a enviada do Templo da Lua em Auberdine.",
	allegiance = "Templo da Lua",
	aliases = { "Gwennyth" },
	sections = {
		{
			title = "Resumo",
			text = [=[Gwennyth Bly'Leggonde foi enviada pelo {link:temple-of-the-moon}Templo da Lua{/link} para descobrir por que grandes criaturas marinhas se lançam nas praias da {link:darkshore}Costa Negra{/link}. Seu estudo dos ossos delas a levou a uma resposta mais sombria do que esperava. Os nagas vinham capturando as feras do mar como montarias e animais de carga, e expulsando as que não podiam usar.]=],
		},
		{
			title = "Feitos",
			text = [=[• Reuniu ossos de criaturas encalhadas ao longo da costa e os enviou a {link:darnassus}Darnassus{/link}.
• Temeu que as criaturas estivessem fugindo das águas perto de {link:teldrassil}Teldrassil{/link}.
• Procurou o cetro que os nagas usam para comandar as feras do mar, e mandou destruí-lo.]=],
		},
	},
	mentions = {
		{ text = "Levado à Praia" },
		{ text = "Levado à Praia" },
		{ text = "Mergulho Sagrado" },
	},
	bonds = {
		{ id = "ruins-of-mathystra", name = "Ruínas de Mathistra", note = "onde os nagas mantêm as feras" },
	},
})

Translate("ptBR", "archaeologist-hollee", {
	title = "Arqueóloga Hollee",
	subtitle = "Arqueóloga da Liga dos Exploradores",
	found = "Auberdine",
	hint = [=[Encontre a arqueóloga que fugiu da escavação do sul de volta a Auberdine.]=],
	allegiance = "Liga dos Exploradores",
	aliases = { "Hollee" },
	sections = {
		{
			title = "Resumo",
			text = [=[Hollee é uma anã da {link:explorers-league}Liga dos Exploradores{/link}. Foi uma honra, diz ela, ser posta sob as ordens do grande {link:prospector-remtravel}Prospector Remtravel{/link}. Foi uma honra menor ver golens se erguerem do chão na escavação enquanto o prospector continuava a escovar pedras. Ela correu até {link:auberdine}Auberdine{/link} em busca de ajuda. Não se esqueceu de um colega dos tempos de estudante, agora no {link:wetlands}Pantanal{/link}.]=],
		},
		{
			title = "Feitos",
			text = [=[• Fugiu dos golens da {link:remtravel-s-excavation}Escavação de Trilheiro{/link} para buscar ajuda.
• Enviou o fóssil do prospector adiante, à Liga.
• Escreveu um bilhete a seu velho amigo {link:tarrel-rockweaver}Tarrel Rockweaver{/link}, perto do {link:menethil-harbor}Porto de Menethil{/link}.]=],
		},
	},
	mentions = {
		{ text = "Problemas na {link:darkshore}Costa Negra{/link}?" },
		{ text = "O Prospector Distraído" },
		{ text = "O Prospector Distraído" },
		{ text = "Amor Não Correspondido" },
	},
	bonds = {
		{ id = "prospector-remtravel", name = "Prospector Remtravel", note = "seu mestre" },
	},
})

Translate("ptBR", "prospector-remtravel", {
	title = "Prospector Remtravel",
	subtitle = "O Prospector Distraído",
	found = "Escavação de Trilheiro",
	hint = [=[Procure o prospector que nunca deixou sua escavação no sudoeste.]=],
	allegiance = "Liga dos Exploradores",
	aliases = { "Remtravel" },
	sections = {
		{
			title = "Resumo",
			text = [=[O Prospector Remtravel é famoso na academia de {link:ironforge}Altaforja{/link} por suas descobertas. É igualmente famoso por não notar nada à sua volta. Sua escavação no sul da {link:darkshore}Costa Negra{/link} foi tomada por golens e troggs. Ele ficou em seu trabalho mesmo assim, chamando por sua assistente e por sua escova de pedra.]=],
		},
		{
			title = "Feitos",
			text = [=[• Descobriu indícios de uma grande sociedade antiga na {link:darkshore}Costa Negra{/link}.
• Encontrou um fóssil misterioso, perdeu-o e encontrou-o de novo.
• Seu fóssil seguiu para {link:darnassus}Darnassus{/link}, e depois para um arqueólogo no {link:menethil-harbor}Porto de Menethil{/link}.]=],
		},
	},
	mentions = {
		{ text = "O Prospector Distraído" },
		{ text = "O Prospector Distraído, levado a Menethil" },
	},
	bonds = {
		{ id = "archaeologist-hollee", name = "Arqueóloga Hollee", note = "sua assistente" },
	},
})

Translate("ptBR", "delgren-the-purifier", {
	title = "Delgren, o Purificador",
	subtitle = "Paladino do Entreposto de Maestra",
	found = "Entreposto de Maestra, no norte do Vale Gris",
	hint = [=[Procure o paladino que guarda as florestas ao lado dos elfos noturnos, ao sul da Costa Negra.]=],
	allegiance = "Luz Sagrada",
	aliases = { "Delgren" },
	sections = {
		{
			title = "Resumo",
			text = [=[Delgren, o Purificador, é um paladino da {link:holy-light}Luz Sagrada{/link} que ofereceu sua espada aos elfos noturnos contra demônios e mortos-vivos. A princípio, os costumes deles lhe eram estranhos. Agora ele os honra como aliados. Aprendeu a língua dos orcs, contra o desprezo de sua ordem, para poder ler as palavras de seus inimigos.]=],
		},
		{
			title = "Feitos",
			text = [=[• Ensinou a {link:balthule-shadowstrike}Balthule Shadowstrike{/link} a Luz e a arte da batalha.
• Quebrou uma gema de alma do {link:cult-of-the-dark-strand}Cult of the Dark Strand{/link} e libertou o espírito que havia nela.
• Leu o tomo do bruxo {link:orcs}orc{/link} {link:ilkrud-magthrull}Ilkrud Magthrull{/link}, e descobriu onde {link:athrikus-narassin}Athrikus{/link} escondia suas últimas gemas de alma.
• Envia suprimentos às {link:sentinels}Sentinelas{/link} de {link:auberdine}Auberdine{/link}.]=],
		},
	},
	mentions = {
		{ text = "A {link:tower-of-althalaxx}Torre de Althalaxx{/link}" },
		{ text = "A {link:tower-of-althalaxx}Torre de Althalaxx{/link}" },
		{ text = "A {link:tower-of-althalaxx}Torre de Althalaxx{/link}" },
		{ text = "A {link:tower-of-althalaxx}Torre de Althalaxx{/link}" },
		{ text = "Suprimentos para {link:auberdine}Auberdine{/link}" },
	},
	bonds = {
		{ id = "balthule-shadowstrike", name = "Balthule Shadowstrike", note = "seu aluno" },
		{ id = "athrikus-narassin", name = "Athrikus Narassin", note = "inimigo" },
	},
})

Translate("ptBR", "balthule-shadowstrike", {
	title = "Balthule Shadowstrike",
	subtitle = "Vigia da Torre",
	found = "Um acampamento escondido perto da Torre de Althalaxx",
	hint = [=[Encontre o vigia que não tira os olhos da Torre de Althalaxx.]=],
	allegiance = "Auberdine · Sentinelas",
	aliases = { "Balthule" },
	sections = {
		{
			title = "Resumo",
			text = [=[Balthule Shadowstrike foi enviado pela {link:sentinel-elissa-starbreeze}Sentinela Elissa Starbreeze{/link} para vigiar a {link:tower-of-althalaxx}Torre de Althalaxx{/link}. Ficou tempo demais, pois temia perder alguma coisa se fosse embora. De restos do pergaminho dos bruxos, descobriu o nome de sua ordem: o {link:cult-of-the-dark-strand}Cult of the Dark Strand{/link}. Estuda a {link:holy-light}Luz Sagrada{/link} com {link:delgren-the-purifier}Delgren, o Purificador{/link}.]=],
		},
		{
			title = "Feitos",
			text = [=[• Juntou as peças dos escritos dos bruxos.
• Viu um clarão ofuscante e ouviu gritos no alto da torre.
• Pediu a cabeça de {link:athrikus-narassin}Athrikus Narassin{/link}.]=],
		},
	},
	mentions = {
		{ text = "A {link:tower-of-althalaxx}Torre de Althalaxx{/link}" },
		{ text = "A {link:tower-of-althalaxx}Torre de Althalaxx{/link}" },
		{ text = "A {link:tower-of-althalaxx}Torre de Althalaxx{/link}" },
		{ text = "A {link:tower-of-althalaxx}Torre de Althalaxx{/link}" },
	},
	bonds = {
		{ id = "delgren-the-purifier", name = "Delgren, o Purificador", note = "seu mestre" },
		{ id = "sentinel-elissa-starbreeze", name = "Sentinela Elissa Starbreeze", note = "enviou-o" },
		{ id = "cult-of-the-dark-strand", name = "Cult of the Dark Strand", note = "o culto que ele vigia" },
	},
})

Translate("ptBR", "sentinel-elissa-starbreeze", {
	title = "Sentinela Elissa Starbreeze",
	subtitle = "Protetora de Auberdine",
	found = "Auberdine",
	hint = "Fale com a Sentinela encarregada da proteção de Auberdine.",
	allegiance = "Sentinelas · Auberdine",
	aliases = { "Elissa Starbreeze" },
	sections = {
		{
			title = "Resumo",
			text = [=[A Sentinela Elissa Starbreeze está encarregada da proteção de {link:auberdine}Auberdine{/link}. Quando coisas estranhas começaram a acontecer em torno da {link:tower-of-althalaxx}Torre de Althalaxx{/link}, ela enviou {link:balthule-shadowstrike}Balthule Shadowstrike{/link} para vigiá-la. Ele não voltou quando devia. Ela sabe que todo perigo da {link:darkshore}Costa Negra{/link} pode um dia chegar à sua cidade, e quer ser avisada antes que isso aconteça.]=],
		},
		{
			title = "Feitos",
			text = [=[• Enviou {link:balthule-shadowstrike}Balthule{/link} para observar a {link:tower-of-althalaxx}Torre de Althalaxx{/link}.
• Recebe suprimentos e mensagens enviados do {link:maestra-s-post}Entreposto de Maestra{/link} por {link:delgren-the-purifier}Delgren, o Purificador{/link}.]=],
		},
	},
	mentions = {
		{ text = "A {link:tower-of-althalaxx}Torre de Althalaxx{/link}" },
		{ text = "Suprimentos para {link:auberdine}Auberdine{/link}" },
	},
	bonds = {
		{ id = "balthule-shadowstrike", name = "Balthule Shadowstrike", note = "seu batedor" },
		{ id = "delgren-the-purifier", name = "Delgren, o Purificador", note = "envia-lhe suprimentos" },
	},
})

Translate("ptBR", "athrikus-narassin", {
	title = "Athrikus Narassin",
	subtitle = "Senhor do Dark Strand",
	found = "O alto da Torre de Althalaxx",
	hint = [=[Enfrente o antigo bruxo que espera no alto da Torre de Althalaxx.]=],
	allegiance = "Cult of the Dark Strand · outrora os Bem-nascidos",
	aliases = { "Athrikus" },
	sections = {
		{
			title = "Resumo",
			text = [=[Athrikus Narassin era um lorde Bem-nascido e um servo favorito da {link:queen-azshara}Rainha Azshara{/link}. Ela lhe deu as cidades gêmeas de {link:ameth-aran}Ameth'Aran{/link} e {link:bashal-aran}Bashal'Aran{/link} para governar, embora ele ficasse em sua torre. Quando o mundo se partiu, ele prometeu ao povo de Ameth'Aran a vida eterna por meio de um feitiço. Seus espíritos ainda permanecem nas ruínas. Ele também prendeu seu próprio imediato, {link:asterion}Asterion{/link}, numa prisão de pedra e magia. Athrikus vive, e lidera o {link:cult-of-the-dark-strand}Cult of the Dark Strand{/link}.]=],
		},
		{
			title = "Feitos",
			text = [=[• Governou as cidades gêmeas para {link:azshara}Azshara{/link}.
• Prendeu almas de Bem-nascidos em gemas de alma, e tirou delas o seu poder.
• Reuniu um grupo de bruxos em sua antiga torre.]=],
		},
	},
	mentions = {
		{ text = "A {link:tower-of-althalaxx}Torre de Althalaxx{/link}" },
		{ text = "A {link:tower-of-althalaxx}Torre de Althalaxx{/link}" },
	},
	bonds = {
		{ id = "asterion", name = "Asterion", note = "o servo que ele aprisionou" },
		{ id = "balthule-shadowstrike", name = "Balthule Shadowstrike", note = "inimigo" },
	},
})

Translate("ptBR", "asterion", {
	title = "Asterion",
	subtitle = "O Prisioneiro de Bashal'Aran",
	found = "Um santuário num penhasco no oeste de Bashal'Aran",
	hint = "Procure a origem da luz azul nas ruínas de Bashal'Aran.",
	allegiance = "outrora os Bem-nascidos",
	sections = {
		{
			title = "Resumo",
			text = [=[Asterion era um mago Bem-nascido, inferior apenas a {link:athrikus-narassin}Athrikus Narassin{/link} nas cidades gêmeas, e famoso tanto pela força do braço quanto pela dos feitiços. Quando andou livre pela última vez, o {link:well-of-eternity}Poço da Eternidade{/link} ainda existia. Seu senhor o selou num santuário em {link:bashal-aran}Bashal'Aran{/link} com um Ancient Moonstone Seal, e por mais de mil anos ele fitou os pilares do lugar. Sua língua é afiada. Ele teme que sua longa solidão tenha partido sua mente.]=],
		},
	},
	chapters = {
		{
			title = "O Selo Destruído",
			hint = "Liberte o espírito preso no santuário de Bashal'Aran.",
			text = [=[O selo foi tomado dos sátiros e destruído na chama azul de {link:ameth-aran}Ameth'Aran{/link}. Asterion estava livre. Sentiu que seu antigo senhor ainda vivia, e seu desespero voltou-se para a vingança.]=],
		},
	},
	mentions = {
		{ text = "{link:bashal-aran}Bashal'Aran{/link}" },
		{ text = "{link:bashal-aran}Bashal'Aran{/link}" },
	},
	bonds = {
		{ id = "athrikus-narassin", name = "Athrikus Narassin", note = "seu antigo senhor e carcereiro" },
	},
})

Translate("ptBR", "anaya-dawnrunner", {
	title = "Anaya Dawnrunner",
	subtitle = "A Assombrada de Ameth'Aran",
	found = "As ruínas de Ameth'Aran",
	hint = [=[Enfrente o espírito inquieto que assombra as ruínas de Ameth'Aran.]=],
	allegiance = "outrora o povo de Ameth'Aran",
	aliases = { "Anaya" },
	sections = {
		{
			title = "Resumo",
			text = [=[Anaya Dawnrunner vivia em {link:ameth-aran}Ameth'Aran{/link} quando a guerra no {link:well-of-eternity}Poço da Eternidade{/link} partiu o mundo. Era a amada de {link:cerellean-whiteclaw}Cerellean Whiteclaw{/link}. Quando a cidade caiu, ele a julgou morta. Dez mil anos depois, encontrou o espírito dela vagando pelas ruínas, preso ali como os outros que confiaram na promessa de {link:athrikus-narassin}Athrikus{/link}.]=],
		},
		{
			title = "Importância",
			text = [=[Sua história é a tristeza de {link:ameth-aran}Ameth'Aran{/link} reduzida a um tamanho que se pode segurar. Seu espírito só podia ser libertado sendo destruído, e aquele que a amava não teve coragem de fazê-lo.]=],
		},
	},
	mentions = {
		{ text = "Por um Amor Eterno" },
	},
	bonds = {
		{ id = "cerellean-whiteclaw", name = "Cerellean Whiteclaw", note = "seu amado" },
	},
})

Translate("ptBR", "cerellean-whiteclaw", {
	title = "Cerellean Whiteclaw",
	subtitle = "Um Adormecido Despertado",
	found = "Auberdine",
	hint = [=[Fale com o elfo noturno enlutado de Auberdine que sonha com Ameth'Aran.]=],
	allegiance = "Auberdine · Elfos noturnos",
	aliases = { "Cerellean" },
	sections = {
		{
			title = "Resumo",
			text = [=[Cerellean Whiteclaw ouviu, depois das batalhas no {link:well-of-eternity}Poço da Eternidade{/link}, que {link:ameth-aran}Ameth'Aran{/link} fora destruída e sua amada {link:anaya-dawnrunner}Anaya{/link} com ela. Seguiu {link:malfurion-stormrage}Shan'do Stormrage{/link} no longo sono e levou sua tristeza para os sonhos. Agora está desperto, e a memória dela ainda o assombra. Vagando pelos bosques, encontrou o espírito dela nas ruínas.]=],
		},
	},
	chapters = {
		{
			title = "Por um Amor Eterno",
			hint = "Liberte o espírito de Anaya Dawnrunner.",
			text = [=[Cerellean sabia que o espírito dela precisava ser libertado, e sabia que não conseguiria fazê-lo. Quando o pingente dela lhe foi trazido de volta, perguntou-se se não deveria ter encontrado forças ele mesmo. Depois pediu que o deixassem sozinho.]=],
		},
	},
	bonds = {
		{ id = "anaya-dawnrunner", name = "Anaya Dawnrunner", note = "sua amada" },
	},
})

Translate("ptBR", "sentinel-tysha-moonblade", {
	title = "Sentinela Tysha Moonblade",
	subtitle = "Exploradora de Ameth'Aran",
	found = "A estrada a oeste de Ameth'Aran",
	hint = [=[Encontre a Sentinela que estuda as ruínas de Ameth'Aran a partir da estrada.]=],
	allegiance = "Sentinelas",
	aliases = { "Tysha Moonblade" },
	sections = {
		{
			title = "Resumo",
			text = [=[A Sentinela Tysha Moonblade foi enviada para explorar as ruínas de {link:ameth-aran}Ameth'Aran{/link}. Encontrou duas grandes tabuletas que contam a história da cidade e de sua queda. Os espíritos a expulsaram antes que ela pudesse terminar de lê-las. Seu povo tem poucos registros do tempo da {link:war-of-the-ancients}Guerra dos Antigos{/link}, e ela pretende levar um relatório completo ao Círculo dos Ancientes.]=],
		},
		{
			title = "Feitos",
			text = [=[• Encontrou as duas tabuletas de {link:ameth-aran}Ameth'Aran{/link}.
• Leva a história delas a {link:auberdine}Auberdine{/link}.]=],
		},
	},
	mentions = {
		{ text = "A Queda de {link:ameth-aran}Ameth'Aran{/link}" },
	},
	bonds = {
		{ id = "anaya-dawnrunner", name = "Anaya Dawnrunner", note = "assombra as ruínas que ela explora" },
	},
})

Translate("ptBR", "barithras-moonshade", {
	title = "Barithras Moonshade",
	subtitle = "Preparador de Poções de Auberdine",
	found = "Auberdine",
	hint = [=[Fale com o elfo noturno de Auberdine que precisa de cogumelos de uma caverna proibida.]=],
	allegiance = "Auberdine · Elfos noturnos",
	aliases = { "Barithras" },
	sections = {
		{
			title = "Resumo",
			text = [=[Barithras Moonshade está criando uma poção que exige cogumelos raros, e eles só crescem na caverna atrás das {link:cliffspring-falls}Quedas de Fontescarpa{/link}. Os Ancientes lhe disseram para se manter longe dela. Sentiram um novo mal escondido ali. Ele esperou, por uma vez, que estivessem errados. Não estavam.]=],
		},
		{
			title = "Feitos",
			text = [=[• Colheu cogumelos atrás das {link:cliffspring-falls}Quedas de Fontescarpa{/link}, e descobriu que a caverna escondia um novo mal.
• Envia a {link:onu}Onu{/link} notícias dos que viram as quedas.]=],
		},
	},
	mentions = {
		{ text = "Cogumelos da Caverna" },
		{ text = "{link:onu}Onu{/link}" },
	},
	bonds = {
		{ id = "onu", name = "Onu", note = "dá ouvidos a seus conselhos" },
		{ id = "lord-sinslayer", name = "Lorde Sinslayer", note = "o mal na caverna" },
	},
})

Translate("ptBR", "gershala-nightwhisper", {
	title = "Gershala Nightwhisper",
	subtitle = "Estudiosa da Corrupção",
	found = "Auberdine",
	hint = [=[Fale com a estudiosa de Auberdine que investiga como a magia deforma um povo.]=],
	allegiance = "Auberdine · Elfos noturnos",
	aliases = { "Gershala" },
	sections = {
		{
			title = "Resumo",
			text = [=[Gershala Nightwhisper estuda a deformação dos povos pela magia. Os nagas e os sátiros já foram elfos. Os elfos de {link:quel-thalas}Quel'Thalas{/link} que agora se chamam elfos sangrentos começaram a lidar com magia demoníaca, e Gershala teme que trilhem o mesmo caminho. {link:azeroth}Azeroth{/link}, em suas palavras, não pode suportar o nascimento de mais uma raça de monstros.]=],
		},
		{
			title = "Feitos",
			text = [=[• Estuda os restos corrompidos de sátiros e nagas das {link:blackfathom-deeps}Profundezas Negras{/link}.
• Seu irmão Argos busca ajuda para ela em {link:stormwind-city}Ventobravo{/link}.]=],
		},
	},
	mentions = {
		{ text = "A Corrupção Além-mar" },
		{ text = "Pesquisando a Corrupção" },
	},
	bonds = {
		{ id = "argos-nightwhisper", name = "Argos Nightwhisper", note = "seu irmão" },
	},
})

Translate("ptBR", "wizbang-cranktoggle", {
	title = "Wizbang Cranktoggle",
	subtitle = "Inventor da Buzzbox",
	found = "Auberdine",
	hint = [=[Encontre o inventor de Auberdine que fala com pessoas muito distantes.]=],
	allegiance = "Auberdine",
	aliases = { "Wizbang" },
	sections = {
		{
			title = "Resumo",
			text = [=[Wizbang Cranktoggle construiu uma máquina que faz uma voz viajar longe pela terra: a buzzbox. Espalhou suas caixas por toda a {link:darkshore}Costa Negra{/link}. Cada uma precisa de conserto constante, e cada uma fica, por projeto dele mesmo, ao lado das criaturas cujas partes podem consertá-la. Ele chama isso de uma decisão muito inteligente.]=],
		},
		{
			title = "Feitos",
			text = [=[• Instalou buzzboxes por toda a {link:darkshore}Costa Negra{/link} e fala através delas.
• Mexe com outros aparelhos, como gaffer jacks e electropellers.]=],
		},
	},
	mentions = {
		{ text = "Buzzbox 827" },
		{ text = "Gaffer Jacks" },
		{ text = "Electropellers" },
	},
	bonds = {
		{ id = "gubber-blump", name = "Gubber Blump", note = "um vizinho junto às docas" },
	},
})

Translate("ptBR", "gubber-blump", {
	title = "Gubber Blump",
	subtitle = "Pescador de Auberdine",
	found = "A praia de Auberdine, perto das docas",
	hint = [=[Encontre o anão que pesca na praia de Auberdine e adora falar de caranguejos.]=],
	allegiance = "A família Blump",
	aliases = { "Gubber" },
	sections = {
		{
			title = "Resumo",
			text = [=[Gubber Blump é um {link:dwarves}anão{/link} de uma família conhecida pela pesca, e ele pesca. Adora caranguejo e é capaz de citar todas as maneiras de prepará-lo. Costumava sair de barco atrás das garoupas da {link:darkshore}Costa Negra{/link}. Nenhum barco sai mais, não desde que os murlocs chegaram.]=],
		},
		{
			title = "Feitos",
			text = [=[• Ensina o ofício da pesca na praia.
• Troca uma vara de pescar da família Blump por uma boa pesca de garoupas.
• Fala com carinho de seu primo, Graun Blump.]=],
		},
	},
	mentions = {
		{ text = "Frutos do Mar" },
		{ text = "A Família e a Vara de Pescar" },
	},
	bonds = {
		{ id = "murkdeep", name = "Murkdeep", note = "os murlocs mantêm os barcos em terra" },
	},
})

Translate("ptBR", "volcor", {
	title = "Volcor",
	subtitle = "O Mestre Perdido",
	found = "Uma caverna no Antro dos Bosqueneros",
	hint = [=[Procure o elfo noturno ferido, escondido numa caverna de pelursos no extremo sul.]=],
	allegiance = "Elfos noturnos",
	sections = {
		{
			title = "Resumo",
			text = [=[Volcor é um {link:night-elves}elfo noturno{/link} que vive nos ermos da {link:darkshore}Costa Negra{/link} com seu companheiro {link:grimclaw}Grimclaw{/link}. Os pelursos {link:blackwood-furbolgs}Bosqueneros{/link} o feriram, e ele se escondeu nas profundezas do antro deles. Enviou Grimclaw para o norte, até seu amigo {link:terenthis}Terenthis{/link}, em busca de ajuda. Espera no escuro com seus ferimentos e sua paciência.]=],
		},
	},
	chapters = {
		{
			title = "Fora do Antro",
			hint = "Tire Volcor do Antro dos Bosqueneros.",
			text = [=[A ajuda chegou envolta num manto de espreitador da lua. Volcor estava rígido por causa dos ferimentos, mas deixou o antro com os próprios pés, pela espada ou pela furtividade. {link:grimclaw}Grimclaw{/link} o esperava na estrada.]=],
		},
	},
	mentions = {
		{ text = "Um Mestre Perdido" },
	},
	bonds = {
		{ id = "grimclaw", name = "Grimclaw", note = "seu companheiro" },
		{ id = "terenthis", name = "Terenthis", note = "seu amigo" },
	},
})

Translate("ptBR", "grimclaw", {
	title = "Grimclaw",
	subtitle = "Companheiro de Volcor",
	found = "Junto à estrada no sul da Costa Negra",
	hint = "Procure a fera fiel que espera junto à estrada do sul.",
	allegiance = "Volcor",
	sections = {
		{
			title = "Resumo",
			text = [=[Grimclaw é o companheiro de {link:volcor}Volcor{/link}. Quando seu mestre foi ferido entre os pelursos, Grimclaw correu sozinho até {link:auberdine}Auberdine{/link} e encontrou {link:terenthis}Terenthis{/link}. Agora espera junto à estrada do sul por aqueles que vêm ajudar. Um aceno basta para chamar sua atenção, e ele mostrará o caminho até seu mestre.]=],
		},
		{
			title = "Feitos",
			text = [=[• Levou a {link:auberdine}Auberdine{/link} a notícia da situação de {link:volcor}Volcor{/link}.
• Guia os salvadores em direção ao {link:blackwood-den}Antro dos Bosqueneros{/link}.]=],
		},
	},
	mentions = {
		{ text = "Um Mestre Perdido" },
	},
	bonds = {
		{ id = "volcor", name = "Volcor", note = "seu mestre" },
		{ id = "terenthis", name = "Terenthis", note = "o amigo até quem ele correu" },
	},
})

Translate("ptBR", "alanndarian-nightsong", {
	title = "Alanndarian Nightsong",
	subtitle = "Amiga das Feras",
	found = "Auberdine",
	hint = [=[Fale com a elfa noturna de Auberdine que cuida dos cervos doentes.]=],
	allegiance = "Auberdine · Círculo Cenariano",
	aliases = { "Alanndarian" },
	sections = {
		{
			title = "Resumo",
			text = [=[Alanndarian Nightsong chamou o {link:cenarion-circle}Círculo Cenariano{/link} da {link:moonglade}Clareira da Lua{/link} quando os cervos da {link:darkshore}Costa Negra{/link} começaram a adoecer. O veneno está na água, levado das {link:cliffspring-falls}Quedas de Fontescarpa{/link} a toda a terra. Ela fez um unguento curativo e curou as feras que pôde. Adverte que alguns em {link:darnassus}Darnassus{/link} se recusam a ver a corrupção que se espalha pela terra.]=],
		},
		{
			title = "Feitos",
			text = [=[• Preparou um unguento para os cervos com a água maculada, raiz-da-terra e fungo lunar.
• Cozinha um ensopado de passolargo de que se orgulha.]=],
		},
	},
	mentions = {
		{ text = "A Fonte Principal" },
		{ text = "Reunindo a Cura" },
		{ text = "Curando os Doentes" },
		{ text = "Vida Fácil de Passolargo" },
	},
	bonds = {
		{ id = "tharnariun-treetender", name = "Tharnariun Treetender", note = "cuida dos ursos doentes" },
	},
})

Translate("ptBR", "gorbold-steelhand", {
	title = "Gorbold Steelhand",
	subtitle = "Mercador de Auberdine",
	found = "Auberdine",
	hint = [=[Encontre o mercador anão de Auberdine cujo irmão espera em Ventobravo.]=],
	allegiance = "A família Steelhand",
	aliases = { "Gorbold" },
	sections = {
		{
			title = "Resumo",
			text = [=[Gorbold Steelhand veio a {link:auberdine}Auberdine{/link} para abastecer os navios que atracam ali. Parecia um bom negócio. Então os murlocs afundaram o Silver Dawning e o Mist Veil quando entravam no porto, e seus capitães afundaram com eles. Os negócios quase pararam. Gorbold quer que os cofres dos capitães sejam trazidos à tona, pelo bem das tripulações que restam.]=],
		},
		{
			title = "Feitos",
			text = [=[• Juntou-se a uma banca de mercador em {link:auberdine}Auberdine{/link} há algumas semanas.
• Procura os pertences dos capitães afogados.]=],
		},
	},
	mentions = {
		{ text = "Negócios em {link:auberdine}Auberdine{/link}" },
		{ text = "Oceano Profundo, Vasto Mar" },
	},
	bonds = {
		{ id = "borgus-steelhand", name = "Borgus Steelhand", note = "seu irmão em Ventobravo" },
	},
})

Translate("ptBR", "arbal", {
	title = "Arbal",
	subtitle = "Anciente da Guerra",
	found = "O Bosque dos Ancientes",
	hint = "Fale com o Anciente da Guerra que está no bosque do sul.",
	allegiance = "Os Ancientes · Bosque dos Ancientes",
	sections = {
		{
			title = "Resumo",
			text = [=[Arbal é um Anciente da Guerra que está ao lado de {link:onu}Onu{/link} no {link:grove-of-the-ancients}Bosque dos Ancientes{/link}. Onde Onu aconselha paciência, Arbal aconselha a guerra. Ele chama os nagas de Bem-nascidos amaldiçoados, caídos do que um dia foram. Eles agora saqueiam seu próprio antigo lar em {link:ruins-of-mathystra}Mathistra{/link} e podem estar ajudando o {link:twilight-s-hammer}Martelo do Crepúsculo{/link}. Arbal não os perdoa.]=],
		},
		{
			title = "Importância",
			text = [=[Os Ancientes da Guerra lutaram ao lado dos elfos noturnos nas grandes batalhas de sua história. Que um deles esteja agora na {link:darkshore}Costa Negra{/link} mostra a gravidade com que o bosque pesa o perigo no norte.]=],
		},
		{
			title = "Feitos",
			text = [=[• Envia combatentes contra os nagas Stormscale de {link:ruins-of-mathystra}Mathistra{/link}.]=],
		},
	},
	mentions = {
		{ text = "Forças Crescentes" },
	},
	bonds = {
		{ id = "onu", name = "Onu", note = "está com ele no bosque" },
	},
})

Translate("ptBR", "baron-marinous", {
	title = "Barão Marinous",
	subtitle = "Guardião de Mathistra",
	found = "As Ruínas de Mathistra",
	hint = [=[Enfrente o elemental que guarda um caminho oculto nas ruínas de Mathistra.]=],
	allegiance = "Desconhecida",
	sections = {
		{
			title = "Resumo",
			text = [=[{link:the-baron}O Barão{/link} Marinous é um elemental poderoso que guarda uma escadaria que desce sob as {link:ruins-of-mathystra}Ruínas de Mathistra{/link}. Quando ele é vencido, tudo o que resta é um globo de água, turvo por dentro por algo que não se deixa ver. O que ele guardava, e quem o pôs ali, ninguém sabe ainda.]=],
		},
		{
			title = "Sem Registro",
			text = [=[Nada está escrito sobre a quem o barão serve. {link:onu}Onu{/link} foi falar com os outros Ancientes.]=],
		},
		{
			title = "Importância",
			text = [=[A presença do barão prova que {link:ruins-of-mathystra}Mathistra{/link} esconde mais do que pedras partidas. Algo sob as ruínas foi considerado digno de guarda, e ainda está ativo de algum modo.]=],
		},
	},
	mentions = {
		{ text = "Barão Marinous" },
	},
	bonds = {
		{ id = "onu", name = "Onu", note = "estuda seus restos" },
	},
})

Translate("ptBR", "jai-vhanel", {
	title = "Jai'vhanel",
	subtitle = "A Coruja Negra",
	found = "Ao norte de Ameth'Aran, perto do sopé das montanhas",
	hint = "Enfrente a coruja negra que caça ao norte de Ameth'Aran.",
	allegiance = "Os ermos",
	aliases = { "Swordfeather" },
	sections = {
		{
			title = "Resumo",
			text = [=[Jai'vhanel, chamada Swordfeather, é uma grande coruja de penas negras como azeviche. Por muito tempo foi uma guardiã da terra em torno de {link:ameth-aran}Ameth'Aran{/link}. Depois enlouqueceu, e começou a atacar viajantes na estrada para {link:auberdine}Auberdine{/link}. Ninguém sabe o que a levou a isso. As {link:sentinels}Sentinelas{/link} puseram um preço em sua cabeça.]=],
		},
		{ title = "Sem Registro", text = "A causa de sua loucura é desconhecida." },
		{
			title = "Importância",
			text = [=[As {link:sentinels}Sentinelas{/link} não a caçaram de bom grado. Sua queda é mais um sinal de que algo deu errado com as criaturas da {link:darkshore}Costa Negra{/link}, dos ursos da floresta às aves das colinas.]=],
		},
	},
	mentions = {
		{ text = "PROCURADO: Jai'vhanel" },
	},
	bonds = {
		{ id = "sentinel-glynda-nal-shea", name = "Sentinela Glynda Nal'Shea", note = "pôs o preço em sua cabeça" },
	},
})

Translate("ptBR", "lord-sinslayer", {
	title = "Lorde Sinslayer",
	subtitle = "Naga das Quedas de Fontescarpa",
	found = "A caverna atrás das Quedas de Fontescarpa",
	hint = [=[Enfrente o lorde naga que espreita na caverna atrás das Quedas de Fontescarpa.]=],
	allegiance = "Nagas",
	aliases = { "Sinslayer" },
	sections = {
		{
			title = "Resumo",
			text = [=[O Lorde Sinslayer lidera os {link:naga}nagas{/link} que tomaram a caverna atrás das {link:cliffspring-falls}Quedas de Fontescarpa{/link}. Os Ancientes sentiram o mal naquela caverna antes que qualquer elfo o tivesse visto. As quedas dão à {link:darkshore}Costa Negra{/link} boa parte de sua água potável, e o veneno que agora corre delas adoeceu os cervos por toda a terra.]=],
		},
		{ title = "Sem Registro", text = "Pouco se sabe de Sinslayer além de seu nome e seu covil." },
		{
			title = "Importância",
			text = [=[A caverna de Sinslayer fica mais perto de {link:auberdine}Auberdine{/link} do que {link:ruins-of-mathystra}Mathistra{/link}. Sua presença mostra que os nagas já não se contentam com as velhas ruínas do nordeste.]=],
		},
	},
	bonds = {
		{ id = "barithras-moonshade", name = "Barithras Moonshade", note = "foi avisado sobre sua caverna" },
	},
})

Translate("ptBR", "murkdeep", {
	title = "Murkdeep",
	subtitle = "Terror dos Greymist",
	found = "Um acampamento murloc na costa ao sul de Auberdine",
	hint = "Enfrente o murloc que guarda as cabanas na costa do sul.",
	allegiance = "Murlocs Greymist",
	sections = {
		{
			title = "Resumo",
			text = [=[Murkdeep é um {link:murlocs}murloc{/link} da tribo Greymist que guarda um acampamento de cabanas na costa ao sul de {link:auberdine}Auberdine{/link}. Matou pelo menos uma Sentinela. Também se acredita que tenha afundado dois navios de carga ao largo da costa. O conselho da vila pôs um preço em sua cabeça, e o povo da cidade diz que dormirá mais tranquilo quando for pago.]=],
		},
		{
			title = "Importância",
			text = [=[Murkdeep é a razão pela qual os pescadores de {link:auberdine}Auberdine{/link} mantêm seus barcos em terra, e a razão pela qual a carga vinda do mar chega atrasada ou não chega.]=],
		},
	},
	mentions = {
		{ text = "PROCURADO: Murkdeep!" },
	},
	bonds = {
		{ id = "sentinel-glynda-nal-shea", name = "Sentinela Glynda Nal'Shea", note = "paga a recompensa" },
	},
})

Translate("ptBR", "kerlonian-evershade", {
	title = "Kerlonian Evershade",
	subtitle = "Druida da Garra",
	found = "Perto do Bosque dos Ancientes",
	hint = [=[Encontre o druida sonolento que perdeu suas coisas perto do bosque do sul.]=],
	allegiance = "Druidas da Garra",
	aliases = { "Kerlonian" },
	sections = {
		{
			title = "Resumo",
			text = [=[Kerlonian Evershade é um Druida da Garra que despertou há pouco do {link:emerald-dream}Sonho Esmeralda{/link}. Desde então vive sonolento. Partiu para o {link:maestra-s-post}Entreposto de Maestra{/link} para encontrar {link:liladris-moonriver}Liladris Moonriver{/link}, parou para um breve cochilo e perdeu seus pertences. Uma trompa em seu baú o acordará se ele cochilar de novo.]=],
		},
		{
			title = "Feitos",
			text = [=[• Despertou do {link:emerald-dream}Sonho Esmeralda{/link} e tomou a estrada para o sul, rumo ao {link:ashenvale}Vale Gris{/link}.
• Adormeceu de novo no caminho, e precisa de um guia para chegar ao {link:maestra-s-post}Entreposto de Maestra{/link}.]=],
		},
	},
	mentions = {
		{ text = "O Adormecido Despertou" },
	},
	bonds = {
		{ id = "cerellean-whiteclaw", name = "Cerellean Whiteclaw", note = "outro adormecido que despertou" },
	},
})

Translate("ptBR", "cult-of-the-dark-strand", {
	title = "Cult of the Dark Strand",
	aliases = { "Dark Strand" },
	sections = {
		{
			title = "Resumo",
			text = [=[O Cult of the Dark Strand é um grupo de bruxos que tomou a {link:tower-of-althalaxx}Torre de Althalaxx{/link} na {link:darkshore}Costa Negra{/link}. Não tinha nenhum nome conhecido pelas {link:sentinels}Sentinelas{/link} até que {link:balthule-shadowstrike}Balthule Shadowstrike{/link} juntou um a partir de restos de seu pergaminho. Seus fanáticos e invocadores do vazio servem a {link:athrikus-narassin}Athrikus Narassin{/link}, o antigo lorde Bem-nascido da torre.]=],
		},
		{
			title = "Seu Poder",
			text = [=[O culto tira sua força de gemas de alma. {link:athrikus-narassin}Athrikus{/link} mantinha nelas as almas de Bem-nascidos aprisionadas, e as escondeu nas terras dos sátiros no norte do {link:ashenvale}Vale Gris{/link}, na {link:night-run}Trilha da Noite{/link} e em {link:satyrnaar}Satyrnaar{/link}. O culto também atua em {link:the-ruins-of-ordil-aran}Ordil'Aran{/link}, no Vale Gris. Tem negócios com o bruxo {link:orcs}orc{/link} {link:ilkrud-magthrull}Ilkrud Magthrull{/link}, do {link:fire-scar-shrine}Santuário Cicatriz de Fogo{/link}, que mantinha anotações sobre seus planos. {link:delgren-the-purifier}Delgren, o Purificador{/link}, fez do fim do culto a sua tarefa.]=],
		},
	},
})

Translate("ptBR", "blackwood-furbolgs", {
	title = "Pelursos Bosqueneros",
	aliases = { "Bosqueneros", "tribo Bosquenera" },
	sections = {
		{
			title = "Resumo",
			text = [=[Os Bosqueneros são uma tribo de {link:furbolgs}pelursos{/link} da {link:darkshore}Costa Negra{/link}. Eram amigos dos elfos noturnos, e os elfos ainda se lembram deles assim. Agora estão corrompidos. Vivem em acampamentos ao longo do {link:cliffspring-river}Rio Fontescarpa{/link}, no norte e no sul, e atacam qualquer elfo que se aproxime.]=],
		},
		{
			title = "A Corrupção",
			text = [=[Os elfos de {link:auberdine}Auberdine{/link} atribuíram parte da loucura dos Bosqueneros aos sátiros. Um {link:satyrs}sátiro{/link} corruptor os domina por meio de um talismã. Quando os pelursos comeram comida misturada com água do poço lunar, ficaram purificados por pouco tempo. O ancião de Auberdine espera que um dia possam ser libertados de vez. Mas o veneno mais profundo corre na terra e na água, e vem da {link:felwood}Selva Maleva{/link}.]=],
		},
	},
})
