-- Generated by tools/build_content.py from content/ptBR/kalimdor/orgrimmar.md. Do not edit.
local _, ns = ...
local Translate = ns.Lore.Translate

Translate("ptBR", "orgrimmar", {
	title = "Orgrimmar",
	sections = {
		{
			title = "Resumo",
			text = [=[Orgrimmar é a capital da {link:horde}Horda{/link}, uma cidade-fortaleza nas montanhas do norte de {link:durotar}Durotar{/link}. Suas muralhas são de madeira, pedra e ferro, e boa parte dela é escavada na rocha vermelha dos cânions. Por seu grande portão passam guerreiros orcs, caçadores trolls, anciões {link:tauren}tauren{/link} e os pálidos emissários dos {link:forsaken}Renegados{/link}. Em seu coração fica o salão do Chefe Guerreiro. A cidade leva o nome de {link:orgrim-doomhammer}Orgrim Doomhammer{/link}, que morreu para que seu povo fosse livre, e foi feita para mostrar ao mundo o que os orcs se tornaram: não uma máquina de guerra dos demônios, mas uma nação.]=],
		},
		{
			title = "Origens",
			text = [=[Vencida a guerra contra a {link:burning-legion}Legião Ardente{/link}, {link:thrall}Thrall{/link} trouxe seu povo para a costa leste de {link:kalimdor}Kalimdor{/link} e pôs-se a construir um lar para ele. Escolheu um lugar onde as montanhas do norte protegeriam as costas da cidade, e deu-lhe o nome de Doomhammer, seu amigo e mestre. Os orcs não a ergueram sozinhos. Os {link:tauren}tauren{/link}, os {link:darkspear-trolls}Lançanegra{/link} e os goblins deram sua ajuda, e a cidade subiu depressa, vale após vale. Enquanto ainda era construída, os humanos de {link:kul-tiras}Kul Tiraz{/link} vieram para derrubá-la. Fracassaram, e Orgrimmar permaneceu de pé.]=],
		},
		{
			title = "Os Dias de Hoje",
			text = [=[Orgrimmar é a maior cidade da {link:horde}Horda{/link}, e seu coração. {link:thrall}Thrall{/link} governa de {link:grommash-hold}Grommash Hold{/link}, com o chefe dos {link:darkspear-trolls}Lançanegra{/link} e seus velhos conselheiros ao lado. Seus mercados são barulhentos, seus salões de treino estão cheios, e seus jovens guerreiros anseiam pela primeira batalha. Mas a cidade tem inimigos dentro de suas muralhas. Os cultistas da {link:burning-blade}Lâmina Ardente{/link} sussurram no {link:cleft-of-shadow}Cleft of Shadow{/link}, e sob a cidade, nas cavernas em chamas das {link:ragefire-chasm}Cavernas Ígneas{/link}, uma seita do {link:shadow-council}Conselho das Sombras{/link} reúne suas forças. Thrall sabe mais sobre eles do que eles imaginam.]=],
		},
		{
			title = "Habitantes",
			text = [=[• {b}Os orcs.{/b} Guerreiros, xamãs, ferreiros e mercadores, livres da maldição do demônio e orgulhosos disso.
• {b}Os trolls {link:darkspear-trolls}Lançanegra{/link}.{/b} Mantêm seu próprio bairro no {link:valley-of-spirits}Valley of Spirits{/link}.
• {b}Os {link:tauren}tauren{/link}.{/b} Anciões e viajantes do {link:thunder-bluff}Penhasco do Trovão{/link}, aliados do Chefe Guerreiro.
• {b}Os {link:forsaken}Renegados{/link}.{/b} Emissários de {link:sylvanas-windrunner}Sylvanas Windrunner{/link}, recém-aceitos na {link:horde}Horda{/link} e vigiados com certa inquietação.
• {b}Os goblins.{/b} Mercadores e engenheiros que servem a quem pagar.
• {b}A {link:burning-blade}Lâmina Ardente{/link}.{/b} Escondida entre os demais, como a podridão se esconde numa madeira sã.]=],
		},
		{
			title = "História",
			text = [=[• {b}A Fundação.{/b} A cidade foi erguida depois da {link:battle-of-mount-hyjal}Batalha do Monte Hyjal{/link}, enquanto os orcs domavam as terras ao redor e expulsavam javaligs, centauros e harpias.
• {b}A Guerra do Almirante.{/b} A frota de {link:daelin-proudmoore}Daelin Proudmoore{/link} ameaçou a nova cidade pelo mar. A {link:horde}Horda{/link} derrubou a fortaleza do almirante e o matou em {link:theramore-isle}Theramore{/link}.
• {b}Os Dias de Hoje.{/b} A Horda cresceu e passou a incluir os {link:forsaken}Renegados{/link} de {link:lordaeron}Lordaeron{/link}, e Orgrimmar tornou-se o ponto de encontro de todos os seus povos.]=],
		},
		{
			title = "Tradições da Cidade",
			text = [=[• A fortaleza do Chefe Guerreiro se chama {link:grommash-hold}Grommash Hold{/link}, em honra a {link:grom-hellscream}Grom Hellscream{/link}, que matou o demônio {link:mannoroth}Mannoroth{/link} e libertou os orcs da maldição do sangue.
• Quando um herói da {link:horde}Horda{/link} traz para casa a cabeça de um grande inimigo, ela é erguida no {link:valley-of-strength}Valley of Strength{/link} para que toda a cidade a veja.
• Na taverna do Valley of Strength bebe um {link:tauren}tauren{/link} chamado {link:gamon}Gamon{/link}. Ele serve a um troll que negocia com os piratas da costa sul, e raramente está sóbrio.
• Os ladinos da cidade dizem que uma sociedade chamada Shattered Hand age nas sombras do Cleft, e que ela acha o Chefe Guerreiro cauteloso demais.]=],
		},
	},
})

Translate("ptBR", "valley-of-strength", {
	title = "Valley of Strength",
	sections = {
		{
			title = "Resumo",
			text = [=[O Valley of Strength fica logo depois do grande portão de {link:orgrimmar}Orgrimmar{/link}. É o lugar mais movimentado da cidade. Ali estão o banco, a casa de leilões e a taverna, e acima deles a torre onde pousam as serpes. Soldados vigiam cada caminho. Viajantes de todos os povos da {link:horde}Horda{/link} lotam suas trilhas, e as notícias de toda {link:kalimdor}Kalimdor{/link} passam por ali. É ali, também, que a Horda celebra suas vitórias. As cabeças de inimigos tombados são erguidas acima do vale, e os senhores supremos da cidade chamam o povo a honrar os heróis que as trouxeram.]=],
		},
	},
})

Translate("ptBR", "the-drag", {
	title = "The Drag",
	aliases = { "Drag" },
	sections = {
		{
			title = "Resumo",
			text = [=[O Drag é uma rua longa e sombria que serpenteia do {link:valley-of-strength}Valley of Strength{/link} para o interior da cidade. Suas paredes são cheias de lojas. Coureiros, alfaiates, alquimistas e engenheiros trabalham em suas barracas, e a fumaça das fogueiras de cozinha paira entre os toldos. É um lugar lotado e barulhento, e nem todo mercador ali é honesto. Quem busca um ofício vem aqui aprendê-lo. Do Drag, caminhos levam ao {link:valley-of-honor}Valley of Honor{/link} e descem para o {link:cleft-of-shadow}Cleft of Shadow{/link}.]=],
		},
	},
})

Translate("ptBR", "cleft-of-shadow", {
	title = "Cleft of Shadow",
	sections = {
		{
			title = "Resumo",
			text = [=[O Cleft of Shadow é um desfiladeiro escuro no coração de {link:orgrimmar}Orgrimmar{/link}, aonde o sol raramente chega. É o bairro dos ladinos, bruxos e envenenadores. O bruxo {link:neeru-fireblade}Neeru Fireblade{/link} mantém sua tenda aqui, e aqui a Shattered Hand se reúne em segredo. No fundo da fenda, uma passagem desce para as {link:ragefire-chasm}Cavernas Ígneas{/link}. A gente honesta da cidade evita o Cleft, e quem vive ali prefere assim. Muitos dos segredos do Chefe Guerreiro são guardados aqui, e também alguns dos de seus inimigos.]=],
		},
	},
})

Translate("ptBR", "valley-of-honor", {
	title = "Valley of Honor",
	sections = {
		{
			title = "Resumo",
			text = [=[O Valley of Honor fica no nordeste de {link:orgrimmar}Orgrimmar{/link} e pertence aos guerreiros da {link:horde}Horda{/link}. No Hall of the Brave, velhos veteranos ensinam aos jovens os caminhos do machado e do escudo. Os caçadores mantêm suas cabanas aqui, e as forjas dos ferreiros da cidade ardem dia e noite. O vale ressoa com o tinir dos martelos e os gritos dos que treinam luta. Um {link:orcs}orc{/link} que deseja ser conhecido como guerreiro vem aqui para prová-lo.]=],
		},
	},
})

Translate("ptBR", "valley-of-spirits", {
	title = "Valley of Spirits",
	sections = {
		{
			title = "Resumo",
			text = [=[O Valley of Spirits se estende pelo sudoeste de {link:orgrimmar}Orgrimmar{/link}. É o bairro dos {link:darkspear-trolls}Lançanegra{/link}. Suas cabanas se erguem entre as construções orcs, e seus médicos bruxos, sacerdotes e magos praticam aqui os velhos costumes da tribo. Os jovens sacerdotes trolls são recebidos no círculo de seus anciões neste vale. Seu lago tranquilo reflete as paredes vermelhas acima. De todos os vales da cidade, é o mais silencioso, e os trolls o mantêm assim. Aqui os Lançanegra se lembram das ilhas que perderam.]=],
		},
	},
})

Translate("ptBR", "valley-of-wisdom", {
	title = "Valley of Wisdom",
	sections = {
		{
			title = "Resumo",
			text = [=[O Valley of Wisdom fica no noroeste de {link:orgrimmar}Orgrimmar{/link}, longe do barulho do portão. É a sede do Chefe Guerreiro. Em sua cabeceira ergue-se {link:grommash-hold}Grommash Hold{/link}, e ao redor dela se reúnem os xamãs da {link:horde}Horda{/link}, que ensinam os jovens a falar com os {link:elements}elementos{/link} como seus ancestrais faziam em Draenor. Os anciões da cidade vêm aqui para aconselhar e ser aconselhados. É um lugar de saber, e de poder. Muitos que buscam o favor do Chefe Guerreiro percorrem seu caminho.]=],
		},
	},
})

Translate("ptBR", "grommash-hold", {
	title = "Grommash Hold",
	sections = {
		{
			title = "Resumo",
			text = [=[Grommash Hold é a fortaleza do Chefe Guerreiro, construída nos penhascos do {link:valley-of-wisdom}Valley of Wisdom{/link}. Leva o nome de {link:grom-hellscream}Grom Hellscream{/link}, cujo sacrifício libertou os orcs do sangue do demônio. Seu salão é vasto e escuro, iluminado pelo fogo. Na outra ponta, {link:thrall}Thrall{/link} recebe a corte de seu trono. {link:vol-jin}Vol'jin{/link} dos {link:darkspear-trolls}Lançanegra{/link} fica ao seu lado, com o velho guerreiro {link:eitrigg}Eitrigg{/link} e o vidente {link:zor-lonetree}Zor Lonetree{/link}. Os guardas de elite Kor'kron vigiam suas portas, e ninguém chega diante do Chefe Guerreiro sem a permissão deles.]=],
		},
	},
})

Translate("ptBR", "thrall", {
	title = "Thrall",
	subtitle = "Chefe Guerreiro da Horda",
	found = "Grommash Hold, no Valley of Wisdom",
	hint = "Peça uma audiência com o Chefe Guerreiro em Grommash Hold.",
	allegiance = "Horda · Clã Lobo do Gelo",
	aliases = { "Chefe Guerreiro Thrall" },
	sections = {
		{
			title = "Resumo",
			text = [=[Thrall é o Chefe Guerreiro da {link:horde}Horda{/link}. Nasceu filho de Durotan, chefe do {link:frostwolf-clan}clã Lobo do Gelo{/link}, e foi criado como escravo entre os humanos. Quebrou suas correntes, libertou seu povo dos campos de internamento e o trouxe de volta aos velhos costumes dos xamãs. Conduziu-o através do mar até {link:kalimdor}Kalimdor{/link} e deu-lhe uma pátria. Até seus inimigos lhe reconhecem a honra.]=],
		},
		{
			title = "Importância",
			text = [=[Thrall fez uma nova {link:horde}Horda{/link} das cinzas da antiga. Sob ele, os {link:orcs}orcs{/link} já não são servos de demônios, e a Horda já não é apenas uma horda de orcs.]=],
		},
		{
			title = "O Escravo",
			text = [=[Durotan e sua companheira, Draka, foram assassinados nos ermos quando o filho ainda era bebê. Um oficial humano chamado {link:aedelas-blackmoore}Aedelas Blackmoore{/link} encontrou a criança e a levou para o {link:durnholde-keep}Forte do Desterro{/link}. Deu-lhe o nome de Thrall, uma palavra que significa escravo, e o criou para lutar na arena e talvez um dia comandar um exército para ele. Uma menina humana, {link:taretha-foxton}Taretha Foxton{/link}, foi bondosa com ele, e com a ajuda dela ele escapou.]=],
		},
		{
			title = "O Libertador",
			text = [=[Nos ermos, Thrall encontrou {link:grom-hellscream}Grom Hellscream{/link} e os últimos clãs livres. Entre os {link:frostwolf-clan}Lobo do Gelo{/link}, nas {link:alterac-mountains}Montanhas de Alterac{/link}, o velho xamã {link:drek-thar}Drek'Thar{/link} o ensinou a falar com os {link:elements}elementos{/link}. Então ele conheceu {link:orgrim-doomhammer}Orgrim Doomhammer{/link}, e juntos atacaram os campos de internamento. Doomhammer tombou em batalha e, antes de morrer, deu a Thrall seu martelo, sua armadura e seu título. Thrall libertou os orcs e quebrou o poder de {link:aedelas-blackmoore}Blackmoore{/link} no {link:durnholde-keep}Forte do Desterro{/link}.]=],
		},
		{
			title = "O Êxodo",
			text = [=[Um profeta veio a Thrall em sonhos e lhe disse que levasse seu povo para o oeste. Ele levou. Uma tempestade lançou sua frota sobre as ilhas dos {link:darkspear-trolls}Lançanegra{/link}, e ele salvou os trolls de seus inimigos. Em {link:kalimdor}Kalimdor{/link} conquistou a amizade de {link:cairne-bloodhoof}Cairne Bloodhoof{/link} e dos {link:tauren}tauren{/link}. Viu Grom cair de novo sob o sangue do demônio, libertou-o e o viu morrer matando {link:mannoroth}Mannoroth{/link}. Na {link:battle-of-mount-hyjal}Batalha do Monte Hyjal{/link}, lutou ao lado de humanos e elfos noturnos contra {link:archimonde}Archimonde{/link}. Depois fundou {link:durotar}Durotar{/link} e {link:orgrimmar}Orgrimmar{/link}, e fez a paz com {link:jaina-proudmoore}Jaina Proudmoore{/link} de {link:theramore-isle}Theramore{/link}.]=],
		},
		{
			title = "Feitos",
			text = [=[• Libertou os orcs dos campos de internamento.
• Conduziu a {link:horde}Horda{/link} a {link:kalimdor}Kalimdor{/link} e fundou a nação de {link:durotar}Durotar{/link}.
• Forjou alianças com os {link:darkspear-trolls}Lançanegra{/link}, os {link:tauren}tauren{/link} e os {link:forsaken}Renegados{/link}.]=],
		},
	},
	chapters = {
		{
			title = "Inimigos Ocultos",
			hint = "Leve ao Chefe Guerreiro a prova vinda da Rocha da Caveira.",
			text = [=[Thrall não tolera traidores, mas não os golpeia cedo demais. Um golpe desferido antes da hora só empurraria a podridão mais fundo. Ele precisava de alguém jovem e desconhecido, que pudesse ir aonde seus próprios agentes não podiam. A insígnia de um tenente da {link:burning-blade}Lâmina Ardente{/link}, tomada na {link:skull-rock}Rocha da Caveira{/link}, era a chave da porta do inimigo.]=],
		},
		{
			title = "O Bruxo na Fenda",
			hint = "Leve a insígnia ao bruxo no Cleft of Shadow.",
			text = [=[Thrall revelou o que poucos em {link:orgrimmar}Orgrimmar{/link} sabiam. O bruxo {link:neeru-fireblade}Neeru Fireblade{/link}, que diz caçar demônios, é o verdadeiro líder da {link:burning-blade}Lâmina Ardente{/link}. Thrall sabe disso há muito tempo, e deixa Neeru acreditar que confia nele. O bruxo é mais útil livre do que morto, pois por meio dele Thrall pretende encontrar o {link:shadow-council}Conselho das Sombras{/link} e destruí-lo de uma vez.]=],
		},
		{
			title = "A Searing Blade",
			hint = "Abata os líderes da Searing Blade nas Cavernas Ígneas.",
			text = [=[Sob a cidade, uma seita chamada Searing Blade respondia a {link:neeru-fireblade}Neeru{/link}. Seus verdadeiros senhores eram um {link:satyrs}sátiro{/link}, {link:bazzalan}Bazzalan{/link}, e um bruxo, {link:jergosh-the-invoker}Jergosh{/link}. Por ordem de Thrall, ambos foram mortos, e ninguém pôde dizer que foi obra dele. Neeru se enfureceu e, em sua raiva, contou ao seu falso tenente novos planos no {link:ashenvale}Vale Gris{/link} e nos {link:the-barrens}Sertões{/link}.]=],
		},
		{
			title = "Rend Vive",
			hint = [=[Descubra o que o Chefe Guerreiro queria que fosse feito com os Rocha Negra.]=],
			text = [=[Chegou a notícia de que Rend Blackhand, dado como morto havia muito tempo, erguera uma {link:horde}Horda{/link} própria no Pico da {link:blackrock-mountain}Rocha Negra{/link} e se chamava Chefe Guerreiro. Thrall bateu o punho no trono. Pediu a cabeça de Rend e, quando ela lhe chegou, honrou quem a trouxe.]=],
		},
	},
	mentions = {
		{ text = "Inimigos Ocultos, a insígnia" },
		{ text = "Inimigos Ocultos, o bruxo" },
		{ text = "Inimigos Ocultos, a Searing Blade" },
		{ text = "Inimigos Ocultos, o último relatório" },
		{ text = "A Sabedoria de {link:eitrigg}Eitrigg{/link}" },
		{ text = "Pela {link:horde}Horda{/link}!" },
		{ text = "O Resgate Real" },
		{ text = "A Princesa Salva?" },
		{ text = "A Negociação da Paz" },
		{ text = "Vitória da {link:horde}Horda{/link}" },
		{ text = "O Senhor da {link:blackrock-mountain}Rocha Negra{/link}" },
	},
	bonds = {
		{ id = "vol-jin", name = "Vol'jin", note = "seu conselheiro e aliado" },
		{ id = "eitrigg", name = "Eitrigg", note = "seu velho conselheiro" },
		{ id = "neeru-fireblade", name = "Neeru Fireblade", note = "o traidor que ele vigia" },
		{ id = "orgrim-doomhammer", name = "Orgrim Doomhammer", note = "seu amigo e mentor" },
		{ id = "grom-hellscream", name = "Grom Hellscream", note = "seu amigo, tombado" },
		{ id = "cairne-bloodhoof", name = "Cairne Bloodhoof", note = "seu aliado" },
		{ id = "jaina-proudmoore", name = "Jaina Proudmoore", note = "sua aliada na paz" },
	},
})

Translate("ptBR", "vol-jin", {
	title = "Vol'jin",
	subtitle = "Chefe dos Lançanegra",
	found = "Grommash Hold, ao lado do Chefe Guerreiro",
	hint = [=[Fale com o troll que fica ao lado do Chefe Guerreiro em Grommash Hold.]=],
	allegiance = "Horda · Trolls Lançanegra",
	sections = {
		{
			title = "Resumo",
			text = [=[Vol'jin é o chefe dos {link:darkspear-trolls}Lançanegra{/link} e um caçador das sombras de grande habilidade. É filho de Sen'jin, que deu a vida para que a tribo pudesse seguir os orcs para um novo mundo. Vol'jin mantém o juramento do pai. Fica ao lado de {link:thrall}Thrall{/link} em {link:grommash-hold}Grommash Hold{/link}, aconselhando o Chefe Guerreiro e falando por seu povo, enquanto os Lançanegra esperam, em sua aldeia à beira-mar, o dia em que poderão retomar suas ilhas.]=],
		},
		{
			title = "Importância",
			text = [=[Por meio de Vol'jin, os {link:trolls}trolls{/link} tornaram-se um verdadeiro povo da {link:horde}Horda{/link}, e não apenas seus aliados. Ele é a prova de que a Horda de {link:thrall}Thrall{/link} é uma liga de povos livres.]=],
		},
		{
			title = "O Juramento de Sen'jin",
			text = [=[Os {link:darkspear-trolls}Lançanegra{/link} eram párias, expulsos das selvas e espalhados pelas ilhas dos mares do sul. Quando uma tempestade lançou a frota de {link:thrall}Thrall{/link} em suas praias, a tribo lutava pela vida contra os humanos e os murlocs das profundezas. Thrall lutou ao lado dos trolls. Seu chefe, Sen'jin, foi levado pelos murlocs e não voltou, mas ele havia previsto que o chefe guerreiro {link:orcs}orc{/link} conduziria seu povo a um novo lar. O filho de Sen'jin jurou a tribo à {link:horde}Horda{/link}.]=],
		},
		{
			title = "As Ilhas e o Traidor",
			text = [=[Depois da guerra contra a Legião, os {link:darkspear-trolls}Lançanegra{/link} se estabeleceram nas {link:echo-isles}Ilhas do Eco{/link}, ao largo da costa de {link:durotar}Durotar{/link}. Sua paz foi curta. A frota de {link:kul-tiras}Kul Tiraz{/link} caiu sobre as ilhas, e Vol'jin teve de ver seu povo evacuado enquanto a {link:horde}Horda{/link} revidava contra os navios humanos. Então veio um golpe pior: {link:zalazane}Zalazane{/link}, um médico bruxo de sua própria tribo, voltou sua magia contra eles. Os Lançanegra livres fugiram para o continente e ali construíram uma aldeia, a que deram o nome de Sen'jin.]=],
		},
		{
			title = "Feitos",
			text = [=[• Jurou os {link:darkspear-trolls}Lançanegra{/link} à {link:horde}Horda{/link} depois da morte do pai.
• Conduziu seu povo a {link:kalimdor}Kalimdor{/link} e o estabeleceu nas {link:echo-isles}Ilhas do Eco{/link}.
• Aconselha o Chefe Guerreiro em {link:grommash-hold}Grommash Hold{/link}.
• Adverte {link:thrall}Thrall{/link}, vez após vez, a não confiar nos humanos.]=],
		},
		{
			title = "Sem Registro",
			text = [=[Pouco está escrito aqui sobre a juventude de Vol'jin. Este registro guarda apenas o que as histórias e seus feitos revelam.]=],
		},
	},
	chapters = {
		{
			title = "As Ordens do Almirante",
			hint = "Leve as ordens do almirante morto a Orgrimmar.",
			text = [=[Quando as ordens de {link:daelin-proudmoore}Daelin Proudmoore{/link} foram encontradas na {link:tiragarde-keep}Bastilha Tiragarde{/link}, elas chegaram por fim a Vol'jin, em {link:grommash-hold}Grommash Hold{/link}. Ele as leu e não se surpreendeu. Havia muito tempo insistia com o Chefe Guerreiro para não confiar nos humanos, e os planos do almirante lhe deram razão. Ele não se vangloriou. Foi imediatamente aconselhar {link:thrall}Thrall{/link}.]=],
		},
		{
			title = "O Mestre das Maldições",
			hint = "Derrube o médico bruxo que domina as Ilhas do Eco.",
			text = [=[A notícia da queda de {link:zalazane}Zalazane{/link} chegou a {link:orgrimmar}Orgrimmar{/link} vinda da {link:sen-jin-village}Aldeia Sen'jin{/link}. Para o chefe dos {link:darkspear-trolls}Lançanegra{/link}, foi um pequeno consolo. A maldição do traidor ainda pesa sobre as ilhas, e muitos do povo de Vol'jin ainda vagam por lá com a mente vazia. O dia do retorno da tribo ao lar ainda não chegou.]=],
		},
	},
	mentions = {
		{ text = "As Ordens do Almirante" },
		{
			text = [=[{link:zalazane}Zalazane{/link}, morto a pedido do {link:master-gadrin}Mestre Gadrin{/link}]=],
		},
	},
	bonds = {
		{ id = "thrall", name = "Thrall", note = "seu Chefe Guerreiro" },
		{ id = "zalazane", name = "Zalazane", note = "o traidor de sua tribo" },
		{ id = "master-gadrin", name = "Mestre Gadrin", note = "ancião de seu povo" },
		{ id = "eitrigg", name = "Eitrigg", note = "um colega conselheiro" },
	},
})

Translate("ptBR", "eitrigg", {
	title = "Eitrigg",
	subtitle = "Conselheiro do Chefe Guerreiro",
	found = "Grommash Hold",
	hint = [=[Fale com o velho guerreiro que aconselha o Chefe Guerreiro em Grommash Hold.]=],
	allegiance = "Horda · clã Rocha Negra (outrora)",
	sections = {
		{
			title = "Resumo",
			text = [=[Eitrigg é um velho guerreiro {link:orcs}orc{/link} do {link:blackrock-clan}clã Rocha Negra{/link} que serve a {link:thrall}Thrall{/link} como conselheiro e supervisor dos recrutas da {link:horde}Horda{/link}. Lutou nas guerras da antiga Horda sob Blackhand e Doomhammer. Passou a odiar os adoradores de demônios que desviaram seu povo e, por um tempo, deixou a Horda de todo. Voltou quando ouviu a visão de Thrall de uma Horda guiada por xamãs em vez de demônios.]=],
		},
		{
			title = "Importância",
			text = [=[Eitrigg é uma ponte entre a antiga {link:horde}Horda{/link} e a nova. Conhece os costumes dos {link:blackrock-mountain}Rocha Negra{/link} melhor que qualquer {link:orcs}orc{/link} em {link:orgrimmar}Orgrimmar{/link}, e sabe quanto custa abandoná-los.]=],
		},
		{
			title = "Feitos",
			text = [=[• Serviu como tenente do chefe guerreiro dos {link:blackrock-mountain}Rocha Negra{/link} nos dias anteriores ao {link:dark-portal}Portal Negro{/link}, ao lado de {link:orgrim-doomhammer}Orgrim Doomhammer{/link}.
• Vigiou a assassina {link:garona}Garona{/link} na {link:second-war}Segunda Guerra{/link}, e a deixou partir quando ela fugiu.
• Deixou a {link:horde}Horda{/link} e vagou para o norte, pelas terras dos humanos, onde foi feito prisioneiro e salvo pelo Chefe Guerreiro.
• Supervisiona o treinamento dos novos recrutas para {link:thrall}Thrall{/link}.]=],
		},
	},
	chapters = {
		{
			title = "Rend Vive",
			hint = "Leve a Eitrigg notícias dos Rocha Negra.",
			text = [=[A notícia veio dos {link:badlands}Ermos{/link}: Rend Blackhand, filho do antigo Chefe Guerreiro Blackhand, estava vivo e reunia o {link:blackrock-clan}clã Rocha Negra{/link} no Pico da {link:blackrock-mountain}Rocha Negra{/link}. Pensava-se que Rend fora morto havia muito tempo. Ninguém em {link:orgrimmar}Orgrimmar{/link} conhecia os Rocha Negra como Eitrigg, e ninguém tinha mais direito à vingança. Ele passou a notícia a {link:thrall}Thrall{/link}.]=],
		},
		{
			title = "A Cabeça de Rend",
			hint = "Leve a cabeça de Rend Blackhand ao Chefe Guerreiro.",
			text = [=[Quando a cabeça de Rend foi posta diante do Chefe Guerreiro, Eitrigg viu quebrada a última sombra do clã a que um dia servira. Os {link:blackrock-mountain}Rocha Negra{/link} mergulharam no caos mais uma vez. Para o velho guerreiro, foi uma dívida saldada.]=],
		},
	},
	mentions = {
		{ text = "A Nova {link:horde}Horda{/link}" },
		{ text = "A Sabedoria de Eitrigg" },
		{ text = "Pela {link:horde}Horda{/link}!" },
	},
	bonds = {
		{ id = "thrall", name = "Thrall", note = "seu Chefe Guerreiro e salvador" },
		{ id = "orgrim-doomhammer", name = "Orgrim Doomhammer", note = "seu velho camarada" },
		{ id = "vol-jin", name = "Vol'jin", note = "um colega conselheiro" },
		{ id = "tirion-fordring", name = "Tirion Fordring", note = "o humano que o salvou" },
	},
})

Translate("ptBR", "neeru-fireblade", {
	title = "Neeru Fireblade",
	subtitle = "Bruxo do Cleft of Shadow",
	found = "Sua tenda no Cleft of Shadow",
	hint = "Procure o bruxo cuja tenda fica no Cleft of Shadow.",
	allegiance = "Horda (declarada)",
	aliases = { "Neeru" },
	sections = {
		{
			title = "Resumo",
			text = [=[Neeru Fireblade é um bruxo que vive no {link:cleft-of-shadow}Cleft of Shadow{/link}. Poucos orcs confiam nos de sua espécie, pois foram os bruxos que primeiro prenderam os orcs aos demônios. Neeru diz usar suas artes apenas contra os demônios. Desde a última guerra, diz ele, tem buscado cada vestígio de corrupção demoníaca na sociedade {link:orcs}orc{/link}, e serve ao Chefe Guerreiro erradicando os cultos que se escondem em sua cidade.]=],
		},
		{
			title = "Importância",
			text = [=[Neeru está no centro da luta contra a {link:burning-blade}Lâmina Ardente{/link}. Cada fio do culto em {link:durotar}Durotar{/link} parece levar de volta ao {link:cleft-of-shadow}Cleft of Shadow{/link}.]=],
		},
		{
			title = "Feitos",
			text = [=[• Estuda as coleiras abrasadoras da {link:burning-blade}Lâmina Ardente{/link}.
• Ordena a destruição da Semente Demoníaca, um objeto de poder demoníaco, no {link:dreadmist-peak}Morro de Brumedo{/link}, nos {link:the-barrens}Sertões{/link}.
• Envia heróis às {link:ragefire-chasm}Cavernas Ígneas{/link} para matar o guarda vil {link:taragaman-the-hungerer}Taragaman{/link}.
• Troca ervas com o médico bruxo {link:witch-doctor-uzer-i}Uzer'i{/link}, de {link:feralas}Feralas{/link}.]=],
		},
	},
	chapters = {
		{
			title = "A Coleira Abrasadora",
			hint = "Leve uma coleira abrasadora de Margoz ao Cleft of Shadow.",
			text = [=[Quando {link:margoz}Margoz{/link} lhe enviou uma coleira abrasadora, Neeru a examinou de perto. Nomeou o culto que a fez, a {link:burning-blade}Lâmina Ardente{/link}, e o objeto de poder em torno do qual ele se reúne: a Semente Demoníaca. Queria que ela fosse destruída.]=],
		},
		{
			title = "A Semente Demoníaca",
			hint = "Destrua a Semente Demoníaca no alto do Morro de Brumedo.",
			text = [=[O assistente de Neeru, Ak'Zeloth, preparou pedras para romper o vínculo da Semente com a Legião. Quando a Semente foi destruída, ondas de poder atravessaram o éter. Ak'Zeloth as sentiu, e advertiu que outros também as tinham sentido.]=],
		},
		{
			title = "Lealdades Verdadeiras",
			hint = "Descubra o que o Chefe Guerreiro sabe sobre Neeru.",
			text = [=[Neeru é o líder secreto da {link:burning-blade}Lâmina Ardente{/link} e um servo do {link:shadow-council}Conselho das Sombras{/link}. Acredita que {link:thrall}Thrall{/link} é um tolo que confia nele. Está enganado: o Chefe Guerreiro sabe, e o deixa viver porque ele é útil. Neeru envia os seguidores leais de Thrall para morrer nas {link:ragefire-chasm}Cavernas Ígneas{/link}, e põe à prova a Searing Blade para ver quais de seus membros são dignos. Quando um jovem tenente da Lâmina veio a ele com a insígnia certa, Neeru acolheu um espião.]=],
		},
		{
			title = "O Faminto",
			hint = "Mate o guarda vil que lidera a Searing Blade.",
			text = [=[Neeru apontou o guarda vil {link:taragaman-the-hungerer}Taragaman, o Faminto{/link}, como o senhor da Searing Blade e pediu seu coração, para agradar ao Chefe Guerreiro. A Searing Blade era descartável para ele. Só dois de seus líderes importavam, e não eram o guarda vil.]=],
		},
	},
	mentions = {
		{ text = "Neeru Fireblade" },
		{ text = "Sombras Ardentes" },
		{ text = "Ak'Zeloth" },
		{ text = "A Semente Demoníaca" },
		{ text = "Inimigos Ocultos" },
		{ text = "Matando a Fera" },
		{ text = "Um Pedido Estranho" },
	},
	bonds = {
		{ id = "thrall", name = "Thrall", note = "o Chefe Guerreiro que o vigia" },
		{ id = "margoz", name = "Margoz", note = "enviou-lhe uma coleira" },
		{ id = "gazz-uz", name = "Gazz'uz", note = "um servo da Lâmina" },
		{ id = "taragaman-the-hungerer", name = "Taragaman, o Faminto", note = "o guarda vil que ele entregou" },
	},
})

Translate("ptBR", "zor-lonetree", {
	title = "Zor Lonetree",
	subtitle = "Vidente Ancião",
	found = "Grommash Hold",
	hint = "Fale com o vidente que serve em Grommash Hold.",
	allegiance = "Horda",
	sections = {
		{
			title = "Resumo",
			text = [=[Zor Lonetree é um vidente ancião da {link:horde}Horda{/link}, um xamã de muitos anos que serve em {link:grommash-hold}Grommash Hold{/link}. Escuta os clamores da terra e envia ajuda aonde os espíritos estão irados. É também bem instruído na política da {link:alliance}Aliança{/link}, e a Horda lhe traz os segredos que toma das mãos humanas.]=],
		},
		{
			title = "Importância",
			text = [=[Zor é uma das vozes sábias em torno do Chefe Guerreiro. Ouve tanto os espíritos quanto os sussurros do inimigo.]=],
		},
		{
			title = "Feitos",
			text = [=[• Envia auxílio à xamã {link:seereth-stonebreak}Seereth Stonebreak{/link}, que combate os goblins que queimam as florestas da {link:stonetalon-mountains}Cordilheira das Torres de Pedra{/link}.
• Estuda o pingente de um nobre tomado de soldados humanos.]=],
		},
	},
	mentions = {
		{ text = "Os Espíritos da Torre de Pedra" },
		{ text = "Apresente-se a Zor" },
		{ text = "A Serviço da {link:horde}Horda{/link}" },
	},
	bonds = {
		{ id = "thrall", name = "Thrall", note = "seu Chefe Guerreiro" },
	},
})

Translate("ptBR", "overlord-runthak", {
	title = "Senhor Supremo Runthak",
	subtitle = "Senhor Supremo do Valley of Strength",
	found = "O Valley of Strength",
	hint = "Fale com o senhor supremo que vigia o Valley of Strength.",
	allegiance = "Horda",
	aliases = { "Runthak" },
	sections = {
		{
			title = "Resumo",
			text = [=[O Senhor Supremo Runthak cumpre as ordens do Chefe Guerreiro sem questionar. Ele mesmo o diz, e se orgulha disso. Mantém a ordem no {link:valley-of-strength}Valley of Strength{/link} e vigia suas multidões. Quando um herói da {link:horde}Horda{/link} volta com a cabeça de um grande inimigo, é Runthak quem chama a cidade para vê-la.]=],
		},
		{
			title = "Importância",
			text = [=[Runthak é a voz dos triunfos da {link:horde}Horda{/link}. Por meio dele, o povo de {link:orgrimmar}Orgrimmar{/link} aprende os nomes dos que lutam por ele.]=],
		},
		{
			title = "Feitos",
			text = [=[• Ergue os troféus das vitórias da {link:horde}Horda{/link} acima do {link:valley-of-strength}Valley of Strength{/link}.
• Recompensa os heróis que o Chefe Guerreiro lhe envia.]=],
		},
	},
	mentions = {
		{ text = "Para que Todos Vejam" },
		{ text = "A Jornada Mal Começou" },
	},
	bonds = {
		{ id = "thrall", name = "Thrall", note = "seu Chefe Guerreiro" },
	},
})

Translate("ptBR", "gamon", {
	title = "Gamon",
	subtitle = "Freguês da Taverna",
	found = "A taverna do Valley of Strength",
	hint = "Encontre o tauren que bebe na taverna do Valley of Strength.",
	allegiance = "Nenhuma",
	sections = {
		{
			title = "Resumo",
			text = [=[Gamon é um {link:tauren}tauren{/link} grandalhão que costuma ser encontrado na taverna do {link:valley-of-strength}Valley of Strength{/link}, e raramente sóbrio. Trabalha como assistente de Tazan, um troll que negocia com os piratas perto da {link:ratchet}Vila Catraca{/link}. Gamon guarda para seu mestre coisas que outros gostariam de ter. Nem sempre percebe quando elas somem. Os ladinos do Cleft sabem bem disso.]=],
		},
		{
			title = "Importância",
			text = [=[Gamon é uma figura pequena numa grande cidade. Mas até um bêbado pode guardar uma chave que a Shattered Hand deseja a ponto de roubá-la.]=],
		},
		{ title = "Feitos", text = "• Guarda a chave da bolsa de Tazan." },
	},
	mentions = {
		{ text = "A Shattered Hand" },
	},
	bonds = {
		{ id = "therzok", name = "Therzok", note = "quer a chave dele" },
	},
})

Translate("ptBR", "kor-ghan", {
	title = "Kor'ghan",
	subtitle = "Envenenador do Cleft",
	found = "O Cleft of Shadow",
	hint = "Encontre o envenenador troll no Cleft of Shadow.",
	allegiance = "Trolls Lançanegra",
	sections = {
		{
			title = "Resumo",
			text = [=[Kor'ghan é um troll {link:darkspear-trolls}Lançanegra{/link} que trabalha no {link:cleft-of-shadow}Cleft of Shadow{/link}. Conhece os venenos dos escorpídeos de {link:durotar}Durotar{/link}, e como transformar o veneno de um escorpídeo em sua cura. É também um mestre de rituais severo, e quem aprende com ele precisa provar seu valor vez após vez. Seus alunos reclamam, mas sobrevivem.]=],
		},
		{
			title = "Importância",
			text = [=[Kor'ghan é quem os jovens de {link:durotar}Durotar{/link} procuram quando o veneno de um escorpídeo está em seu sangue.]=],
		},
		{
			title = "Feitos",
			text = [=[• Prepara um antídoto contra o veneno dos rabos-peçonhentos a partir das próprias bolsas de veneno dos escorpídeos.
• Salvou o jovem guerreiro Rhinag da ferroada de um rabo-peçonhento.]=],
		},
	},
	mentions = {
		{ text = "Em Busca de uma Cura" },
		{ text = "Encontrando o Antídoto" },
	},
})
