-- Generated by tools/build_content.py from content/eastern-kingdoms/tirisfal-glades.md. Do not edit.
local _, ns = ...
local Add = ns.Lore.Add

Add({
	id = "tirisfal-glades",
	title = "Tirisfal Glades",
	aliases = { "Tirisfal" },
	faction = "Horde",
	continent = "Eastern Kingdoms",
	maps = { 1420, 18 },
	zone = "Tirisfal Glades",
	unlock = {
		{ type = "zone" },
		{ type = "map" },
	},
	regionKind = "zone",
	kind = "region",
	sections = {
		{
			title = "Summary",
			text = [=[Tirisfal Glades was once the heart of {link:lordaeron}Lordaeron{/link}. Its long green valleys fed the greatest of the human kingdoms, and on its eastern edge stood the kingdom's {link:capital-city}Capital City{/link}. Now the glades are grey. Mist hangs over empty farms, the mills turn for no one, and the crows are fat. The land belongs to the {link:forsaken}Forsaken{/link}, the dead who woke to their own minds again. From {link:brill}Brill{/link} and the {link:undercity}Undercity{/link} they hold it against the living and the dead alike.]=],
		},
		{
			title = "Origins",
			text = [=[No chronicle records the year when the first settlers came to Tirisfal. They came from {link:arathor}Arathor{/link}, in the long centuries after the {link:troll-wars}Troll Wars{/link}, and they found rich soil and quiet forests. Their farmsteads grew into a kingdom, and that kingdom took the name of {link:lordaeron}Lordaeron{/link}. In later ages, noble families from the old {link:arathi-highlands}Arathi{/link} heartland bought great estates in the glades. The Agamands, who owned the mills of the northern highlands, were counted the most prosperous of them all.]=],
		},
		{
			title = "The Present Day",
			text = [=[The {link:forsaken}Forsaken{/link} of {link:sylvanas-windrunner}Sylvanas Windrunner{/link} rule Tirisfal, but they rule a land at war. The {link:scourge}Scourge{/link} still holds the {link:agamand-mills}Agamand Mills{/link} and slips past the {link:the-bulwark}Bulwark{/link}, the wall that guards the glades from the Plaguelands to the east. The {link:scarlet-crusade}Scarlet Crusade{/link} marches out of its monastery in the north-east and keeps watchtowers across the land. {link:gnolls}Gnolls{/link} rob the mass graves for corpses to feed the Lich King's armies. In the capital, the {link:royal-apothecary-society}Royal Apothecary Society{/link} works on a new plague, and the Deathguard keep living prisoners in the cellar of a tavern until the apothecaries have need of them.

New troubles have come as well. Not long ago the necropolis {red:naxxramas}Naxxramas{/red} struck at the {link:undercity}Undercity{/link}, and the shards of its great crystal still lie scattered in the fields near the ruined capital, where the {link:cult-of-the-damned}Cult of the Damned{/link} hunts for them. In the western mountains, a new order of Forsaken paladins keeps a fortress of its own. Few of their people trust them.]=],
		},
		{
			title = "Inhabitants",
			text = [=[• {b}The {link:forsaken}Forsaken{/link}.{/b} The Deathguard patrol the roads, the executors give the orders, and the newly risen wake in the crypt of {link:deathknell}Deathknell{/link} every day.
• {b}The {link:scourge}Scourge{/link}.{/b} Mindless dead, skeletons and necromancers still infest the mills, the farms and the old crypts.
• {b}The {link:scarlet-crusade}Scarlet Crusade{/link}.{/b} Zealots in red who burn every undead they find, whether it serves the Lich King or not.
• {b}The Rot Hide gnolls.{/b} Slaves of the Scourge who dig up the dead.
• {b}{link:murlocs}Murlocs{/link} and beasts.{/b} The Vile Fin tribes of the coast and lakes, darkhounds, duskbats and the great spiders of the eastern vales.]=],
		},
		{
			title = "History",
			text = [=[• {b}The Plague.{/b} In the {link:third-war}Third War{/link}, the plague of the {link:cult-of-the-damned}Cult of the Damned{/link} swept the glades. Whole families died and rose again as {link:scourge}Scourge{/link}.
• {b}The Fall.{/b} Prince {link:arthas-menethil}Arthas Menethil{/link} murdered his father {link:terenas-menethil}Terenas Menethil{/link} in his own throne room. The capital fell, and Tirisfal fell with it. That was the {link:fall-of-lordaeron}Fall of Lordaeron{/link}.
• {b}The {link:forsaken}Forsaken{/link}.{/b} When the Lich King's grip weakened, {link:sylvanas-windrunner}Sylvanas{/link} and her followers broke free and claimed the ruins of the capital. Beneath it they built the {link:undercity}Undercity{/link}.
• {b}The Necropolis.{/b} When Naxxramas came against the Undercity, the Forsaken fought it on the surface. The {link:argent-dawn}Argent Dawn{/link} fought beside them, and many fell.]=],
		},
		{
			title = "Lore of the Glades",
			text = [=[• The {link:forsaken}Forsaken{/link} say that the crypt-keepers of {link:deathknell}Deathknell{/link} were ready to burn many of the new risen before they woke.
• Before the plague, the reclusive folk of {link:shadowvale}Shadowvale{/link} brewed a green elixir from herbs of the western hills. It was sought by apothecaries, mystics and poisoners alike, even after it was forbidden in the capital.]=],
		},
	},
})

Add({
	id = "deathknell",
	title = "Deathknell",
	parent = "tirisfal-glades",
	unlock = {
		{
			type = "subzone",
			name = "Deathknell",
			areas = { 154 },
		},
	},
	regionKind = "place",
	kind = "region",
	sections = {
		{
			title = "Summary",
			text = [=[Deathknell is a small village of the dead in the west of {link:tirisfal-glades}Tirisfal{/link}. Its crypt stands on a hill above a chapel and a graveyard. Here the {link:forsaken}Forsaken{/link} bring the bodies they find, and here many wake from the Lich King's thrall to their own minds again. The undertaker {link:undertaker-mordo}Mordo{/link} greets them. {link:shadow-priest-sarvis}Shadow Priest Sarvis{/link} explains what they have become, and {link:executor-arren}Executor Arren{/link} puts them to work. The village is not safe. Mindless dead wander its northern houses, spiders fill the gold mine of Night Web's Hollow, and the {link:scarlet-crusade}Scarlet Crusade{/link} keeps a camp to the south-east.]=],
		},
	},
})

Add({
	id = "brill",
	title = "Brill",
	parent = "tirisfal-glades",
	unlock = {
		{
			type = "subzone",
			name = "Brill",
			areas = { 159 },
		},
		{
			type = "subzone",
			name = "Gallows' End Tavern",
			areas = { 2119 },
		},
		{
			type = "subzone",
			name = "Brill Town Hall",
			areas = { 2118 },
		},
	},
	regionKind = "place",
	kind = "region",
	sections = {
		{
			title = "Summary",
			text = [=[Brill is the chief town of the {link:forsaken}Forsaken{/link} in {link:tirisfal-glades}Tirisfal{/link}, on the road between {link:deathknell}Deathknell{/link} and the {link:undercity}Undercity{/link}. Its town hall is the seat of {link:magistrate-sevren}Magistrate Sevren{/link} and {link:executor-zygand}Executor Zygand{/link}, who command the Deathguard of the glades. Its graveyard is tended by junior apothecaries, and its inn, the Gallows' End Tavern, keeps a cellar where captured humans and dwarves wait for the apothecaries' experiments. Not far from the town, the zeppelins of the {link:horde}Horde{/link} rise from their towers, and in these days even a trainer of Forsaken paladins keeps a place in Brill.]=],
		},
	},
})

Add({
	id = "agamand-mills",
	title = "Agamand Mills",
	aliases = { "Agamand Family Crypt" },
	parent = "tirisfal-glades",
	unlock = {
		{
			type = "subzone",
			name = "Agamand Mills",
			areas = { 157 },
		},
		{
			type = "subzone",
			name = "Agamand Family Crypt",
			areas = { 158 },
		},
	},
	regionKind = "place",
	kind = "region",
	sections = {
		{
			title = "Summary",
			text = [=[The Agamand Mills stand in the highlands of northern {link:tirisfal-glades}Tirisfal{/link}. They were the wealth of the Agamand family, the richest house in the glades. When the plague came, the Agamands fortified their home and bade their workers stay and fight. All of them died, and all of them rose. Now the mills are the strongest outpost of the {link:scourge}Scourge{/link} in Tirisfal. At their northern end lies the Agamand Family Crypt, where a skeletal captain named Dargol has raised the family's ancestors to fight for the Lich King.]=],
		},
	},
})

Add({
	id = "solliden-farmstead",
	title = "Solliden Farmstead",
	aliases = { "Solliden" },
	parent = "tirisfal-glades",
	unlock = {
		{
			type = "subzone",
			name = "Solliden Farmstead",
			areas = { 156 },
		},
	},
	regionKind = "place",
	kind = "region",
	sections = {
		{
			title = "Summary",
			text = [=[The Solliden Farmstead lies in western {link:tirisfal-glades}Tirisfal{/link}, north of {link:deathknell}Deathknell{/link}. It is one of the last places in the glades where living humans still work the fields. The pumpkins still grow, and the farmers still bring in their harvest, because the {link:scarlet-crusade}Scarlet Crusade{/link} guards them from a tower to the west. The {link:forsaken}Forsaken{/link} hate the farm for its life. The apothecaries of {link:brill}Brill{/link} find a use for its pumpkins all the same. On the bluffs to the north-west rises {link:bandarion-keep}Bandarion Keep{/link}.]=],
		},
	},
})

Add({
	id = "garren-s-haunt",
	title = "Garren's Haunt",
	parent = "tirisfal-glades",
	unlock = {
		{
			type = "subzone",
			name = "Garren's Haunt",
			areas = { 164 },
		},
	},
	regionKind = "place",
	kind = "region",
	sections = {
		{
			title = "Summary",
			text = [=[Garren's Haunt is a farmstead in the north of {link:tirisfal-glades}Tirisfal{/link}, with a farmhouse, a barn and wide grey fields. No chronicle records who Garren was. The Rot Hide gnolls hold the farm now. They serve the {link:scourge}Scourge{/link} and rob the Mass Graves to the south-west, where the dead of the first plague were buried. Their leader is a {link:gnolls}gnoll{/link} called Maggot Eye, and the town of {link:brill}Brill{/link} has sentenced him to death for his crimes against the {link:forsaken}Forsaken{/link}. {link:executor-zygand}Executor Zygand{/link} has promised a reward to whoever carries out the sentence and brings back his paw.]=],
		},
	},
})

Add({
	id = "venomweb-vale",
	title = "Venomweb Vale",
	parent = "tirisfal-glades",
	unlock = {
		{
			type = "subzone",
			name = "Venomweb Vale",
			areas = { 812 },
		},
	},
	regionKind = "place",
	kind = "region",
	sections = {
		{
			title = "Summary",
			text = [=[Venomweb Vale is a wide valley in the far east of {link:tirisfal-glades}Tirisfal{/link}, below the heights of the {link:scarlet-monastery}Scarlet Monastery{/link}. Its woods are thick with webs. The great spiders that nest there carry a venom that the apothecaries of {link:brill}Brill{/link} believe once preserved an ancient plague. Of late the Deathguard have also seen a rogue abomination wandering near the vale. Such a creature should not have passed the {link:the-bulwark}Bulwark{/link} unnoticed, and the Deathguard keep the matter quiet. At the northern edge of the vale, the {link:scarlet-crusade}Scarlet Crusade{/link} keeps a camp of its own.]=],
		},
	},
})

Add({
	id = "scarlet-watch-post",
	title = "Scarlet Watch Post",
	parent = "tirisfal-glades",
	unlock = {
		{
			type = "subzone",
			name = "Scarlet Watch Post",
			areas = { 459 },
		},
	},
	regionKind = "place",
	kind = "region",
	sections = {
		{
			title = "Summary",
			text = [=[The Scarlet Watch Post is a tower of the {link:scarlet-crusade}Scarlet Crusade{/link} in the north-east of {link:tirisfal-glades}Tirisfal{/link}, beyond Faol's Rest. It watches the northern approaches of the {link:scarlet-monastery}Scarlet Monastery{/link}. Its commander, Captain Melrache, is known to the {link:forsaken}Forsaken{/link} as a ruthless man, and he never goes without his two bodyguards. The tower is one of several that the Crusade keeps across the glades. From each of them its patrols ride out to burn the dead. Captain Perrine holds a ruined tower south-west of {link:brill}Brill{/link}, and Captain Vachon another in the south-east, near the Balnir Farmstead.]=],
		},
	},
})

Add({
	id = "brightwater-lake",
	title = "Brightwater Lake",
	aliases = { "Gunther's Retreat" },
	parent = "tirisfal-glades",
	unlock = {
		{
			type = "subzone",
			name = "Brightwater Lake",
			areas = { 162 },
		},
		{
			type = "subzone",
			name = "Gunther's Retreat",
			areas = { 163 },
		},
	},
	regionKind = "place",
	kind = "region",
	sections = {
		{
			title = "Summary",
			text = [=[Brightwater Lake is the largest lake in {link:tirisfal-glades}Tirisfal{/link}, north-east of {link:brill}Brill{/link}. On an island at its heart stands Gunther's Retreat, the camp of a lich named {link:gunther-arcanus}Gunther Arcanus{/link}. He is free of the Lich King, yet he believed for a long time that he was the only one, and his servants attacked all who came near. Off the island's southern shore stands an old bloody altar. The {link:scourge}Scourge{/link} agent {link:lillith-nefara}Lillith Nefara{/link} sleeps there until a candle of beckoning wakes her.]=],
		},
	},
})

Add({
	id = "capital-city",
	title = "Capital City",
	aliases = { "Lordaeron City" },
	parent = "tirisfal-glades",
	unlock = {
		{
			type = "subzone",
			name = "Ruins of Lordaeron",
			areas = { 153 },
		},
	},
	regionKind = "place",
	kind = "region",
	sections = {
		{
			title = "Summary",
			text = [=[The ruins of Capital City stand on the eastern edge of {link:tirisfal-glades}Tirisfal{/link}. For centuries it was the seat of the kings of {link:lordaeron}Lordaeron{/link}. Here Prince {link:arthas-menethil}Arthas Menethil{/link} came home from Northrend and slew his father on his throne. The city was sacked and left in ruins. Its broken walls and its empty throne room now guard the way down to the {link:undercity}Undercity{/link}, the city of the {link:forsaken}Forsaken{/link} beneath it. Parts of the old streets are still not theirs. {link:scourge}Scourge{/link} forces linger in the eastern ruins, and the Forsaken fight to take them back.]=],
		},
	},
})

Add({
	id = "whispering-forest",
	title = "Whispering Forest",
	parent = "tirisfal-glades",
	unlock = {
		{ type = "subzone", name = "Whispering Forest" },
	},
	regionKind = "place",
	kind = "region",
	sections = {
		{
			title = "Summary",
			text = [=[The Whispering Forest lies in the mountains of western {link:tirisfal-glades}Tirisfal{/link}, below the cliff called {link:bandarion-keep}Northface Rock{/link}. Its woods are dark and its roots are said to run deep. Some folk in the {link:undercity}Undercity{/link} say that the forest is touched by the void, and that things crawl beneath it that should not. Diseased stags and does wander its glades. By a ring of great mushrooms walks a ghostly knight bound there by an oath. To the south-west lie the ruins of {link:shadowvale}Shadowvale{/link}, and above it all stands Bandarion Keep.]=],
		},
	},
})

Add({
	id = "bandarion-keep",
	title = "Bandarion Keep",
	aliases = { "Northface Rock" },
	parent = "tirisfal-glades",
	unlock = {
		{ type = "subzone", name = "Bandarion Keep" },
	},
	regionKind = "place",
	kind = "region",
	sections = {
		{
			title = "Summary",
			text = [=[Bandarion Keep is the monastery of {link:tyr-s-watch}Tyr's Watch{/link}, the order of {link:forsaken}Forsaken{/link} paladins. It stands on Northface Rock, the steep bluff between the {link:whispering-forest}Whispering Forest{/link} and the rest of {link:tirisfal-glades}Tirisfal{/link}. In the last war the {link:argent-dawn}Argent Dawn{/link} held it against the {link:scourge}Scourge{/link}. When the Dawn withdrew to the Plaguelands, the fortress fell into ruin, and the Vile Fin murlocs made it a spawning ground. {link:danitha-morr}Danitha Morr{/link} and her paladins drove them out and began to rebuild. She named the keep after {link:garek-bandarion}Garek Bandarion{/link}, the first of the Forsaken to take up the {link:holy-light}Holy Light{/link} again.]=],
		},
	},
})

Add({
	id = "shadowvale",
	title = "Shadowvale",
	parent = "tirisfal-glades",
	unlock = {
		{ type = "subzone", name = "Shadowvale" },
	},
	regionKind = "place",
	kind = "region",
	sections = {
		{
			title = "Summary",
			text = [=[Shadowvale is a ruined village deep in the {link:whispering-forest}Whispering Forest{/link}, south-west of {link:bandarion-keep}Bandarion Keep{/link}. Its folk were strange and private in life, and they did not welcome visitors. Now the village belongs to the Tarnished, risen paladins who turn the Light against their own people. Mindless dead gather in the cellars beneath it. A cultist is said to have carried a shard of the necropolis crystal down there, and whatever it does, it makes the dead stronger or more numerous.]=],
		},
	},
})

Add({
	kind = "topic",
	id = "tyr-s-watch",
	title = "Tyr's Watch",
	category = "group",
	region = "tirisfal-glades",
	unlock = {
		{ type = "read" },
		{ type = "quest", id = 91282 },
		{ type = "subzone", name = "Bandarion Keep" },
	},
	sections = {
		{
			title = "Summary",
			text = [=[Tyr's Watch is an order of {link:forsaken}Forsaken{/link} paladins, newly founded in {link:tirisfal-glades}Tirisfal Glades{/link}. Its members were servants of the {link:holy-light}Holy Light{/link} in life. They died, rose, and found that the Light still answered them, though its touch now burns their flesh. They keep their monastery at {link:bandarion-keep}Bandarion Keep{/link}, and {link:danitha-morr}Danitha Morr{/link} leads them.]=],
		},
		{
			title = "Beliefs",
			text = [=[The paladins of Tyr's Watch teach that pain is no reason to turn from the Light. Healing hurts them, so they learn to heal through the pain, and they call it a crucible. They teach that the pursuit of good for its own sake is the heart of their calling. They seek out the wretched and the forgotten of the {link:undercity}Undercity{/link} and help them in small ways, because they believe that small acts also bind them to the Light.]=],
		},
		{
			title = "The Order and Its People",
			text = [=[The {link:forsaken}Forsaken{/link} remember well what the living did to them in the name of the Light. Many fear that a paladin will one day smite them as a monster. Some risen paladins do exactly that. The order calls them the Tarnished, and it hunts them. The Dark Lady herself mistrusts Tyr's Watch and has told its paladins that she is watching. {link:danitha-morr}Danitha{/link} believes it may take years, or decades, before her order is fully trusted. She means to earn that trust anyway.]=],
		},
	},
})

Add({
	kind = "figure",
	id = "shadow-priest-sarvis",
	title = "Shadow Priest Sarvis",
	aliases = { "Sarvis" },
	subtitle = "Priest of Deathknell",
	tier = "C",
	region = "tirisfal-glades",
	npc = { 1569 },
	allegiance = "Forsaken",
	found = "The chapel of Deathknell",
	pin = { x = 30.8, y = 66.2 },
	unlock = {
		{ type = "interact" },
	},
	hint = "Speak with the shadow priest in the chapel of Deathknell.",
	sections = {
		{
			title = "Summary",
			text = [=[Shadow Priest Sarvis keeps the chapel at the foot of the hill in {link:deathknell}Deathknell{/link}. When the newly risen stumble out of the crypt, cold and confused, it is Sarvis who tells them the truth. They are dead. They are free of the Lich King. And they belong now to {link:sylvanas-windrunner}the Dark Lady{/link}, who leads the {link:forsaken}Forsaken{/link} in their war against the {link:scourge}Scourge{/link} and against the humans who hunt them.]=],
		},
		{
			title = "Significance",
			text = [=[Sarvis gives the new {link:forsaken}Forsaken{/link} their first purpose. He sends them against the mindless dead of the village, the former brothers and sisters who could not be brought into the fold.]=],
		},
		{
			title = "Deeds",
			text = [=[• He welcomes the risen who wake in the crypt of {link:deathknell}Deathknell{/link}.
• He sends them to destroy the mindless zombies and the Rattlecage skeletons.]=],
		},
	},
	mentions = {
		{
			text = "Rude Awakening",
			unlock = {
				{ type = "quest", id = 363 },
			},
		},
		{
			text = "The Mindless Ones",
			unlock = {
				{ type = "quest", id = 364 },
			},
		},
		{
			text = "Rattling the Rattlecages",
			unlock = {
				{ type = "quest", id = 3901 },
			},
		},
	},
	bonds = {
		{ id = "undertaker-mordo", name = "Undertaker Mordo", note = "sends the risen to him" },
		{ id = "executor-arren", name = "Executor Arren", note = "commands Deathknell" },
	},
})

Add({
	kind = "figure",
	id = "undertaker-mordo",
	title = "Undertaker Mordo",
	aliases = { "Mordo" },
	subtitle = "Caretaker of the Crypt",
	tier = "C",
	region = "tirisfal-glades",
	npc = { 1568 },
	allegiance = "Forsaken",
	found = "Before the crypt of Deathknell",
	pin = { x = 30.2, y = 71.7 },
	unlock = {
		{ type = "interact" },
	},
	hint = [=[Speak with the undertaker who waits outside the crypt of Deathknell.]=],
	sections = {
		{
			title = "Summary",
			text = [=[Mordo is the undertaker of {link:deathknell}Deathknell{/link} and the caretaker of its crypt. He is often the first face a new {link:forsaken}Forsaken{/link} sees. He does not pretend that the waking is gentle. The bodies that do not stir are burned, and he says plainly that many who rise very nearly went into the fire with them.]=],
		},
		{
			title = "Significance",
			text = [=[Mordo stands at the threshold of the {link:forsaken}Forsaken{/link}'s second life. Everyone who wakes in {link:deathknell}Deathknell{/link} passes through his hands, and he sends each of them to the chapel below.]=],
		},
		{
			title = "Deeds",
			text = [=[• He keeps the crypt of {link:deathknell}Deathknell{/link} and tends the dead brought there.
• He sends the newly risen to {link:shadow-priest-sarvis}Shadow Priest Sarvis{/link}.]=],
		},
	},
	mentions = {
		{
			text = "Rude Awakening",
			unlock = {
				{ type = "quest", id = 363 },
			},
		},
	},
	bonds = {
		{ id = "shadow-priest-sarvis", name = "Shadow Priest Sarvis", note = "receives the risen" },
	},
})

Add({
	kind = "figure",
	id = "executor-arren",
	title = "Executor Arren",
	aliases = { "Arren" },
	subtitle = "Executor of Deathknell",
	tier = "C",
	region = "tirisfal-glades",
	npc = { 1570 },
	allegiance = "Forsaken · Deathguard",
	found = "Deathknell",
	pin = { x = 32.2, y = 66.0 },
	unlock = {
		{ type = "interact" },
	},
	hint = "Speak with the executor who commands Deathknell.",
	sections = {
		{
			title = "Summary",
			text = [=[Executor Arren commands {link:deathknell}Deathknell{/link}. He has few soldiers and many troubles. Spiders have overrun the gold mine his people need, and a camp of the {link:scarlet-crusade}Scarlet Crusade{/link} has sprung up to the south-east. He answers to {link:executor-zygand}Executor Zygand{/link} in {link:brill}Brill{/link}, and he sends every capable recruit to deal with what his Deathguard cannot.]=],
		},
		{
			title = "Significance",
			text = [=[Arren is a practical commander. He mocks the zealots who will not listen to reason, and he knows the value of a captured letter.]=],
		},
		{
			title = "Deeds",
			text = [=[• He orders the spiders cleared from the mine of Night Web's Hollow.
• He strikes at the Crusade's camp near {link:deathknell}Deathknell{/link}.
• He sends the messenger's stolen papers to {link:brill}Brill{/link}.]=],
		},
	},
	chapters = {
		{
			key = "the-red-messenger",
			title = "The Red Messenger",
			hint = "Stop the Scarlet messenger sent to Deathknell.",
			unlock = {
				{ type = "quest", id = 382 },
			},
			text = [=[Word came from {link:brill}Brill{/link} that the {link:scarlet-monastery}Scarlet Monastery{/link} had sent a messenger to the crusaders near {link:deathknell}Deathknell{/link}. Arren had him hunted down. Most of the papers he carried were worthless. One was not: a map of the Crusade's commanders and agents across the glades.]=],
		},
	},
	mentions = {
		{
			text = "Night Web's Hollow",
			unlock = {
				{ type = "quest", id = 380 },
			},
		},
		{
			text = "The {link:scarlet-crusade}Scarlet Crusade{/link}",
			unlock = {
				{ type = "quest", id = 381 },
			},
		},
		{
			text = "The Red Messenger",
			unlock = {
				{ type = "quest", id = 382 },
			},
		},
		{
			text = "Vital Intelligence",
			unlock = {
				{ type = "quest", id = 383 },
			},
		},
	},
	bonds = {
		{ id = "executor-zygand", name = "Executor Zygand", note = "his superior" },
		{ id = "aramis-hammerhand", name = "Aramis Hammerhand", note = "a paladin he distrusts" },
	},
})

Add({
	kind = "figure",
	id = "deathguard-saltain",
	title = "Deathguard Saltain",
	aliases = { "Saltain" },
	subtitle = "Deathguard of Deathknell",
	tier = "C",
	region = "tirisfal-glades",
	npc = { 1740 },
	allegiance = "Forsaken · Deathguard",
	found = "Deathknell",
	pin = { x = 31.6, y = 65.6 },
	unlock = {
		{ type = "interact" },
	},
	hint = "Speak with the loud Deathguard of Deathknell.",
	sections = {
		{
			title = "Summary",
			text = [=[Deathguard Saltain has the voice and temper of a drill sergeant. New {link:forsaken}Forsaken{/link} rise in {link:deathknell}Deathknell{/link} every day, and most of them rise with nothing at all. Saltain wants them clothed and armed before they stumble off to war, so he sets the fresh recruits to searching the village for anything useful. He has no patience for the slow.]=],
		},
		{
			title = "Significance",
			text = [=[Saltain shows the {link:forsaken}Forsaken{/link} at their most practical. Nothing is wasted in {link:deathknell}Deathknell{/link}, not even the gear of the dead.]=],
		},
		{
			title = "Deeds",
			text = [=[• He gathers scavenged goods for the recruits yet to rise.
• He rewards the diligent with the best of what has been found.]=],
		},
	},
	mentions = {
		{
			text = "Scavenging {link:deathknell}Deathknell{/link}",
			unlock = {
				{ type = "quest", id = 3902 },
			},
		},
	},
	bonds = {
		{ id = "executor-arren", name = "Executor Arren", note = "his commander" },
	},
})

Add({
	kind = "figure",
	id = "novice-elreth",
	title = "Novice Elreth",
	aliases = { "Elreth" },
	subtitle = "Tender of the Wounded",
	tier = "C",
	region = "tirisfal-glades",
	npc = { 1661 },
	allegiance = "Forsaken",
	found = "The chapel of Deathknell",
	pin = { x = 30.9, y = 66.1 },
	unlock = {
		{ type = "interact" },
	},
	hint = "Speak with the novice who tends the wounded in Deathknell.",
	sections = {
		{
			title = "Summary",
			text = [=[Novice Elreth tends the wounded of {link:deathknell}Deathknell{/link}, sews armor and clothing, and serves {link:shadow-priest-sarvis}Shadow Priest Sarvis{/link} in whatever he needs. She was the friend of a woman named Marla Fipps, and she remembers Marla's story. Marla's husband Samuel died of the plague and rose among the {link:scourge}Scourge{/link}. Marla escaped the plague only to die at his hands. Her last wish was to be buried with him.]=],
		},
		{
			title = "Significance",
			text = [=[Elreth is one of the few in {link:deathknell}Deathknell{/link} who still speaks of love. She asks that Marla's wish be granted.]=],
		},
		{
			title = "Deeds",
			text = [=[• She makes armor for the new risen from the paws and wings of beasts.
• She seeks to lay {link:samuel-fipps}Samuel Fipps{/link} in his wife's grave.]=],
		},
	},
	mentions = {
		{
			text = "The Damned",
			unlock = {
				{ type = "quest", id = 376 },
			},
		},
		{
			text = "Marla's Last Wish",
			unlock = {
				{ type = "quest", id = 6395 },
			},
		},
	},
	bonds = {
		{ id = "samuel-fipps", name = "Samuel Fipps", note = "husband of her friend" },
		{ id = "shadow-priest-sarvis", name = "Shadow Priest Sarvis", note = "she serves him" },
	},
})

Add({
	kind = "figure",
	id = "samuel-fipps",
	title = "Samuel Fipps",
	subtitle = "The Husband of Marla",
	tier = "C",
	region = "tirisfal-glades",
	npc = { 1919 },
	allegiance = "Scourge",
	found = "A ruined camp on the road north-east of Deathknell",
	pin = { x = 36.7, y = 61.6 },
	unlock = {
		{ type = "target" },
	},
	hint = [=[Find the mindless husband who roams a ruined camp north-east of Deathknell.]=],
	sections = {
		{
			title = "Summary",
			text = [=[Samuel Fipps lived with his wife Marla before the plague. The plague took him, and he rose as a mindless servant of the {link:scourge}Scourge{/link}. Marla was spared that fate, but not his. She died at the hands of the husband she loved. Samuel still wanders a ruined camp by the road north-east of {link:deathknell}Deathknell{/link}, with no memory of what he was or what he did.]=],
		},
		{
			title = "Significance",
			text = [=[Samuel's tale is one of the saddest in {link:deathknell}Deathknell{/link}, for he never knew what he had done. It ends only when his remains are buried in the first row of the village graveyard, in the grave of his wife.]=],
		},
	},
	mentions = {
		{
			text = "Marla's Last Wish",
			unlock = {
				{ type = "quest", id = 6395 },
			},
		},
	},
	bonds = {
		{ id = "novice-elreth", name = "Novice Elreth", note = "friend of his wife" },
	},
})

Add({
	kind = "figure",
	id = "aramis-hammerhand",
	title = "Aramis Hammerhand",
	aliases = { "Aramis" },
	subtitle = "Paladin of Deathknell",
	tier = "C",
	region = "tirisfal-glades",
	npc = { 244808 },
	allegiance = "Tyr's Watch · Forsaken",
	found = "The chapel of Deathknell",
	unlock = {
		{ type = "interact" },
	},
	hint = "Speak with the paladin who trains the risen in Deathknell.",
	sections = {
		{
			title = "Summary",
			text = [=[Aramis Hammerhand is a {link:forsaken}Forsaken{/link} paladin who trains the newly risen servants of the Light in {link:deathknell}Deathknell{/link}. He tells them that not even death can stop the Light, and that its touch will hurt them now. They must endure it and grow strong through it. He knows that many Forsaken fear his kind, and he does what he can to prove that paladins do not mean them harm.]=],
		},
		{
			title = "Significance",
			text = [=[Aramis is the first teacher of {link:tyr-s-watch}Tyr's Watch{/link} that most risen paladins ever meet.]=],
		},
		{
			title = "Deeds",
			text = [=[• He frees newly risen {link:forsaken}Forsaken{/link} caught in the webs of Night Web's Hollow.
• He sends the frightened and the lost back to the Light, or grants them a clean end.
• He sends his students on to {link:brill}Brill{/link}.]=],
		},
	},
	mentions = {
		{
			text = "Rediscovering the Light",
			unlock = {
				{ type = "quest", id = 90902 },
			},
		},
		{
			text = "Coming to Terms",
			unlock = {
				{ type = "quest", id = 91208 },
			},
		},
		{
			text = "A Light in the Darkness",
			unlock = {
				{ type = "quest", id = 98389 },
			},
		},
		{
			text = "Continue Your Training",
			unlock = {
				{ type = "quest", id = 91209 },
			},
		},
	},
	bonds = {
		{ id = "executor-arren", name = "Executor Arren", note = "distrusts paladins" },
		{ id = "danitha-morr", name = "Danitha Morr", note = "leads his order" },
	},
})

Add({
	kind = "figure",
	id = "apothecary-johaan",
	title = "Apothecary Johaan",
	aliases = { "Johaan" },
	subtitle = "Apothecary of Brill",
	tier = "C",
	region = "tirisfal-glades",
	npc = { 1518 },
	allegiance = "Royal Apothecary Society",
	found = "Brill",
	pin = { x = 59.4, y = 52.4 },
	unlock = {
		{ type = "interact" },
	},
	hint = "Find the apothecary who works in Brill.",
	sections = {
		{
			title = "Summary",
			text = [=[Apothecary Johaan serves the {link:royal-apothecary-society}Royal Apothecary Society{/link} in {link:brill}Brill{/link}. The Dark Lady has challenged the Society to brew a new plague, deadlier than any disease in the world, to bring ruin to the armies of {link:arthas-menethil}Arthas{/link}. Johaan pursues that task with patience and pleasure. He gathers blood, scales and venom from the beasts of {link:tirisfal-glades}Tirisfal{/link}, and he tests his brews on the prisoners in the cellar of the Gallows' End Tavern.]=],
		},
		{
			title = "Significance",
			text = [=[Johaan shows what the Society's work means in practice. The plague is meant for the {link:scourge}Scourge{/link}, but he takes quiet delight in its promise for the rest of {link:azeroth}Azeroth{/link}.]=],
		},
		{
			title = "Deeds",
			text = [=[• He brews a new plague from darkhound blood, {link:murlocs}murloc{/link} scales and spider venom.
• He poisons a captured {link:dwarves}dwarf{/link} and a captured zealot with his brews.
• He shares his findings with the apothecaries of {link:silverpine-forest}Silverpine{/link}.]=],
		},
	},
	mentions = {
		{
			text = "Fields of Grief",
			unlock = {
				{ type = "quest", id = 407 },
			},
		},
		{
			text = "A New Plague",
			unlock = {
				{ type = "quest", id = 367 },
			},
		},
		{
			text = "A New Plague",
			unlock = {
				{ type = "quest", id = 369 },
			},
		},
		{
			text = "A New Plague",
			unlock = {
				{ type = "quest", id = 492 },
			},
		},
		{
			text = "Delivery to {link:silverpine-forest}Silverpine Forest{/link}",
			unlock = {
				{ type = "quest", id = 445 },
			},
		},
	},
	bonds = {
		{ id = "master-apothecary-faranell", name = "Master Apothecary Faranell", note = "master of his Society" },
		{ id = "sylvanas-windrunner", name = "Sylvanas Windrunner", note = "set the Society its task" },
	},
})

Add({
	kind = "figure",
	id = "coleman-farthing",
	title = "Coleman Farthing",
	aliases = { "Coleman" },
	subtitle = "Former Worker of the Mills",
	tier = "C",
	region = "tirisfal-glades",
	npc = { 1500 },
	allegiance = "Forsaken",
	found = "The Gallows' End Tavern, Brill",
	pin = { x = 61.7, y = 52.3 },
	unlock = {
		{ type = "interact" },
	},
	hint = [=[Find the Forsaken who drinks to revenge in the Gallows' End Tavern.]=],
	sections = {
		{
			title = "Summary",
			text = [=[Coleman Farthing worked the {link:agamand-mills}Agamand Mills{/link} in life. When the plague came, the Agamands fortified their home and persuaded their workers to stay and defend it. Coleman stayed. He died, and he rose. Now he blames the Agamands for his undeath, and he wants their remains. He keeps their bones as trophies, and his only warmth is the knowledge that the family is destroyed.]=],
		},
		{
			title = "Significance",
			text = [=[Coleman shows how the {link:forsaken}Forsaken{/link} remember their old lives. He does not grieve. He hates.]=],
		},
		{
			title = "Deeds",
			text = [=[• He collects the remains of the Agamands, one by one.
• He sends others to rob the family crypt of its heirlooms.
• He speaks well of those who serve him to {link:magistrate-sevren}Magistrate Sevren{/link}.]=],
		},
	},
	mentions = {
		{
			text = "Deaths in the Family",
			unlock = {
				{ type = "quest", id = 354 },
			},
		},
		{
			text = "The Haunted Mills",
			unlock = {
				{ type = "quest", id = 362 },
			},
		},
		{
			text = "Speak with {link:magistrate-sevren}Sevren{/link}",
			unlock = {
				{ type = "quest", id = 355 },
			},
		},
		{
			text = "Agamand Heirlooms",
			unlock = {
				{ type = "quest", id = 1821 },
			},
		},
	},
	bonds = {
		{ id = "gregor-agamand", name = "Gregor Agamand", note = "his old master" },
		{ id = "yvette-farthing", name = "Yvette Farthing", note = "of the same name" },
		{ id = "magistrate-sevren", name = "Magistrate Sevren", note = "hears his reports" },
	},
})

Add({
	kind = "figure",
	id = "yvette-farthing",
	title = "Yvette Farthing",
	aliases = { "Yvette" },
	subtitle = "A Forsaken of Brill",
	tier = "C",
	region = "tirisfal-glades",
	npc = { 1560 },
	allegiance = "Forsaken",
	found = "The Gallows' End Tavern, Brill",
	pin = { x = 61.6, y = 52.6 },
	unlock = {
		{ type = "interact" },
	},
	hint = [=[Find the woman in the Gallows' End Tavern to whom a letter was never delivered.]=],
	sections = {
		{
			title = "Summary",
			text = [=[In life, Yvette Farthing loved {link:thurman-agamand}Thurman Agamand{/link}, the eldest son of the family. When the plague came she begged him to leave the mills with her and her father. He would not abandon his family. Thurman wrote her a letter that never reached her. When it finally does, she weeps for a moment. Then her face grows cold. Love, she says, has no place among the {link:forsaken}Forsaken{/link}.]=],
		},
		{
			title = "Significance",
			text = [=[Yvette's story is a small picture of the {link:forsaken}Forsaken{/link}'s choice: to put away the life that was lost, even when it still hurts.]=],
		},
		{
			title = "Deeds",
			text = [=[• She suspected that a man named Brand meant {link:thurman-agamand}Thurman{/link} harm.]=],
		},
	},
	mentions = {
		{
			text = "A Letter Undelivered",
			unlock = {
				{ type = "quest", id = 361 },
			},
		},
	},
	bonds = {
		{ id = "thurman-agamand", name = "Thurman Agamand", note = "her love in life" },
		{ id = "coleman-farthing", name = "Coleman Farthing", note = "of the same name" },
	},
})

Add({
	kind = "figure",
	id = "magistrate-sevren",
	title = "Magistrate Sevren",
	aliases = { "Sevren" },
	subtitle = "Magistrate of Brill",
	tier = "C",
	region = "tirisfal-glades",
	npc = { 1499 },
	allegiance = "Forsaken",
	found = "Brill Town Hall",
	pin = { x = 61.3, y = 50.8 },
	unlock = {
		{ type = "interact" },
	},
	hint = "Speak with the magistrate in the town hall of Brill.",
	sections = {
		{
			title = "Summary",
			text = [=[Magistrate Sevren governs {link:brill}Brill{/link} from its town hall. He keeps the records of the dead of {link:tirisfal-glades}Tirisfal{/link}, and he watches the east, where the defenders of the {link:the-bulwark}Bulwark{/link} hold back the {link:scourge}Scourge{/link} of the Plaguelands. He fears most an attack from the rear, and he sends his agents to find the Scourge that slip past the wall.]=],
		},
		{
			title = "Significance",
			text = [=[Sevren is the steady hand of {link:forsaken}Forsaken{/link} rule in the glades. Even the mage {link:bethor-iceshard}Bethor Iceshard{/link} of the {link:undercity}Undercity{/link} sends to him when he needs a proven agent.]=],
		},
		{
			title = "Deeds",
			text = [=[• He sends patrols east toward the {link:the-bulwark}Bulwark{/link} and the Balnir Farmstead.
• He sends fighters against the Rot Hide graverobbers and the crypt of the Agamands.
• He sends an agent to {link:bethor-iceshard}Bethor Iceshard{/link} to recruit a wayward lich.]=],
		},
	},
	mentions = {
		{
			text = "Speak with Sevren",
			unlock = {
				{ type = "quest", id = 355 },
			},
		},
		{
			text = "Graverobbers",
			unlock = {
				{ type = "quest", id = 358 },
			},
		},
		{
			text = "{link:forsaken}Forsaken{/link} Duties",
			unlock = {
				{ type = "quest", id = 359 },
			},
		},
		{
			text = "The Family Crypt",
			unlock = {
				{ type = "quest", id = 408 },
			},
		},
		{
			text = "The Prodigal Lich",
			unlock = {
				{ type = "quest", id = 405 },
			},
		},
		{
			text = "The Engraved Ring",
			unlock = {
				{ type = "quest", id = 440 },
			},
		},
	},
	bonds = {
		{ id = "executor-zygand", name = "Executor Zygand", note = "shares the town hall" },
		{ id = "bethor-iceshard", name = "Bethor Iceshard", note = "his superior in the Undercity" },
		{ id = "coleman-farthing", name = "Coleman Farthing", note = "speaks for his agents" },
	},
})

Add({
	kind = "figure",
	id = "executor-zygand",
	title = "Executor Zygand",
	aliases = { "Zygand" },
	subtitle = "Executor of Brill",
	tier = "C",
	region = "tirisfal-glades",
	npc = { 1515 },
	allegiance = "Forsaken · Deathguard",
	found = "Brill Town Hall",
	pin = { x = 60.6, y = 51.8 },
	unlock = {
		{ type = "interact" },
	},
	hint = [=[Speak with the executor who commands the Deathguard of Brill.]=],
	sections = {
		{
			title = "Summary",
			text = [=[Executor Zygand commands the Deathguard of {link:tirisfal-glades}Tirisfal{/link} from {link:brill}Brill{/link}. It is his duty, he says, to see {link:sylvanas-windrunner}the Dark Lady{/link}'s will done perfectly. He keeps a ledger of his soldiers' failings and enjoys their punishment. He plans the war against the {link:scarlet-crusade}Scarlet Crusade{/link} from the papers taken at {link:deathknell}Deathknell{/link}, and he means to strike down its captains one by one.]=],
		},
		{
			title = "Significance",
			text = [=[Zygand is the cold face of {link:forsaken}Forsaken{/link} discipline. He finds few delights in death, and pain is chief among them.]=],
		},
		{
			title = "Deeds",
			text = [=[• He orders the deaths of the Crusade's captains in their towers.
• He punishes his own Deathguard for their lapses.
• He pays the bounty on Maggot Eye.]=],
		},
	},
	mentions = {
		{
			text = "Vital Intelligence",
			unlock = {
				{ type = "quest", id = 383 },
			},
		},
		{
			text = "At War With The {link:scarlet-crusade}Scarlet Crusade{/link}",
			unlock = {
				{ type = "quest", id = 370 },
			},
		},
		{
			text = "At War With The {link:scarlet-crusade}Scarlet Crusade{/link}",
			unlock = {
				{ type = "quest", id = 372 },
			},
		},
		{
			text = "WANTED: Maggot Eye",
			unlock = {
				{ type = "quest", id = 398 },
			},
		},
		{
			text = "Discipline",
			unlock = {
				{ type = "quest", id = 99134 },
			},
		},
		{
			text = "Patience",
			unlock = {
				{ type = "quest", id = 99141 },
			},
		},
	},
	bonds = {
		{ id = "executor-arren", name = "Executor Arren", note = "reports to him" },
		{ id = "magistrate-sevren", name = "Magistrate Sevren", note = "shares the town hall" },
	},
})

Add({
	kind = "figure",
	id = "gordo",
	title = "Gordo",
	subtitle = "Abomination of Brill",
	tier = "C",
	region = "tirisfal-glades",
	npc = { 10666 },
	allegiance = "Royal Apothecary Society",
	found = "The fields west of Brill",
	pin = { x = 43.1, y = 54.7 },
	unlock = {
		{ type = "interact" },
	},
	hint = [=[Look for the abomination who gathers weeds in the fields west of Brill.]=],
	sections = {
		{
			title = "Summary",
			text = [=[Gordo is an abomination who serves the apothecaries of {link:brill}Brill{/link}. His master sends him to gather weeds, and Gordo, with his big hands, asks passers-by to pick them for him. He usually gathers the wrong ones. His master, Junior Apothecary Holland, finds him more trouble than help.]=],
		},
		{
			title = "Significance",
			text = [=[Gordo is an old servant of the {link:forsaken}Forsaken{/link}. In the first days of the {link:undercity}Undercity{/link}, he wandered off and was lost in the glades, and he had to be found and brought home.]=],
		},
		{
			title = "Deeds",
			text = [=[• He gathers gloom weed for his master, who wanted doom weed.
• He was once asked to write a report for {link:executor-zygand}Executor Zygand{/link}. Nothing useful came of it.]=],
		},
	},
	mentions = {
		{
			text = "Gordo's Task",
			unlock = {
				{ type = "quest", id = 5481 },
			},
		},
		{
			text = "Patience",
			unlock = {
				{ type = "quest", id = 99141 },
			},
		},
	},
	bonds = {
		{ id = "garek-bandarion", name = "Garek Bandarion", note = "once found him" },
		{ id = "dark-ranger-anya", name = "Dark Ranger Anya", note = "once found him" },
	},
})

Add({
	kind = "figure",
	id = "gunther-arcanus",
	title = "Gunther Arcanus",
	aliases = { "Gunther" },
	subtitle = "The Lich of Brightwater Lake",
	tier = "C",
	region = "tirisfal-glades",
	npc = { 1497 },
	allegiance = "Forsaken",
	found = "Gunther's Retreat, on the island in Brightwater Lake",
	pin = { x = 68.2, y = 41.9 },
	unlock = {
		{ type = "interact" },
	},
	hint = "Seek the lich who dwells on the island in Brightwater Lake.",
	sections = {
		{
			title = "Summary",
			text = [=[Gunther Arcanus was a mage of the {link:kirin-tor}Kirin Tor{/link} of {link:dalaran}Dalaran{/link} and a skilled necromancer. He studied beside {link:bethor-iceshard}Bethor Iceshard{/link} and {link:thule-ravenclaw}Thule Ravenclaw{/link}. Thule betrayed his friends to the Lich King. Gunther and Bethor died of the plague. Gunther rose as a lich with a free mind, but he believed he was the only one of his kind, and he took every other undead for a slave of the {link:scourge}Scourge{/link}.]=],
		},
		{
			title = "Significance",
			text = [=[Gunther's return is a prize for the {link:forsaken}Forsaken{/link}. His power has grown in death, and his knowledge of necromancy is of great use to {link:sylvanas-windrunner}the Dark Lady{/link}.]=],
		},
		{
			title = "Deeds",
			text = [=[• He demands proof that the {link:forsaken}Forsaken{/link} are truly enemies of the {link:scourge}Scourge{/link}.]=],
		},
	},
	chapters = {
		{
			key = "the-prodigal-lich",
			title = "The Prodigal Lich",
			hint = "Bring the lich of Brightwater Lake back to his old friend.",
			unlock = {
				{ type = "quest", id = 411 },
			},
			text = [=[{link:bethor-iceshard}Bethor{/link} laid a spell on Gunther's stolen book, so that when Gunther saw it, he would know his old friend was free. Gunther wanted more than a spell. He asked for the death of the {link:scourge}Scourge{/link} agent {link:lillith-nefara}Lillith Nefara{/link}. When she was slain, he believed at last that he was not alone.]=],
		},
	},
	mentions = {
		{
			text = "The Lich's Identity",
			unlock = {
				{ type = "quest", id = 357 },
			},
		},
		{
			text = "Return the Book",
			unlock = {
				{ type = "quest", id = 366 },
			},
		},
		{
			text = "Proving Allegiance",
			unlock = {
				{ type = "quest", id = 409 },
			},
		},
		{
			text = "The Prodigal Lich Returns",
			unlock = {
				{ type = "quest", id = 411 },
			},
		},
	},
	bonds = {
		{ id = "bethor-iceshard", name = "Bethor Iceshard", note = "his old friend" },
		{ id = "lillith-nefara", name = "Lillith Nefara", note = "the Scourge agent he wanted dead" },
	},
})

Add({
	kind = "figure",
	id = "gregor-agamand",
	title = "Gregor Agamand",
	aliases = { "Gregor" },
	subtitle = "Head of the Agamand Family",
	tier = "C",
	region = "tirisfal-glades",
	npc = { 1654 },
	allegiance = "Scourge",
	found = "The Agamand Mills",
	pin = { x = 46.7, y = 29.3 },
	unlock = {
		{ type = "target" },
	},
	hint = "Face the head of the Agamand family among the mills.",
	sections = {
		{
			title = "Summary",
			text = [=[Gregor Agamand was the head of the richest family in {link:tirisfal-glades}Tirisfal{/link}. When the {link:scourge}Scourge{/link} first came, he chose to fight. He fortified the mills and persuaded his workers to stay and defend them. His pride doomed them all. Gregor died with his household and rose as a mindless servant of the Lich King. He still walks among the mills he once owned.]=],
		},
		{
			title = "Significance",
			text = [=[To the {link:forsaken}Forsaken{/link} of {link:brill}Brill{/link}, Gregor is the man who chained them to the Agamands' fate. His own former workers want his bones.]=],
		},
		{
			title = "Deeds",
			text = [=[• He held the {link:agamand-mills}Agamand Mills{/link} against the plague, and lost them.
• He was the father of {link:thurman-agamand}Thurman{/link} and {link:devlin-agamand}Devlin{/link}.]=],
		},
	},
	mentions = {
		{
			text = "Deaths in the Family",
			unlock = {
				{ type = "quest", id = 354 },
			},
		},
	},
	bonds = {
		{ id = "thurman-agamand", name = "Thurman Agamand", note = "his eldest son" },
		{ id = "devlin-agamand", name = "Devlin Agamand", note = "his younger son" },
		{ id = "nissa-agamand", name = "Nissa Agamand", note = "of the same house" },
		{ id = "coleman-farthing", name = "Coleman Farthing", note = "his former worker" },
	},
})

Add({
	kind = "figure",
	id = "nissa-agamand",
	title = "Nissa Agamand",
	aliases = { "Nissa" },
	subtitle = "Lady of the Agamand House",
	tier = "C",
	region = "tirisfal-glades",
	npc = { 1655 },
	allegiance = "Scourge",
	found = "The Agamand Mills",
	pin = { x = 49.7, y = 36.3 },
	unlock = {
		{ type = "target" },
	},
	hint = "Face the Agamand lady who walks the mills.",
	sections = {
		{
			title = "Summary",
			text = [=[Nissa Agamand was a member of the Agamand household in the days before the plague. She died with the rest of the family when the mills fell, and she rose with them as a servant of the {link:scourge}Scourge{/link}. She wanders the mills to this day, among the kin who died beside her. Her former workers count her among the Agamands whose pride doomed them.]=],
		},
		{
			title = "Significance",
			text = [=[Nissa is one of the family whose remains {link:coleman-farthing}Coleman Farthing{/link} has sworn to collect, one by one.]=],
		},
		{
			title = "Unrecorded",
			text = [=[No chronicle records Nissa's place in the family. It is not written whether she was {link:gregor-agamand}Gregor{/link}'s wife, daughter or kin.]=],
		},
	},
	mentions = {
		{
			text = "Deaths in the Family",
			unlock = {
				{ type = "quest", id = 354 },
			},
		},
	},
	bonds = {
		{ id = "gregor-agamand", name = "Gregor Agamand", note = "of the same house" },
		{ id = "coleman-farthing", name = "Coleman Farthing", note = "wants her remains" },
	},
})

Add({
	kind = "figure",
	id = "thurman-agamand",
	title = "Thurman Agamand",
	aliases = { "Thurman" },
	subtitle = "Eldest Son of the Agamands",
	tier = "C",
	region = "tirisfal-glades",
	npc = { 1656 },
	allegiance = "Scourge",
	found = "The Agamand Mills",
	pin = { x = 44.0, y = 33.6 },
	unlock = {
		{ type = "target" },
	},
	hint = "Face the eldest Agamand son among the mills.",
	sections = {
		{
			title = "Summary",
			text = [=[Thurman was the eldest son of {link:gregor-agamand}Gregor Agamand{/link}. He was tall and gentle, and he loved {link:yvette-farthing}Yvette Farthing{/link}. When the plague came she begged him to flee with her. He would not leave his family. He wrote her a letter before the end, but it was never sent. Thurman died at the mills and rose as a servant of the {link:scourge}Scourge{/link}.]=],
		},
		{
			title = "Significance",
			text = [=[Thurman's letter is the only kind word left of the Agamands. Even so, the woman he loved no longer wants it.]=],
		},
		{
			title = "Deeds",
			text = [=[• He stayed at the mills out of loyalty to his family.
• He wrote a letter to {link:yvette-farthing}Yvette Farthing{/link} that never reached her.]=],
		},
	},
	mentions = {
		{
			text = "Deaths in the Family",
			unlock = {
				{ type = "quest", id = 354 },
			},
		},
		{
			text = "A Letter Undelivered",
			unlock = {
				{ type = "quest", id = 361 },
			},
		},
	},
	bonds = {
		{ id = "yvette-farthing", name = "Yvette Farthing", note = "his love" },
		{ id = "gregor-agamand", name = "Gregor Agamand", note = "his father" },
		{ id = "devlin-agamand", name = "Devlin Agamand", note = "his younger brother" },
	},
})

Add({
	kind = "figure",
	id = "devlin-agamand",
	title = "Devlin Agamand",
	aliases = { "Devlin" },
	subtitle = "Younger Son of the Agamands",
	tier = "C",
	region = "tirisfal-glades",
	npc = { 1657 },
	allegiance = "Scourge",
	found = "The road leading to the Agamand Mills",
	pin = { x = 47.3, y = 40.8 },
	unlock = {
		{ type = "target" },
	},
	hint = "Listen for the mad chatter by the road to the Agamand Mills.",
	sections = {
		{
			title = "Summary",
			text = [=[Devlin was the younger son of {link:gregor-agamand}Gregor Agamand{/link}. His brother {link:thurman-agamand}Thurman{/link} was tall and gentle. Devlin was weak and sharp of tongue. When the mills fell to the plague, he was quick to die, and no one was surprised. He rose as a servant of the {link:scourge}Scourge{/link}, and his mad chattering can still be heard by the road that leads up to the mills. Travellers on that road hear him long before they see him.]=],
		},
		{
			title = "Significance",
			text = [=[{link:coleman-farthing}Coleman Farthing{/link} wants Devlin's bones for his mantle. Of all the Agamands, it is Devlin whom he names with the most open scorn.]=],
		},
	},
	mentions = {
		{
			text = "The Haunted Mills",
			unlock = {
				{ type = "quest", id = 362 },
			},
		},
	},
	bonds = {
		{ id = "thurman-agamand", name = "Thurman Agamand", note = "his elder brother" },
		{ id = "gregor-agamand", name = "Gregor Agamand", note = "his father" },
		{ id = "coleman-farthing", name = "Coleman Farthing", note = "wants his bones" },
	},
})

Add({
	kind = "figure",
	id = "lillith-nefara",
	title = "Lillith Nefara",
	subtitle = "Agent of the Scourge",
	tier = "C",
	region = "tirisfal-glades",
	npc = { 1946 },
	allegiance = "Scourge",
	found = [=[An old altar off the southern shore of the island in Brightwater Lake]=],
	unlock = {
		{ type = "target" },
	},
	hint = [=[Light a candle of beckoning on the old altar in Brightwater Lake.]=],
	sections = {
		{
			title = "Summary",
			text = [=[Lillith Nefara is a powerful agent of the {link:scourge}Scourge{/link}. She sleeps beside an old, bloody altar just off the southern shore of {link:gunther-arcanus}Gunther{/link}'s island in {link:brightwater-lake}Brightwater Lake{/link}. A candle of beckoning, lit upon the altar, wakes her. Gunther keeps such candles in a crate at his camp. The lich Gunther Arcanus knows her well, and he counts her death as proof that someone is truly the Lich King's foe.]=],
		},
		{
			title = "Significance",
			text = [=[Lillith is the test that {link:gunther-arcanus}Gunther{/link} sets for the {link:forsaken}Forsaken{/link}. Only when she falls does he believe that others have broken free as he has.]=],
		},
		{
			title = "Unrecorded",
			text = [=[No chronicle records who Lillith was in life, or why she keeps to the altar.]=],
		},
	},
	mentions = {
		{
			text = "Proving Allegiance",
			unlock = {
				{ type = "quest", id = 409 },
			},
		},
	},
	bonds = {
		{ id = "gunther-arcanus", name = "Gunther Arcanus", note = "wants her dead" },
	},
})

Add({
	kind = "figure",
	id = "garek-bandarion",
	title = "Garek Bandarion",
	aliases = { "Garek", "Captain Bandarion" },
	subtitle = "The First Forsaken Paladin",
	tier = "A",
	region = "tirisfal-glades",
	allegiance = "Forsaken · Deathguard · formerly the City Guard of Lordaeron",
	found = "Remembered at Bandarion Keep",
	unlock = {
		{ type = "read" },
		{ type = "subzone", name = "Bandarion Keep" },
		{ type = "quest", id = 96896 },
		{ type = "quest", id = 92421 },
	},
	hint = "Seek the keep in the western hills that bears his name.",
	sections = {
		{
			title = "Summary",
			text = [=[Garek Bandarion was a soldier of {link:lordaeron}Lordaeron{/link} who died in its fall and rose among the {link:forsaken}Forsaken{/link}. He became the first captain of the Deathguard, and he was the first of the Forsaken to take up the {link:holy-light}Holy Light{/link} as a paladin. He fell when the necropolis {red:naxxramas}Naxxramas{/red} came against the {link:undercity}Undercity{/link}. The paladins of {link:tyr-s-watch}Tyr's Watch{/link} named their monastery after him, and they still speak his name as a battle cry.]=],
		},
		{
			title = "Significance",
			text = [=[To the {link:forsaken}Forsaken{/link} paladins, Garek is proof that the Light did not abandon them in death. To the Deathguard, he is the captain who built their ranks. His life joins the last days of the living kingdom to the first days of the dead one.]=],
		},
		{
			title = "Deeds",
			text = [=[• In life, he served in the City Guard of the capital under Captain Landen, who chose him as his successor.
• On the day {link:arthas-menethil}Arthas{/link} murdered his father, he and Landen led survivors out through the sewers beneath the city.
• He took his vengeance on Baron Rivendare, the lord who betrayed the kingdom to the {link:cult-of-the-damned}Cult of the Damned{/link}, and died of his wounds and the plague.
• As a {link:forsaken}Forsaken{/link}, he fought beside {link:dark-ranger-anya}Dark Ranger Anya{/link} in the first days of the {link:undercity}Undercity{/link}.
• He rose to be captain of the Deathguard.
• He died in the defense of the Undercity against Naxxramas.]=],
		},
	},
	chapters = {
		{
			key = "the-last-days-of-lordaeron",
			title = "The Last Days of Lordaeron",
			hint = [=[Learn what the Forsaken of the Undercity say of their first captain.]=],
			unlock = {
				{ type = "quest", id = 92421 },
			},
			text = [=[Garek was a young guardsman who longed for battle, and his captain, Landen, told him that protecting the people was the greater glory. On the night {link:arthas-menethil}Arthas{/link} slew King {link:terenas-menethil}Terenas Menethil{/link}, they found the throne room full of cultists. {link:uther-the-lightbringer}Uther the Lightbringer{/link} sent them to save whom they could. Beneath the city they found that the cult had long been ready. Landen stayed behind to hold back Baron Rivendare so that Garek could lead the people to safety. Garek never forgave the baron. He hunted him to Stratholme and killed him there, and he died of his wounds.]=],
		},
		{
			key = "a-second-life",
			title = "A Second Life",
			hint = "Hear the paladins of Bandarion Keep speak of their founder.",
			unlock = {
				{ type = "quest", id = 96896 },
			},
			text = [=[Garek woke in the vaults of the {link:undercity}Undercity{/link} with no memory but his name. The apothecary Putress wished to use his body for parts. {link:dark-ranger-anya}Dark Ranger Anya{/link} stopped him. Garek swore himself to {link:sylvanas-windrunner}Sylvanas{/link}, and with Anya he gathered the free-willed dead from the ruins, cleared the tunnels and helped the city grow. When the {link:scarlet-crusade}Scarlet Crusade{/link} broke through the walls of the Undercity, he led the Deathguard against them. Somewhere in those years, the Light began to answer him again.]=],
		},
		{
			key = "the-keep-of-his-name",
			title = "The Keep of His Name",
			hint = "Learn why the fortress on Northface Rock bears his name.",
			unlock = {
				{ type = "quest", id = 96899 },
			},
			text = [=[When Naxxramas came to the ruins of the capital, the {link:forsaken}Forsaken{/link} and the {link:argent-dawn}Argent Dawn{/link} fought it together on the surface. Garek did not come back. {link:danitha-morr}Danitha Morr{/link} and {link:leonid-barthalomew}Leonid Barthalomew{/link} fought in that battle and lost many friends there. When Danitha took the old fortress on {link:bandarion-keep}Northface Rock{/link} for her order, she named it after him.]=],
		},
	},
	mentions = {
		{
			text = "A Righteous Cause",
			unlock = {
				{ type = "quest", id = 96896 },
			},
		},
		{
			text = "{link:bandarion-keep}Bandarion Keep{/link}",
			unlock = {
				{ type = "quest", id = 96899 },
			},
		},
		{
			text = "Light's Justice",
			unlock = {
				{ type = "quest", id = 92421 },
			},
		},
	},
	bonds = {
		{ id = "dark-ranger-anya", name = "Dark Ranger Anya", note = "his companion" },
		{ id = "danitha-morr", name = "Danitha Morr", note = "named the keep after him" },
		{ id = "leonid-barthalomew", name = "Leonid Barthalomew", note = "a friend" },
		{ id = "sylvanas-windrunner", name = "Sylvanas Windrunner", note = "his queen" },
	},
})

Add({
	kind = "figure",
	id = "dark-ranger-anya",
	title = "Dark Ranger Anya",
	aliases = { "Anya" },
	subtitle = "Dark Ranger of the Banshee Queen",
	tier = "B",
	region = "tirisfal-glades",
	allegiance = "Forsaken · formerly the Farstriders of Quel'Thalas",
	found = "Unknown in these days",
	unlock = {
		{ type = "read" },
	},
	hint = "Learn of her through the tales of Garek Bandarion.",
	sections = {
		{
			title = "Summary",
			text = [=[Anya is a dark ranger, one of the undead elves who serve {link:sylvanas-windrunner}Sylvanas Windrunner{/link}. In life she was a ranger of {link:quel-thalas}Quel'Thalas{/link} under Sylvanas's command. She died defending her homeland against the {link:scourge}Scourge{/link} and rose as its slave. She remembers everything she did in that time. When she broke free, Sylvanas gave her a place to belong, and for that Anya gave the Dark Lady her loyalty for all time.]=],
		},
		{
			title = "Significance",
			text = [=[Anya is one of the first dark rangers of the {link:forsaken}Forsaken{/link}, and one of those who saw the {link:undercity}Undercity{/link} rise from the tunnels. She was the companion of {link:garek-bandarion}Garek Bandarion{/link} through the early wars of the dead kingdom. Where he lost his memories, she kept all of hers, and she taught him that for many Forsaken death is a clean slate and a second life. She trusts the living very little. When a paladin of the old Silver Hand showed mercy to a Forsaken laborer and his captain killed the man anyway, Anya told Garek that the living would never see the undead as people, and could not be trusted.]=],
		},
		{
			title = "Deeds",
			text = [=[• She fell in the defense of {link:quel-thalas}Quel'Thalas{/link}, and did terrible things as a slave of the Lich King.
• She stopped the apothecary Putress from cutting up {link:garek-bandarion}Garek{/link} for parts when he woke.
• She told Garek that his lost memory was a mercy, for she remembered her own crimes all too well.
• With Garek, she rescued the free-willed dead from the ruins of the capital.
• She fought beside him against the {link:scarlet-crusade}Scarlet Crusade{/link} and against Naxxramas.
• With {link:sylvanas-windrunner}Sylvanas{/link} and the dark ranger Clea, she rode to the {link:the-marris-stead}Marris Stead{/link} in search of {link:nathanos-blightcaller}Nathanos Marris{/link}.]=],
		},
		{
			title = "Unrecorded",
			text = [=[No chronicle of these days records where Anya serves now, or what she did after {link:garek-bandarion}Garek{/link} fell.]=],
		},
	},
	bonds = {
		{ id = "garek-bandarion", name = "Garek Bandarion", note = "her companion" },
		{ id = "sylvanas-windrunner", name = "Sylvanas Windrunner", note = "her queen" },
	},
})

Add({
	kind = "figure",
	id = "danitha-morr",
	title = "Danitha Morr",
	aliases = { "Danitha" },
	subtitle = "Commander of Bandarion Keep",
	tier = "B",
	region = "tirisfal-glades",
	npc = { 246378 },
	allegiance = "Tyr's Watch · Forsaken",
	found = "Bandarion Keep",
	unlock = {
		{ type = "interact" },
	},
	hint = "Speak with the leader of the paladins at Bandarion Keep.",
	sections = {
		{
			title = "Summary",
			text = [=[Danitha Morr leads the paladins of {link:tyr-s-watch}Tyr's Watch{/link} from {link:bandarion-keep}Bandarion Keep{/link}. She calls herself the closest thing the keep has to a commander. She fought in the defense of the {link:undercity}Undercity{/link} when Naxxramas came, and she lost friends there, among them {link:garek-bandarion}Garek Bandarion{/link}. When she took the ruined fortress on Northface Rock, she named it after him.]=],
		},
		{
			title = "Significance",
			text = [=[Danitha is trying to do what no {link:forsaken}Forsaken{/link} has done before: to build an order of the {link:holy-light}Holy Light{/link} among the dead and win it a place in their kingdom. Her people fear paladins. Her queen mistrusts them. She believes the work may take decades, and she does it anyway.]=],
		},
		{
			title = "Deeds",
			text = [=[• She rebuilds {link:bandarion-keep}Bandarion Keep{/link} with salvage from the ruins of {link:shadowvale}Shadowvale{/link}.
• She hunts the Tarnished, the risen paladins who turn their blades on the {link:forsaken}Forsaken{/link}.
• She sends her paladins to help the poor of the {link:undercity}Undercity{/link}.
• She sends her order into {link:silverpine-forest}Silverpine{/link} to win the trust of the {link:horde}Horde{/link}.]=],
		},
		{ title = "Unrecorded", text = "Little is written of Danitha's life before death." },
	},
	chapters = {
		{
			key = "a-home-in-the-hills",
			title = "A Home in the Hills",
			hint = "Find your way to Bandarion Keep and meet its commander.",
			unlock = {
				{ type = "quest", id = 91294 },
			},
			text = [=[The keep was a ruin when Danitha's paladins came. Vile Fin murlocs had made it a spawning ground, and they fought to take it back even after they were driven out. Danitha had few materials, fewer allies and a great many walls to mend. She welcomed every newcomer who still held to the Light.]=],
		},
		{
			key = "the-tarnished",
			title = "The Tarnished",
			hint = [=[Deal with the risen paladins who have made Shadowvale their den.]=],
			unlock = {
				{ type = "quest", id = 91317 },
			},
			text = [=[Not every paladin who rises can accept what he has become. Some keep the hatreds of their old lives and kill the {link:forsaken}Forsaken{/link} they meet. Every such killing makes it easier for the order's enemies to stir up fear. Danitha had the Tarnished of {link:shadowvale}Shadowvale{/link} destroyed and their commander, {link:rudolph-gelhardt}Rudolph Gelhardt{/link}, beheaded.]=],
		},
		{
			key = "a-token-of-good-faith",
			title = "A Token of Good Faith",
			hint = "Carry Danitha's gift to the Dark Lady.",
			unlock = {
				{ type = "quest", id = 95803 },
			},
			text = [=[Danitha sent {link:rudolph-gelhardt}Gelhardt{/link}'s head to the {link:undercity}Undercity{/link}, to show {link:sylvanas-windrunner}the Dark Lady{/link} that {link:tyr-s-watch}Tyr's Watch{/link} keeps its own house in order. Sylvanas did not doubt Danitha's sincerity. She said that she expected more paladins to go mad, and that she might one day decide to tolerate the order no longer. She told its paladins to serve well, and that she would be watching.]=],
		},
	},
	mentions = {
		{
			text = "Touring the Grounds",
			unlock = {
				{ type = "quest", id = 91294 },
			},
		},
		{
			text = "The Tarnished",
			unlock = {
				{ type = "quest", id = 91317 },
			},
		},
		{
			text = "A Token of Good Faith",
			unlock = {
				{ type = "quest", id = 95803 },
			},
		},
		{
			text = "A Lesson in Divinity",
			unlock = {
				{ type = "quest", id = 94427 },
			},
		},
		{
			text = "Diplomatic Incident",
			unlock = {
				{ type = "quest", id = 91858 },
			},
		},
		{
			text = "A Righteous Cause",
			unlock = {
				{ type = "quest", id = 96896 },
			},
		},
	},
	bonds = {
		{ id = "garek-bandarion", name = "Garek Bandarion", note = "a fallen friend" },
		{ id = "leonid-barthalomew", name = "Leonid Barthalomew", note = "an old comrade" },
		{ id = "rudolph-gelhardt", name = "Rudolph Gelhardt", note = "the Tarnished commander" },
		{ id = "sylvanas-windrunner", name = "Sylvanas Windrunner", note = "mistrusts her order" },
	},
})

Add({
	kind = "figure",
	id = "leonid-barthalomew",
	title = "Leonid Barthalomew",
	aliases = { "Leonid", "Leonid Barthalomew the Revered" },
	subtitle = "Emissary of the Argent Dawn",
	tier = "C",
	region = "tirisfal-glades",
	npc = { 267008 },
	allegiance = "Argent Dawn",
	found = "Bandarion Keep",
	unlock = {
		{ type = "interact" },
	},
	hint = [=[Speak with the undead emissary of the Argent Dawn at Bandarion Keep.]=],
	sections = {
		{
			title = "Summary",
			text = [=[Leonid Barthalomew is an undead knight of the {link:argent-dawn}Argent Dawn{/link}, called the Revered by his comrades. He came to {link:bandarion-keep}Bandarion Keep{/link} with another {link:forsaken}Forsaken{/link} of the Dawn to visit old friends. He knows the fortress well. The Dawn held it in the {link:scourge}Scourge{/link}'s last push into {link:tirisfal-glades}Tirisfal{/link}, and he fought from its walls. He also fought for the {link:undercity}Undercity{/link} when Naxxramas came, beside {link:danitha-morr}Danitha Morr{/link} and {link:garek-bandarion}Garek Bandarion{/link}.]=],
		},
		{
			title = "Significance",
			text = [=[Leonid is a bridge between the Dawn and the {link:forsaken}Forsaken{/link}, though he admits that his history with {link:sylvanas-windrunner}the Dark Lady{/link} is colorful.]=],
		},
		{
			title = "Deeds",
			text = [=[• He fought against the {link:scourge}Scourge{/link} in the defense of the {link:undercity}Undercity{/link}.
• He sends a letter to an old friend, the goblin {link:glix-xizzix}Glix Xizzix{/link} of the Undercity.]=],
		},
	},
	mentions = {
		{
			text = "A Righteous Cause",
			unlock = {
				{ type = "quest", id = 96896 },
			},
		},
		{
			text = "{link:bandarion-keep}Bandarion Keep{/link}",
			unlock = {
				{ type = "quest", id = 96899 },
			},
		},
		{
			text = "Leonid's Letter",
			unlock = {
				{ type = "quest", id = 98545 },
			},
		},
	},
	bonds = {
		{ id = "danitha-morr", name = "Danitha Morr", note = "an old comrade" },
		{ id = "garek-bandarion", name = "Garek Bandarion", note = "a mutual friend" },
		{ id = "glix-xizzix", name = "Glix Xizzix", note = "an old friend" },
	},
})

Add({
	kind = "figure",
	id = "rudolph-gelhardt",
	title = "Rudolph Gelhardt",
	aliases = { "Gelhardt" },
	subtitle = "Commander of the Tarnished",
	tier = "C",
	region = "tirisfal-glades",
	npc = { 259431 },
	allegiance = "The Tarnished",
	found = "Shadowvale, in the Whispering Forest",
	unlock = {
		{ type = "target" },
	},
	hint = [=[Face the commander of the Tarnished in the ruins of Shadowvale.]=],
	sections = {
		{
			title = "Summary",
			text = [=[Rudolph Gelhardt is a risen paladin who never accepted his undeath. He carries the prejudices of his old life into the new one, and he turns the {link:holy-light}Holy Light{/link} against the {link:forsaken}Forsaken{/link}. He leads the Tarnished, who have made the ruins of {link:shadowvale}Shadowvale{/link} their den. Every Forsaken they kill makes it harder for the paladins of {link:tyr-s-watch}Tyr's Watch{/link} to be trusted. His followers are drudges and zealots, and they fight for him to the very end.]=],
		},
		{
			title = "Significance",
			text = [=[Gelhardt is the danger that the {link:forsaken}Forsaken{/link} fear in every paladin. His head is the proof that {link:danitha-morr}Danitha Morr{/link} offers {link:sylvanas-windrunner}the Dark Lady{/link}.]=],
		},
	},
	mentions = {
		{
			text = "The Tarnished",
			unlock = {
				{ type = "quest", id = 91317 },
			},
		},
		{
			text = "A Token of Good Faith",
			unlock = {
				{ type = "quest", id = 95803 },
			},
		},
	},
	bonds = {
		{ id = "danitha-morr", name = "Danitha Morr", note = "ordered his death" },
	},
})
