-- LibProfessionDB names — WoW Vanilla, ptBR, Mining
-- Auto-generated by ProfessionDB tools/build_authoritative_data.py. Do not hand-edit.
-- 13 recipes

if GetLocale() ~= "ptBR" then return end
local lib = LibStub and LibStub("LibProfessionDB-1.0", true)
if not lib or not lib:IsGameVersion("Vanilla") then return end

lib:LoadNames(186, {
		[2657] = {
			["name"] = "Fundir Cobre",
		},
		[2658] = {
			["name"] = "Fundir Prata",
		},
		[2659] = {
			["name"] = "Fundir Bronze",
		},
		[3304] = {
			["name"] = "Fundir Estanho",
		},
		[3307] = {
			["name"] = "Fundir Ferro",
		},
		[3308] = {
			["name"] = "Fundir Ouro",
		},
		[3569] = {
			["name"] = "Fundir Aço",
		},
		[10097] = {
			["name"] = "Fundir Mithril",
		},
		[10098] = {
			["name"] = "Fundir Veraprata",
		},
		[14891] = {
			["name"] = "Fundir Ferro Negro",
		},
		[16153] = {
			["name"] = "Fundir Tório",
		},
		[22967] = {
			["name"] = "Fundir Elemêntio",
		},
		[1213638] = {
			["name"] = "Fundir Barra de Tório Infusa em Obsidiana",
		},
	})
