-- Generated by tools/build_content.py from content/ptBR/eastern-kingdoms/wetlands.md. Do not edit.
local _, ns = ...
local Translate = ns.Lore.Translate

Translate("ptBR", "wetlands", {
	title = "Pantanal",
	aliases = { "O Pantanal" },
	sections = {
		{
			title = "Resumo",
			text = [=[O Pantanal é uma vasta terra de charcos, juncos e águas negras e lentas, ao norte das montanhas de Khaz Modan. A névoa paira sobre ela durante boa parte do ano. Uma grande estrada a atravessa: sobe de {link:dun-algaz}Dun Algaz{/link} ao sul, segue para o norte passando pelas ruínas de antigas fortalezas anãs e termina na {link:thandol-span}Ponte Thandol{/link}, a ponte que une as terras dos anões aos reinos humanos do norte. Uma segunda estrada vira para oeste, rumo ao mar, onde o {link:menethil-harbor}Porto de Menethil{/link} mantém a vigília da {link:alliance}Aliança{/link} sobre a costa. Sempre foi uma terra dura, rica em crocoliscos e raptores e pobre em conforto. Agora é também uma terra em guerra.]=],
		},
		{
			title = "Origens",
			text = [=[Nenhuma crônica registra quem ergueu as primeiras pedras nestes pântanos. Os anões os reivindicam há muitos séculos. No leste ergue-se a fortaleza montanhesa de {link:grim-batol}Grim Batol{/link}, outrora sede do clã Martelo Feroz. Na Guerra dos Três Martelos, os {link:dark-iron-dwarves}Ferro Negro{/link} atacaram Grim Batol, e a feitiçaria sombria ali liberada deixou a fortaleza maculada. Os Martelo Feroz a abandonaram e partiram para o norte, para os picos das {link:the-hinterlands}Terras Agrestes{/link}. A {link:explorers-league}Liga dos Exploradores{/link} ainda encontra coisas mais antigas sob a lama: ossos de grandes feras e pedras gravadas numa escrita que nenhum {link:dwarves}anão{/link} escreveu.]=],
		},
		{
			title = "Os Dias Atuais",
			text = [=[O {link:menethil-harbor}Porto de Menethil{/link} guarda a costa oeste para a {link:alliance}Aliança{/link}, sob os anões do {link:kingdom-of-ironforge}Reino de Altaforja{/link}. Além de suas muralhas, o Pantanal está se desfazendo. Sabotadores {link:dark-iron-dwarves}Ferro Negro{/link} destruíram a {link:thandol-span}Ponte Thandol{/link} e tomaram {link:dun-modr}Dun Modr{/link}, e os sobreviventes do regimento que os guardava esperam nas ruínas por uma reserva que nunca chega. Os {link:dragonmaw-clan}orcs Presa do Dragão{/link}, derrotados e dispersos depois da {link:second-war}Segunda Guerra{/link}, encontraram um novo chefe e um novo acampamento. Avançaram sobre {link:dun-algaz}Dun Algaz{/link} e ameaçam isolar Menethil de {link:loch-modan}Loch Modan{/link}. No {link:whelgar-s-excavation-site}Sítio de Escavação de Whelgar{/link}, raptores mataram a maior parte de uma equipe da {link:explorers-league}Liga dos Exploradores{/link}. Acima dessa escavação, a névoa começou a descer das montanhas, luzes piscam nas alturas e construtos de pedra caminham onde ninguém caminha há eras. A única notícia de esperança vem pelo mar: novos navios agora partem de Menethil para {link:southshore}Costa Sul{/link} e seguem até {link:auberdine}Auberdine{/link}.]=],
		},
		{
			title = "Habitantes",
			text = [=[• {b}Os anões de {link:ironforge}Altaforja{/link}.{/b} Soldados, mineiros, sacerdotes e estudiosos guardam o {link:menethil-harbor}Porto de Menethil{/link}, o acampamento diante de {link:dun-modr}Dun Modr{/link} e a escavação da {link:explorers-league}Liga dos Exploradores{/link}.
• {b}O povo de Menethil.{/b} {link:humans}Humanos{/link} dos antigos reinos trabalham nas docas, tabernas e curtumes ao lado dos anões.
• {b}O {link:dragonmaw-clan}clã Presa do Dragão{/link}.{/b} {link:orcs}Orcs{/link} que outrora montavam dragões vermelhos na guerra, agora acampados nas colinas a leste da estrada.
• {b}Os {link:dark-iron-dwarves}Ferro Negro{/link}.{/b} Seus sabotadores, escavadores e bruxos dominam Dun Modr e o {link:direforge-hill}Monte Umbraforja{/link}.
• {b}Os gnolls Pelemusgo.{/b} Um clã de {link:gnolls}gnolls{/link} dos charcos, numeroso demais para a terra que o alimenta.
• {b}Os murlocs Peixeazul.{/b} {link:murlocs}Murlocs{/link} que saqueiam a costa e os navios mercantes que passam por ela.
• {b}Os mortos afogados.{/b} Marinheiros amaldiçoados ainda caminham pelos destroços da {link:the-lost-fleet}Frota Perdida{/link}, na costa noroeste.]=],
		},
		{
			title = "História",
			text = [=[• {b}Os Três Martelos.{/b} {link:grim-batol}Grim Batol{/link} silenciou depois da guerra dos três clãs, e os Martelo Feroz deixaram o Pantanal para trás.
• {b}A {link:second-war}Segunda Guerra{/link}.{/b} A {link:horde}Horda{/link} invadiu Khaz Modan. O {link:dragonmaw-clan}clã Presa do Dragão{/link} fez de Grim Batol sua fortaleza, e os orcs construíram um porto na costa oeste para atacar {link:hillsbrad-foothills}Eira dos Montes{/link} pelo mar. {link:the-drag}Drag{/link}ões vermelhos sob comando {link:orcs}orc{/link} queimaram a {link:third-fleet}Terceira Frota{/link} de {link:kul-tiras}Kul Tiraz{/link} diante destas costas.
• {b}Menethil.{/b} O Almirante {link:daelin-proudmoore}Daelin Proudmoore{/link} expulsou os orcs de seu porto, e a {link:alliance}Aliança{/link} ergueu um porto próprio no mesmo lugar, batizado em honra do Rei {link:terenas-menethil}Terenas Menethil{/link}.
• {b}Os Dias Atuais.{/b} Os {link:dark-iron-dwarves}Ferro Negro{/link} se ergueram no norte, os Presa do Dragão voltaram no leste, e as reservas de {link:ironforge}Altaforja{/link} foram enviadas para lutar em outras frentes.]=],
		},
		{
			title = "Lendas do Pantanal",
			text = [=[• As peles de crocolisco do curtume de Menethil são vendidas em portos do mundo inteiro.
• Um espírito do pântano, chamado {link:rethiel-the-greenwarden}Guarda Verde{/link}, caminha entre os crocoliscos a leste da bifurcação para {link:dun-modr}Dun Modr{/link}. Quem o procura ouve que não vai voltar.
• Os gnolls Pelemusgo queimam árvores vivas para se aquecer, e o Guarda Verde não os perdoou.
• O último sobrevivente da {link:third-fleet}Terceira Frota{/link} diz que, em seus sonhos, ainda ouve os gemidos de seus irmãos afogados.]=],
		},
	},
})

Translate("ptBR", "menethil-harbor", {
	title = "Porto de Menethil",
	sections = {
		{
			title = "Resumo",
			text = [=[O Porto de Menethil é o porto da {link:alliance}Aliança{/link} na costa oeste do {link:wetlands}Pantanal{/link}. Ergue-se no lugar onde a {link:horde}Horda{/link} outrora construiu navios para a {link:second-war}Segunda Guerra{/link}, e muito da madeira e do ferro que ela roubou de Khaz Modan ainda está espalhado por suas docas. Sua fortaleza leva o nome do Rei {link:terenas-menethil}Terenas Menethil{/link}. Os anões de {link:ironforge}Altaforja{/link} o comandam, e o {link:captain-stoutfist}Capitão Stoutfist{/link} planeja sua defesa na sala de guerra da Bastilha Menethil. Navios partem de seus píeres para {link:auberdine}Auberdine{/link}, para {link:theramore-isle}Theramore{/link}, do outro lado do mar, e agora também para {link:southshore}Costa Sul{/link}. Na Taberna Aguafunda, marinheiros, estudiosos, espiões e um sobrevivente bêbado da {link:third-fleet}Terceira Frota{/link} dividem as mesmas mesas.]=],
		},
	},
})

Translate("ptBR", "dun-modr", {
	title = "Dun Modr",
	sections = {
		{
			title = "Resumo",
			text = [=[Dun Modr é uma cidade anã no norte do {link:wetlands}Pantanal{/link}, na estrada para a {link:thandol-span}Ponte Thandol{/link}. Um regimento de {link:ironforge}Altaforja{/link} guardava a cidade e a ponte mais adiante. Os {link:dark-iron-dwarves}Ferro Negro{/link} atacaram primeiro a ponte e depois caíram sobre a cidade antes que o regimento pudesse se reorganizar, e a maioria dos anões foi morta. {link:longbraid-the-grim}Longbraid, o Severo{/link}, tocou a retirada. O que resta de seu regimento acampa agora logo além das muralhas, enquanto soldados, escavadores e demolidores Ferro Negro dominam as ruas. Uma criatura de fogo foi vista acorrentada entre eles, e um elemental chamado Modr caminha pelas ruínas.]=],
		},
	},
})

Translate("ptBR", "thandol-span", {
	title = "Ponte Thandol",
	aliases = { "A Ponte Thandol" },
	sections = {
		{
			title = "Resumo",
			text = [=[A Ponte Thandol é a grande ponte na borda norte do {link:wetlands}Pantanal{/link}. Ela cruza um desfiladeiro profundo até o {link:arathi-highlands}Planalto Arathi{/link} e leva a estrada principal entre Khaz Modan e as terras do norte. Os {link:dark-iron-dwarves}Ferro Negro{/link} explodiram sua ponte oeste numa emboscada, e muitos anões morreram com ela, entre eles o irmão de {link:longbraid-the-grim}Longbraid, o Severo{/link}. O plano foi traçado por um Ferro Negro chamado {link:kam-deepfury}Kam Deepfury{/link}. Seus agentes esconderam mais explosivos do outro lado do desfiladeiro para derrubar o que restava. Se a Ponte cair, os anões perdem sua principal linha de suprimentos para o norte.]=],
		},
	},
})

Translate("ptBR", "whelgar-s-excavation-site", {
	title = "Sítio de Escavação de Whelgar",
	aliases = { "Escavação de Whelgar" },
	sections = {
		{
			title = "Resumo",
			text = [=[O Sítio de Escavação de Whelgar é uma escavação da {link:explorers-league}Liga dos Exploradores{/link} no meio do {link:wetlands}Pantanal{/link}. A equipe do {link:prospector-whelgar}Prospector Whelgar{/link} desenterrava relíquias antigas quando começou a encontrar ossos enormes. Logo depois, os raptores malhados do pântano varreram o lugar. Muitos escavadores morreram. Três sobreviventes resistem num penhasco acima das ruínas de seu acampamento. Entre os achados há uma tábua quebrada, gravada na escrita dos titãs: a {link:goaz-stone}Pedra de Goaz{/link}. Mais acima, nas colinas a sudeste, além da antiga escavação, fica um segundo acampamento que a Liga abriu, e dele um caminho leva ao {link:excavation-site}Sítio de Escavação{/link}.]=],
		},
	},
})

Translate("ptBR", "dun-algaz", {
	title = "Dun Algaz",
	sections = {
		{
			title = "Resumo",
			text = [=[Dun Algaz é o desfiladeiro entre {link:loch-modan}Loch Modan{/link} e o {link:wetlands}Pantanal{/link}, guardado em sua boca sul pelos anões da {link:algaz-station}Estação Algaz{/link}. É a única estrada pela qual os soldados de {link:ironforge}Altaforja{/link} podem chegar ao {link:menethil-harbor}Porto de Menethil{/link} por terra. Os {link:dragonmaw-clan}orcs Presa do Dragão{/link} sempre se mantiveram nas colinas, mas agora desceram ao desfiladeiro em grande número, liderados por um senhor da guerra chamado {link:ma-ruk-wyrmscale}Ma'ruk Wyrmscale{/link}. Ninguém em Menethil sabe dizer o que os levou a isso. Se eles tomarem Dun Algaz, o porto ficará sozinho.]=],
		},
	},
})

Translate("ptBR", "grim-batol", {
	title = "Grim Batol",
	sections = {
		{
			title = "Resumo",
			text = [=[Grim Batol é uma fortaleza montanhesa no extremo leste do {link:wetlands}Pantanal{/link}, atrás dos Portões {link:dragonmaw-clan}Presa do Dragão{/link}. Foi construída pelos anões Martelo Feroz, que a deixaram depois da Guerra dos Três Martelos, quando uma feitiçaria sombria corrompeu seus salões. Na {link:second-war}Segunda Guerra{/link}, o clã Presa do Dragão fez dela sua fortaleza. Ali mantiveram {link:alexstrasza}Alexstrasza{/link}, rainha dos dragões vermelhos, acorrentada pelo poder de um artefato criado por {link:deathwing}Asa da Morte{/link}, e criaram seus filhotes como montarias de guerra. A rainha já foi libertada. {link:the-drag}Drag{/link}ões vermelhos agora se reúnem diante dos portões de Grim Batol, e não toleram estranhos.]=],
		},
	},
})

Translate("ptBR", "angerfang-encampment", {
	title = "Acampamento Presirada",
	sections = {
		{
			title = "Resumo",
			text = [=[O Acampamento Presirada é o acampamento de guerra dos {link:dragonmaw-clan}orcs Presa do Dragão{/link}, nas colinas a leste da estrada do {link:wetlands}Pantanal{/link}. Depois da {link:second-war}Segunda Guerra{/link}, os poucos Presa do Dragão que sobreviveram à vingança dos dragões vermelhos fugiram de {link:grim-batol}Grim Batol{/link} e se esconderam nestas montanhas. Aqui, sob o {link:chieftain-nek-rosh}Chefe Nek'rosh{/link}, voltaram a ficar fortes. Seus estandartes de guerra tremulam sobre o acampamento, seus centuriões e guardiões das sombras treinam nele, e suas catapultas de cerco estão prontas para a marcha sobre o {link:menethil-harbor}Porto de Menethil{/link}.]=],
		},
	},
})

Translate("ptBR", "dragonmaw-retreat", {
	title = "Dragonmaw Retreat",
	sections = {
		{
			title = "Resumo",
			text = [=[Dragonmaw Retreat é um reduto escondido dos {link:dragonmaw-clan}orcs Presa do Dragão{/link} nas colinas do leste do {link:wetlands}Pantanal{/link}. Aqui o clã guarda armas para soldados que ainda não armou. Seus guerreiros não são apenas combatentes: vinculadores de almas e recuperadores andam entre eles, e ali foi visto um dragonete, curvado e subjugado. O {link:captain-stoutfist}Capitão Stoutfist{/link} ficaria feliz em ver esse arsenal levado embora antes que possa ser usado. O que os orcs pretendem recuperar, os anões só podem adivinhar.]=],
		},
	},
})

Translate("ptBR", "mosshide-fen", {
	title = "Charco Pelemusgo",
	sections = {
		{
			title = "Resumo",
			text = [=[O Charco Pelemusgo é um trecho de pântano no sul do {link:wetlands}Pantanal{/link}, perto do portão {link:dwarves}anão{/link} de Algaz. Seu nome vem dos gnolls Pelemusgo. Os gnolls viveram em paz nos charcos por muitos anos, mas seu número cresceu. Eles pisoteiam os arbustos e as flores do pântano, cortam suas árvores para suas fogueiras e carregam pederneiras toscas para acendê-las. O espírito chamado {link:rethiel-the-greenwarden}Guarda Verde{/link} os marcou como uma ferida na terra.]=],
		},
	},
})

Translate("ptBR", "sundown-marsh", {
	title = "Pântano do Ocaso",
	sections = {
		{
			title = "Resumo",
			text = [=[O Pântano do Ocaso fica no norte do {link:wetlands}Pantanal{/link}, uma terra baixa e úmida de poças e juncos. Os gnolls Pelemusgo também caçam aqui, com seus místicos e alfas entre eles. Coisas mais estranhas se erguem da água. Rastejantes do charco se arrastam pelos canais, e senhores do charco ainda maiores se erguem entre eles. {link:rethiel-the-greenwarden}O Guarda Verde{/link} os chama de bolhas febris na terra, nascidas de uma supuração que ninguém sabe explicar, e deseja devolvê-los ao pântano.]=],
		},
	},
})

Translate("ptBR", "saltspray-glen", {
	title = "Vale Espuma de Sal",
	sections = {
		{
			title = "Resumo",
			text = [=[O Vale Espuma de Sal é uma depressão no noroeste do {link:wetlands}Pantanal{/link}, aberta ao vento que vem do mar. É terra de raptores. Os raptores navalhadentes que caçam aqui recebem esse nome por seus dentes, longos e afiados o bastante para perfurar as escamas de um dragonete, e dizem que seus ovos têm gemas do tamanho da cabeça de um {link:gnomes}gnomo{/link}. O {link:dwarves}anão{/link} {link:howin-kindfeather}Howin Kindfeather{/link} manda caçadores aqui em busca de ambos.]=],
		},
	},
})

Translate("ptBR", "ironbeard-s-tomb", {
	title = "Tumba dos Barbaférreos",
	sections = {
		{
			title = "Resumo",
			text = [=[A Tumba dos Barbaférreos é um antigo local de sepultamento {link:dwarves}anão{/link} no norte do {link:wetlands}Pantanal{/link}, não muito longe de {link:dun-modr}Dun Modr{/link}. Quem quer que tenha sido Ironbeard, a tumba sobreviveu a seu nome. Gosmas carmesins gotejantes agora rastejam por ela e engolem o que tocam. Uma mulher de Menethil chamada {link:sida}Sida{/link} ainda vem até aqui uma vez por semana, com gosmas ou sem elas, e certa vez teve de fugir delas sem sua bolsa.]=],
		},
		{
			title = "Sem Registro",
			text = [=[Nenhuma crônica diz quem foi Ironbeard, quando foi sepultado aqui, nem por que {link:sida}Sida{/link} visita sua tumba.]=],
		},
	},
})

Translate("ptBR", "direforge-hill", {
	title = "Monte Umbraforja",
	sections = {
		{
			title = "Resumo",
			text = [=[O Monte Umbraforja ergue-se a leste de {link:dun-modr}Dun Modr{/link}. É o principal acampamento dos {link:dark-iron-dwarves}Ferro Negro{/link} no {link:wetlands}Pantanal{/link}. Daqui seus escavadores cavam, seus sabotadores partem e seus demolidores levam a pólvora que derrubou a {link:thandol-span}Ponte Thandol{/link}. Seu senhor nestas terras é o bruxo {link:balgaras-the-foul}Balgaras, o Imundo{/link}, que raramente é visto nos combates. Os anões do acampamento de {link:longbraid-the-grim}Longbraid{/link} sabem que a guerra pelo norte será decidida neste monte.]=],
		},
	},
})

Translate("ptBR", "raptor-ridge", {
	title = "Serra dos Raptores",
	sections = {
		{
			title = "Resumo",
			text = [=[A Serra dos Raptores é uma plataforma alta e rochosa no nordeste do {link:wetlands}Pantanal{/link}. É o lar dos raptores navalhadentes, e uma grande matriarca de sua espécie domina a serra. Poucos caçadores a escalam de boa vontade. Os que o fazem vêm atrás dos dentes e dos ovos dos navalhadentes, e voltam com cicatrizes.]=],
		},
	},
})

Translate("ptBR", "bluegill-marsh", {
	title = "Pântano Peixeazul",
	sections = {
		{
			title = "Resumo",
			text = [=[O Pântano Peixeazul fica na costa ao norte do {link:menethil-harbor}Porto de Menethil{/link}. Os murlocs Peixeazul subiram das águas profundas e construíram seus casebres ao longo da margem. Atacam pescadores e mercadores na estrada, e quando o navio mercante {i}Blind Princess{/i} passou, arrastaram boa parte de sua carga para o mar. Um {link:murlocs}murloc{/link} chamado Gobbler lidera ataques a partir da enseada do rio e sempre escapa de volta para a segurança dos casebres.]=],
		},
	},
})

Translate("ptBR", "black-channel-marsh", {
	title = "Pântano do Canal Negro",
	sections = {
		{
			title = "Resumo",
			text = [=[O Pântano do Canal Negro é um labirinto de águas escuras e juncos no oeste do {link:wetlands}Pantanal{/link}, entre o {link:menethil-harbor}Porto de Menethil{/link} e a escavação da {link:explorers-league}Liga dos Exploradores{/link}. Seus canais são o refúgio dos crocoliscos gigantes que os curtidores de Menethil tanto prezam, e os raptores malhados das colinas descem até suas margens para caçar. O aprendiz do curtidor veio até aqui para esfolar crocoliscos, e os crocoliscos levaram sua perna.]=],
		},
	},
})

Translate("ptBR", "the-green-belt", {
	title = "Zona Verde",
	sections = {
		{
			title = "Resumo",
			text = [=[A Zona Verde é um longo vale de relva e água no leste do {link:wetlands}Pantanal{/link}, a leste do ponto em que a estrada se bifurca rumo a {link:dun-modr}Dun Modr{/link}. Dragonetes carmesins fazem ninhos ao longo dele. Ursos enlouquecidos por alguma doença vagam por suas encostas. {link:rethiel-the-greenwarden}O Guarda Verde{/link}, espírito do pântano, caminha aqui entre os crocoliscos, e os orcs das colinas nunca estão longe.]=],
		},
	},
})

Translate("ptBR", "the-lost-fleet", {
	title = "Frota Perdida",
	sections = {
		{
			title = "Resumo",
			text = [=[A Frota Perdida é o cemitério de navios na costa noroeste do {link:wetlands}Pantanal{/link}. Aqui a {link:third-fleet}Terceira Frota{/link} de {link:kul-tiras}Kul Tiraz{/link} queimou e afundou sob o fogo dos dragões vermelhos na {link:second-war}Segunda Guerra{/link}. Seus cascos ainda jazem nas águas rasas. Nem todas as tripulações encontraram descanso. Algo amaldiçoado foi escondido a bordo de um dos navios, e seu poder prende os marinheiros e fuzileiros afogados em seus conveses apodrecidos, e o capitão deles entre eles.]=],
		},
	},
})

Translate("ptBR", "thelgen-rock", {
	title = "Rocha de Thelgen",
	sections = {
		{
			title = "Resumo",
			text = [=[A Rocha de Thelgen é uma caverna nas colinas do sul do {link:wetlands}Pantanal{/link}, a sudeste da escavação de {link:prospector-whelgar}Whelgar{/link}. Aranhas a enchem, e seu veneno é tão forte que os alquimistas de Menethil precisam de suas glândulas intactas para fazer antídoto. Uma grande aranha chamada Leech Widow caça perto de sua entrada. O caminho que passa pela Rocha de Thelgen sobe para as terras altas onde fica o {link:excavation-site}Sítio de Escavação{/link}.]=],
		},
	},
})

Translate("ptBR", "the-drunken-dwarf", {
	title = "The Drunken Dwarf",
	sections = {
		{
			title = "Resumo",
			text = [=[The Drunken Dwarf é uma taberna aberta há pouco tempo no sul do {link:wetlands}Pantanal{/link}, perto da estrada que sai de {link:dun-algaz}Dun Algaz{/link}. É uma visão bem-vinda para os viajantes que atravessaram o desfiladeiro com orcs em seus calcanhares. Aurian Highgrove cuida do balcão. Os Firebrew, Bhalir e Agriel, cuidam da cozinha. Seu nome, "O Anão Bêbado", é uma promessa que a maioria de seus hóspedes cumpre de bom grado.]=],
		},
	},
})

Translate("ptBR", "captain-stoutfist", {
	title = "Capitão Stoutfist",
	subtitle = "Comandante da Bastilha Menethil",
	found = "A sala de guerra da Bastilha Menethil",
	hint = [=[Procure o capitão que planeja a defesa de Menethil na sala de guerra de sua fortaleza.]=],
	allegiance = "Reino de Altaforja",
	aliases = { "Stoutfist" },
	sections = {
		{
			title = "Resumo",
			text = [=[O Capitão Stoutfist comanda o {link:menethil-harbor}Porto de Menethil{/link} em nome do {link:kingdom-of-ironforge}Reino de Altaforja{/link}. Da sala de guerra da Bastilha Menethil, ele vigia três inimigos ao mesmo tempo: os {link:dark-iron-dwarves}Ferro Negro{/link} no norte, os {link:dragonmaw-clan}Presa do Dragão{/link} nas colinas e os orcs que agora sufocam o desfiladeiro de {link:dun-algaz}Dun Algaz{/link}. Tem poucos soldados e menos reforços ainda. Convoca todo guerreiro que chega pelo desfiladeiro.]=],
		},
		{
			title = "Importância",
			text = [=[Stoutfist é o homem de quem depende toda a costa oeste. Se Menethil cair, a {link:alliance}Aliança{/link} perde seu porto no norte e a estrada entre {link:ironforge}Altaforja{/link} e o mar.]=],
		},
		{
			title = "Feitos",
			text = [=[• Recebe os relatórios de {link:valstag-ironjaw}Valstag Ironjaw{/link} sobre o avanço dos {link:dragonmaw-clan}Presa do Dragão{/link} em {link:dun-algaz}Dun Algaz{/link}.
• Envia guerreiros contra o {link:angerfang-encampment}Acampamento Presirada{/link} para tomar os estandartes de guerra dos orcs.
• Ordena que as catapultas dos Presa do Dragão sejam queimadas, e que o chefe deles morra.
• Quer as armas de {link:dragonmaw-retreat}Dragonmaw Retreat{/link} tomadas antes que possam armar novos soldados.]=],
		},
	},
	chapters = {
		{
			title = "A Cartada de Nek'rosh",
			hint = [=[Descubra o que os Presa do Dragão construíram em seu acampamento.]=],
			text = [=[Os guerreiros que atacaram Presirada voltaram com mais do que estandartes. Tinham visto catapultas. {link:chieftain-nek-rosh}Nek'rosh{/link} pretendia sitiar Menethil, e com {link:dun-algaz}Dun Algaz{/link} em mãos orcs, nenhuma ajuda chegaria ao porto a tempo. Stoutfist distribuiu isca de fogo e deu uma ordem simples: queimem as máquinas e depois cortem a fera pelo pescoço.]=],
		},
		{
			title = "A Estatueta do Rei",
			hint = "Leve a estatueta recuperada à fortaleza de Menethil.",
			text = [=[A estatueta de prata tomada dos murlocs tinha como destino a fortaleza dele. Stoutfist ficou orgulhoso de ter nas mãos um memorial do {link:terenas-menethil}Rei Terenas{/link}, cujo nome sua fortaleza leva, mas sabia bem o que era seu porto: um lugar calmo numa tempestade de inimigos. Temia o que os {link:dragonmaw-clan}Presa do Dragão{/link} fariam com algo assim, e a enviou a {link:stormwind-city}Ventobravo{/link} para que fosse guardada em segurança.]=],
		},
	},
	mentions = {
		{ text = "Apresente-se ao Capitão Stoutfist" },
		{ text = "Estandartes de Guerra" },
		{ text = "A Cartada de {link:chieftain-nek-rosh}Nek'rosh{/link}" },
		{ text = "Derrote {link:chieftain-nek-rosh}Nek'rosh{/link}" },
		{ text = "Devolva a Estatueta" },
		{ text = "Um Amigo da Família, para o Grão-lorde" },
		{ text = "Um Amigo da Família, para a Catedral" },
		{ text = "Desarmamento Forçado" },
	},
	bonds = {
		{ id = "valstag-ironjaw", name = "Valstag Ironjaw", note = "traz-lhe relatórios de Dun Algaz" },
		{ id = "chieftain-nek-rosh", name = "Chefe Nek'rosh", note = "inimigo" },
		{ id = "karl-boran", name = "Karl Boran", note = "enviou-lhe a estatueta" },
		{ id = "bolvar-fordragon", name = "Bolvar Fordragon", note = "o Grão-lorde a quem a confia" },
	},
})

Translate("ptBR", "valstag-ironjaw", {
	title = "Valstag Ironjaw",
	subtitle = "Oficial de Menethil",
	found = "Porto de Menethil, perto da fortaleza",
	hint = [=[Encontre o anão de Menethil que recebe os relatórios da estrada de Algaz.]=],
	allegiance = "Reino de Altaforja",
	aliases = { "Valstag" },
	sections = {
		{
			title = "Resumo",
			text = [=[Valstag Ironjaw recebe aqueles que abrem caminho à força por {link:dun-algaz}Dun Algaz{/link} até Menethil. Ele conhece bem os orcs. Os {link:dragonmaw-clan}Presa do Dragão{/link} sempre se mantiveram nas colinas, e ele não consegue explicar por que agora se lançaram sobre o desfiladeiro. Também conhece a história do chão sob suas botas. O porto foi primeiro um estaleiro {link:orcs}orc{/link}, construído com madeira e ferro roubados de Khaz Modan, e muito desse saque ainda está espalhado pelas docas.]=],
		},
		{
			title = "Feitos",
			text = [=[• Envia notícias dos combates de Algaz ao {link:captain-stoutfist}Capitão Stoutfist{/link}.
• Recolhe a velha madeira e o velho ferro orcs do porto para reforçar suas defesas.]=],
		},
	},
	mentions = {
		{ text = "A Travessia de Algaz" },
		{
			text = [=[Apresente-se ao {link:captain-stoutfist}Capitão Stoutfist{/link}]=],
		},
		{ text = "Espólios de Guerra" },
	},
	bonds = {
		{ id = "captain-stoutfist", name = "Capitão Stoutfist", note = "seu comandante" },
		{ id = "mountaineer-rockgar", name = "Montanhista Rockgar", note = "envia-lhe voluntários pelo desfiladeiro" },
	},
})

Translate("ptBR", "karl-boran", {
	title = "Karl Boran",
	subtitle = "Agente da Marinha Mercante",
	found = "As docas do Porto de Menethil",
	hint = [=[Fale com o homem nas docas que paga pela segurança dos mercadores.]=],
	allegiance = "Marinha Mercante",
	sections = {
		{
			title = "Resumo",
			text = [=[Karl Boran cuida dos mercadores que negociam pelo {link:menethil-harbor}Porto de Menethil{/link}. Os murlocs Peixeazul tornaram esse trabalho difícil. Eles atormentam a estrada da costa e atacam os navios, e quando investiram contra o navio mercante {i}Blind Princess{/i}, arrastaram boa parte de sua carga para o mar. A peça mais preciosa era uma estatueta de prata, um memorial do Rei {link:terenas-menethil}Terenas Menethil{/link}. Boran paga bem para tê-la de volta.]=],
		},
		{
			title = "Feitos",
			text = [=[• Põe a cabeça do {link:murlocs}murloc{/link} Gobbler e de seus parentes a prêmio.
• Envia gente para vasculhar os casebres dos murlocs em busca da carga perdida do {i}Blind Princess{/i}.]=],
		},
	},
	mentions = {
		{ text = "Garras das {link:blackfathom-deeps}Profundezas{/link}" },
		{ text = "Recuperando Mercadorias" },
		{ text = "Devolva a Estatueta" },
	},
	bonds = {
		{ id = "captain-stoutfist", name = "Capitão Stoutfist", note = "a estatueta era destinada à fortaleza dele" },
	},
})

Translate("ptBR", "first-mate-fitzsimmons", {
	title = "Imediato Fitzsimmons",
	subtitle = "Último Sobrevivente da Terceira Frota",
	found = "A Taberna Aguafunda, Porto de Menethil",
	hint = [=[Pague uma bebida ao marinheiro que afoga suas lembranças na Taberna Aguafunda.]=],
	allegiance = "Kul Tiraz (no passado)",
	aliases = { "Fitzsimmons" },
	sections = {
		{
			title = "Resumo",
			text = [=[Fitzsimmons era imediato do {i}Wave Mistress{/i}, um navio de linha da {link:third-fleet}Terceira Frota{/link} de {link:kul-tiras}Kul Tiraz{/link}. Na última viagem da frota, dragões vermelhos montados por orcs caíram sobre ela e a queimaram diante da costa do {link:wetlands}Pantanal{/link}. Só ele sobreviveu. Agora passa os dias na Taberna Aguafunda, cheirando mal e com sede, e as noites sonhando com seus irmãos afogados.]=],
		},
		{
			title = "Importância",
			text = [=[Fitzsimmons é a memória viva da {link:third-fleet}Frota Condenada{/link}. Só ele sabe que algo terrível foi escondido a bordo de um de seus navios, e que seu poder impede os mortos de descansar.]=],
		},
		{
			title = "Feitos",
			text = [=[• Conta a história da {link:third-fleet}Terceira Frota{/link} a quem lhe paga hidromel.
• Pede que seus irmãos amaldiçoados sejam libertados.
• Envia buscadores ao fantasma do {link:captain-halyndor}Capitão Halyndor{/link} atrás da chave do cofre do navio.
• Indica o caminho até o {link:rethiel-the-greenwarden}Guarda Verde{/link}, e avisa o buscador para não ir.]=],
		},
	},
	chapters = {
		{
			title = "A Frota Condenada",
			hint = [=[Solte a língua do velho marinheiro com uma caneca de hidromel.]=],
			text = [=[Com uma bebida nova na mão, Fitzsimmons conta tudo sem rodeios. A frota zarpou; os dragões vieram; os navios queimaram e afundaram. Ele não sabe por que sobreviveu. Amaldiçoa seu capitão por tê-los levado à perdição, e bebe a seus irmãos em seus túmulos de água.]=],
		},
		{
			title = "O Olho Amaldiçoado",
			hint = "Abra o cofre do Intrepid.",
			text = [=[O {link:captain-halyndor}Capitão Halyndor{/link} guardava a coisa trancada em seu cofre a bordo do {i}Intrepid{/i}. Quando o cofre foi aberto, continha um orbe enegrecido que pulsava com uma luz doentia: um Olho de Paleth, corrompido pela tristeza que havia testemunhado. Fitzsimmons não quis tocá-lo. Enviou-o ao sacerdote {link:glorin-steelbrow}Glorin Steelbrow{/link}.]=],
		},
	},
	mentions = {
		{ text = "{link:third-fleet}A Terceira Frota{/link}" },
		{ text = "A Tripulação Amaldiçoada" },
		{ text = "Quebrando a Maldição" },
		{ text = "{link:rethiel-the-greenwarden}O Guarda Verde{/link}" },
	},
	bonds = {
		{ id = "captain-halyndor", name = "Capitão Halyndor", note = "seu antigo capitão, a quem culpa" },
		{ id = "glorin-steelbrow", name = "Glorin Steelbrow", note = "recebeu o Olho" },
		{ id = "rethiel-the-greenwarden", name = "Rethiel, o Guarda Verde", note = "o espírito contra o qual adverte" },
	},
})

Translate("ptBR", "glorin-steelbrow", {
	title = "Glorin Steelbrow",
	subtitle = "Sacerdote de Menethil",
	found = "A Taberna Aguafunda, Porto de Menethil",
	hint = [=[Encontre o sacerdote anão que conhece os segredos da frota afundada.]=],
	allegiance = "Reino de Altaforja · Igreja da Luz Sagrada",
	aliases = { "Glorin" },
	sections = {
		{
			title = "Resumo",
			text = [=[Glorin Steelbrow é um sacerdote {link:dwarves}anão{/link} da {link:holy-light}Luz Sagrada{/link} que vive no {link:menethil-harbor}Porto de Menethil{/link}. Ele conhece os destroços da {link:third-fleet}Terceira Frota{/link} melhor que a maioria. Um navio que navegava com ela, o {i}Flying Osprey{/i}, levava uma carga de ferro forjado pela Luz, um metal que golpeia com força sagrada. Glorin sabe dizer onde ele está e quem sabe trabalhá-lo. Mas quando o Olho Amaldiçoado de Paleth chegou a suas mãos, ele não conseguiu purificá-lo. Os Olhos foram feitos por sacerdotes humanos, e só um mestre humano poderia curar um deles.]=],
		},
		{
			title = "Feitos",
			text = [=[• Envia buscadores aos destroços do {i}Flying Osprey{/i} atrás de ferro forjado pela Luz.
• Envia o Olho Amaldiçoado de Paleth ao {link:archbishop-benedictus}Arcebispo Benedictus{/link}, em {link:stormwind-city}Ventobravo{/link}.]=],
		},
	},
	mentions = {
		{ text = "A {link:third-fleet}Frota Condenada{/link}" },
		{ text = "Ferro Forjado pela Luz" },
		{ text = "Os Lingotes Perdidos" },
		{ text = "Braço Abençoado" },
		{ text = "O Olho de Paleth" },
		{ text = "Purificando o Olho" },
	},
	bonds = {
		{ id = "first-mate-fitzsimmons", name = "Imediato Fitzsimmons", note = "um bêbado a quem não paga bebidas" },
		{ id = "archbishop-benedictus", name = "Arcebispo Benedictus", note = "pode purificar o Olho" },
	},
})

Translate("ptBR", "innkeeper-helbrek", {
	title = "Estalajadeiro Helbrek",
	subtitle = "Dono da Taberna Aguafunda",
	found = "A Taberna Aguafunda, Porto de Menethil",
	hint = "Alugue um quarto na Taberna Aguafunda.",
	allegiance = "Reino de Altaforja",
	aliases = { "Helbrek" },
	sections = {
		{
			title = "Resumo",
			text = [=[Helbrek cuida da Taberna Aguafunda, a casa mais movimentada do {link:menethil-harbor}Porto de Menethil{/link}. Todos que desembarcam no {link:wetlands}Pantanal{/link} passam sob seu teto cedo ou tarde: marinheiros vindos dos navios, soldados vindos da estrada de Algaz, estudiosos da {link:explorers-league}Liga dos Exploradores{/link} à espera de escolta até sua escavação. {link:mikhail}Mikhail{/link} serve as bebidas em seu balcão. Um sobrevivente bêbado da {link:third-fleet}Terceira Frota{/link} ocupa suas mesas, e nem todo hóspede é o que parece.]=],
		},
		{
			title = "Sem Registro",
			text = [=[Pouco se escreveu sobre o próprio Helbrek. Sua taberna diz mais sobre o porto do que ele.]=],
		},
	},
	bonds = {
		{ id = "mikhail", name = "Mikhail", note = "seu taberneiro" },
		{ id = "first-mate-fitzsimmons", name = "Imediato Fitzsimmons", note = "um freguês habitual" },
	},
})

Translate("ptBR", "mikhail", {
	title = "Mikhail",
	subtitle = "Taberneiro da Taberna Aguafunda",
	found = "O balcão da Taberna Aguafunda",
	hint = [=[Mencione um velho amigo de Ventobravo ao taberneiro da Taberna Aguafunda.]=],
	allegiance = "Taberna Aguafunda (no passado, agente de Ventobravo)",
	sections = {
		{
			title = "Resumo",
			text = [=[Mikhail serve bebidas na Taberna Aguafunda. Alguns anos atrás, deixou {link:stormwind-city}Ventobravo{/link} e o trabalho sombrio que fazia lá, e se estabeleceu à beira-mar. Ainda é amigo de {link:elling-trias}Elling Trias{/link}, e para quem chega em nome de Elling, sua hospitalidade não tem limites. Ele admite, um pouco envergonhado, que às vezes sente falta da antiga emoção.]=],
		},
	},
	chapters = {
		{
			title = "O Homem Junto à Porta",
			hint = "Ajude Mikhail com o estranho que escuta com atenção demais.",
			text = [=[Um freguês junto à porta vinha escutando com atenção demais. Era {link:tapoke-slim-jahn}Tapoke Jahn{/link}, chamado Slim, e uma vez pego, falou. Tinha aceitado moedas dos {link:defias-brotherhood}Défias{/link} para pôr o homem deles a bordo de um navio real no porto. Mikhail jurou que até um ladino precisa guardar alguma honra, e mandou avisar Elling na mesma hora.]=],
		},
	},
	mentions = {
		{ text = "O Diplomata Desaparecido" },
		{ text = "O Diplomata Desaparecido" },
		{ text = "O Diplomata Desaparecido" },
		{
			text = [=[O Diplomata Desaparecido, para {link:theramore-isle}Theramore{/link}]=],
		},
	},
	bonds = {
		{ id = "elling-trias", name = "Elling Trias", note = "seu velho amigo em Ventobravo" },
		{ id = "tapoke-slim-jahn", name = "Tapoke \"Slim\" Jahn", note = "o traidor que ele desmascarou" },
		{ id = "innkeeper-helbrek", name = "Estalajadeiro Helbrek", note = "seu patrão" },
	},
})

Translate("ptBR", "tapoke-slim-jahn", {
	title = "Tapoke \"Slim\" Jahn",
	subtitle = "Um Traidor na Taberna",
	found = "A Taberna Aguafunda, Porto de Menethil",
	hint = [=[Observe o freguês que escuta com atenção demais na Taberna Aguafunda.]=],
	allegiance = "Irmandade Défias (por dinheiro)",
	aliases = { "Slim", "Tapoke Jahn" },
	sections = {
		{
			title = "Resumo",
			text = [=[Tapoke Jahn, a quem o submundo chama de Slim, bebe na Taberna Aguafunda e mantém os ouvidos abertos. Foi pago pela {link:defias-brotherhood}Irmandade Défias{/link} para uma única tarefa no {link:menethil-harbor}Porto de Menethil{/link}, e a cumpriu. Quando soube que estranhos perguntavam por ele, tentou escapulir pela porta.]=],
		},
	},
	chapters = {
		{
			title = "O Que Slim Sabia",
			hint = "Detenha Slim antes que ele fuja da taberna.",
			text = [=[Slim não fora pago o bastante para morrer pelos {link:defias-brotherhood}Défias{/link}, e disse isso. O prisioneiro que eles haviam capturado não era diplomata nenhum. Era o rei de {link:stormwind-city}Ventobravo{/link}, navegando em segredo para {link:theramore-isle}Theramore{/link}. A parte de Slim fora pôr um homem, chamado {link:private-hendel}Hendel{/link}, a bordo do navio do rei no porto. Ele acreditava que os Défias trabalhavam para alguém maior do que eles.]=],
		},
	},
	mentions = {
		{ text = "O Diplomata Desaparecido" },
		{ text = "O Diplomata Desaparecido" },
	},
	bonds = {
		{ id = "mikhail", name = "Mikhail", note = "o desmascarou" },
		{ id = "varian-wrynn", name = "Varian Wrynn", note = "o rei que ele ajudou a trair" },
	},
})

Translate("ptBR", "sida", {
	title = "Sida",
	subtitle = "Uma Mulher de Menethil",
	found = "Porto de Menethil, perto da loja de mercadorias gerais",
	hint = [=[Fale com a mulher de Menethil que perdeu a bolsa para uma gosma.]=],
	allegiance = "Porto de Menethil",
	sections = {
		{
			title = "Resumo",
			text = [=[Sida vive no {link:menethil-harbor}Porto de Menethil{/link}. Uma vez por semana, ela caminha até a {link:ironbeard-s-tomb}Tumba dos Barbaférreos{/link}, perto de {link:dun-modr}Dun Modr{/link}, atravessando uma terra em guerra. Em sua última visita, as gosmas da tumba vieram atrás dela. Em pânico, ela atirou a bolsa em uma delas, e a gosma a engoliu inteira. Ela escapou, mas a bolsa guardava algo de que ela precisava muito.]=],
		},
		{
			title = "Sem Registro",
			text = [=[Sida não diz por que visita a tumba, nem o que guardava na bolsa. O curtidor {link:james-halloran}James Halloran{/link} certa vez pensou em mandar a esposa falar com ela, embora não tenha dito por quê.]=],
		},
	},
	mentions = {
		{ text = "Cavando na Gosma" },
		{ text = "Entrega Diária" },
	},
	bonds = {
		{ id = "james-halloran", name = "James Halloran", note = "um vizinho que fala dela" },
	},
})

Translate("ptBR", "james-halloran", {
	title = "James Halloran",
	subtitle = "Curtidor de Menethil",
	found = "A casa dos Halloran, Porto de Menethil",
	hint = [=[Encontre o curtidor cujas peles de crocolisco são vendidas em todos os portos.]=],
	allegiance = "Porto de Menethil",
	sections = {
		{
			title = "Resumo",
			text = [=[James Halloran é o curtidor do {link:menethil-harbor}Porto de Menethil{/link}. Suas peles de crocolisco curtidas são procuradas do outro lado do mar, e navios as levam a portos do mundo inteiro. Caçadores como Einar Stonegrip lhe trazem peles do pântano. Seu aprendiz, a quem ama como a um filho, saiu atrás dos crocoliscos gigantes da costa e voltou com uma perna só.]=],
		},
		{
			title = "Feitos",
			text = [=[• Compra peles de crocoliscos jovens e gigantes.
• Nestes dias encontrou um comércio mais rico: as escamas dos dragonetes carmesins da {link:the-green-belt}Zona Verde{/link}.]=],
		},
	},
	mentions = {
		{ text = "Entrega Diária" },
		{ text = "Peles de Crocolisco Jovem" },
		{ text = "Os Deveres do Aprendiz" },
		{ text = "Crocos do Céu" },
		{ text = "Entrega de Caixote Carmesim" },
	},
	bonds = {
		{ id = "howin-kindfeather", name = "Howin Kindfeather", note = "encomendou suas escamas de dragonete" },
		{ id = "sida", name = "Sida", note = "uma vizinha" },
	},
})

Translate("ptBR", "sylessa-duskwhisper", {
	title = "Sylessa Duskwhisper",
	subtitle = "Buscadora da Flor",
	found = "Porto de Menethil",
	hint = [=[Fale com a elfa noturna que cruzou o mar até Menethil em busca de uma flor.]=],
	allegiance = "Elfos noturnos de Teldrassil",
	sections = {
		{
			title = "Resumo",
			text = [=[Sylessa Duskwhisper é uma {link:night-elves}elfa noturna{/link} que veio ao {link:menethil-harbor}Porto de Menethil{/link} de {link:auberdine}Auberdine{/link} e da grande árvore {link:teldrassil}Teldrassil{/link}. Ela busca uma única flor. Entre a carga do {i}Flying Osprey{/i}, perdido com a {link:third-fleet}Terceira Frota{/link} diante desta costa, estava Nord'el, a Flor dos Céus. Ela floresceu sob a lua cheia no pico do {link:mount-hyjal}Monte Hyjal{/link}, o antigo lar de seu povo, e sua perda ainda o entristece.]=],
		},
		{
			title = "Feitos",
			text = [=[• Busca ajuda para recuperar Nord'el dos destroços do {i}Flying Osprey{/i}, onde agora vivem saqueadores murlocs.]=],
		},
	},
	mentions = {
		{ text = "Flor dos Céus" },
	},
	bonds = {
		{ id = "glorin-steelbrow", name = "Glorin Steelbrow", note = "conhece os mesmos destroços" },
	},
})

Translate("ptBR", "caitlin-grassman", {
	title = "Caitlin Grassman",
	subtitle = "Alquimista de Menethil",
	found = "Porto de Menethil",
	hint = [=[Fale com a alquimista de Menethil que precisa do veneno de uma aranha.]=],
	allegiance = "Porto de Menethil",
	sections = {
		{
			title = "Resumo",
			text = [=[Caitlin Grassman cuida da alquimia do {link:menethil-harbor}Porto de Menethil{/link}, e o {link:wetlands}Pantanal{/link} a mantém ocupada. Ela jura que tudo no pântano é venenoso, como se o veneno corresse pela própria terra. Não pode sair do porto de novo até ter preparado mais antídoto. Para isso precisa de uma glândula de veneno das aranhas da {link:thelgen-rock}Rocha de Thelgen{/link}, inteira e intacta, o que é mais difícil de achar do que parece.]=],
		},
	},
	mentions = {
		{ text = "Perigos Alquímicos" },
	},
})

Translate("ptBR", "bart-tidewater", {
	title = "Bart Tidewater",
	subtitle = "Capitão do Maiden's Virtue",
	found = "As docas do Porto de Menethil",
	hint = [=[Encontre o autoproclamado capitão que anda pelas docas de Menethil.]=],
	allegiance = "Porto de Menethil",
	sections = {
		{
			title = "Resumo",
			text = [=[Bart Tidewater diz ser capitão do {i}Maiden's Virtue{/i} e anda pelas docas de Menethil como se fossem dele. Nem todos concordam com seu título. Um velho conhecido chamado {link:tom-half-fish-wilson}Half-fish{/link} diz que o {i}Virtue{/i} nunca navegou além de uma rocha em {link:tanaris}Tanaris{/link}, que Bart é um ator que ganhou o navio nas cartas, e que trapaceou para isso. Mesmo assim, Half-fish lhe mandou um presente.]=],
		},
	},
	mentions = {
		{ text = "Falta de Virtude" },
	},
})

Translate("ptBR", "archaeologist-flagongut", {
	title = "Arqueólogo Flagongut",
	subtitle = "Estudioso da Liga dos Exploradores",
	found = "A Taberna Aguafunda, Porto de Menethil",
	hint = [=[Encontre o arqueólogo que espera na Taberna Aguafunda por uma escolta até a escavação.]=],
	allegiance = "Liga dos Exploradores",
	aliases = { "Flagongut" },
	sections = {
		{
			title = "Resumo",
			text = [=[Flagongut é um arqueólogo da {link:explorers-league}Liga dos Exploradores{/link}. Numa das conferências da Liga em {link:ironforge}Altaforja{/link}, ele mostrou um fóssil que acreditava guardar um poder oculto. Encontrou uma relíquia, a Pedra de Relu, que julgava capaz de despertá-lo. Na estrada para a escavação de {link:prospector-whelgar}Whelgar{/link}, raptores o atacaram, e um deles engoliu a pedra. Desde então ele espera na Taberna Aguafunda por uma escolta.]=],
		},
		{
			title = "Feitos",
			text = [=[• Estuda os fósseis da escavação de {link:prospector-whelgar}Whelgar{/link} e da escavação de {link:prospector-remtravel}Remtravel{/link}, na {link:darkshore}Costa Negra{/link}.
• Busca a Pedra de Relu, perdida na barriga de um raptor malhado.]=],
		},
	},
	chapters = {
		{
			title = "A Pedra de Relu",
			hint = "Leve ao arqueólogo os dois fósseis e a pedra.",
			text = [=[Com a pedra e os dois fósseis diante de si, Flagongut pôs-se a trabalhar. O que lhe respondeu não foi um simples segredo do passado. Um espírito foi invocado, e ele gritou de espanto.]=],
		},
	},
	mentions = {
		{ text = "O Prospector Distraído" },
		{ text = "O Prospector Distraído" },
	},
	bonds = {
		{ id = "prospector-whelgar", name = "Prospector Whelgar", note = "guarda o fóssil original" },
		{ id = "prospector-remtravel", name = "Prospector Remtravel", note = "encontrou o outro fóssil" },
		{ id = "archaeologist-hollee", name = "Arqueóloga Hollee", note = "enviou-lhe o fóssil de Remtravel" },
	},
})

Translate("ptBR", "tarrel-rockweaver", {
	title = "Tarrel Rockweaver",
	subtitle = "Marido da Escavação",
	found = "A estrada ao norte do Porto de Menethil",
	hint = [=[Encontre o anão aflito que espera cartas do lado de fora de Menethil.]=],
	allegiance = "Liga dos Exploradores",
	aliases = { "Tarrel" },
	sections = {
		{
			title = "Resumo",
			text = [=[Tarrel Rockweaver espera do lado de fora do {link:menethil-harbor}Porto de Menethil{/link} por notícias de sua esposa, {link:merrin-rockweaver}Merrin{/link}, que trabalha na escavação de {link:prospector-whelgar}Whelgar{/link}. Toda semana ela lhe escrevia. Então se passaram duas semanas sem uma palavra. Ele é um estudioso dedicado das escavações, e uma velha amiga dos tempos de estudante se lembra dele com carinho. Em Menethil, porém, ele é apenas um marido assustado.]=],
		},
		{
			title = "Feitos",
			text = [=[• Pede aos batedores de {link:longbraid-the-grim}Longbraid{/link} que procurem a equipe da escavação.
• Chora os mortos da escavação e anseia por um dia em que o povo de {link:magni-bronzebeard}Magni{/link} possa viver sem medo.]=],
		},
	},
	mentions = {
		{ text = "Em Busca da Equipe de Escavação" },
		{ text = "Em Busca da Equipe de Escavação" },
		{ text = "Amor Não Correspondido" },
	},
	bonds = {
		{ id = "merrin-rockweaver", name = "Merrin Rockweaver", note = "sua esposa" },
		{ id = "archaeologist-hollee", name = "Arqueóloga Hollee", note = "sua antiga colega de estudos" },
	},
})

Translate("ptBR", "merrin-rockweaver", {
	title = "Merrin Rockweaver",
	subtitle = "Sobrevivente da Escavação",
	found = "O penhasco acima do Sítio de Escavação de Whelgar",
	hint = [=[Encontre a escavadora que sobreviveu aos raptores na Escavação de Whelgar.]=],
	allegiance = "Liga dos Exploradores",
	aliases = { "Merrin" },
	sections = {
		{
			title = "Resumo",
			text = [=[Merrin Rockweaver era uma das escavadoras da equipe de {link:prospector-whelgar}Whelgar{/link}. Estavam desenterrando artefatos raros quando encontraram os primeiros ossos enormes, e então vieram os raptores. Ela sobreviveu porque {link:ormer-ironbraid}Ormer Ironbraid{/link} se manteve firme enquanto ela e o prospector fugiam. Agora os três estão presos num penhasco acima das ruínas de seu trabalho.]=],
		},
		{
			title = "Feitos",
			text = [=[• Envia uma carta ao marido, {link:tarrel-rockweaver}Tarrel{/link}, contando o que aconteceu à escavação.]=],
		},
	},
	mentions = {
		{ text = "Em Busca da Equipe de Escavação" },
	},
	bonds = {
		{ id = "tarrel-rockweaver", name = "Tarrel Rockweaver", note = "seu marido" },
		{ id = "ormer-ironbraid", name = "Ormer Ironbraid", note = "salvou sua vida" },
		{ id = "prospector-whelgar", name = "Prospector Whelgar", note = "seu líder" },
	},
})

Translate("ptBR", "ormer-ironbraid", {
	title = "Ormer Ironbraid",
	subtitle = "Defensor da Escavação",
	found = "O penhasco acima do Sítio de Escavação de Whelgar",
	hint = [=[Encontre o anão que protege os sobreviventes da escavação de Whelgar.]=],
	allegiance = "Liga dos Exploradores",
	aliases = { "Ormer" },
	sections = {
		{
			title = "Resumo",
			text = [=[Ormer Ironbraid é o {link:dwarves}anão{/link} que salvou o que podia ser salvo na escavação de {link:prospector-whelgar}Whelgar{/link}. Quando os raptores invadiram o lugar, ele os conteve enquanto {link:merrin-rockweaver}Merrin{/link} e o velho prospector fugiam para o penhasco. Não conseguiu salvar os demais. Não vai deixar os dois que protege, por isso pede a outros que executem a vingança que planejou.]=],
		},
		{
			title = "Feitos",
			text = [=[• Pede que os raptores da escavação sejam repelidos, espécie por espécie.
• Acredita que um grande raptor chamado Sarltooth guiou os outros até o lugar, e o quer morto.]=],
		},
	},
	mentions = {
		{ text = "A Vingança de Ormer" },
		{ text = "A Vingança de Ormer" },
		{ text = "A Vingança de Ormer" },
	},
	bonds = {
		{ id = "merrin-rockweaver", name = "Merrin Rockweaver", note = "ele a salvou" },
		{ id = "prospector-whelgar", name = "Prospector Whelgar", note = "ele o salvou" },
	},
})

Translate("ptBR", "prospector-whelgar", {
	title = "Prospector Whelgar",
	subtitle = "Líder da Escavação do Pantanal",
	found = "O penhasco acima do Sítio de Escavação de Whelgar",
	hint = [=[Procure o velho prospector que lidera a escavação da Liga dos Exploradores no Pantanal.]=],
	allegiance = "Liga dos Exploradores",
	aliases = { "Whelgar" },
	sections = {
		{
			title = "Resumo",
			text = [=[O Prospector Whelgar lidera a escavação da {link:explorers-league}Liga dos Exploradores{/link} que leva seu nome. Ele é velho, velho demais, diz, para descer entre as feras que tomaram seu acampamento. Mas sua mente é afiada. Pouco antes de os raptores chegarem, ele desenterrou uma grande tábua, a {link:goaz-stone}Pedra de Goaz{/link}, gravada na escrita dos titãs e quebrada em quatro pontos. Ele acredita que os pedaços que faltam guardam a chave de um mistério maior que qualquer outro que a Liga já encontrou.]=],
		},
		{
			title = "Importância",
			text = [=[A tábua de Whelgar fala de um plano divino e de uma profecia condenada, e de Deuses Antigos acorrentados sob a terra. Poucos achados da Liga tocaram em coisas mais antigas ou mais sombrias.]=],
		},
		{
			title = "Feitos",
			text = [=[• Guarda o fóssil original que o {link:archaeologist-flagongut}Arqueólogo Flagongut{/link} deseja estudar.
• Sobreviveu ao ataque dos raptores à sua escavação com {link:merrin-rockweaver}Merrin Rockweaver{/link} e {link:ormer-ironbraid}Ormer Ironbraid{/link}.
• Trabalha para traduzir a escrita titânica da {link:goaz-stone}Pedra de Goaz{/link}.]=],
		},
		{
			title = "Sem Registro",
			text = [=[Nenhuma crônica registra a vida de Whelgar antes da escavação, nem há quanto tempo ele serve à Liga.]=],
		},
	},
	chapters = {
		{
			title = "A Pedra de Goaz",
			hint = "Recupere os fragmentos perdidos da tábua do prospector.",
			text = [=[Os fragmentos se chamavam Ados, Modr, Golm e Neru, e estavam espalhados pelas ruínas da escavação, entre relíquias antigas e terra solta. Quando o último foi encaixado, Whelgar se debruçou sobre a pedra e começou a ler. Novas palavras lhe vieram de imediato, e ele as disse em voz alta: Deuses Antigos, acorrentados sob a terra. Não disse o que temia que significassem. Disse apenas que era o começo de algo grandioso.]=],
		},
	},
	mentions = {
		{ text = "Desvendando o Passado" },
		{ text = "O Prospector Distraído" },
		{ text = "Em Busca da Equipe de Escavação" },
	},
	bonds = {
		{ id = "merrin-rockweaver", name = "Merrin Rockweaver", note = "uma escavadora de sua equipe" },
		{ id = "ormer-ironbraid", name = "Ormer Ironbraid", note = "salvou sua vida" },
		{ id = "archaeologist-flagongut", name = "Arqueólogo Flagongut", note = "quer seu fóssil" },
	},
})

Translate("ptBR", "longbraid-the-grim", {
	title = "Longbraid, o Severo",
	subtitle = "Comandante do Regimento de Dun Modr",
	found = "O acampamento diante de Dun Modr",
	hint = [=[Procure o comandante anão que mantém o acampamento diante da caída Dun Modr.]=],
	allegiance = "Reino de Altaforja",
	aliases = { "Longbraid" },
	sections = {
		{
			title = "Resumo",
			text = [=[Longbraid, o Severo, liderava o regimento de {link:ironforge}Altaforja{/link} que guardava {link:dun-modr}Dun Modr{/link} e a {link:thandol-span}Ponte Thandol{/link}. Perdeu as duas. Os {link:dark-iron-dwarves}Ferro Negro{/link} explodiram a ponte oeste numa emboscada, e seu irmão morreu com ela. Antes que o regimento pudesse se recuperar, eles caíram sobre a cidade. Longbraid tocou a trompa de retirada, e agora mantém um pequeno acampamento do lado de fora das muralhas com os poucos que sobreviveram.]=],
		},
		{
			title = "Importância",
			text = [=[Longbraid é a dor e a teimosia de Khaz Modan num único {link:dwarves}anão{/link}. Não tem reserva, nem aliados de sobra, nem cidade, e ainda assim não abandonou a estrada do norte.]=],
		},
		{
			title = "Feitos",
			text = [=[• Tocou a retirada quando {link:dun-modr}Dun Modr{/link} caiu, e salvou o que restava de seu regimento.
• Mandou um cavaleiro para o sul, a Menethil, com o ferido {link:harlo-barnaby}Harlo Barnaby{/link}.
• Caça o bruxo que lidera os {link:dark-iron-dwarves}Ferro Negro{/link} no {link:wetlands}Pantanal{/link}.
• Enviou um batedor, o Velho Rustlocke, à ponte leste, e o batedor nunca voltou.]=],
		},
	},
	chapters = {
		{
			title = "A Queda de Dun Modr",
			hint = "Traga notícias do soldado ferido em Menethil.",
			text = [=[Longbraid soube que o jovem {link:harlo-barnaby}Harlo{/link} sobrevivera, e por um momento a notícia lhe deu esperança. Então contou o resto sem rodeios. {link:dun-modr}Dun Modr{/link} estava perdida. O regimento que a guardava era agora apenas uma sombra de si mesmo.]=],
		},
		{
			title = "Uma Tarefa Sombria",
			hint = "Cace o bruxo que lidera os Ferro Negro.",
			text = [=[Os {link:dark-iron-dwarves}Ferro Negro{/link} do {link:wetlands}Pantanal{/link} eram liderados por {link:balgaras-the-foul}Balgaras, o Imundo{/link}, um bruxo que mandava outros morrerem e se mantinha fora de alcance. Quando sua orelha foi posta diante de Longbraid, o comandante não sentiu alegria. Os mortos não voltariam. Mas os vivos talvez dormissem, e o resto dos Ferro Negro teria de ser expulso antes que viesse um novo senhor.]=],
		},
	},
	mentions = {
		{ text = "A Queda de {link:dun-modr}Dun Modr{/link}" },
		{ text = "Uma Tarefa Sombria" },
		{ text = "A Fúria Vem de Longe, seu irmão vingado" },
		{ text = "Em Busca da Equipe de Escavação" },
	},
	bonds = {
		{ id = "motley-garmason", name = "Motley Garmason", note = "preso pela honra a ficar a seu lado" },
		{ id = "rhag-garmason", name = "Rhag Garmason", note = "seu oficial" },
		{ id = "harlo-barnaby", name = "Harlo Barnaby", note = "um soldado que ele mandou para a segurança" },
		{ id = "balgaras-the-foul", name = "Balgaras, o Imundo", note = "inimigo" },
		{ id = "kam-deepfury", name = "Kam Deepfury", note = "planejou a morte de seu irmão" },
	},
})

Translate("ptBR", "motley-garmason", {
	title = "Motley Garmason",
	subtitle = "Soldado de Dun Modr",
	found = "O acampamento diante de Dun Modr",
	hint = [=[Fale com o anão do acampamento de Longbraid que mais odeia os Ferro Negro.]=],
	allegiance = "Reino de Altaforja",
	aliases = { "Motley" },
	sections = {
		{
			title = "Resumo",
			text = [=[Motley Garmason serve no regimento destroçado de {link:longbraid-the-grim}Longbraid{/link}. Está preso pela honra a ficar ao lado de seu comandante, e isso o irrita. Enquanto os soldados de {link:ironforge}Altaforja{/link} lutam pela {link:alliance}Aliança{/link} em terras distantes, diz ele, os próprios lares dos anões caem diante dos {link:dark-iron-dwarves}Ferro Negro{/link}. Ele quer o acampamento Ferro Negro pressionado com tanta força que a reserva, se um dia vier, possa terminar o trabalho.]=],
		},
		{
			title = "Feitos",
			text = [=[• Pede ataques contra os {link:dark-iron-dwarves}Ferro Negro{/link} do {link:direforge-hill}Monte Umbraforja{/link}.
• Quer a cabeça de {link:kam-deepfury}Kam Deepfury{/link}, preso no {link:the-stockade}Cárcere{/link} de {link:stormwind-city}Ventobravo{/link}, pela morte do irmão de {link:longbraid-the-grim}Longbraid{/link}.]=],
		},
	},
	mentions = {
		{ text = "A Guerra dos {link:dark-iron-dwarves}Ferro Negro{/link}" },
		{ text = "A Fúria Vem de Longe" },
	},
	bonds = {
		{ id = "longbraid-the-grim", name = "Longbraid, o Severo", note = "seu comandante" },
		{ id = "rhag-garmason", name = "Rhag Garmason", note = "tem o mesmo sobrenome" },
		{ id = "kam-deepfury", name = "Kam Deepfury", note = "o conspirador que ele quer morto" },
	},
})

Translate("ptBR", "rhag-garmason", {
	title = "Rhag Garmason",
	subtitle = "Soldado de Dun Modr",
	found = "O acampamento diante de Dun Modr",
	hint = [=[Fale com o anão do acampamento de Longbraid que vigia a Ponte Thandol.]=],
	allegiance = "Reino de Altaforja",
	aliases = { "Rhag" },
	sections = {
		{
			title = "Resumo",
			text = [=[Rhag Garmason ouviu a explosão que despedaçou a {link:thandol-span}Ponte Thandol{/link}. Ele vigia o que resta da ponte a partir do acampamento de {link:longbraid-the-grim}Longbraid{/link}. Quando o batedor Ebenezer Rustlocke não voltou, foi Rhag quem descobriu por quê: o velho {link:dwarves}anão{/link} morrera numa emboscada, com ordens {link:dark-iron-dwarves}Ferro Negro{/link} agarradas a seu lado. Essas ordens falavam de mais explosivos à espera do outro lado do desfiladeiro.]=],
		},
		{
			title = "Feitos",
			text = [=[• Buscou saber o destino do Velho Rustlocke.
• Viu o último trecho da {link:thandol-span}Ponte Thandol{/link} salvo de uma segunda explosão.
• Enviou um pedido de soldados ao Capitão {link:captain-nials}Nials{/link}, na {link:refuge-pointe}Ponta do Refúgio{/link}, no {link:arathi-highlands}Planalto Arathi{/link}. A resposta foi não. {link:stromgarde-keep}Stromgarde{/link} havia caído, e seus próprios soldados tinham uma cidade a reconquistar.]=],
		},
	},
	mentions = {
		{ text = "{link:thandol-span}A Ponte Thandol{/link}" },
		{ text = "{link:thandol-span}A Ponte Thandol{/link}" },
		{ text = "{link:thandol-span}A Ponte Thandol{/link}" },
		{ text = "Apelo à {link:alliance}Aliança{/link}" },
	},
	bonds = {
		{ id = "longbraid-the-grim", name = "Longbraid, o Severo", note = "seu comandante" },
		{ id = "motley-garmason", name = "Motley Garmason", note = "tem o mesmo sobrenome" },
	},
})

Translate("ptBR", "roggo-harlbarrow", {
	title = "Roggo Harlbarrow",
	subtitle = "Batedor de Dun Modr",
	found = "O acampamento diante de Dun Modr",
	hint = [=[Encontre o anão do acampamento de Longbraid que reúne notícias do inimigo.]=],
	allegiance = "Reino de Altaforja",
	aliases = { "Roggo" },
	sections = {
		{
			title = "Resumo",
			text = [=[Roggo Harlbarrow é os olhos e os ouvidos do acampamento de {link:longbraid-the-grim}Longbraid{/link}. Foi ele quem descobriu que um bruxo chamado {link:balgaras-the-foul}Balgaras, o Imundo{/link}, lidera os {link:dark-iron-dwarves}Ferro Negro{/link} no {link:wetlands}Pantanal{/link}, e ele quem provou que {link:kam-deepfury}Kam Deepfury{/link} planejou o ataque à {link:thandol-span}Ponte Thandol{/link}. Também tentou, repetidas vezes, alcançar as forças de reserva de {link:ironforge}Altaforja{/link}. Nenhuma respondeu.]=],
		},
		{
			title = "Feitos",
			text = [=[• Revelou que {link:balgaras-the-foul}Balgaras, o Imundo{/link}, é o líder dos {link:dark-iron-dwarves}Ferro Negro{/link}.
• Reuniu as provas contra {link:kam-deepfury}Kam Deepfury{/link}.
• Contou a {link:rhag-garmason}Rhag{/link} sobre o acampamento da {link:alliance}Aliança{/link} na {link:refuge-pointe}Ponta do Refúgio{/link}.]=],
		},
	},
	bonds = {
		{ id = "longbraid-the-grim", name = "Longbraid, o Severo", note = "seu comandante" },
	},
})

Translate("ptBR", "ashlan-stonesmirk", {
	title = "Ashlan Stonesmirk",
	subtitle = "Especialista em Explosivos de Dun Modr",
	found = "O acampamento diante de Dun Modr",
	hint = [=[Encontre o especialista em explosivos do acampamento de Longbraid.]=],
	allegiance = "Reino de Altaforja",
	aliases = { "Ashlan" },
	sections = {
		{
			title = "Resumo",
			text = [=[Ashlan Stonesmirk foi designado ao regimento de {link:dun-modr}Dun Modr{/link} por seu conhecimento de pólvora explosiva. Quando uma pólvora estranha foi encontrada perto do {link:stonewrought-dam}Dique Lapidado{/link}, em {link:loch-modan}Loch Modan{/link}, ela foi enviada a ele. Ele a reconheceu de imediato por seus cristais prateados e por seu cheiro: seafório. Seca, é inofensiva. Molhada, poderia arrancar a própria {link:ironforge}Altaforja{/link} da montanha. Ele também sabia como torná-la segura.]=],
		},
		{
			title = "Feitos",
			text = [=[• Identificou a pólvora dos {link:dark-iron-dwarves}Ferro Negro{/link} e deu a receita para desarmá-la.]=],
		},
	},
	mentions = {
		{ text = "Uma Ameaça Sombria se Aproxima" },
		{ text = "Uma Ameaça Sombria se Aproxima" },
	},
	bonds = {
		{ id = "chief-engineer-hinderweir-vii", name = "Engenheiro-chefe Hinderweir VII", note = "enviou-lhe a pólvora" },
	},
})

Translate("ptBR", "harlo-barnaby", {
	title = "Harlo Barnaby",
	subtitle = "Soldado Ferido de Dun Modr",
	found = "Porto de Menethil",
	hint = "Fale com o soldado ferido que despertou em Menethil.",
	allegiance = "Reino de Altaforja",
	aliases = { "Harlo" },
	sections = {
		{
			title = "Resumo",
			text = [=[Harlo Barnaby é um jovem soldado do regimento de {link:longbraid-the-grim}Longbraid{/link}. Enquanto os anões fugiam de {link:dun-modr}Dun Modr{/link}, um machado perdido o atingiu nas costas e tudo ficou escuro. Ele acordou no {link:menethil-harbor}Porto de Menethil{/link}, longe dos combates, sem ideia de quem mais havia sobrevivido. Seus ferimentos são graves, mas sua esperança não se foi. Ele acredita que Longbraid ainda vive.]=],
		},
		{
			title = "Feitos",
			text = [=[• Pede notícias de {link:longbraid-the-grim}Longbraid{/link} e de seu regimento.]=],
		},
	},
	mentions = {
		{ text = "A Queda de {link:dun-modr}Dun Modr{/link}" },
	},
	bonds = {
		{ id = "longbraid-the-grim", name = "Longbraid, o Severo", note = "seu comandante, que o mandou para a segurança" },
	},
})

Translate("ptBR", "balgaras-the-foul", {
	title = "Balgaras, o Imundo",
	subtitle = "Bruxo dos Ferro Negro",
	found = "Entre os Ferro Negro de Dun Modr e do Monte Umbraforja",
	hint = [=[Cace o bruxo Ferro Negro que se esconde atrás de seus soldados.]=],
	allegiance = "Anões Ferro Negro",
	aliases = { "Balgaras" },
	sections = {
		{
			title = "Resumo",
			text = [=[Balgaras, o Imundo, comanda os {link:dark-iron-dwarves}Ferro Negro{/link} no {link:wetlands}Pantanal{/link}. É um bruxo e, segundo todos os relatos, um covarde. Manda seus soldados fazerem o trabalho e se mantém longe do perigo, movendo-se entre as ruínas de {link:dun-modr}Dun Modr{/link} e o acampamento no {link:direforge-hill}Monte Umbraforja{/link}. Muitos anões de {link:ironforge}Altaforja{/link} morreram por suas ordens.]=],
		},
		{
			title = "Feitos",
			text = [=[• Lidera os {link:dark-iron-dwarves}Ferro Negro{/link} que tomaram {link:dun-modr}Dun Modr{/link}.
• Há muito escapa dos caçadores de {link:longbraid-the-grim}Longbraid{/link}.]=],
		},
	},
	mentions = {
		{ text = "Uma Tarefa Sombria" },
	},
	bonds = {
		{ id = "longbraid-the-grim", name = "Longbraid, o Severo", note = "quer sua orelha" },
	},
})

Translate("ptBR", "captain-halyndor", {
	title = "Capitão Halyndor",
	subtitle = "Capitão do Intrepid",
	found = "Os destroços do Intrepid, na Frota Perdida",
	hint = "Enfrente o capitão afogado que ainda caminha pelo Intrepid.",
	allegiance = "A Terceira Frota afogada",
	aliases = { "Halyndor" },
	sections = {
		{
			title = "Resumo",
			text = [=[Halyndor era capitão do {i}Intrepid{/i}, um navio da {link:third-fleet}Terceira Frota{/link} de {link:kul-tiras}Kul Tiraz{/link}. Ele guardava a chave de seu cofre, e nesse cofre jazia um Olho de Paleth amaldiçoado. Quando os dragões vermelhos afundaram a frota, Halyndor afundou com seu navio. Nunca o deixou. Seu imediato, o único sobrevivente, o amaldiçoa por ter levado a frota à perdição.]=],
		},
	},
	mentions = {
		{ text = "Quebrando a Maldição" },
	},
	bonds = {
		{ id = "first-mate-fitzsimmons", name = "Imediato Fitzsimmons", note = "culpa-o" },
	},
})

Translate("ptBR", "rethiel-the-greenwarden", {
	title = "Rethiel, o Guarda Verde",
	subtitle = "Espírito do Pântano",
	found = "O pântano a leste da bifurcação para Dun Modr",
	hint = [=[Procure o espírito do pântano entre os crocoliscos a leste da estrada para Dun Modr.]=],
	allegiance = "O Pantanal",
	aliases = { "O Guarda Verde", "Guarda Verde", "Rethiel" },
	sections = {
		{
			title = "Resumo",
			text = [=[O Guarda Verde é um espírito do pântano vivo. Os marinheiros de Menethil falam dele como de uma fera que parte homens ao meio. A verdade é mais estranha. Ele tem muitos nomes e responde a poucos, mas aqueles em quem confia podem chamá-lo de Rethiel. Sente o {link:wetlands}Pantanal{/link} como seu próprio corpo. Diz que a terra chora por feridas que supuram, e que os povos do mundo já puseram sua fé à prova antes.]=],
		},
		{
			title = "Feitos",
			text = [=[• Pede que os gnolls Pelemusgo sejam reduzidos, pois cresceram além do que a terra suporta.
• Despedaça as pederneiras dos gnolls e as lança ao mar.
• Busca devolver ao pântano os rastejantes do charco febris.]=],
		},
	},
	mentions = {
		{ text = "O Guarda Verde" },
		{ text = "Patas que Pisoteiam" },
		{ text = "Tabu do Fogo" },
		{ text = "Bolhas na Terra" },
	},
	bonds = {
		{ id = "first-mate-fitzsimmons", name = "Imediato Fitzsimmons", note = "afasta os buscadores dele" },
	},
})

Translate("ptBR", "howin-kindfeather", {
	title = "Howin Kindfeather",
	subtitle = "Cavaleiro de Grifo do Pantanal",
	found = [=[Um acampamento à beira da estrada, a leste do Sítio de Escavação de Whelgar]=],
	hint = [=[Encontre o anão e seu grifo acampados à beira da estrada, a leste da escavação de Whelgar.]=],
	allegiance = "Clã Martelo Feroz",
	aliases = { "Howin" },
	sections = {
		{
			title = "Resumo",
			text = [=[Howin Kindfeather acampa à beira da estrada do {link:wetlands}Pantanal{/link} com seu grifo, Bassbeak. Certa vez mandou a ave a Menethil com uma carta para encomendar escamas de dragonete, algo que o curtidor do porto ainda admira. Ele cospe quando fala dos {link:dark-iron-dwarves}Ferro Negro{/link}, dos {link:dragonmaw-clan}Presa do Dragão{/link} e dos dracos que eles montavam, e não consegue decidir qual odeia mais. Pretende acertar as coisas. Seu plano precisa de um manto contra o fogo de dragão, dentes para costurá-lo e um grifo de barriga cheia.]=],
		},
		{
			title = "Feitos",
			text = [=[• Compra as escamas dos dragonetes carmesins, que protegem contra o fogo de dragão.
• Reúne dentes e ovos de navalhadente para seu plano.]=],
		},
	},
	mentions = {
		{ text = "Entrega de Caixote Carmesim" },
		{ text = "Agulhas de Navalhadente" },
		{ text = "Tempos Difíceis" },
	},
	bonds = {
		{ id = "james-halloran", name = "James Halloran", note = "vendeu-lhe as escamas" },
	},
})

Translate("ptBR", "hervdana-saegrund", {
	title = "Hervdana Saegrund",
	subtitle = "Xamã das Cachoeiras do Sul",
	found = "Uma caverna sob as cachoeiras do sul",
	hint = [=[Procure a xamã cuja família vive numa caverna sob as cachoeiras do sul.]=],
	allegiance = "Xamãs",
	aliases = { "Hervdana" },
	sections = {
		{
			title = "Resumo",
			text = [=[Hervdana Saegrund é uma xamã cuja família vive numa caverna sob as cachoeiras do sul do {link:wetlands}Pantanal{/link}, com Frothrik Saegrund entre eles. {link:norric-lochthane}Norric Lochthane{/link} lhe envia seus alunos. Ela ensina que a água deve ser compreendida em todas as suas formas: doce onde encontra a salobra, conspurcada onde algo sombrio se infiltrou, e pura onde repousou intocada por eras. Seus alunos coletam água em {link:redridge-mountains}Cristarrubra{/link} e em {link:ashenvale}Vale Gris{/link} antes de voltar a Norric.]=],
		},
	},
	mentions = {
		{ text = "Chamado da Água" },
		{ text = "Chamado da Água, ao pé das cachoeiras" },
		{
			text = [=[Chamado da Água, da {link:stonewatch-falls}Cachoeira do Mirante de Pedra{/link}]=],
		},
		{ text = "Chamado da Água, de {link:astranaar}Astranaar{/link}" },
		{
			text = [=[Chamado da Água, de volta a {link:norric-lochthane}Norric{/link}]=],
		},
	},
	bonds = {
		{ id = "norric-lochthane", name = "Norric Lochthane", note = "envia-lhe seus alunos" },
	},
})

Translate("ptBR", "chieftain-nek-rosh", {
	title = "Chefe Nek'rosh",
	subtitle = "Chefe dos Presa do Dragão",
	found = "Acampamento Presirada",
	hint = [=[Enfrente o chefe que lidera os Presa do Dragão de seu acampamento nas colinas do leste.]=],
	allegiance = "Clã Presa do Dragão",
	aliases = { "Nek'rosh" },
	sections = {
		{
			title = "Resumo",
			text = [=[Nek'rosh é o chefe do {link:dragonmaw-clan}clã Presa do Dragão{/link} no {link:wetlands}Pantanal{/link}. É filho de Nekros, que liderou o clã nos anos em que ele mantinha os dragões vermelhos cativos. Nekros dobrou os dragões à sua vontade com uma magia poderosa. Quando a magia falhou, os dragões se voltaram contra seus senhores, e Nekros foi morto. Seu filho jurou vingança contra os dragões que o mataram.]=],
		},
		{
			title = "Importância",
			text = [=[Sob Nek'rosh, um clã destroçado voltou a ser um exército. Os {link:dragonmaw-clan}Presa do Dragão{/link} avançaram sobre {link:dun-algaz}Dun Algaz{/link}, construíram máquinas de cerco e voltaram os olhos para o {link:menethil-harbor}Porto de Menethil{/link}.]=],
		},
		{
			title = "Feitos",
			text = [=[• Reuniu os {link:dragonmaw-clan}Presa do Dragão{/link} dispersos no {link:angerfang-encampment}Acampamento Presirada{/link}.
• Lançou seus guerreiros sobre {link:dun-algaz}Dun Algaz{/link}, cortando a estrada entre Menethil e {link:loch-modan}Loch Modan{/link}.
• Construiu catapultas para sitiar o {link:menethil-harbor}Porto de Menethil{/link}.]=],
		},
		{
			title = "Sem Registro",
			text = [=[As crônicas da {link:second-war}Segunda Guerra{/link} falam dos {link:dragonmaw-clan}Presa do Dragão{/link} que mantiveram a Rainha {link:the-drag}Drag{/link}ão em {link:grim-batol}Grim Batol{/link}. Que papel o próprio Nek'rosh teve naqueles anos, elas não dizem.]=],
		},
	},
	chapters = {
		{
			title = "O Filho de Nekros",
			hint = [=[Leve os estandartes de guerra dos Presa do Dragão ao capitão na Bastilha Menethil.]=],
			text = [=[Quando os estandartes foram postos diante dele, o {link:captain-stoutfist}Capitão Stoutfist{/link} contou o que os anões sabiam de seu inimigo. Os {link:dragonmaw-clan}Presa do Dragão{/link} já não eram o que tinham sido quando montavam dragões. Seu chefe era filho do {link:orcs}orc{/link} que outrora escravizara a revoada vermelha, e não havia esquecido como seu pai morreu.]=],
		},
		{
			title = "Derrote Nek'rosh",
			hint = "Queime as catapultas e abata o chefe.",
			text = [=[As catapultas queimaram primeiro, e Menethil ficou a salvo delas. Então Nek'rosh caiu em seu próprio acampamento. {link:captain-stoutfist}Stoutfist{/link} julgou o golpe decisivo, um golpe do qual o clã talvez nunca se recuperasse.]=],
		},
	},
	mentions = {
		{ text = "Estandartes de Guerra" },
		{ text = "A Cartada de Nek'rosh" },
		{ text = "Derrote Nek'rosh" },
	},
	bonds = {
		{ id = "captain-stoutfist", name = "Capitão Stoutfist", note = "inimigo" },
		{ id = "ma-ruk-wyrmscale", name = "Ma'ruk Wyrmscale", note = "seu senhor da guerra em Dun Algaz" },
		{ id = "alexstrasza", name = "Alexstrasza", note = "rainha dos dragões que seu pai escravizou" },
	},
})

Translate("ptBR", "ma-ruk-wyrmscale", {
	title = "Ma'ruk Wyrmscale",
	subtitle = "Senhor da Guerra Presa do Dragão",
	found = "Dun Algaz",
	hint = [=[Enfrente o senhor da guerra Presa do Dragão que domina o desfiladeiro de Dun Algaz.]=],
	allegiance = "Clã Presa do Dragão",
	aliases = { "Ma'ruk" },
	sections = {
		{
			title = "Resumo",
			text = [=[Ma'ruk Wyrmscale é um senhor da guerra do {link:dragonmaw-clan}clã Presa do Dragão{/link}. Lidera os orcs que desceram ao desfiladeiro de {link:dun-algaz}Dun Algaz{/link}, onde emboscam todo viajante entre {link:loch-modan}Loch Modan{/link} e o {link:wetlands}Pantanal{/link}. Enquanto ele dominar o desfiladeiro, nenhum reforço chega ao {link:menethil-harbor}Porto de Menethil{/link} por terra.]=],
		},
		{
			title = "Importância",
			text = [=[Ma'ruk é o fio da lâmina de {link:chieftain-nek-rosh}Nek'rosh{/link}. O cerco do chefe a Menethil depende de seu domínio sobre o desfiladeiro.]=],
		},
	},
	bonds = {
		{ id = "chieftain-nek-rosh", name = "Chefe Nek'rosh", note = "seu chefe" },
	},
})

Translate("ptBR", "dragonmaw-clan", {
	title = "Clã Presa do Dragão",
	aliases = { "clã Presa do Dragão", "orcs Presa do Dragão", "Presa do Dragão" },
	sections = {
		{
			title = "Resumo",
			text = [=[Os Presa do Dragão são um clã de {link:orcs}orcs{/link} da antiga {link:horde}Horda{/link}. Na {link:second-war}Segunda Guerra{/link}, fizeram o que nenhum outro clã conseguiu: tornaram os dragões vermelhos seus servos. De sua fortaleza em {link:grim-batol}Grim Batol{/link}, mantiveram {link:alexstrasza}Alexstrasza{/link}, a Rainha {link:the-drag}Drag{/link}ão, cativa pelo poder de um artefato forjado por {link:deathwing}Asa da Morte{/link}, e criaram seus filhotes como montarias de guerra. Dragões vermelhos montados por orcs Presa do Dragão queimaram os navios da {link:alliance}Aliança{/link} no mar.]=],
		},
		{
			title = "A Queda",
			text = [=[A magia que prendia os dragões falhou. A revoada vermelha se voltou contra o clã e o caçou sem piedade. Nekros, que liderava os Presa do Dragão, foi morto, e o clã foi quase destruído. Os poucos que sobreviveram fugiram de {link:grim-batol}Grim Batol{/link} e se esconderam nas montanhas a leste da estrada do {link:wetlands}Pantanal{/link}.]=],
		},
		{
			title = "Nestes Dias",
			text = [=[Os Presa do Dragão voltaram a ficar fortes sob o {link:chieftain-nek-rosh}Chefe Nek'rosh{/link}, filho de Nekros. Do {link:angerfang-encampment}Acampamento Presirada{/link} e do escondido {link:dragonmaw-retreat}Dragonmaw Retreat{/link}, eles atacam para o oeste, e tomaram o desfiladeiro de {link:dun-algaz}Dun Algaz{/link}. Constroem catapultas, juntam armas e, dizem os sussurros, ainda sonham com dragões. Os anões de Menethil os chamam de ferozes, mas sabem que o clã sem seus dragões é uma ameaça menor que o clã que outrora escureceu o céu.]=],
		},
	},
})

Translate("ptBR", "third-fleet", {
	title = "Terceira Frota",
	aliases = { "A Terceira Frota", "a Frota Condenada", "Frota Condenada" },
	sections = {
		{
			title = "Resumo",
			text = [=[A Terceira Frota de {link:kul-tiras}Kul Tiraz{/link} navegou na {link:second-war}Segunda Guerra{/link}, a última grande guerra contra a {link:horde}Horda{/link}. Seus navios vieram das costas de {link:lordaeron}Lordaeron{/link}, e pelo menos uma embarcação que não era sua juntou-se a ela em busca de proteção: o {i}Flying Osprey{/i}, que levava uma carga de ferro forjado pela Luz. Diante da costa do {link:wetlands}Pantanal{/link}, orcs montados em dragões vermelhos caíram sobre a frota. Os navios queimaram e afundaram, e os destroços ainda jazem ao longo da costa noroeste, no lugar chamado {link:the-lost-fleet}Frota Perdida{/link}.]=],
		},
		{
			title = "A Maldição",
			text = [=[Algo foi escondido a bordo do {i}Intrepid{/i}: um Olho de Paleth amaldiçoado, trancado no cofre do capitão. Os Olhos foram feitos por sacerdotes humanos para brilhar com luz sagrada, mas este havia testemunhado tristeza demais. Seu poder prende as tripulações afogadas em seus cascos apodrecidos. Só um homem da frota ainda vive, o imediato {link:first-mate-fitzsimmons}Fitzsimmons{/link}, e ele bebe em Menethil para não sonhar com eles.]=],
		},
		{
			title = "A Carga",
			text = [=[Os murlocs da costa saquearam o {i}Flying Osprey{/i}. Seus lingotes forjados pela Luz são prezados por aqueles que combatem os mortos-vivos. Uma elfa noturna de {link:teldrassil}Teldrassil{/link}, {link:sylessa-duskwhisper}Sylessa Duskwhisper{/link}, diz que o navio também levava Nord'el, uma flor do {link:mount-hyjal}Monte Hyjal{/link}.]=],
		},
	},
})

Translate("ptBR", "goaz-stone", {
	title = "Pedra de Goaz",
	aliases = { "A Pedra de Goaz" },
	sections = {
		{
			title = "Resumo",
			text = [=[A Pedra de Goaz é uma grande tábua desenterrada pelo {link:prospector-whelgar}Prospector Whelgar{/link} em sua escavação no {link:wetlands}Pantanal{/link}, pouco antes de os raptores a invadirem. Ela é gravada na escrita dos titãs. Quando foi encontrada, estava quebrada em quatro pontos, e os pedaços perdidos traziam os nomes Ados, Modr, Golm e Neru. Mesmo em parte, a tábua falava de um plano divino e de uma profecia condenada.]=],
		},
		{
			title = "A Leitura",
			text = [=[Quando os quatro fragmentos foram restaurados, {link:prospector-whelgar}Whelgar{/link} começou o lento trabalho da tradução. As primeiras palavras novas que leu falavam de Deuses Antigos, acorrentados sob a terra. A {link:explorers-league}Liga dos Exploradores{/link} já encontrou entalhes titânicos antes, mas raramente algum que falasse tão claramente do que jaz lá embaixo.]=],
		},
		{
			title = "Os Dias Atuais",
			text = [=[{link:prospector-whelgar}Whelgar{/link} não terminou sua leitura. Acima de sua escavação, nas colinas, uma névoa começou a descer das montanhas e construtos dos titãs voltaram a caminhar. Se a pedra e o despertar das terras altas estão ligados, a Liga ainda não sabe.]=],
		},
	},
})
