-- Generated by tools/build_content.py from content/frFR/kalimdor/felwood.md. Do not edit.
local _, ns = ...
local Translate = ns.Lore.Translate

Translate("frFR", "felwood", {
	title = "Gangrebois",
	sections = {
		{
			title = "Résumé",
			text = [=[Gangrebois est une forêt mourante du nord de {link:kalimdor}Kalimdor{/link}, entre {link:ashenvale}Orneval{/link} au sud et les neiges de {link:winterspring}Berceau-de-l'Hiver{/link} au nord-est. Ses arbres sont noirs et tordus, ses ruisseaux coulent verts et fétides, et son air sent la pourriture et la fumée. Elle fut jadis la marche septentrionale de la grande forêt des elfes de la nuit. C'est aujourd'hui la blessure que la {link:burning-legion}Légion ardente{/link} laissa derrière elle quand elle fut chassée du monde. Les bêtes de Gangrebois sont folles, ses furbolgs sont sauvages, et des démons errent encore dans ses creux. Pourtant, quelques druides demeurent dans ses clairières du sud, et ils n'ont pas renoncé à elle.]=],
		},
		{
			title = "Origines",
			text = [=[La forêt fut un foyer des {link:night-elves}elfes de la nuit{/link} pendant des âges innombrables. Leurs puits de lune et leurs refuges des saisons sont épars dans ses bois, et les pierres blanches des {link:ruins-of-constellas}Ruines de Constellas{/link} se dressent encore dans ses clairières de l'ouest. Les anciens tréants qui gardaient les kaldorei vivaient parmi ses arbres. Pendant la {link:third-war}Troisième Guerre{/link}, la Légion vint en {link:kalimdor}Kalimdor{/link}. Le seigneur de l'effroi {link:tichondrius}Tichondrius{/link} porta dans la forêt le Crâne de {link:gul-dan}Gul'dan{/link}, une relique gorgée de puissance démoniaque, et par elle il déversa la corruption dans la terre. Des infernaux tombèrent du ciel en flammes et laissèrent des cratères qui suppurent encore. Quand {link:illidan-stormrage}Illidan Stormrage{/link} prit pour lui la puissance du crâne et tua le seigneur de l'effroi, le mal était déjà fait. La forêt qui survécut était une forêt gangrenée, et l'on se mit à l'appeler Gangrebois.]=],
		},
		{
			title = "Le temps présent",
			text = [=[Gangrebois n'appartient à personne, et bien des puissances se la disputent. Au sud, les druides du {link:emerald-circle}Cercle d'émeraude{/link} tiennent un petit camp appelé le {link:emerald-sanctuary}Sanctuaire d'émeraude{/link}, où ils étudient le mal et cherchent son remède. La {link:horde}Horde{/link} tient le {link:bloodvenom-post}Poste de la Vénéneuse{/link} à l'ouest, et l'{link:alliance}Alliance{/link} entretient un perchoir d'hippogriffes à la {link:talonbranch-glade}Clairière de Griffebranche{/link}, au nord-est. Entre eux se trouve l'ennemi. Les démonistes du {link:shadow-council}Conseil des ombres{/link} ont fait de {link:jaedenar}Jaedenar{/link} le siège de leur ordre, et ils y marchandent avec les démons. Les {link:satyrs}satyres{/link} Jadefeu souillent les anciens puits de lune. Les {link:furbolgs}furbolgs{/link} {link:deadwood-furbolgs}Mort-bois{/link} sont devenus fous. À l'extrême nord, les furbolgs {link:timbermaw-furbolgs}Grumegueules{/link} tiennent le passage vers {link:winterspring}Berceau-de-l'Hiver{/link} et ne font confiance à presque personne. La souillure ne reste pas à Gangrebois : les druides de {link:darkshore}Sombrivage{/link} craignent qu'elle ne s'infiltre vers l'ouest, dans leurs propres forêts.]=],
		},
		{
			title = "Habitants",
			text = [=[• {b}Le {link:emerald-circle}Cercle d'émeraude{/link}.{/b} Des druides du {link:cenarion-circle}Cercle cénarien{/link}, de l'{link:alliance}Alliance{/link} comme de la {link:horde}Horde{/link}, qui ont juré de guérir la forêt.
• {b}Le {link:shadow-council}Conseil des ombres{/link}.{/b} Des démonistes et des cultistes qui tiennent {link:jaedenar}Jaedenar{/link} avec des démons de la Légion à leurs côtés.
• {b}Les satyres Jadefeu.{/b} Ils hantent les {link:ruins-of-constellas}Ruines de Constellas{/link}, le {link:jadefire-glen}Vallon des Jadefeu{/link} et le {link:jadefire-run}Défilé des Jadefeu{/link}, et répandent la corruption partout où ils vont.
• {b}Les furbolgs {link:deadwood-furbolgs}Mort-bois{/link}.{/b} Une tribu rendue folle par la gangrène, avec des villages à l'extrême sud et à l'extrême nord de la forêt.
• {b}Les furbolgs {link:timbermaw-furbolgs}Grumegueules{/link}.{/b} La seule tribu qui a gardé sa raison, et qui garde les tunnels des Grumegueules.
• {b}La nature corrompue.{/b} Des élémentaires Warpwood, des tréants flétris, des limons, des ours, des loups et des chouettards rendus fous, et des infernaux qui arpentent encore le {link:shatter-scar-vale}Val Grêlé{/link}.]=],
		},
		{
			title = "Histoire",
			text = [=[• {b}La forêt {link:night-elves}kaldorei{/link}.{/b} Pendant des millénaires, les bois du nord furent une terre paisible de puits de lune, de refuges et d'anciens.
• {b}La {link:third-war}Troisième Guerre{/link}.{/b} L'armée de la Légion marcha sur le mont Hyjal. {link:tichondrius}Tichondrius{/link} corrompit la forêt avec le {link:skull-of-gul-dan}Crâne de Gul'dan{/link}, et des infernaux furent appelés sur elle.
• {b}Le choix d'{link:illidan-stormrage}Illidan{/link}.{/b} Illidan Stormrage consuma le crâne, prit la forme d'un démon et tua Tichondrius dans ces bois. Son frère le bannit pour cela.
• {b}Le temps présent.{/b} L'armée de la Légion fut brisée à la {link:battle-of-mount-hyjal}bataille du mont Hyjal{/link}, mais Gangrebois ne guérit pas. Démons, satyres et démonistes demeurent, et seule une poignée de druides leur tient tête.]=],
		},
		{
			title = "Légendes de la forêt",
			text = [=[• Les druides du {link:emerald-circle}Cercle d'émeraude{/link} ont appris à faire un baume qui rend la santé à une plante corrompue. Des fleurs-chantantes, des fleurs-du-vent, des racines-fouets et des fleurs de dragon de nuit que l'on croyait perdues ont refleuri sous leurs soins.
• Une flûte taillée dans le bois d'un ancien tombé fut trouvée entre les mains d'un {link:satyrs}satyre{/link}. L'esprit de l'ancien y était lié et ne put trouver le repos que lorsque les eaux du {link:temple-of-the-moon}temple de la Lune{/link} le libérèrent.
• Le {link:shadow-council}Conseil des ombres{/link} garde sa forteresse avec quatre braseros qui ont pour noms Douleur, Malveillance, Souffrance et Haine.
• Les esprits de trois anciens, {link:vartrus-the-ancient}Vartrus{/link}, Stoma et Hastat, répondent encore à ceux qui viennent à un certain rocher du {link:irontree-woods}Bois d'Arbrefer{/link}.]=],
		},
	},
})

Translate("frFR", "emerald-sanctuary", {
	title = "Sanctuaire d'émeraude",
	sections = {
		{
			title = "Résumé",
			text = [=[Le Sanctuaire d'émeraude est un petit camp de druides au sud de {link:felwood}Gangrebois{/link}, près de la frontière d'{link:ashenvale}Orneval{/link}. C'est le foyer du {link:emerald-circle}Cercle d'émeraude{/link}. Ici, des druides elfes de la nuit et taurens travaillent côte à côte, quelles que soient ailleurs les querelles de leurs peuples. Ils recueillent des échantillons de chaque chose souillée que donne la forêt et cherchent le moyen de la purifier. Les amis de l'un ou l'autre camp y sont les bienvenus. Tout autour, la forêt est sombre et hostile, et des satyres Jadefeu rôdent dans le vallon voisin.]=],
		},
	},
})

Translate("frFR", "bloodvenom-post", {
	title = "Poste de la Vénéneuse",
	sections = {
		{
			title = "Résumé",
			text = [=[Le Poste de la Vénéneuse est la tête de pont de la {link:horde}Horde{/link} dans l'ouest de {link:felwood}Gangrebois{/link}, un camp de tentes et de palissades à la lisière des bois corrompus. Des orcs d'{link:orgrimmar}Orgrimmar{/link} et des {link:forsaken}Réprouvés{/link} d'{link:undercity}Undercity{/link} partagent ses feux. C'est un poste difficile en terre hostile. Ses guerriers ont combattu {link:shadow-council}le Conseil{/link} des ombres et les furbolgs fous de la forêt, et certains ne sont pas revenus. Ses agents regardent plus loin : l'un étudie les puits de lune corrompus des satyres, un autre les sélénides de {link:winterspring}Berceau-de-l'Hiver{/link}. Un maître des coursiers du vent maintient le lien entre le poste et le reste de la Horde.]=],
		},
	},
})

Translate("frFR", "talonbranch-glade", {
	title = "Clairière de Griffebranche",
	sections = {
		{
			title = "Résumé",
			text = [=[La Clairière de Griffebranche est un petit camp {link:night-elves}elfe de la nuit{/link} dans le nord-est de {link:felwood}Gangrebois{/link}. Des hippogriffes nichent dans ses arbres et portent messages et voyageurs vers le reste de l'{link:alliance}Alliance{/link}. Quelques kaldorei la tiennent : un marchand, un forgeron d'armes, et les maîtres qui forment les druides et les chasseurs à la longue guerre contre la corruption. C'est un lieu de repos avant la route du nord, et l'un des derniers avant-postes des elfes de la nuit dans la forêt qui fut jadis tout entière à eux.]=],
		},
	},
})

Translate("frFR", "jaedenar", {
	title = "Jaedenar",
	aliases = { "Fort des ombres" },
	sections = {
		{
			title = "Résumé",
			text = [=[Jaedenar se trouve dans l'ouest de {link:felwood}Gangrebois{/link}, au bout d'un sentier qui quitte la route principale. Ce fut jadis un lieu des elfes de la nuit, avec un puits de lune en son cœur et des refuges sous terre. C'est aujourd'hui le siège du {link:shadow-council}Conseil des ombres{/link}. Cultistes, démonistes et leurs molosses tiennent la surface, et le puits de lune s'est corrompu. En dessous se trouve le Fort des ombres, la forteresse du Conseil, où des démons de la Légion marchent ouvertement. Ses salles sont gardées par quatre braseros de protection. Tout au fond, un seigneur de l'effroi tient sa cour, et les démonistes qui le servent concluent leurs pactes dans l'ombre.]=],
		},
	},
})

Translate("frFR", "irontree-woods", {
	title = "Bois d'Arbrefer",
	aliases = { "Caverne d'Arbrefer" },
	sections = {
		{
			title = "Résumé",
			text = [=[Le Bois d'Arbrefer est le cœur septentrional de {link:felwood}Gangrebois{/link}, une étendue d'arbres flétris et de ruines. Des tréants y marchaient jadis en gardiens de la forêt. La corruption les a tordus, et ceux qui restent errent et piétinent parmi les arbres morts. Dans la Caverne d'Arbrefer, les élémentaires Warpwood sont tombés si bas que les druides n'espèrent plus les purifier. Pourtant, les bois ne sont pas tout à fait perdus. Dans les ruines de leur partie sud s'attarde l'esprit d'une ancienne nommée {link:arei}Arei{/link}, et les esprits de trois autres anciens répondent encore à une pierre parmi les arbres.]=],
		},
	},
})

Translate("frFR", "shatter-scar-vale", {
	title = "Val Grêlé",
	sections = {
		{
			title = "Résumé",
			text = [=[Le Val Grêlé s'étend à l'est de la route, au centre de {link:felwood}Gangrebois{/link}. Pendant la {link:third-war}Troisième Guerre{/link}, la Légion fit tomber ses infernaux sur cette vallée, et les cratères qu'ils creusèrent balafrent encore le sol. Une eau verte et fétide s'est amassée dans les fosses et ne s'est jamais éclaircie. Des infernaux marchent encore parmi elles, stupides et destructeurs, avec à leurs côtés des élémentaires d'entropie pure. Les druides avaient espéré trouver une source pure à Gangrebois. Ils ne la trouvèrent pas ici. Quelque part dans le val gisent les restes calcinés de l'infernal {link:kroshius}Kroshius{/link}.]=],
		},
	},
})

Translate("frFR", "ruins-of-constellas", {
	title = "Ruines de Constellas",
	aliases = { "Constellas" },
	sections = {
		{
			title = "Résumé",
			text = [=[Les Ruines de Constellas se trouvent dans le sud-ouest de {link:felwood}Gangrebois{/link}. Ce fut une ville des elfes de la nuit, et en son cœur se dresse un puits de lune qui fut jadis un symbole de renouveau. Les satyres Jadefeu ont fait des ruines leur demeure, et le puits de lune déborde désormais de corruption. Ses eaux servent à faire naître d'autres satyres, et une bête qui en boit devient plus grande, plus forte et tout à fait immonde. Le {link:satyrs}satyre{/link} {link:xavathras}Xavathras{/link} régnait ici, et son œuvre nourrissait les desseins d'un autre satyre au nord.]=],
		},
	},
})

Translate("frFR", "jadefire-glen", {
	title = "Vallon des Jadefeu",
	sections = {
		{
			title = "Résumé",
			text = [=[Le Vallon des Jadefeu est un creux sombre du sud de {link:felwood}Gangrebois{/link}, tout près du {link:emerald-sanctuary}Sanctuaire d'émeraude{/link}. Il tire son nom des {link:satyrs}satyres{/link} Jadefeu qui le tiennent. Leurs gangreliges et leurs voleurs s'y rassemblent pour répandre la corruption parmi les bêtes de la forêt du sud. Les druides du sanctuaire vivent avec les satyres presque à leur porte, et ils comptent le vallon parmi les premiers lieux à purifier si la forêt doit un jour guérir.]=],
		},
	},
})

Translate("frFR", "jadefire-run", {
	title = "Défilé des Jadefeu",
	sections = {
		{
			title = "Résumé",
			text = [=[Le Défilé des Jadefeu se trouve au nord-ouest de {link:felwood}Gangrebois{/link}. C'est le second camp des satyres Jadefeu, et le plus dangereux. Des invocateurs infernaux, des traîtres et des filous s'y rassemblent sous le {link:satyrs}satyre{/link} {link:xavaric}Xavaric{/link}, qui recevait les fruits du puits de lune corrompu de {link:ruins-of-constellas}Constellas{/link}. Les satyres du Défilé se nourrissent de la corruption des créatures de la forêt. Parmi eux, on trouva une flûte de bois taillée dans un ancien tombé, et elle apprit aux druides que la cruauté des satyres atteignait jusqu'aux protecteurs de la forêt.]=],
		},
	},
})

Translate("frFR", "deadwood-village", {
	title = "Village des Mort-bois",
	sections = {
		{
			title = "Résumé",
			text = [=[Le Village des Mort-bois est un village {link:furbolgs}furbolg{/link} à l'extrême sud de {link:felwood}Gangrebois{/link}, près de la frontière d'{link:ashenvale}Orneval{/link}. Il appartient à la {link:deadwood-furbolgs}tribu Mort-bois{/link}, que la gangrène a rendue folle. Guerriers, éclaireurs et jardiniers gardent ses huttes, et leur suzerain, {link:overlord-ror}Ror{/link}, est un grand furbolg souillé d'une force terrible. Le furbolg {link:timbermaw-furbolgs}Grumegueules{/link} {link:grazle}Grazle{/link} surveille le village depuis les environs et demande à ceux qui voudraient être les amis de sa tribu d'en réduire le nombre.]=],
		},
	},
})

Translate("frFR", "felpaw-village", {
	title = "Village de Gangrepatte",
	sections = {
		{
			title = "Résumé",
			text = [=[Le Village de Gangrepatte est le camp septentrional des furbolgs {link:deadwood-furbolgs}Mort-bois{/link}, dans les collines au pied de l'entrée des {link:timbermaw-furbolgs}Grumegueules{/link}. Guetteurs de la tanière, vengeurs et chamans y vivent sous le chef Bloodmaw. {link:timbermaw-hold}Les Grumegueules{/link} qui gardent leur repaire le regardent d'en haut avec tristesse, car ses habitants sont leurs propres frères. Dans son camp se dresse un chaudron de breuvage vert et puant. Des furbolgs {link:winterfall-furbolgs}Tombe-hiver{/link} venus des neiges au-delà ont été vus traversant le repaire, et certains soupçonnent que le breuvage leur est porté au nord.]=],
		},
	},
})

Translate("frFR", "timbermaw-hold", {
	title = "Les Grumegueules",
	sections = {
		{
			title = "Résumé",
			text = [=[Les Grumegueules sont le foyer des furbolgs {link:timbermaw-furbolgs}Grumegueules{/link}, un réseau de tunnels dans les montagnes à la lisière nord de {link:felwood}Gangrebois{/link}. Ses passages traversent la roche jusqu'à {link:winterspring}Berceau-de-l'Hiver{/link} et forment la seule route vers le nord. Les furbolgs les gardent farouchement. Les étrangers qui n'ont pas gagné leur confiance sont accueillis à coups de lance, et tuer un Grumegueules, même pour se défendre, c'est devenir leur ennemi. À l'intérieur, leurs anciens, leurs mystiques et leurs marchands font vivre la tribu, et ils étudient la corruption qui a pris leurs frères.]=],
		},
	},
})

Translate("frFR", "eridan-bluewind", {
	title = "Eridan Bluewind",
	subtitle = "Druidesse du Cercle d'émeraude",
	found = "Le Sanctuaire d'émeraude, au sud de Gangrebois",
	hint = [=[Cherchez la druidesse du Cercle d'émeraude qui sent la souffrance des anciens.]=],
	allegiance = "Cercle d'émeraude · Cercle cénarien",
	aliases = { "Eridan" },
	sections = {
		{
			title = "Résumé",
			text = [=[Eridan Bluewind est une druidesse du {link:emerald-circle}Cercle d'émeraude{/link} qui vit au {link:emerald-sanctuary}Sanctuaire d'émeraude{/link}. Elle s'est vouée à la guérison de {link:felwood}Gangrebois{/link}, et elle porte sa douleur en elle. Une grande part de son œuvre est la guerre. Elle envoie des alliés contre les satyres Jadefeu qui répandent la corruption, et elle use ses propres forces à tenter de défaire ce qu'ils ont fait.]=],
		},
		{
			title = "Importance",
			text = [=[Eridan fut la première du {link:emerald-circle}Cercle d'émeraude{/link} à voir que les satyres de {link:felwood}Gangrebois{/link} n'étaient pas seulement cruels, mais organisés. Le camp de {link:xavathras}Xavathras{/link} au sud, apprit-elle, entretenait un puits de lune corrompu au profit de {link:xavaric}Xavaric{/link} au nord. Elle soupçonne que quelque chose de plus grand encore se tient derrière eux. Son savoir s'étend aussi bien au-delà de Gangrebois : des voyageurs viennent la chercher pour des secrets des éléments que peu d'autres connaissent.]=],
		},
		{
			title = "Hauts faits",
			text = [=[• Elle envoya des combattants contre {link:xavathras}Xavathras{/link} aux {link:ruins-of-constellas}Ruines de Constellas{/link} et contre {link:xavaric}Xavaric{/link} au {link:jadefire-run}Défilé des Jadefeu{/link}.
• Elle libéra l'esprit d'un ancien que les satyres avaient lié dans une flûte.
• Elle enseigna la fabrication d'un totem capable de briser l'aura de l'élémentaire de feu {link:blazerunner}Blazerunner{/link} dans le {link:un-goro-crater}Cratère d'Un'Goro{/link}.]=],
		},
	},
	chapters = {
		{
			title = "Les Jadefeu",
			hint = "Abattez les seigneurs satyres des Jadefeu.",
			text = [=[Quand {link:xavathras}Xavathras{/link} tomba, Eridan ne se réjouit pas. Elle avait senti que le {link:satyrs}satyre{/link} n'était qu'une partie d'un plan plus vaste. La vérité vint lentement : Xavathras avait entretenu un puits de lune corrompu et en faisait passer le butin au nord, à {link:xavaric}Xavaric{/link}. Les deux tués, elle pria pour qu'Elune garde ceux qui avaient accompli cette tâche. La guérison, elle le savait, prendrait bien plus longtemps que la mise à mort.]=],
		},
		{
			title = "L'ancien lié",
			hint = [=[Apportez à la druidesse la flûte trouvée sur un satyre, et l'eau bénie du temple de la Lune.]=],
			text = [=[La flûte de {link:xavaric}Xavaric{/link} avait été taillée dans l'un des anciens tréants qui gardaient les elfes de la nuit. Par la magie gangrenée, l'esprit de l'ancien avait été lié au bois et torturé là. Eridan pouvait à peine la tenir. Elle la lava dans l'eau bénie d'Elune, et le lien se brisa. Elle pensait que la flûte, jouée en un lieu sacré, pourrait appeler les esprits des anciens qui hantent encore la forêt.]=],
		},
		{
			title = "La mission d'un étranger",
			hint = [=[Venez voir Eridan de la part d'un vagabond du Cratère d'Un'Goro.]=],
			text = [=[Un étranger du {link:un-goro-crater}Cratère d'Un'Goro{/link} avait prononcé son nom alors qu'il ne se souvenait guère d'autre chose. Eridan ne le connaissait pas, mais elle connaissait son dessein. Elle rassembla des griffes et le cœur d'un tréant d'Arbrefer, et les envoya avec le Livre d'Aquor à un cercle de pierres en {link:tanaris}Tanaris{/link}, où l'élémentaire d'eau Aquementas pouvait être appelé pour les forger en un totem.]=],
		},
	},
	mentions = {
		{ text = "La flûte de {link:xavaric}Xavaric{/link}" },
		{ text = "La mémoire de {link:linken}Linken{/link}" },
		{ text = "Cœur d'argent" },
		{ text = "Aquementas" },
		{ text = "La corruption des Jadefeu" },
		{ text = "Anciens gangrelés" },
		{ text = "Purifiée !" },
		{ text = "Nouvelle corruption" },
	},
	bonds = {
		{ id = "xavathras", name = "Xavathras", note = "le satyre qu'elle fit tuer" },
		{ id = "xavaric", name = "Xavaric", note = "le seigneur satyre du nord" },
		{ id = "arei", name = "Arei", note = "un esprit ancien de la forêt" },
		{ id = "greta-mosshoof", name = "Greta Mosshoof", note = "du même cercle" },
	},
})

Translate("frFR", "greta-mosshoof", {
	title = "Greta Mosshoof",
	subtitle = "Druidesse du Cercle d'émeraude",
	found = "Le Sanctuaire d'émeraude, au sud de Gangrebois",
	hint = [=[Cherchez la druidesse du Cercle d'émeraude qui fait la guerre au Conseil des ombres.]=],
	allegiance = "Cercle d'émeraude · Cercle cénarien",
	aliases = { "Greta" },
	sections = {
		{
			title = "Résumé",
			text = [=[Greta Mosshoof est une druidesse du {link:emerald-circle}Cercle d'émeraude{/link}, et elle prie la Terre-Mère. Là où d'autres membres de son cercle cherchent à guérir la forêt, elle s'est chargée de frapper la cause de son mal. Son ennemi est le {link:shadow-council}Conseil des ombres{/link} de {link:jaedenar}Jaedenar{/link}, et elle entend lui couper la tête.]=],
		},
		{
			title = "Importance",
			text = [=[Greta est la stratège de la guerre du Cercle contre {link:jaedenar}Jaedenar{/link}. Elle comprend qu'on ne peut combattre {link:shadow-council}le Conseil{/link} à l'aveugle, et elle a la patience d'apprendre avant de frapper. Elle garde aussi un espoir plus grand : réunir un remède qui pourrait un jour guérir les arbres et les créatures de {link:felwood}Gangrebois{/link}.]=],
		},
		{
			title = "Hauts faits",
			text = [=[• Elle éprouva la résolution de ceux qui venaient l'aider contre les cultistes de {link:jaedenar}Jaedenar{/link}.
• Elle fit purifier par les esprits de l'eau l'eau corrompue du puits de lune de Jaedenar.
• Elle scruta le Fort des ombres par divination et apprit qui dirigeait {link:shadow-council}le Conseil{/link}.
• Elle envoya ses alliés contre le seigneur des ombres {link:shadow-lord-fel-dan}Fel'dan{/link} et ses serviteurs.
• Elle chercha le sang du drake vert {link:morphaz}Morphaz{/link} pour le second remède de {link:felwood}Gangrebois{/link}.]=],
		},
	},
	chapters = {
		{
			title = "L'eau contre le feu",
			hint = [=[Faites purifier l'eau du puits de lune de Jaedenar, et versez-la sur les braseros du Fort des ombres.]=],
			text = [=[Le Conseil protégeait le {link:jaedenar}Fort des ombres{/link} par des sorts qui brûlaient dans quatre braseros. Greta fit chercher de l'eau du puits de lune corrompu au cœur de Jaedenar, puis l'envoya au sud à une vieille amie, une chamane qui vit au bord de la mer au sud de {link:ratchet}Ratchet{/link}. Les esprits de l'eau entendirent la chamane et bénirent la cause. Avec l'eau purifiée, les flammes furent éteintes. Pendant un bref moment, avant que les démonistes ne renouvellent leurs protections, Greta put voir à l'intérieur du Fort.]=],
		},
		{
			title = "La tête du serpent",
			hint = "Frappez le mortel qui dirige le Conseil des ombres.",
			text = [=[Ce que Greta vit lui apprit qu'il n'existait aucun moyen habile d'y entrer. {link:shadow-lord-fel-dan}Fel'dan{/link}, le seigneur des ombres, était le mortel qui commandait en bas, et c'était lui qui concluait les pactes avec la Légion. Elle envoya ses alliés droit sur lui. Quand sa tête lui revint, elle loua la Terre-Mère. Elle espérait que, sans lui, {link:shadow-council}le Conseil{/link} se retournerait contre lui-même.]=],
		},
		{
			title = "Le second remède",
			hint = "Rapportez-lui le sang du drake Morphaz, du temple englouti.",
			text = [=[On dit que le drake vert {link:morphaz}Morphaz{/link} est immunisé contre tout poison et toute maladie, et bien des druides moururent pour l'apprendre. Greta voulait son sang. Quand il arriva, elle put à peine y croire. Il faudrait une vie entière, dit-elle, pour défaire ce qui s'était passé à {link:felwood}Gangrebois{/link}, mais le Cercle avait enfin les moyens de commencer.]=],
		},
	},
	mentions = {
		{ text = "Les forces de {link:jaedenar}Jaedenar{/link}" },
		{ text = "Collecte de l'eau corrompue" },
		{ text = "En quête d'une aide spirituelle" },
		{ text = "L'eau purifiée retourne à {link:felwood}Gangrebois{/link}" },
		{ text = "Éteindre les flammes de protection" },
		{ text = "Un dernier coup" },
		{ text = "Le sang de {link:morphaz}Morphaz{/link}" },
	},
	bonds = {
		{ id = "shadow-lord-fel-dan", name = "Seigneur des ombres Fel'dan", note = "la tête du serpent" },
		{ id = "eridan-bluewind", name = "Eridan Bluewind", note = "du même cercle" },
		{ id = "morphaz", name = "Morphaz", note = "dont elle chercha le sang" },
	},
})

Translate("frFR", "lord-banehollow", {
	title = "Seigneur Banehollow",
	subtitle = "Seigneur de l'effroi de Jaedenar",
	found = "Les profondeurs du Fort des ombres, à Jaedenar",
	hint = [=[Drapez-vous d'ombre et cherchez le seigneur de l'effroi au fond de Jaedenar.]=],
	allegiance = "Légion ardente · Conseil des ombres",
	aliases = { "Banehollow" },
	sections = {
		{
			title = "Résumé",
			text = [=[Le seigneur Banehollow est un seigneur de l'effroi qui tient sa cour dans les profondeurs de {link:jaedenar}Jaedenar{/link}, le siège du {link:shadow-council}Conseil des ombres{/link}. Il est vieux, patient et cruel. Les démonistes du Conseil vont et viennent devant lui, et seuls ceux qui portent l'ombre même du Conseil peuvent l'approcher sans dommage.]=],
		},
		{
			title = "Importance",
			text = [=[Banehollow est le démon qui se tient derrière les démonistes mortels de {link:jaedenar}Jaedenar{/link}, et il a des rivaux jusque parmi les siens. Le premier d'entre eux est le seigneur Hel'nurath, qui règne sur un domaine appelé Xoroth, au-delà de ce monde, et y élève les fameux destriers de l'effroi. Banehollow garde une réserve de poussière d'étoile de Xoroth, et les démonistes qui veulent ouvrir un chemin vers ce royaume doivent la lui marchander.]=],
		},
		{
			title = "Hauts faits",
			text = [=[• Il règne depuis les profondeurs du {link:jaedenar}Fort des ombres{/link}.
• Il démasqua son serviteur {link:ulathek}Ulathek{/link}, espion de Hel'nurath.
• Il vend la poussière d'étoile de Xoroth par l'entremise de son serviteur Ur'dan.]=],
		},
		{
			title = "Non consigné",
			text = [=[Aucune chronique ne rapporte depuis combien de temps Banehollow demeure à {link:felwood}Gangrebois{/link}, ni quel pacte le lie au {link:shadow-council}Conseil des ombres{/link}.]=],
		},
	},
	chapters = {
		{
			title = "Un invité à Jaedenar",
			hint = [=[Venez à Jaedenar déguisé par les potions ténébreuses des Steppes ardentes.]=],
			text = [=[Le gobelin {link:gorzeeki-wildeyes}Gorzeeki Wildeyes{/link} prépare des potions qui permettent à qui les boit de passer pour un membre du {link:shadow-council}Conseil des ombres{/link}. Ceux qui les boivent peuvent traverser {link:jaedenar}Jaedenar{/link} et se tenir devant Banehollow. Il ne les accueille pas chaleureusement. Sa patience, dit-il, s'étend sur des millénaires, et pourtant ils n'en auront pas plus d'un instant.]=],
		},
		{
			title = "Le cœur du traître",
			hint = "Prouvez vos services au seigneur de l'effroi.",
			text = [=[{link:ulathek}Ulathek{/link} rampait devant son maître tout en complotant avec Hel'nurath, qui espérait prendre à Banehollow son pouvoir sur {link:felwood}Gangrebois{/link}. Banehollow le savait. Il voulait qu'on le dise à Ulathek, et il voulait contempler sa peur. Puis il voulait son cœur, qu'il comptait laisser pourrir une semaine avant de le manger.]=],
		},
		{
			title = "Poussière d'étoile de Xoroth",
			hint = [=[Achetez la poussière d'étoile de Xoroth au serviteur du seigneur de l'effroi.]=],
			text = [=[Banehollow devina aussitôt pourquoi un démoniste voulait de la poussière d'étoile : pour ouvrir un portail vers le domaine de son rival et y voler l'un de ses destriers de l'effroi. L'idée ne le troubla pas. Il laissa son serviteur Ur'dan vendre la poussière d'étoile, contre un prix. Elle retourna à {link:gorzeeki-wildeyes}Gorzeeki{/link}, et de lui à {link:mor-zul-bloodbringer}Mor'zul Bloodbringer{/link}, qui en avait besoin pour son encre.]=],
		},
	},
	mentions = {
		{ text = "Seigneur Banehollow" },
		{
			text = [=[{link:ulathek}Ulathek{/link} {link:illidan-stormrage}le Traître{/link}]=],
		},
		{ text = "Poussière d'étoile xorothienne" },
	},
	bonds = {
		{ id = "ulathek", name = "Ulathek", note = "son serviteur perfide" },
		{ id = "gorzeeki-wildeyes", name = "Gorzeeki Wildeyes", note = "lui envoie des visiteurs" },
		{ id = "mor-zul-bloodbringer", name = "Mor'zul Bloodbringer", note = "reçoit sa poussière d'étoile" },
		{ id = "shadow-lord-fel-dan", name = "Seigneur des ombres Fel'dan", note = "le seigneur mortel du Conseil, au-dessous de lui" },
	},
})

Translate("frFR", "tichondrius", {
	title = "Tichondrius",
	subtitle = "Seigneur de l'effroi de la Légion ardente",
	hint = [=[Découvrez qui empoisonna la forêt du nord avec le Crâne de Gul'dan.]=],
	allegiance = "Légion ardente",
	sections = {
		{
			title = "Résumé",
			text = [=[Tichondrius était un seigneur de l'effroi, l'un des nathrezim qui servent la {link:burning-legion}Légion ardente{/link}. Pendant la {link:third-war}Troisième Guerre{/link}, il fut parmi les démons qui guidaient le {link:scourge}Fléau{/link} au nom de la Légion, et il donnait ses ordres au chevalier de la mort {link:arthas-menethil}Arthas Menethil{/link}. Quand la Légion vint en {link:kalimdor}Kalimdor{/link}, il porta le Crâne de {link:gul-dan}Gul'dan{/link} dans la forêt du nord et l'empoisonna par la sombre puissance du crâne. Cette forêt est {link:felwood}Gangrebois{/link}. Il y fut tué par {link:illidan-stormrage}Illidan Stormrage{/link}.]=],
		},
		{
			title = "Importance",
			text = [=[De tous les démons de la {link:third-war}Troisième Guerre{/link}, Tichondrius laissa la marque la plus profonde sur la terre elle-même. {link:archimonde}Archimonde{/link} tomba au mont Hyjal et son armée fut brisée, mais la corruption que Tichondrius avait semée ne mourut pas avec lui. Chaque {link:furbolgs}furbolg{/link} fou, chaque tréant flétri et chaque puits de lune souillé de {link:felwood}Gangrebois{/link} fait partie de son héritage. Sa mort changea aussi {link:illidan-stormrage}Illidan{/link} à jamais : pour le vaincre, Illidan prit en lui la puissance du crâne, et son peuple le bannit pour cela.]=],
		},
		{
			title = "Le Fléau et la Légion",
			text = [=[Le roi-liche fit le {link:scourge}Fléau{/link}, mais il ne le fit pas libre. Les seigneurs de l'effroi de la Légion veillaient sur lui, et Tichondrius était parmi eux. Après qu'{link:arthas-menethil}Arthas{/link} eut tué son père et se fut donné tout entier au Fléau, Tichondrius mit à l'épreuve la loyauté du prince et lui confia ses tâches. Arthas porta les restes du nécromancien {link:kel-thuzad}Kel'Thuzad{/link} jusqu'au puits de Soleil de {link:quel-thalas}Quel'Thalas{/link}, où Kel'Thuzad fut relevé en liche. Kel'Thuzad, à son tour, appela {link:archimonde}Archimonde{/link} dans le monde à {link:dalaran}Dalaran{/link}. Le seigneur de la Légion enfin venu, le Fléau avait rempli son office, et les démons se tournèrent vers {link:kalimdor}Kalimdor{/link}.]=],
		},
		{
			title = "L'empoisonnement de la forêt",
			text = [=[L'armée d'{link:archimonde}Archimonde{/link} marcha sur le mont Hyjal et l'Arbre-Monde {link:nordrassil}Nordrassil{/link}. Tichondrius vint dans les forêts du nord avec le {link:skull-of-gul-dan}Crâne de Gul'dan{/link}, les restes du démoniste qui avait le premier lié les orcs à la Légion. Le crâne gardait encore une grande part de la puissance gangrenée de {link:gul-dan}Gul'dan{/link}, et Tichondrius s'en servit pour corrompre les bois autour de lui. Les arbres noircirent et les eaux tournèrent. Bêtes et furbolgs devinrent fous. Des infernaux tombèrent du ciel en flammes, et les anciens qui gardaient la forêt furent détruits.]=],
		},
		{
			title = "La mort du seigneur de l'effroi",
			text = [=[{link:tyrande-whisperwind}Tyrande Whisperwind{/link} avait libéré {link:illidan-stormrage}Illidan{/link} de sa longue captivité pour combattre les démons. Illidan apprit l'existence du crâne et partit le chercher. Il le prit, et il en consuma la puissance. Elle le changea : il lui poussa des cornes et de grandes ailes sombres, et il devint lui-même en partie démon. Avec cette puissance, il tua Tichondrius. La victoire lui coûta tout le reste. {link:malfurion-stormrage}Malfurion Stormrage{/link} ne put pardonner ce que son frère était devenu, et il bannit Illidan des forêts des elfes de la nuit.]=],
		},
		{
			title = "Non consigné",
			text = [=[Aucune chronique ne dit comment Tichondrius en vint à détenir le crâne, ni combien de temps il demeura dans la forêt avant qu'{link:illidan-stormrage}Illidan{/link} ne le trouve.]=],
		},
	},
	chapters = {
		{
			title = "La mémoire des anciens",
			hint = "Guidez l'esprit d'un ancien hors de la forêt corrompue.",
			text = [=[L'esprit ancien {link:arei}Arei{/link} se souvient encore de la forêt d'avant la venue de la Légion. Elle se souvient des infernaux, de la destruction et du chaos. Elle se souvient que le {link:skull-of-gul-dan}crâne de Gul'dan{/link} veilla à ce que rien dans la forêt ne soit épargné. Même en esprit, elle ne peut échapper à la souffrance de la terre. Elle demande seulement qu'on la guide hors d'elle, afin de pouvoir reposer.]=],
		},
	},
	mentions = {
		{ text = "Esprit ancien" },
	},
	bonds = {
		{ id = "illidan-stormrage", name = "Illidan Stormrage", note = "son meurtrier" },
		{ id = "gul-dan", name = "Gul'dan", note = "le démoniste dont il utilisa le crâne" },
		{ id = "archimonde", name = "Archimonde", note = "son maître pendant la Troisième Guerre" },
		{ id = "arthas-menethil", name = "Arthas Menethil", note = "le chevalier de la mort qu'il commandait" },
		{ id = "arei", name = "Arei", note = "une ancienne qui se souvient de sa corruption" },
	},
})

Translate("frFR", "skull-of-gul-dan", {
	title = "Crâne de Gul'dan",
	aliases = { "crâne de Gul'dan" },
	sections = {
		{
			title = "Résumé",
			text = [=[Le Crâne de Gul'dan était le crâne du démoniste {link:orcs}orc{/link} {link:gul-dan}Gul'dan{/link}, fondateur du {link:shadow-council}Conseil des ombres{/link}. Il survécut à la mort du démoniste dans la tombe de {link:sargeras}Sargeras{/link} et garda une grande part de sa puissance gangrenée. Pendant la {link:third-war}Troisième Guerre{/link}, le seigneur de l'effroi {link:tichondrius}Tichondrius{/link} l'apporta en {link:kalimdor}Kalimdor{/link} et s'en servit pour corrompre la forêt du nord. {link:illidan-stormrage}Illidan Stormrage{/link} le lui prit et en consuma la puissance, et par elle il devint une créature à moitié démon.]=],
		},
		{
			title = "Son héritage",
			text = [=[Le crâne n'existe plus, mais son œuvre demeure. La forêt qu'il empoisonna s'appelle {link:felwood}Gangrebois{/link}. Les esprits des anciens se souviennent qu'il n'épargna rien, et les druides du {link:emerald-circle}Cercle d'émeraude{/link} luttent encore contre ce qu'il laissa derrière lui.]=],
		},
	},
})

Translate("frFR", "shadow-council", {
	title = "Conseil des ombres",
	aliases = { "le Conseil" },
	sections = {
		{
			title = "Résumé",
			text = [=[Le Conseil des ombres est un ordre secret de démonistes au service de la {link:burning-legion}Légion ardente{/link}. Il naquit parmi les orcs de Draenor, et il survécut à la {link:horde}Horde{/link} qu'il gouvernait jadis. Aujourd'hui, son siège est {link:jaedenar}Jaedenar{/link}, à {link:felwood}Gangrebois{/link}, et ses sectes sont éparpillées de par le monde.]=],
		},
		{
			title = "Origines",
			text = [=[Le seigneur démon {link:kil-jaeden}Kil'jaeden{/link} choisit le démoniste {link:gul-dan}Gul'dan{/link} pour serviteur parmi les orcs. Gul'dan rassembla les plus ambitieux de ses pairs démonistes en un conseil caché. Celui-ci gouverna les clans orcs derrière un chef de guerre fantoche et les mena à boire le sang de {link:mannoroth}Mannoroth{/link}. Par Gul'dan, il ouvrit la {link:dark-portal}Porte des Ténèbres{/link}.]=],
		},
		{
			title = "La chute",
			text = [=[Dans les jours qui suivirent la {link:first-war}Première Guerre{/link}, le Conseil établit son siège au {red:blackrock-spire}Pic Blackrock{/red}. {link:orgrim-doomhammer}Orgrim Doomhammer{/link} se retourna contre lui en ce lieu, tua la plupart de ses membres et fit {link:gul-dan}Gul'dan{/link} prisonnier. Gul'dan trahit plus tard la {link:horde}Horde{/link} et mourut. On crut que le Conseil était mort avec lui.]=],
		},
		{
			title = "Le temps présent",
			text = [=[Il n'en était rien. À {link:jaedenar}Jaedenar{/link}, le seigneur des ombres {link:shadow-lord-fel-dan}Fel'dan{/link} dirige l'ordre et conclut ses pactes avec la Légion, tandis qu'un seigneur de l'effroi tient sa cour dans les profondeurs. On impute au Conseil bien des maux à {link:felwood}Gangrebois{/link} et ailleurs. Sa marque apparaît parmi les démonistes des {link:arathi-highlands}Hautes-terres d'Arathi{/link}. À {link:orgrimmar}Orgrimmar{/link}, la {link:burning-blade}Lame ardente{/link} et la Searing Blade servent ses desseins, et les Shadowsworn des {link:blasted-lands}Terres foudroyées{/link} sont ses héritiers. {link:thrall}Thrall{/link} sait qu'il vit, et il entend le trouver.]=],
		},
	},
})

Translate("frFR", "emerald-circle", {
	title = "Cercle d'émeraude",
	sections = {
		{
			title = "Résumé",
			text = [=[Le Cercle d'émeraude est une confrérie de druides du {link:cenarion-circle}Cercle cénarien{/link} qui se sont voués à {link:felwood}Gangrebois{/link}. {link:night-elves}Elfes de la nuit{/link} et taurens y servent ensemble, et ils accueillent aussi bien les amis de l'{link:alliance}Alliance{/link} que ceux de la {link:horde}Horde{/link}. Depuis le {link:emerald-sanctuary}Sanctuaire d'émeraude{/link}, ils étudient la corruption et tentent de l'inverser.]=],
		},
		{
			title = "Leur œuvre",
			text = [=[• Ils combattent les satyres Jadefeu et le {link:shadow-council}Conseil des ombres{/link}, qui répandent et nourrissent la corruption.
• Ils ont appris à faire des baumes qui guérissent les plantes corrompues, mais ils ne partagent ce savoir qu'avec ceux qui font leurs preuves.
• Ils cherchent une eau pure, et un remède qui pourrait guérir les arbres et les créatures de la forêt.
• Ils étudient les furbolgs de {link:felwood}Gangrebois{/link} et d'ailleurs, et la folie qui s'est emparée d'eux.]=],
		},
		{
			title = "Non consigné",
			text = [=[Aucune chronique ne rapporte quand le Cercle d'émeraude fut fondé, ni qui le dirigea le premier.]=],
		},
	},
})

Translate("frFR", "deadwood-furbolgs", {
	title = "Furbolgs Mort-bois",
	aliases = { "Mort-bois", "tribu Mort-bois" },
	sections = {
		{
			title = "Résumé",
			text = [=[Les Mort-bois sont une tribu de {link:furbolgs}furbolgs{/link} de {link:felwood}Gangrebois{/link} que la gangrène a rendus fous. Ils tiennent le {link:deadwood-village}Village des Mort-bois{/link} au sud de la forêt et le {link:felpaw-village}Village de Gangrepatte{/link} au nord, et ils attaquent tous ceux qui approchent.]=],
		},
		{
			title = "La folie",
			text = [=[{link:timbermaw-hold}Les Grumegueules{/link} disent que les Mort-bois ne sont pas mauvais par nature. C'est la gangrène qui souille leur esprit, et on ne peut la défaire. Leurs totems rituels empestent la décomposition et le désespoir. Dans leur camp du nord, un breuvage vert et pourrissant bouillonne dans un chaudron, et il répand peut-être la folie parmi les furbolgs {link:winterfall-furbolgs}Tombe-hiver{/link} de {link:winterspring}Berceau-de-l'Hiver{/link}.]=],
		},
		{
			title = "Leurs chefs",
			text = [=[• {b}Le suzerain {link:overlord-ror}Ror{/link}{/b} règne sur le {link:deadwood-village}Village des Mort-bois{/link}, au sud.
• {b}Le chef Bloodmaw{/b} règne sur le camp proche des {link:timbermaw-furbolgs}Grumegueules{/link}, au nord.]=],
		},
	},
})

Translate("frFR", "timbermaw-furbolgs", {
	title = "Furbolgs Grumegueules",
	aliases = { "Grumegueules", "tribu Grumegueules" },
	sections = {
		{
			title = "Résumé",
			text = [=[{link:timbermaw-hold}Les Grumegueules{/link} sont la seule tribu de {link:furbolgs}furbolgs{/link} qui a échappé à la corruption. Ils demeurent aux Grumegueules, les tunnels entre {link:felwood}Gangrebois{/link} et {link:winterspring}Berceau-de-l'Hiver{/link}, et ils les gardent contre tous.]=],
		},
		{
			title = "Un peuple méfiant",
			text = [=[{link:timbermaw-hold}Les Grumegueules{/link} font confiance à très peu. Bien des voyageurs tuent désormais tout {link:furbolgs}furbolg{/link} qu'ils voient, sans se demander s'il est ami ou ennemi. Les Grumegueules en ont tiré la leçon. Ils n'accueillent que ceux qui font leurs preuves contre les tribus corrompues, les {link:deadwood-furbolgs}Mort-bois{/link} de {link:felwood}Gangrebois{/link} et les {link:winterfall-furbolgs}Tombe-hiver{/link} de {link:winterspring}Berceau-de-l'Hiver{/link}. Il leur est douloureux de combattre leurs propres frères, mais ils le font. Le {link:magni-bronzebeard}roi Magni{/link} d'{link:ironforge}Ironforge{/link} et le chef de guerre de la {link:horde}Horde{/link} ont tous deux tenté de les approcher par le passé.]=],
		},
		{
			title = "Leur espoir",
			text = [=[{link:timbermaw-hold}Les Grumegueules{/link} croient que les {link:winterfall-furbolgs}Tombe-hiver{/link} sont gouvernés par un démon. S'il était détruit, la guérison des Tombe-hiver pourrait commencer, et leur repaire serait sûr pour des années.]=],
		},
	},
})

Translate("frFR", "arathandris-silversky", {
	title = "Arathandris Silversky",
	subtitle = "Druidesse du Cercle d'émeraude",
	found = "Une clairière à l'est du Sanctuaire d'émeraude",
	hint = [=[Trouvez la druidesse qui garde le secret de la guérison des plantes de Gangrebois.]=],
	allegiance = "Cercle d'émeraude · Cercle cénarien",
	aliases = { "Arathandris" },
	sections = {
		{
			title = "Résumé",
			text = [=[Arathandris Silversky est une druidesse du {link:emerald-circle}Cercle d'émeraude{/link} qui a appris à guérir les plantes corrompues de {link:felwood}Gangrebois{/link}. Elle souffre avec la forêt et garde jalousement son savoir, car entre de mauvaises mains il pourrait causer un désastre. Ceux qui voudraient l'apprendre doivent d'abord faire leurs preuves.]=],
		},
		{
			title = "Hauts faits",
			text = [=[• Elle demanda l'ambre de sang des élémentaires Warpwood de la {link:irontree-woods}Caverne d'Arbrefer{/link}, pour étudier la corruption.
• Elle fait les baumes cénariens qui purifient les fleurs-chantantes, les fleurs-du-vent, les racines-fouets et les fleurs de dragon de nuit.]=],
		},
	},
	mentions = {
		{ text = "Purifier {link:felwood}Gangrebois{/link}" },
		{ text = "Du baume par la chasse" },
	},
	bonds = {
		{ id = "maybess-riverbreeze", name = "Maybess Riverbreeze", note = "fait le même travail à l'ouest" },
	},
})

Translate("frFR", "maybess-riverbreeze", {
	title = "Maybess Riverbreeze",
	subtitle = "Druidesse du Cercle d'émeraude",
	found = "Une clairière à l'ouest du Sanctuaire d'émeraude",
	hint = [=[Trouvez la druidesse qui fait des baumes pour les plantes malades de Gangrebois.]=],
	allegiance = "Cercle d'émeraude · Cercle cénarien",
	aliases = { "Maybess" },
	sections = {
		{
			title = "Résumé",
			text = [=[Maybess Riverbreeze est une druidesse du {link:emerald-circle}Cercle d'émeraude{/link} qui fait les baumes qui guérissent les plantes de {link:felwood}Gangrebois{/link}. Comme {link:arathandris-silversky}Arathandris Silversky{/link}, elle ne partage pas son art avec des étrangers. Elle demande d'abord une preuve de bonne foi : l'ambre de sang tiré des élémentaires Warpwood, qu'on ne peut plus sauver. Elle admet qu'une telle épreuve peut sembler étrange. Pour elle, sauver d'innombrables vies doit justifier les moyens.]=],
		},
	},
	mentions = {
		{ text = "Purifier {link:felwood}Gangrebois{/link}" },
		{ text = "Du baume par la chasse" },
	},
	bonds = {
		{ id = "arathandris-silversky", name = "Arathandris Silversky", note = "fait le même travail à l'est" },
	},
})

Translate("frFR", "taronn-redfeather", {
	title = "Taronn Redfeather",
	subtitle = "Druide du Cercle d'émeraude",
	found = "Le Sanctuaire d'émeraude",
	hint = [=[Parlez au druide du Cercle d'émeraude qui cherche une eau pure.]=],
	allegiance = "Cercle d'émeraude · Cercle cénarien",
	aliases = { "Taronn" },
	sections = {
		{
			title = "Résumé",
			text = [=[Taronn Redfeather, du {link:emerald-circle}Cercle d'émeraude{/link}, cherche à {link:felwood}Gangrebois{/link} une seule source d'eau pure. Il croyait que guérir la terre serait bien plus facile s'il en trouvait une. Il espérait que les cratères du {link:shatter-scar-vale}Val Grêlé{/link}, où tombèrent les infernaux, se seraient éclaircis avec le temps. Ce n'était pas le cas. Il avoue que les infernaux l'effraient, tout stupides qu'ils sont. Il entend désormais sauver les créatures de la forêt qu'il peut, et abattre celles qui sont trop corrompues pour être sauvées.]=],
		},
	},
	mentions = {
		{ text = "Vérifier la corruption" },
	},
	bonds = {
		{ id = "greta-mosshoof", name = "Greta Mosshoof", note = "du même cercle" },
	},
})

Translate("frFR", "kelek-skykeeper", {
	title = "Kelek Skykeeper",
	subtitle = "Druide du Cercle d'émeraude",
	found = "Le Sanctuaire d'émeraude",
	hint = [=[Apportez à l'érudit des furbolgs du Cercle d'émeraude les écrits d'un chef Tombe-hiver.]=],
	allegiance = "Cercle d'émeraude · Cercle cénarien",
	aliases = { "Kelek" },
	sections = {
		{
			title = "Résumé",
			text = [=[Kelek Skykeeper, du {link:emerald-circle}Cercle d'émeraude{/link}, connaît les furbolgs de {link:felwood}Gangrebois{/link} mieux que quiconque au {link:emerald-sanctuary}Sanctuaire d'émeraude{/link}. Quand {link:donova-snowden}Donova Snowden{/link} de {link:winterspring}Berceau-de-l'Hiver{/link} voulut savoir ce qui poussait les furbolgs {link:winterfall-furbolgs}Tombe-hiver{/link} à brasser et boire leur étrange eau-de-feu, elle lui envoya un journal grossier. Il avait été pris à leur chef. Kelek ne prétend pas en savoir beaucoup sur les Tombe-hiver, et il l'accepta avec joie. Il compte le traduire et faire savoir ce qu'il apprendra.]=],
		},
	},
	mentions = {
		{ text = "Paroles du Grand Chef" },
	},
	bonds = {
		{ id = "deadwood-furbolgs", name = "Furbolgs Mort-bois", note = "la tribu qu'il a étudiée" },
	},
})

Translate("frFR", "jessir-moonbow", {
	title = "Jessir Moonbow",
	subtitle = "Amie d'Arko'narin",
	found = "Le Sanctuaire d'émeraude, avec sa chatte Della",
	hint = [=[Trouvez l'amie qui attend des nouvelles des captifs de Jaedenar.]=],
	allegiance = "Elfes de la nuit",
	aliases = { "Jessir" },
	sections = {
		{
			title = "Résumé",
			text = [=[Jessir Moonbow attend au {link:emerald-sanctuary}Sanctuaire d'émeraude{/link} avec sa chatte, Della. Ses amis {link:arko-narin}Arko'narin{/link} et le paladin {link:trey-lightforge}Trey Lightforge{/link} devaient l'y rejoindre. Ils ne vinrent jamais, car {link:shadow-council}le Conseil{/link} des ombres les avait capturés tous deux. Quand Arko'narin s'échappa, elle ne passa que le temps de parler du sort de Trey. Jessir connaissait le chagrin qu'Arko'narin refusait de montrer. Elle demanda que le bourreau de Trey soit tué et ses restes ramenés, afin que son amie trouve un peu de paix.]=],
		},
	},
	mentions = {
		{ text = "Sauvetage à {link:jaedenar}Jaedenar{/link}" },
		{ text = "Le châtiment de la Lumière" },
		{ text = "Les restes de {link:trey-lightforge}Trey Lightforge{/link}" },
	},
	bonds = {
		{ id = "arko-narin", name = "Arko'narin", note = "son amie" },
		{ id = "trey-lightforge", name = "Trey Lightforge", note = "son ami, tué à Jaedenar" },
		{ id = "rakaiah", name = "Rakaiah", note = "le bourreau de Trey" },
	},
})

Translate("frFR", "arko-narin", {
	title = "Arko'narin",
	subtitle = "Captive du Fort des ombres",
	found = "Une cage dans le Fort des ombres",
	hint = "Trouvez l'elfe de la nuit retenue dans une cage à Jaedenar.",
	allegiance = "Elfes de la nuit",
	aliases = { "Arko" },
	sections = {
		{
			title = "Résumé",
			text = [=[Arko'narin est une {link:night-elves}elfe de la nuit{/link} que {link:shadow-council}le Conseil{/link} des ombres fit prisonnière et enferma dans une cage du {link:jaedenar}Fort des ombres{/link}. Elle s'attendait à être sacrifiée aux démons du Conseil. Une clé d'os rouge, prise à l'un des cultistes, la libéra. Avant de fuir, elle refusa de partir sans l'épée Lightforge, qui avait appartenu à son ami {link:trey-lightforge}Trey{/link}. Elle la porta hors de Jaedenar et se hâta vers {link:darnassus}Darnassus{/link} pour avertir ses supérieurs, trop pressée même pour laisser les druides la soigner.]=],
		},
	},
	mentions = {
		{ text = "Une étrange clé rouge" },
		{ text = "Sauvetage à {link:jaedenar}Jaedenar{/link}" },
	},
	bonds = {
		{ id = "trey-lightforge", name = "Trey Lightforge", note = "son ami proche" },
		{ id = "jessir-moonbow", name = "Jessir Moonbow", note = "son amie" },
	},
})

Translate("frFR", "trey-lightforge", {
	title = "Trey Lightforge",
	subtitle = "Chevalier de la Main d'argent",
	found = "Ses restes, dans le Fort des ombres",
	hint = [=[Trouvez ce que le Conseil des ombres a laissé d'un paladin à Jaedenar.]=],
	allegiance = "Chevaliers de la Main d'argent",
	aliases = { "Trey" },
	sections = {
		{
			title = "Résumé",
			text = [=[Trey Lightforge était un paladin, un chevalier de la Main d'argent, venu à {link:felwood}Gangrebois{/link} avec son amie {link:arko-narin}Arko'narin{/link}. Le {link:shadow-council}Conseil des ombres{/link} les captura tous deux. La succube {link:rakaiah}Rakaiah{/link} tortura Trey dans le {link:jaedenar}Fort des ombres{/link} jusqu'à sa mort, et Arko'narin rencontra son esprit avant de s'échapper. Son épée, Lightforge, fut portée hors de Jaedenar par la main de celle-ci. Ses restes demeurèrent sur place jusqu'à ce que son bourreau soit tué et qu'on puisse les rapporter à ses amis.]=],
		},
	},
	mentions = {
		{ text = "Le châtiment de la Lumière" },
		{ text = "Les restes de Trey Lightforge" },
	},
	bonds = {
		{ id = "arko-narin", name = "Arko'narin", note = "son amie" },
		{ id = "rakaiah", name = "Rakaiah", note = "son bourreau" },
	},
})

Translate("frFR", "winna-hazzard", {
	title = "Winna Hazzard",
	subtitle = "Réprouvée du Poste de la Vénéneuse",
	found = "Le Poste de la Vénéneuse, avec son chaton",
	hint = [=[Trouvez l'étrange Réprouvée du Poste de la Vénéneuse qui garde un chaton.]=],
	allegiance = "Réprouvés · Horde",
	aliases = { "Winna" },
	sections = {
		{
			title = "Résumé",
			text = [=[Winna Hazzard est l'une des {link:forsaken}Réprouvés{/link}, et elle garde un chaton au {link:bloodvenom-post}Poste de la Vénéneuse{/link}. D'autres la disent cruelle. Elle affirme ne vouloir que donner à la {link:horde}Horde{/link} tous les avantages sur l'{link:alliance}Alliance{/link}. Sa dernière étude porte sur le puits de lune corrompu des satyres aux {link:ruins-of-constellas}Ruines de Constellas{/link}. Un peu de son eau fit grandir et forcir son chaton, et elle fit lâcher l'animal près du puits lui-même. Ce qui en revint lui plut beaucoup.]=],
		},
	},
	mentions = {
		{ text = "Une étrange personne" },
		{ text = "Le puits de corruption" },
		{ text = "Sabres corrompus" },
	},
	bonds = {
		{ id = "trull-failbane", name = "Trull Failbane", note = "partage le poste" },
	},
})

Translate("frFR", "trull-failbane", {
	title = "Trull Failbane",
	subtitle = "Éclaireur du Poste de la Vénéneuse",
	found = "Le Poste de la Vénéneuse",
	hint = [=[Parlez à l'agent de la Horde du Poste de la Vénéneuse qui étudie les sélénides.]=],
	allegiance = "Horde · Orgrimmar",
	aliases = { "Trull" },
	sections = {
		{
			title = "Résumé",
			text = [=[Trull Failbane, du {link:bloodvenom-post}Poste de la Vénéneuse{/link}, regarde au nord vers {link:winterspring}Berceau-de-l'Hiver{/link}. Il a entendu dire que ses sélénides gardent des secrets des elfes de la nuit, et il veut que cette terre s'ouvre à la {link:horde}Horde{/link}. Quand on prit à l'un des chouettards un collier luisant, il sut que sa magie le dépassait. Il l'envoya à {link:nara-wildmane}Nara Wildmane{/link} de {link:thunder-bluff}Thunder Bluff{/link}. Elle vit qu'Elune elle-même avait créé les sélénides pour garder ses lieux sacrés.]=],
		},
	},
	mentions = {
		{ text = "Gardiens sauvages" },
		{ text = "Garder les secrets" },
	},
	bonds = {
		{ id = "winna-hazzard", name = "Winna Hazzard", note = "partage le poste" },
		{ id = "nara-wildmane", name = "Nara Wildmane", note = "l'experte en qui il a confiance" },
	},
})

Translate("frFR", "dreka-sur", {
	title = "Dreka'Sur",
	subtitle = "Veuve du Poste de la Vénéneuse",
	found = "Le Poste de la Vénéneuse",
	hint = [=[Écoutez la veuve du Poste de la Vénéneuse qui veut voir son mari vengé.]=],
	allegiance = "Horde · Orgrimmar",
	aliases = { "Dreka" },
	sections = {
		{
			title = "Résumé",
			text = [=[Le mari de Dreka'Sur combattit dans tout {link:felwood}Gangrebois{/link} pour l'honneur de leur clan. Il affronta {link:shadow-council}le Conseil{/link} des ombres et échappa bien des fois à la mort. Puis un druide lui demanda son aide contre le suzerain {link:overlord-ror}Ror{/link}, un grand {link:furbolgs}furbolg{/link} souillé près de la frontière d'{link:ashenvale}Orneval{/link}. On ne revit ni l'un ni l'autre. Peu importe à Dreka'Sur que Ror soit fou ou simplement sauvage. Elle voulait sa main griffue. Quand elle arriva, elle dit que son mari était mort au combat et qu'il en aurait été fier.]=],
		},
	},
	mentions = {
		{ text = "Le dernier combat d'un mari" },
	},
	bonds = {
		{ id = "overlord-ror", name = "Suzerain Ror", note = "a tué son mari" },
	},
})

Translate("frFR", "grazle", {
	title = "Grazle",
	subtitle = "Émissaire des Grumegueules",
	found = "Un camp au sud-est du Sanctuaire d'émeraude",
	hint = [=[Cherchez le furbolg Grumegueules qui attend près des Mort-bois du sud.]=],
	allegiance = "Furbolgs Grumegueules",
	sections = {
		{
			title = "Résumé",
			text = [=[Grazle est un {link:furbolgs}furbolg{/link} {link:timbermaw-furbolgs}Grumegueules{/link} qui attend au sud de {link:felwood}Gangrebois{/link}, près de la {link:deadwood-furbolgs}tribu Mort-bois{/link}. Il sait que bien des voyageurs tuent désormais tout furbolg à vue, et que c'est pour cela que son peuple fait confiance à si peu. Il offre un moyen de gagner cette confiance : repousser les Mort-bois. Pour chaque lot de plumes prises aux coiffes des Mort-bois, il veillera à ce que l'exploit soit connu parmi les siens. Ceux qui font leurs preuves, il les envoie au nord auprès de {link:nafien}Nafien{/link}.]=],
		},
	},
	mentions = {
		{ text = "Allié des {link:timbermaw-furbolgs}Grumegueules{/link}" },
		{ text = "Parler à {link:nafien}Nafien{/link}" },
		{ text = "Des plumes pour Grazle" },
	},
	bonds = {
		{ id = "nafien", name = "Nafien", note = "son frère au repaire" },
		{ id = "deadwood-furbolgs", name = "Furbolgs Mort-bois", note = "la tribu qu'il combat" },
	},
})

Translate("frFR", "nafien", {
	title = "Nafien",
	subtitle = "Garde des Grumegueules",
	found = "Devant l'entrée sud des Grumegueules",
	hint = "Parlez au furbolg qui garde la route des Grumegueules.",
	allegiance = "Furbolgs Grumegueules",
	sections = {
		{
			title = "Résumé",
			text = [=[Nafien monte la garde à l'entrée des {link:timbermaw-furbolgs}Grumegueules{/link} du côté de {link:felwood}Gangrebois{/link}. Il a peut-être l'air sauvage, mais il a le cœur doux, et il s'afflige que son peuple doive combattre ses propres frères. Les {link:deadwood-furbolgs}Mort-bois{/link} du camp en contrebas ne sont pas mauvais par nature, dit-il ; la gangrène a empoisonné leur esprit, et on ne peut pas les aider. Il demande à d'autres de faire ce qui doit être fait, et il leur demande de lui épargner les détails. Il envoie ceux qui l'aident auprès de {link:salfa}Salfa{/link}, à la porte de {link:winterspring}Berceau-de-l'Hiver{/link}.]=],
		},
	},
	mentions = {
		{ text = "Les {link:deadwood-furbolgs}Mort-bois{/link} du nord" },
		{ text = "Parler à {link:salfa}Salfa{/link}" },
		{ text = "Des plumes pour Nafien" },
	},
	bonds = {
		{ id = "grazle", name = "Grazle", note = "son frère du sud" },
	},
})

Translate("frFR", "gorn-one-eye", {
	title = "Gorn One Eye",
	subtitle = "Ancien des Grumegueules",
	found = "À l'intérieur des Grumegueules",
	hint = [=[Cherchez le furbolg borgne qui parle au nom des Grumegueules.]=],
	allegiance = "Furbolgs Grumegueules",
	sections = {
		{
			title = "Résumé",
			text = [=[Gorn One Eye parle au nom des {link:timbermaw-furbolgs}Grumegueules{/link} dans leur repaire. Lui et son peuple trouvèrent un moyen d'appeler le démon qui gouverne les furbolgs {link:winterfall-furbolgs}Tombe-hiver{/link} : une torche plantée à l'entrée de la grotte du chef Tombe-hiver. Quand le démon Xandivious fut tué, {link:gorn}Gorn{/link} déclara le repaire sûr pour des années. Il envoya aussi l'offrande de paix des Grumegueules au roi {link:magni-bronzebeard}Magni Bronzebeard{/link} et à {link:thrall}Thrall{/link}, qui avaient tous deux tenté d'approcher son peuple auparavant.]=],
		},
	},
	mentions = {
		{ text = "La racine de tous les maux" },
		{ text = "La négociation de la paix" },
		{ text = "La négociation de la paix" },
	},
	bonds = {
		{ id = "meilosh", name = "Meilosh", note = "du même repaire" },
		{ id = "magni-bronzebeard", name = "Magni Bronzebeard", note = "reçut son offrande" },
		{ id = "thrall", name = "Thrall", note = "reçut son offrande" },
	},
})

Translate("frFR", "meilosh", {
	title = "Meilosh",
	subtitle = "Marchand des Grumegueules",
	found = "À l'intérieur des Grumegueules",
	hint = [=[Trouvez le furbolg qui fait commerce de belles étoffes à l'intérieur des Grumegueules.]=],
	allegiance = "Furbolgs Grumegueules",
	sections = {
		{
			title = "Résumé",
			text = [=[Meilosh commerce au nom des {link:timbermaw-furbolgs}Grumegueules{/link}. Son peuple préfère se tenir à l'écart du monde, et il concède que cela ne favorise guère le commerce. Il y a quelque temps, un {link:night-elves}elfe de la nuit{/link}, l'un des rares étrangers que la tribu appelle ami, vint au repaire vêtu d'une cape d'étoffe runique. Son peuple l'admira tant qu'il veut désormais des vêtements à lui. Il prend l'étoffe runique de ceux en qui la tribu a confiance, et donne en échange des marchandises des Grumegueules.]=],
		},
	},
	mentions = {
		{ text = "Étoffe runique" },
		{ text = "Étoffe sacrée" },
	},
	bonds = {
		{ id = "gorn-one-eye", name = "Gorn One Eye", note = "du même repaire" },
	},
})

Translate("frFR", "shadow-lord-fel-dan", {
	title = "Seigneur des ombres Fel'dan",
	subtitle = "Seigneur du Conseil des ombres",
	found = "Les profondeurs du Fort des ombres",
	hint = [=[Descendez au fond du Fort des ombres et affrontez le seigneur mortel du Conseil.]=],
	allegiance = "Conseil des ombres",
	aliases = { "Fel'dan" },
	sections = {
		{
			title = "Résumé",
			text = [=[Le seigneur des ombres Fel'dan est le mortel qui dirige {link:shadow-council}le Conseil{/link} des ombres à {link:jaedenar}Jaedenar{/link}. C'est lui qui conclut les pactes du Conseil avec la Légion. Deux succubes le servent, Moora et Salia. {link:greta-mosshoof}Greta Mosshoof{/link}, du {link:emerald-circle}Cercle d'émeraude{/link}, l'appela la tête du serpent. Elle espérait que, sans lui, le Conseil en viendrait à se disputer son propre pouvoir, et donnerait leur chance à ses ennemis.]=],
		},
	},
	mentions = {
		{ text = "Un dernier coup" },
	},
	bonds = {
		{ id = "greta-mosshoof", name = "Greta Mosshoof", note = "voulut sa mort" },
		{ id = "lord-banehollow", name = "Seigneur Banehollow", note = "le seigneur de l'effroi de Jaedenar" },
	},
})

Translate("frFR", "rakaiah", {
	title = "Rakaiah",
	found = "À l'intérieur du Fort des ombres",
	hint = [=[Trouvez la succube qui tortura un chevalier de la Main d'argent.]=],
	allegiance = "Conseil des ombres · Légion ardente",
	sections = {
		{
			title = "Résumé",
			text = [=[Rakaiah est une succube qui sert {link:shadow-council}le Conseil{/link} des ombres dans le {link:jaedenar}Fort des ombres{/link}. Elle fut le bourreau du paladin {link:trey-lightforge}Trey Lightforge{/link}, et elle le maintint dans la douleur jusqu'à sa mort. Ses restes gisaient près de ses appartements. Ses amis du {link:emerald-sanctuary}Sanctuaire d'émeraude{/link} demandèrent qu'elle soit tuée avant qu'on les rapporte, afin que celle qui l'avait brisé ne lui survive pas.]=],
		},
	},
	mentions = {
		{ text = "Le châtiment de la Lumière" },
	},
	bonds = {
		{ id = "trey-lightforge", name = "Trey Lightforge", note = "sa victime" },
	},
})

Translate("frFR", "ulathek", {
	title = "Ulathek",
	subtitle = "Serviteur de Banehollow",
	found = "Ses quartiers dans le Fort des ombres",
	hint = [=[Portez le message du seigneur de l'effroi au serviteur qui l'a trahi.]=],
	allegiance = "Conseil des ombres",
	sections = {
		{
			title = "Résumé",
			text = [=[Ulathek était un serviteur du seigneur {link:lord-banehollow}Banehollow{/link} à {link:jaedenar}Jaedenar{/link}. Il rampait devant son maître tout en espionnant pour le seigneur Hel'nurath de Xoroth, qui espérait prendre à Banehollow son pouvoir sur {link:felwood}Gangrebois{/link}. Banehollow l'apprit. Il demanda qu'on dise à Ulathek que son secret était connu, afin que le seigneur de l'effroi puisse savourer la peur du serviteur. Puis il demanda le cœur du traître.]=],
		},
	},
	mentions = {
		{ text = "Ulathek {link:illidan-stormrage}le Traître{/link}" },
	},
	bonds = {
		{ id = "lord-banehollow", name = "Seigneur Banehollow", note = "le maître qu'il trahit" },
	},
})

Translate("frFR", "xavathras", {
	title = "Xavathras",
	found = "Les Ruines de Constellas",
	hint = [=[Affrontez le satyre cruel qui règne sur les ruines du sud-ouest.]=],
	allegiance = "Satyres Jadefeu",
	sections = {
		{
			title = "Résumé",
			text = [=[Xavathras est un {link:satyrs}satyre{/link} cruel qui mène les Jadefeu aux {link:ruins-of-constellas}Ruines de Constellas{/link}. Sous ses ordres, les satyres portent la corruption à chaque créature qu'ils rencontrent. Il entretenait le puits de lune corrompu des ruines, et il ne le faisait pas pour lui-même : son butin partait au nord, vers {link:xavaric}Xavaric{/link}. {link:eridan-bluewind}Eridan Bluewind{/link}, du {link:emerald-circle}Cercle d'émeraude{/link}, ne vit dans sa chute que le premier pas d'une longue entreprise.]=],
		},
	},
	mentions = {
		{ text = "La corruption des Jadefeu" },
	},
	bonds = {
		{ id = "xavaric", name = "Xavaric", note = "le satyre qu'il servait" },
		{ id = "eridan-bluewind", name = "Eridan Bluewind", note = "voulut sa mort" },
	},
})

Translate("frFR", "xavaric", {
	title = "Xavaric",
	found = "Le Défilé des Jadefeu, au nord-ouest",
	hint = "Affrontez le seigneur satyre du camp Jadefeu du nord.",
	allegiance = "Satyres Jadefeu",
	sections = {
		{
			title = "Résumé",
			text = [=[Xavaric mène les satyres Jadefeu du {link:jadefire-run}Défilé des Jadefeu{/link}, au nord de {link:felwood}Gangrebois{/link}. Le puits de lune corrompu de {link:ruins-of-constellas}Constellas{/link} était entretenu à son profit. Il portait une simple flûte de bois noueux. Ceux qui la tenaient ressentaient un effroi soudain, et ses sculptures semblaient bouger. {link:eridan-bluewind}Eridan Bluewind{/link} apprit qu'elle avait été taillée dans un ancien tréant tombé, dont l'esprit y avait été lié.]=],
		},
	},
	mentions = {
		{ text = "La flûte de Xavaric" },
		{ text = "Nouvelle corruption" },
	},
	bonds = {
		{ id = "xavathras", name = "Xavathras", note = "entretenait le puits de lune pour lui" },
		{ id = "eridan-bluewind", name = "Eridan Bluewind", note = "libéra l'esprit de sa flûte" },
	},
})

Translate("frFR", "overlord-ror", {
	title = "Suzerain Ror",
	subtitle = "Suzerain des Mort-bois",
	found = "Le Village des Mort-bois, à l'extrême sud",
	hint = "Affrontez le grand furbolg souillé des Mort-bois du sud.",
	allegiance = "Furbolgs Mort-bois",
	aliases = { "Ror" },
	sections = {
		{
			title = "Résumé",
			text = [=[Le suzerain Ror règne sur le {link:deadwood-village}Village des Mort-bois{/link}, près de la frontière d'{link:ashenvale}Orneval{/link}. C'est un grand {link:furbolgs}furbolg{/link}, souillé par la corruption de la forêt. Un druide et un guerrier de la {link:horde}Horde{/link} l'affrontèrent ensemble, et aucun ne revint. La veuve du guerrier, {link:dreka-sur}Dreka'Sur{/link} du {link:bloodvenom-post}Poste de la Vénéneuse{/link}, n'eut de repos qu'on lui ait apporté sa main griffue.]=],
		},
	},
	mentions = {
		{ text = "Le dernier combat d'un mari" },
	},
	bonds = {
		{ id = "dreka-sur", name = "Dreka'Sur", note = "la veuve qu'il fit" },
		{ id = "deadwood-furbolgs", name = "Furbolgs Mort-bois", note = "sa tribu" },
	},
})

Translate("frFR", "niby-the-almighty", {
	title = "Niby le Tout-Puissant",
	found = "Un petit camp au nord de Jaedenar, avec son diablotin Impsy",
	hint = [=[Trouvez l'invocateur qui se dit tout-puissant et son diablotin, au centre de Gangrebois.]=],
	allegiance = "Inconnue",
	aliases = { "Niby" },
	sections = {
		{
			title = "Résumé",
			text = [=[Niby le Tout-Puissant est un invocateur qui tient un camp au centre de {link:felwood}Gangrebois{/link} avec son diablotin, Impsy. Il connaît le secret pour lier un infernal, et il l'enseigne aux démonistes en échange du noyau de l'infernal mort {link:kroshius}Kroshius{/link}. Niby laisse les détails à Impsy. Le diablotin fait le travail et murmure que son maître est toqué. Quand on apporte le noyau, Niby est trop occupé par sa plus grande conjuration pour parler longtemps.]=],
		},
	},
	mentions = {
		{ text = "Ce que Niby ordonne" },
		{ text = "Essence gangrenée parfaite" },
		{ text = "Le noyau infernal de {link:kroshius}Kroshius{/link}" },
	},
	bonds = {
		{ id = "kroshius", name = "Kroshius", note = "l'infernal dont il veut le noyau" },
	},
})

Translate("frFR", "kroshius", {
	title = "Kroshius",
	found = "Un tas de pierre calcinée dans le Val Grêlé",
	hint = [=[Trouvez l'infernal éteint du Val Grêlé, et réveillez-le si vous l'osez.]=],
	allegiance = "Légion ardente",
	sections = {
		{
			title = "Résumé",
			text = [=[Kroshius était un infernal de la Légion tombé dans le {link:shatter-scar-vale}Val Grêlé{/link}. Son feu s'est presque entièrement éteint, et il gît là comme un tas de gravats. Mais il n'est pas tout à fait mort. Un feu gangrené, fait d'essences de démons venus de trois coins du monde, peut le réveiller. Ceux qui le réveillent doivent être prêts à le combattre, car son noyau infernal est le prix que demande {link:niby-the-almighty}Niby le Tout-Puissant{/link}.]=],
		},
	},
	mentions = {
		{ text = "Le noyau infernal de Kroshius" },
	},
	bonds = {
		{ id = "niby-the-almighty", name = "Niby le Tout-Puissant", note = "veut son noyau" },
	},
})

Translate("frFR", "arei", {
	title = "Arei",
	subtitle = "Esprit ancien",
	found = "Bois d'Arbrefer",
	hint = "Guidez un esprit perdu des anciens hors du Bois d'Arbrefer.",
	allegiance = "Les anciens de la forêt",
	sections = {
		{
			title = "Résumé",
			text = [=[Arei est l'esprit d'une ancienne, l'une des gardiennes de la forêt, qui s'attarde dans le {link:irontree-woods}Bois d'Arbrefer{/link}. Elle se souvient de {link:felwood}Gangrebois{/link} tel qu'il était, paisible et serein, avant que la Légion ne vienne avec ses infernaux et le crâne de {link:gul-dan}Gul'dan{/link}. Même en esprit, elle souffre avec la terre. Elle demanda qu'on la guide vers l'est, hors de la corruption, pour reposer. Le druide {link:kayneth-stillwind}Kayneth Stillwind{/link} du {link:forest-song}Chant des forêts{/link} fut informé de son passage.]=],
		},
	},
	mentions = {
		{ text = "Esprit ancien" },
	},
	bonds = {
		{ id = "tichondrius", name = "Tichondrius", note = "la corruption dont elle se souvient" },
		{ id = "eridan-bluewind", name = "Eridan Bluewind", note = "parla des esprits des bois" },
	},
})

Translate("frFR", "vartrus-the-ancient", {
	title = "Vartrus l'Ancien",
	subtitle = "Esprit des anciens",
	found = "Une pierre du Bois d'Arbrefer",
	hint = "Rendez une feuille pétrifiée à l'ancien qui l'a perdue.",
	allegiance = "Les anciens de la forêt",
	aliases = { "Vartrus" },
	sections = {
		{
			title = "Résumé",
			text = [=[Vartrus est l'un des trois anciens, avec Stoma et Hastat, qui protégeaient cette forêt. Ils disent que leurs corps furent détruits quand {link:archimonde}Archimonde{/link} et la Légion marchèrent sur Hyjal, mais que leurs esprits demeurent. Ils répondent à une pierre du {link:irontree-woods}Bois d'Arbrefer{/link}. À ceux qui prouvent leur valeur, Vartrus confie des tâches contre les corrupteurs démoniaques encore en liberté dans le monde. La récompense est un bâton des anciens.]=],
		},
	},
	mentions = {
		{ text = "La feuille ancienne" },
		{ text = "Une présentation" },
		{ text = "Le bâton des anciens" },
	},
	bonds = {
		{ id = "arei", name = "Arei", note = "un autre esprit des bois" },
	},
})
