-- Generated by tools/build_content.py from content/raids/the-barrow-deeps.md. Do not edit.
local _, ns = ...
local Add = ns.Lore.Add

Add({
	id = "the-barrow-deeps",
	title = "The Barrow Deeps",
	aliases = { "Barrow Deeps" },
	continent = "Kalimdor",
	zone = "The Barrow Deeps",
	unlock = {
		{ type = "zone" },
	},
	regionKind = "raid",
	kind = "region",
	sections = {
		{
			title = "Summary",
			text = [=[The Barrow Deeps are the lowest reaches of the barrows of the {link:night-elves}night elves{/link}, far beneath the dens where their druids slept. The kaldorei did not dig them for the living. For ten thousand years they held a single prisoner: {link:illidan-stormrage}Illidan Stormrage{/link}, the Betrayer. Few went down into them, and fewer spoke of what they had seen. Now their silence is broken, and only a small, hardened band may hope to walk them.]=],
		},
		{
			title = "Origins",
			text = [=[The barrow dens were made for the druids of {link:malfurion-stormrage}Malfurion Stormrage{/link}. After the {link:war-of-the-ancients}War of the Ancients{/link}, the druids gave themselves to a long sleep. Their spirits wandered the {link:emerald-dream}Emerald Dream{/link}, while their bodies rested in halls of root and stone. Among them slept the Druids of the Claw, druids who could take the shape of the great bear.

Deeper still lay a darker work. When {link:illidan-stormrage}Illidan{/link} made a new Well upon {link:mount-hyjal}Mount Hyjal{/link}, Malfurion judged it a crime against the world. He had his brother chained beneath the earth, in a prison below the barrows. Maiev Shadowsong and her wardens were set to keep him there, and they kept him for ten thousand years. In all that time the druids slept on in the dens above him.]=],
		},
		{
			title = "The Third War",
			text = [=[When the {link:burning-legion}Burning Legion{/link} returned, {link:tyrande-whisperwind}Tyrande Whisperwind{/link} woke the sleeping druids, and the Druids of the Claw rose from their dens to fight. Tyrande then went down into the prison against the wishes of her beloved. She cut her way past its wardens and set {link:illidan-stormrage}Illidan{/link} free, believing that his power was needed against the demons. {link:malfurion-stormrage}Malfurion{/link} later banished his brother from the forests of the {link:night-elves}kaldorei{/link}. The cell beneath the barrows was left empty, and the Betrayer did not return to it.]=],
		},
		{
			title = "In the Present Day",
			text = [=[The Barrow Deeps are no longer a quiet place. Something stirs in the dark halls below the dens, and the paths that the wardens once walked are dangerous again. Those who would go down must be few in number and the best of their kind.]=],
		},
		{
			title = "Unrecorded",
			text = [=[What has woken in the Barrow Deeps, and what it seeks there, no chronicle of this age has yet set down. Nor do the old tales say where the deepest halls lie in relation to the dens above them.]=],
		},
	},
})
