-- Generated by tools/build_content.py from content/topics/world-and-history.md. Do not edit.
local _, ns = ...
local Add = ns.Lore.Add

Add({
	id = "azeroth",
	title = "Azeroth",
	unlock = {
		{ type = "always" },
	},
	regionKind = "world",
	kind = "region",
	sections = {
		{
			title = "Summary",
			text = [=[Azeroth is the world. Its seas hold the continents of the {link:eastern-kingdoms}Eastern Kingdoms{/link}, {link:kalimdor}Kalimdor{/link} and frozen Northrend, and countless isles besides. Jungles, deserts, forests and fields of ice lie side by side across it, and in every land the ruins of older ages rest beneath the towns of the new. It is a world of many peoples and of very long memory. Again and again it has been made to bleed by powers that covet it, and again and again it has endured.]=],
		},
		{
			title = "Origins",
			text = [=[The oldest histories say that Azeroth was shaped by the titans, godlike beings who journeyed among the stars to bring order to the worlds they found. When they came to Azeroth, it was ruled by raging elementals and by ancient evils that had fastened themselves upon the world. The chronicles name these evils the Old Gods. The titans broke the power of both. They bound the elemental lords within a realm set apart from the world, and they imprisoned the Old Gods deep beneath the earth, for they could not be slain without wounding the world itself. Then the titans shaped the land. Their servants raised the mountains, carved the valleys and filled the seas. The earthen, beings of living stone, were set to tend the deep places of the world. Among the dragons, the titans chose five and gave each a share of their power. These became the Aspects, charged to guard Azeroth when its makers were gone. Then the titans departed, and the world was left to its own peoples.]=],
		},
		{
			title = "The Ages of the World",
			text = [=[• {b}The Kaldorei Empire.{/b} At the heart of a single great continent lay the {link:well-of-eternity}Well of Eternity{/link}. On its shores the {link:night-elves}night elves{/link} raised an empire of wonders under {link:queen-azshara}Queen Azshara{/link}.
• {b}The War of the Ancients.{/b} The reckless magic of the Highborne drew the eye of the {link:burning-legion}Burning Legion{/link}. In the {link:war-of-the-ancients}War of the Ancients{/link}, the night elves fought for the survival of the world, and the destruction of the Well brought about the {link:great-sundering}Great Sundering{/link}. The one continent was broken into many.
• {b}The Younger Races.{/b} In the ages that followed, the troll empires waned and the {link:dwarves}dwarves{/link} awoke beneath the mountains. The {link:high-elves}high elves{/link} founded {link:quel-thalas}Quel'Thalas{/link}, and the {link:humans}human{/link} tribes united as {link:arathor}Arathor{/link} to fight the {link:troll-wars}Troll Wars{/link}.
• {b}The Age of the {link:horde}Horde{/link}.{/b} When the {link:dark-portal}Dark Portal{/link} opened, the {link:orcs}orcs{/link} of another world poured into Azeroth. The {link:first-war}First War{/link}, the {link:second-war}Second War{/link} and the {link:third-war}Third War{/link} followed, each more terrible than the last.]=],
		},
		{
			title = "A Shared Name",
			text = [=[The name Azeroth once belonged to a human kingdom as well. The {link:arathi-highlands}Arathi{/link} exiles who settled the southern forests called their new realm Azeroth, and its capital was {link:stormwind-city}Stormwind{/link}. In time the realm came to be known by the name of its city, and today it is the {link:kingdom-of-stormwind}Kingdom of Stormwind{/link}. Old soldiers of the {link:first-war}First War{/link} still sometimes speak of "Azeroth" and mean only the kingdom they lost.]=],
		},
		{
			title = "The Present Day",
			text = [=[The {link:third-war}Third War{/link} ended with the fall of {link:archimonde}Archimonde{/link} at the foot of {link:nordrassil}Nordrassil{/link}, but it did not bring peace. The {link:scourge}Scourge{/link} holds the north of {link:lordaeron}Lordaeron{/link}. Servants of the {link:burning-legion}Burning Legion{/link} still haunt the forests of {link:kalimdor}Kalimdor{/link}. The {link:alliance}Alliance{/link} and the {link:horde}Horde{/link}, who stood together on {link:mount-hyjal}Mount Hyjal{/link}, now watch one another with suspicion across the {link:the-barrens}Barrens{/link} and the woods of {link:ashenvale}Ashenvale{/link}. Beneath {link:blackrock-mountain}Blackrock Mountain{/link}, the {link:dark-iron-dwarves}Dark Iron Dwarves{/link} serve a lord of living fire. Azeroth has survived every war yet fought upon it. No chronicler would dare to say that it cannot fall.]=],
		},
	},
})

Add({
	id = "eastern-kingdoms",
	title = "Eastern Kingdoms",
	unlock = {
		{ type = "always" },
	},
	regionKind = "continent",
	kind = "region",
	sections = {
		{
			title = "Summary",
			text = [=[The Eastern Kingdoms stretch from the frozen peaks of {link:alterac-mountains}Alterac{/link} to the jungles of {link:stranglethorn-vale}Stranglethorn{/link}. They are the homeland of {link:humans}humankind{/link}, of the {link:dwarves}dwarves{/link} and {link:gnomes}gnomes{/link}, and of the {link:high-elves}high elves{/link} of {link:quel-thalas}Quel'Thalas{/link}. Here stood the great human kingdoms of old, and here the {link:horde}Horde{/link} made its first war upon {link:azeroth}Azeroth{/link}. The lands bear the scars of every war since. Once-proud realms lie in ruin, and the north has become a land of the dead.]=],
		},
		{
			title = "Origins",
			text = [=[Before the {link:great-sundering}Great Sundering{/link}, these lands were the eastern reaches of a single continent. When the {link:well-of-eternity}Well of Eternity{/link} was destroyed, the seas rushed in and tore them away. What remained was a land already old. The titans had left their works here, among them {link:uldaman}the vault of Uldaman{/link} in the stony {link:badlands}Badlands{/link}. Their earthen servants slept in its halls. Over long ages the earthen changed. Their flesh softened and their lives grew short, and from them came the dwarves of Khaz Modan. Another titan-forged people, it is written, gave rise to the gnomes. The trolls were older still in these lands. The Amani ruled the northern forests, and the Gurubashi held the southern jungles.]=],
		},
		{
			title = "History",
			text = [=[• {b}The Coming of the Elves.{/b} Exiled from {link:kalimdor}Kalimdor{/link}, the Highborne crossed the sea and founded {link:quel-thalas}Quel'Thalas{/link} in the northern forests, upon lands the Amani claimed as their own.
• {b}Arathor.{/b} The human tribes of the north were united by {link:thoradin}Thoradin{/link}, who raised the city of {link:stromgarde-keep}Strom{/link}. Together with the elves, his armies broke the Amani in the {link:troll-wars}Troll Wars{/link}. In return the elves taught humans the ways of {link:arathor}Arathi{/link} magic, and Dalaran was later founded by the mages of that line.
• {b}The Seven Kingdoms.{/b} In time Arathor divided. The kingdoms of {link:lordaeron}Lordaeron{/link}, {link:gilneas}Gilneas{/link}, {link:kul-tiras}Kul Tiras{/link}, {link:alterac-mountains}Alterac{/link}, {link:dalaran}Dalaran{/link} and Stromgarde rose in the north. In the south, {link:arathi-highlands}Arathi{/link} exiles founded the realm that became the {link:kingdom-of-stormwind}Kingdom of Stormwind{/link}.
• {b}The Three Hammers.{/b} Beneath the mountains, the dwarves of {link:kingdom-of-ironforge}Ironforge{/link} split into the Bronzebeard, Wildhammer and Dark Iron clans. Their war ended in fire. The Dark Iron sorcerer-thane {link:ruins-of-thaurissan}Thaurissan{/link} called forth Ragnaros, lord of fire, and the summoning raised {link:blackrock-mountain}Blackrock Mountain{/link} and scorched the lands around it.
• {b}The Wars of the {link:horde}Horde{/link}.{/b} The {link:dark-portal}Dark Portal{/link} opened in the south. {link:stormwind-city}Stormwind{/link} fell in the {link:first-war}First War{/link}. The {link:alliance}Alliance{/link} of Lordaeron threw back the Horde in the {link:second-war}Second War{/link}. Then came the plague of undeath, the {link:culling-of-stratholme}Culling of Stratholme{/link} and the {link:fall-of-lordaeron}Fall of Lordaeron{/link}.]=],
		},
		{
			title = "The Present Day",
			text = [=[{link:stormwind-city}Stormwind{/link} has risen again, though its king is missing and its regent, {link:bolvar-fordragon}Bolvar Fordragon{/link}, holds a realm stretched thin. {link:magni-bronzebeard}Magni Bronzebeard{/link} rules in {link:ironforge}Ironforge{/link}, which also shelters the gnomes, for {link:gnomeregan}Gnomeregan{/link} has been lost to its own ruin. North of the {link:thandol-span}Thandol Span{/link}, the great kingdom of {link:lordaeron}Lordaeron{/link} is no more. The {link:scourge}Scourge{/link} holds the Plaguelands. The zealots of the {link:scarlet-crusade}Scarlet Crusade{/link} fight it with fire and suspicion alike. In the ruins of the old capital, the {link:forsaken}Forsaken{/link} have made a home beneath the earth. In {link:blackrock-mountain}Blackrock Mountain{/link}, Dark Iron and {link:orcs}orc{/link} wage war on each other. And in the south, the {link:dark-portal}Dark Portal{/link} stands silent in the {link:blasted-lands}Blasted Lands{/link}.]=],
		},
	},
})

Add({
	id = "kalimdor",
	title = "Kalimdor",
	unlock = {
		{ type = "always" },
	},
	regionKind = "continent",
	kind = "region",
	sections = {
		{
			title = "Summary",
			text = [=[Kalimdor lies across the sea to the west of the {link:eastern-kingdoms}Eastern Kingdoms{/link}. It is a land of old forests and red canyons, of great plains and burning deserts. It is the homeland of the {link:night-elves}night elves{/link} and the {link:tauren}tauren{/link}, and the ancient heart of the world. The Kalimdor of today is only what survived the {link:great-sundering}Great Sundering{/link}. Before that cataclysm, a single continent held nearly all the lands of {link:azeroth}Azeroth{/link}, and the lake at its center was the {link:well-of-eternity}Well of Eternity{/link}.]=],
		},
		{
			title = "Origins",
			text = [=[The oldest peoples of Kalimdor were the trolls, whose empires spread far across the primordial continent. A tribe of trolls who settled beside the Well was changed by its power over many generations. They became the night elves, who named the land Kalimdor. Beside the Well they built the cities of the Kaldorei Empire under {link:queen-azshara}Queen Azshara{/link}. Their pursuit of {link:arcane-magic}arcane magic{/link} drew the {link:burning-legion}Burning Legion{/link} into the world. In the {link:war-of-the-ancients}War of the Ancients{/link} the Well was destroyed, and the continent was shattered. The seas poured into the wound, and the Maelstrom has churned there ever since. Upon the slopes of {link:mount-hyjal}Mount Hyjal{/link}, the survivors planted {link:nordrassil}Nordrassil{/link}, and for ten thousand years the night elves kept a hidden vigil over their forests.]=],
		},
		{
			title = "History",
			text = [=[• {b}The Long Vigil.{/b} Under {link:malfurion-stormrage}Malfurion Stormrage{/link} and {link:tyrande-whisperwind}Tyrande Whisperwind{/link}, the night elves forswore arcane magic. The druids slept in the {link:emerald-dream}Emerald Dream{/link}, and the {link:sentinels}Sentinels{/link} guarded the forests alone.
• {b}The Peoples of the Wilds.{/b} Across the plains roamed the {link:tauren}tauren{/link}. They were beset for generations by the {link:centaurs}centaur{/link} of the south, the {link:quilboar}quilboar{/link} of the {link:the-barrens}Barrens{/link}, the {link:harpies}harpies{/link} of the cliffs and the {link:furbolgs}furbolgs{/link} of the forests.
• {b}The Third War.{/b} In the {link:third-war}Third War{/link}, a new {link:horde}Horde{/link} under {link:thrall}Thrall{/link} crossed the sea, and so did the humans of {link:jaina-proudmoore}Jaina Proudmoore{/link}. The {link:burning-legion}Burning Legion{/link} followed them. Orc, human and {link:night-elves}night elf{/link}, once strangers and foes, stood together at the {link:battle-of-mount-hyjal}Battle of Mount Hyjal{/link}, and there {link:archimonde}Archimonde{/link} was destroyed.]=],
		},
		{
			title = "The Present Day",
			text = [=[Kalimdor is no longer a hidden land. The night elves have planted a new tree, {link:teldrassil}Teldrassil{/link}, and its city of {link:darnassus}Darnassus{/link} looks out over the northern sea. The orcs have founded {link:durotar}Durotar{/link} and the city of {link:orgrimmar}Orgrimmar{/link}, and the {link:tauren}tauren{/link} of {link:cairne-bloodhoof}Cairne Bloodhoof{/link} have made {link:thunder-bluff}Thunder Bluff{/link} their home in {link:mulgore}Mulgore{/link}. The {link:darkspear-trolls}Darkspear trolls{/link} dwell beside the orcs. {link:jaina-proudmoore}Jaina Proudmoore{/link} holds {link:theramore-isle}Theramore{/link} in {link:dustwallow-marsh}Dustwallow Marsh{/link}. Yet the peace of Hyjal is fraying. Orc loggers cut the trees of {link:ashenvale}Ashenvale{/link}, and the {link:sentinels}Sentinels{/link} answer with arrows. Goblins of the {link:steamwheedle-cartel}Steamwheedle Cartel{/link} and the {link:venture-company}Venture Company{/link} trade and plunder along the coasts. The forests of {link:felwood}Felwood{/link} still bear the taint of the Legion, and older mysteries sleep in the deserts of the south.]=],
		},
	},
})

Add({
	kind = "topic",
	id = "war-of-the-ancients",
	title = "War of the Ancients",
	category = "event",
	unlock = {
		{ type = "read" },
	},
	sections = {
		{
			title = "Summary",
			text = [=[The War of the Ancients was the first invasion of {link:azeroth}Azeroth{/link} by the {link:burning-legion}Burning Legion{/link}. It was fought some ten thousand years before the {link:dark-portal}Dark Portal{/link} opened, and it ended the Kaldorei Empire. Its last hour brought the {link:great-sundering}Great Sundering{/link}, which broke the world.]=],
		},
		{
			title = "Origins",
			text = [=[The Highborne of the {link:night-elves}night elf{/link} court drew ever deeper upon the power of the {link:well-of-eternity}Well of Eternity{/link}. Their magic was felt beyond the world by {link:sargeras}Sargeras{/link}, the fallen titan who leads the {link:burning-legion}Burning Legion{/link}. He whispered to {link:queen-azshara}Queen Azshara{/link}, and she believed him. {link:azshara}Azshara{/link} and her Highborne worked to open a gateway in the Well, so that Sargeras and his demons could enter {link:azeroth}Azeroth{/link}.]=],
		},
		{
			title = "History",
			text = [=[The first demons came through, led by {link:archimonde}Archimonde{/link} and {link:mannoroth}Mannoroth{/link}, and they slaughtered the night elves who stood in their path. A resistance formed against them and against the queen. It was led by {link:malfurion-stormrage}Malfurion Stormrage{/link}, a young student of the demigod {link:cenarius}Cenarius{/link}, together with the priestess {link:tyrande-whisperwind}Tyrande Whisperwind{/link} and Malfurion's twin brother {link:illidan-stormrage}Illidan Stormrage{/link}. The demigods of the wilds and the dragonflights joined the fight. The war was nearly lost when the Earth-Warder of the dragons betrayed his kind. He was the Aspect who would become {link:deathwing}Deathwing{/link}. In the end the defenders reached the Highborne's palace and broke their spells as {link:sargeras}Sargeras{/link} tried to pass through. The gateway collapsed, and the {link:well-of-eternity}Well of Eternity{/link} tore itself apart.]=],
		},
		{
			title = "Significance",
			text = [=[The war taught the night elves that arcane magic had nearly doomed the world. They forswore it, turned to druidism and the worship of Elune, and began their long vigil. It also left {link:illidan-stormrage}Illidan{/link} a traitor in the eyes of his people, for he had worked with the Highborne in secret, and afterwards he made a new Well atop {link:mount-hyjal}Mount Hyjal{/link}.]=],
		},
	},
})

Add({
	kind = "topic",
	id = "great-sundering",
	title = "Great Sundering",
	aliases = { "Sundering" },
	category = "event",
	unlock = {
		{ type = "read" },
	},
	sections = {
		{
			title = "Summary",
			text = [=[The Great Sundering was the cataclysm that ended the {link:war-of-the-ancients}War of the Ancients{/link}. When the {link:well-of-eternity}Well of Eternity{/link} collapsed, the single continent of the ancient world was shattered, and the seas rushed in to fill the wound. The face of {link:azeroth}Azeroth{/link} was changed forever.]=],
		},
		{
			title = "History",
			text = [=[The gateway of the Highborne was undone in the war's final hour. The Well, fed with more power than it could hold, imploded. The explosion tore the heart out of the continent. Most of the Kaldorei Empire, with its shining capital of Zin-Azshari, was swallowed by the sea. {link:queen-azshara}Queen Azshara{/link} and many of her Highborne were dragged beneath the waves. Where the Well had been, the waters began to spin, and the great storm known as the Maelstrom was born. It has never ceased.]=],
		},
		{
			title = "The World After",
			text = [=[Only fragments of the old continent remained above the water. The largest of these became {link:kalimdor}Kalimdor{/link} in the west and the {link:eastern-kingdoms}Eastern Kingdoms{/link} in the east, and the frozen land of Northrend lay to the north. The surviving night elves gathered on the slopes of {link:mount-hyjal}Mount Hyjal{/link}. There they found that {link:illidan-stormrage}Illidan Stormrage{/link} had carried vials of the Well's water and poured them into a mountain lake, making a second Well. To guard it, the Aspects planted {link:nordrassil}Nordrassil{/link} above its waters.]=],
		},
		{
			title = "Significance",
			text = [=[For the night elves, the Sundering was proof of the cost of {link:arcane-magic}arcane magic{/link}. For the world, it meant ten thousand years of separation. The peoples of the east and the west forgot each other until the {link:third-war}Third War{/link} brought them together again. The {link:naga}naga{/link} who haunt the coasts today are said to be the drowned Highborne, changed beyond recognition.]=],
		},
	},
})

Add({
	kind = "topic",
	id = "troll-wars",
	title = "Troll Wars",
	category = "event",
	unlock = {
		{ type = "read" },
	},
	sections = {
		{
			title = "Summary",
			text = [=[The Troll Wars were fought between the Amani trolls and the young kingdoms of humans and {link:high-elves}high elves{/link}, some two thousand eight hundred years before the {link:dark-portal}Dark Portal{/link} opened. From them came the alliance of elves and humans, and the first human mages.]=],
		},
		{
			title = "Origins",
			text = [=[The Highborne exiled from {link:kalimdor}Kalimdor{/link} founded {link:quel-thalas}Quel'Thalas{/link} in the northern forests of the {link:eastern-kingdoms}Eastern Kingdoms{/link}. Those forests had belonged to the Amani, and the trolls never forgave the theft. They made war on the elves for thousands of years. At last they gathered a great host, perhaps joined by their Gurubashi kin, and set out to destroy Quel'Thalas altogether.]=],
		},
		{
			title = "History",
			text = [=[In the same age, {link:thoradin}Thoradin{/link} of the {link:arathi-highlands}Arathi{/link} tribe had united the human tribes of the north into the nation of {link:arathor}Arathor{/link}, with its capital at {link:stromgarde-keep}Strom{/link}. The elves of {link:quel-thalas}Quel'Thalas{/link} sent envoys to him in desperation. Thoradin agreed to aid them if the elves would teach his people magic. The elves chose one hundred humans with a gift for the art and taught them only what was needed. The allied armies met the Amani host in the south of the {link:alterac-mountains}Alterac Mountains{/link}. The human mages and elven magisters called down fire upon the trolls, and the flames burned away the wounds that trolls can otherwise heal. The Amani broke and fled, and their empire never recovered.]=],
		},
		{
			title = "Significance",
			text = [=[In gratitude, the elves of {link:quel-thalas}Quel'Thalas{/link} swore an oath of friendship to the line of {link:thoradin}Thoradin{/link}. That oath would bring them into the {link:second-war}Second War{/link}. The magic taught to humankind spread far beyond the first hundred. It gave rise to {link:dalaran}Dalaran{/link} and to the {link:kirin-tor}Kirin Tor{/link}, and it drew the notice of the {link:burning-legion}Burning Legion{/link} once more.]=],
		},
	},
})

Add({
	kind = "topic",
	id = "first-war",
	title = "First War",
	category = "event",
	unlock = {
		{ type = "read" },
	},
	sections = {
		{
			title = "Summary",
			text = [=[The First War was the invasion of the human kingdom of {link:azeroth}Azeroth{/link} by the orcish {link:horde}Horde{/link}. It began when the {link:dark-portal}Dark Portal{/link} opened in the Black Morass, and it ended with the fall of {link:stormwind-city}Stormwind{/link}. It was the first war of {link:orcs}orc{/link} and human, and the beginning of the age that has shaped the world ever since.]=],
		},
		{
			title = "Origins",
			text = [=[On their world of Draenor, the {link:orcs}orcs{/link} had been corrupted by the demon lord {link:kil-jaeden}Kil'jaeden{/link} through the warlock {link:gul-dan}Gul'dan{/link} and his {link:shadow-council}Shadow Council{/link}. Their homeland was dying. In {link:azeroth}Azeroth{/link}, {link:medivh}Medivh{/link}, the Guardian of {link:tirisfal-glades}Tirisfal{/link}, had long been possessed by the spirit of {link:sargeras}Sargeras{/link}. Working with Gul'dan, Medivh helped open a gateway between the two worlds.]=],
		},
		{
			title = "History",
			text = [=[The first orcs came through in small numbers and raided the Black Morass. Then the portal widened and the {link:horde}Horde{/link} came in strength, under the warchief Blackhand. King {link:llane-wrynn}Llane Wrynn{/link} and his champion {link:anduin-lothar}Anduin Lothar{/link} fought them for years across the southern kingdom. The Horde burned the farms of {link:elwynn-forest}Elwynn{/link}, the forests of {link:duskwood}Duskwood{/link} and {link:northshire-abbey}Northshire Abbey{/link}. Lothar and the young mage {link:khadgar}Khadgar{/link} at last slew the mad Guardian in his tower of {link:karazhan}Karazhan{/link}. It was too late for the kingdom. The half-{link:orcs}orc{/link} {link:garona}Garona{/link} slew King Llane in his own keep, {link:orgrim-doomhammer}Orgrim Doomhammer{/link} took the Horde from Blackhand, and {link:stormwind-city}Stormwind{/link} was sacked.]=],
		},
		{
			title = "Significance",
			text = [=[{link:anduin-lothar}Lothar{/link} led the survivors north across the sea to {link:lordaeron}Lordaeron{/link}, taking with him {link:llane-wrynn}Llane{/link}'s son {link:varian-wrynn}Varian{/link}. Their warnings led King {link:terenas-menethil}Terenas Menethil{/link} to gather the {link:alliance}Alliance{/link} and prepare for the {link:second-war}Second War{/link}.]=],
		},
	},
})

Add({
	kind = "topic",
	id = "second-war",
	title = "Second War",
	category = "event",
	unlock = {
		{ type = "read" },
	},
	sections = {
		{
			title = "Summary",
			text = [=[The Second War was fought between the {link:horde}Horde{/link} under {link:orgrim-doomhammer}Orgrim Doomhammer{/link} and the {link:alliance}Alliance{/link} of {link:lordaeron}Lordaeron{/link}. The Horde marched north to conquer the human kingdoms that survived the {link:first-war}First War{/link}. It was broken at {link:blackrock-mountain}Blackrock{/link} Spire.]=],
		},
		{
			title = "History",
			text = [=[King {link:terenas-menethil}Terenas Menethil{/link} of {link:lordaeron}Lordaeron{/link} gathered the human kingdoms into an {link:alliance}Alliance{/link}, with {link:anduin-lothar}Anduin Lothar{/link} as its commander. The dwarves of {link:kingdom-of-ironforge}Ironforge{/link} and the gnomes joined them. So did the elves of {link:quel-thalas}Quel'Thalas{/link}, bound by the old oath they had sworn to the line of {link:thoradin}Thoradin{/link}, for Lothar was its last heir. The {link:horde}Horde{/link} came in greater strength than before. Doomhammer brought ogres and the Amani trolls of Zul'jin to his side. The {link:dragonmaw-clan}Dragonmaw clan{/link} enslaved the red dragonflight and rode its dragons into battle. {link:gul-dan}Gul'dan{/link} raised death knights from the corpses of fallen human knights. The Horde overran Khaz Modan and burned the borders of Quel'Thalas. Lord Perenolde of {link:alterac-mountains}Alterac{/link} betrayed the Alliance to the orcs. The Horde reached the walls of the Lordaeron capital itself.]=],
		},
		{
			title = "The Turning of the War",
			text = [=[At the height of the war, {link:gul-dan}Gul'dan{/link} abandoned Doomhammer. He sailed away with his followers to seek the Tomb of {link:sargeras}Sargeras{/link}, and the {link:horde}Horde{/link} was forced to turn back to punish him. The {link:alliance}Alliance{/link} seized the moment. It drove the Horde south to {link:blackrock-mountain}Blackrock{/link} Spire. There {link:anduin-lothar}Lothar{/link} fell to Doomhammer's hand. His lieutenant {link:turalyon}Turalyon{/link} took up his banner and crushed the Horde in the {link:burning-steppes}Burning Steppes{/link}.]=],
		},
		{
			title = "Significance",
			text = [=[The surviving orcs were herded into internment camps. The {link:dark-portal}Dark Portal{/link} was destroyed. The {link:alliance}Alliance{/link} had won, but its victory was costly. Its kingdoms soon quarrelled over the price of the camps, and {link:gilneas}Gilneas{/link} and {link:stromgarde-keep}Stromgarde{/link} left the Alliance.]=],
		},
	},
})

Add({
	kind = "topic",
	id = "third-war",
	title = "Third War",
	category = "event",
	unlock = {
		{ type = "read" },
	},
	sections = {
		{
			title = "Summary",
			text = [=[The Third War was the second invasion of {link:azeroth}Azeroth{/link} by the {link:burning-legion}Burning Legion{/link}. It began in {link:lordaeron}Lordaeron{/link} with a plague of undeath and ended in {link:kalimdor}Kalimdor{/link} with the destruction of {link:archimonde}Archimonde{/link}. It cost humankind its greatest kingdom and the night elves their immortality.]=],
		},
		{
			title = "Origins",
			text = [=[After the {link:second-war}Second War{/link}, the demon {link:kil-jaeden}Kil'jaeden{/link} bound the spirit of the {link:orcs}orc{/link} shaman {link:ner-zhul}Ner'zhul{/link} in a frozen prison in Northrend and made him the Lich King. Through the necromancer {link:kel-thuzad}Kel'Thuzad{/link} and his {link:cult-of-the-damned}Cult of the Damned{/link}, the Lich King spread a plague through the villages of {link:lordaeron}Lordaeron{/link}. Its victims rose as the undead {link:scourge}Scourge{/link}. At the same time, the young orc {link:thrall}Thrall{/link} freed his people from the internment camps and forged a new {link:horde}Horde{/link}.]=],
		},
		{
			title = "History",
			text = [=[A mysterious prophet warned the kings of the east to flee west across the sea. King {link:terenas-menethil}Terenas Menethil{/link} would not listen, but {link:thrall}Thrall{/link} and {link:jaina-proudmoore}Jaina Proudmoore{/link} heeded the call. The prophet was {link:medivh}Medivh{/link}, returned from death. In {link:lordaeron}Lordaeron{/link}, Prince {link:arthas-menethil}Arthas Menethil{/link} hunted the plague to its source. After the {link:culling-of-stratholme}Culling of Stratholme{/link} he sailed to Northrend and took up the cursed blade Frostmourne. He returned as a death knight and brought about the {link:fall-of-lordaeron}Fall of Lordaeron{/link}. The {link:scourge}Scourge{/link} raised {link:kel-thuzad}Kel'Thuzad{/link} at the Sunwell of {link:quel-thalas}Quel'Thalas{/link}, and {link:archimonde}Archimonde{/link} entered the world at {link:dalaran}Dalaran{/link} and destroyed it. Then the Legion followed the {link:horde}Horde{/link} and the humans into {link:kalimdor}Kalimdor{/link}. There the night elves rose from their vigil.]=],
		},
		{
			title = "Significance",
			text = [=[{link:orcs}Orcs{/link}, humans and night elves at last made common cause. At the {link:battle-of-mount-hyjal}Battle of Mount Hyjal{/link} they destroyed {link:archimonde}Archimonde{/link}. From the war came the new {link:horde}Horde{/link}'s lands in {link:kalimdor}Kalimdor{/link}, the city of {link:theramore-isle}Theramore{/link} and the {link:forsaken}Forsaken{/link}. Its wounds are still open.]=],
		},
	},
})

Add({
	kind = "topic",
	id = "battle-of-mount-hyjal",
	title = "Battle of Mount Hyjal",
	aliases = { "Battle of Hyjal" },
	category = "event",
	unlock = {
		{ type = "read" },
	},
	sections = {
		{
			title = "Summary",
			text = [=[The Battle of Mount Hyjal was the last battle of the {link:third-war}Third War{/link}. On the slopes of the sacred mountain, orcs, humans and night elves stood together against the {link:burning-legion}Burning Legion{/link}. The demon lord {link:archimonde}Archimonde{/link} was destroyed at the roots of {link:nordrassil}Nordrassil{/link}.]=],
		},
		{
			title = "Origins",
			text = [=[The Legion had come to {link:kalimdor}Kalimdor{/link} for the World Tree. {link:archimonde}Archimonde{/link} meant to drain the power of the second {link:well-of-eternity}Well of Eternity{/link} that lay beneath its roots, and by doing so to consume the world. The {link:scourge}Scourge{/link} marched before him. The night elves of {link:tyrande-whisperwind}Tyrande Whisperwind{/link} and {link:malfurion-stormrage}Malfurion Stormrage{/link} could not stand alone. {link:medivh}Medivh{/link} brought together their leaders, {link:thrall}Thrall{/link} of the {link:horde}Horde{/link} and {link:jaina-proudmoore}Jaina Proudmoore{/link} of the humans. He told them that only together could they survive.]=],
		},
		{
			title = "History",
			text = [=[{link:malfurion-stormrage}Malfurion{/link} devised the plan. The humans made their stand on the lower slopes, then the orcs higher up, and each held as long as they could before falling back. While they fought, Malfurion prepared a trap at the summit. {link:archimonde}Archimonde{/link} broke through each line in turn and at last reached the tree. As he climbed {link:nordrassil}Nordrassil{/link}, Malfurion sounded the Horn of {link:cenarius}Cenarius{/link}. The spirits of the night elves' ancestors, gathered as countless wisps, swarmed upon the demon. Their power, and the power of the World Tree, was released in a single blast. Archimonde was destroyed.]=],
		},
		{
			title = "Significance",
			text = [=[The victory saved the world, but it came at a great price. {link:nordrassil}Nordrassil{/link} gave up its power, and the night elves lost the immortality it had granted them. The tree was scorched but not slain. The battle also forged a brief peace between the {link:alliance}Alliance{/link} and the {link:horde}Horde{/link}.]=],
		},
	},
})

Add({
	kind = "topic",
	id = "culling-of-stratholme",
	title = "Culling of Stratholme",
	category = "event",
	unlock = {
		{ type = "read" },
	},
	sections = {
		{
			title = "Summary",
			text = [=[The Culling of Stratholme was the slaughter of the people of Stratholme by the soldiers of Prince {link:arthas-menethil}Arthas Menethil{/link}. It happened in the {link:third-war}Third War{/link}, when the plague of undeath reached the city. It marked the beginning of the prince's fall.]=],
		},
		{
			title = "Origins",
			text = [=[{link:arthas-menethil}Arthas{/link} had hunted the plague across {link:lordaeron}Lordaeron{/link} with the sorceress {link:jaina-proudmoore}Jaina Proudmoore{/link} and his mentor {link:uther-the-lightbringer}Uther the Lightbringer{/link}. He learned that the {link:cult-of-the-damned}Cult of the Damned{/link} had tainted the grain shipped from the granaries of {link:ruins-of-andorhal}Andorhal{/link}. At Stratholme he found that the tainted grain had already been given out. Everyone who had eaten it would soon die and rise again as one of the {link:scourge}Scourge{/link}.]=],
		},
		{
			title = "History",
			text = [=[{link:arthas-menethil}Arthas{/link} ordered the city purged before its people could turn. {link:uther-the-lightbringer}Uther{/link} refused to take part, and Arthas stripped him of his command for treason. {link:jaina-proudmoore}Jaina{/link} would not watch, and she left him. The prince led the soldiers who stayed loyal into Stratholme and put its people to the sword, house by house. Where they had not yet been reached, citizens were already turning. The dreadlord Mal'Ganis was waiting in the city. He mocked the prince and challenged him to follow to Northrend. Arthas swore to hunt him down.]=],
		},
		{
			title = "Significance",
			text = [=[The Culling broke the bond between {link:arthas-menethil}Arthas{/link} and those who loved him. It sent him north, to Frostmourne and to the {link:fall-of-lordaeron}Fall of Lordaeron{/link}.]=],
		},
		{
			title = "In the Present Day",
			text = [=[Stratholme lies in ruins in the {link:eastern-plaguelands}Eastern Plaguelands{/link}. The {link:scourge}Scourge{/link} holds much of the city. The {link:scarlet-crusade}Scarlet Crusade{/link} clings to the rest, still fighting the dead that {link:arthas-menethil}Arthas{/link}'s sword could not save.]=],
		},
	},
})

Add({
	kind = "topic",
	id = "fall-of-lordaeron",
	title = "Fall of Lordaeron",
	category = "event",
	unlock = {
		{ type = "read" },
	},
	sections = {
		{
			title = "Summary",
			text = [=[The Fall of Lordaeron was the ruin of the greatest human kingdom by the {link:scourge}Scourge{/link}. It came in the {link:third-war}Third War{/link}, when Prince {link:arthas-menethil}Arthas Menethil{/link} returned from Northrend as the servant of the Lich King. Of all the kingdoms that had led the {link:alliance}Alliance{/link}, none fell so far or so fast.]=],
		},
		{
			title = "History",
			text = [=[In Northrend, {link:arthas-menethil}Arthas{/link} took up the runeblade Frostmourne and slew the dreadlord Mal'Ganis. He lost his soul to the blade. He sailed home, and the people of the capital greeted him as a hero. He walked into the throne room and slew his father, King {link:terenas-menethil}Terenas Menethil{/link}. The {link:scourge}Scourge{/link} swept over the kingdom behind him. Arthas killed {link:uther-the-lightbringer}Uther the Lightbringer{/link} and took the ashes of his father's urn, so that the remains of {link:kel-thuzad}Kel'Thuzad{/link} could be carried in it. He marched into {link:quel-thalas}Quel'Thalas{/link}, cut down its defenders under {link:sylvanas-windrunner}Sylvanas Windrunner{/link}, and raised Kel'Thuzad in the waters of the Sunwell. Soon after, the Scourge helped {link:archimonde}Archimonde{/link} enter the world at {link:dalaran}Dalaran{/link}.]=],
		},
		{
			title = "After the Fall",
			text = [=[When {link:archimonde}Archimonde{/link} was destroyed, the dreadlords sought to rule the ruined kingdom themselves. {link:arthas-menethil}Arthas{/link} turned against them before he answered his master's call to the north. {link:sylvanas-windrunner}Sylvanas{/link}, now undead, broke free of the Lich King's will. She and her {link:forsaken}Forsaken{/link} cast down the dreadlords and claimed the ruins of the capital.]=],
		},
		{
			title = "In the Present Day",
			text = [=[{link:lordaeron}Lordaeron{/link} is gone. Its heartland is the Plaguelands, held by the {link:scourge}Scourge{/link}. The {link:scarlet-crusade}Scarlet Crusade{/link} fights the dead in {link:tirisfal-glades}Tirisfal Glades{/link} and beyond. Beneath the broken throne room, the {link:forsaken}Forsaken{/link} have built the {link:undercity}Undercity{/link}.]=],
		},
	},
})

Add({
	kind = "topic",
	id = "dark-portal",
	title = "Dark Portal",
	category = "structure",
	unlock = {
		{ type = "read" },
	},
	sections = {
		{
			title = "Summary",
			text = [=[The Dark Portal is the great gateway between {link:azeroth}Azeroth{/link} and the {link:orcs}orc{/link} homeland of Draenor. It stands in the {link:blasted-lands}Blasted Lands{/link}, which were once the swamps of the Black Morass. Through it came the {link:horde}Horde{/link}, and with it began the {link:first-war}First War{/link}.]=],
		},
		{
			title = "Origins",
			text = [=[The portal was opened by the warlock {link:gul-dan}Gul'dan{/link} and his {link:shadow-council}Shadow Council{/link} from Draenor, with the help of {link:medivh}Medivh{/link} on {link:azeroth}Azeroth{/link}. Medivh was the Guardian of {link:tirisfal-glades}Tirisfal{/link}, but his mind had long been held by {link:sargeras}Sargeras{/link}, lord of the {link:burning-legion}Burning Legion{/link}. At first the rift was narrow, and only a few scouts passed through. Then it was widened, and the whole {link:horde}Horde{/link} crossed into the swamp.]=],
		},
		{
			title = "History",
			text = [=[The {link:horde}Horde{/link} built a great fortress around the portal, and it became their road for reinforcements. When the {link:second-war}Second War{/link} was lost, the {link:alliance}Alliance{/link} destroyed the Dark Portal. Some years later, the shaman {link:ner-zhul}Ner'zhul{/link} opened it again and led a new Horde through to steal artifacts of power. The Alliance sent an expedition across into Draenor to end the threat at its source. Ner'zhul tore open rifts to other worlds, and the portal was destroyed again. The expedition did not return. None in {link:azeroth}Azeroth{/link} know what became of it.]=],
		},
		{
			title = "In the Present Day",
			text = [=[The Dark Portal stands dark and silent at the southern end of the {link:blasted-lands}Blasted Lands{/link}. The mages and soldiers of {link:nethergarde-keep}Nethergarde Keep{/link} watch over it. Demons still roam the barren land around it.]=],
		},
	},
})

Add({
	kind = "topic",
	id = "well-of-eternity",
	title = "Well of Eternity",
	category = "structure",
	unlock = {
		{ type = "read" },
	},
	sections = {
		{
			title = "Summary",
			text = [=[The Well of Eternity was a vast lake of arcane power at the heart of the ancient world. On its shores the Kaldorei Empire rose. Its destruction ended the {link:war-of-the-ancients}War of the Ancients{/link} and caused the {link:great-sundering}Great Sundering{/link}.]=],
		},
		{
			title = "Nature",
			text = [=[The oldest histories say that the Well filled a wound in the earth, left by the titans' war upon the Old Gods. Its waters were black and deep, and they held the raw power of the world itself. The trolls who settled near it were changed over many generations, and they became the {link:night-elves}night elves{/link}. They learned to wield its power, and their mastery of {link:arcane-magic}arcane magic{/link} made their empire the wonder of the world.]=],
		},
		{
			title = "History",
			text = [=[The {link:night-elves}night elf{/link} queen {link:queen-azshara}Azshara{/link} built her palace on the Well's shores, and her Highborne drew upon it ever more deeply. Their magic drew the {link:burning-legion}Burning Legion{/link}. The Highborne tried to open a gateway for {link:sargeras}Sargeras{/link} within the Well itself. When the gateway was undone, the Well collapsed, and the continent was torn apart. Where it had been, the Maelstrom now rages.]=],
		},
		{
			title = "Its Legacy",
			text = [=[Something of the Well survived. {link:illidan-stormrage}Illidan Stormrage{/link} saved vials of its waters and poured them into a lake on {link:mount-hyjal}Mount Hyjal{/link}, making a second Well. There the Aspects planted {link:nordrassil}Nordrassil{/link}. The exiled Highborne carried another vial east. With it they made the Sunwell, the fount of {link:quel-thalas}Quel'Thalas{/link}. In the {link:third-war}Third War{/link}, {link:archimonde}Archimonde{/link} came to {link:kalimdor}Kalimdor{/link} to consume the power of the second Well, and he failed.]=],
		},
	},
})

Add({
	kind = "topic",
	id = "nordrassil",
	title = "Nordrassil",
	category = "structure",
	unlock = {
		{ type = "read" },
	},
	sections = {
		{
			title = "Summary",
			text = [=[Nordrassil is the World Tree, which rises from the summit of {link:mount-hyjal}Mount Hyjal{/link} in {link:kalimdor}Kalimdor{/link}. For ten thousand years it guarded the second {link:well-of-eternity}Well of Eternity{/link} and gave the {link:night-elves}night elves{/link} their immortality. It was the center of the {link:battle-of-mount-hyjal}Battle of Mount Hyjal{/link}.]=],
		},
		{
			title = "Origins",
			text = [=[After the {link:great-sundering}Great Sundering{/link}, the surviving night elves found that {link:illidan-stormrage}Illidan Stormrage{/link} had made a new Well atop {link:mount-hyjal}Mount Hyjal{/link}. The dragon Aspects came to them. {link:alexstrasza}Alexstrasza{/link} placed a sacred seed in the waters of the new Well, and a great tree rose from it, its roots drinking from the Well and sealing it away. Nozdormu blessed the tree so that the night elves would live as long as it stood. Ysera bound it to the {link:emerald-dream}Emerald Dream{/link}, so that the druids might walk the Dream through it.]=],
		},
		{
			title = "History",
			text = [=[Under its boughs the night elves kept their long vigil. The druids of {link:malfurion-stormrage}Malfurion Stormrage{/link} slept in its shadow, their spirits wandering the Dream. In the {link:third-war}Third War{/link}, {link:archimonde}Archimonde{/link} marched on the tree to drain the Well beneath it. As he climbed its trunk, Malfurion called the spirits of the ancestors, and the power of Nordrassil was spent in destroying the demon.]=],
		},
		{
			title = "In the Present Day",
			text = [=[Nordrassil still stands, scarred and weakened. The night elves are no longer immortal. They have planted a new tree, {link:teldrassil}Teldrassil{/link}, off the northern coast, but it was grown without the blessing of the Aspects. Many of the old druids doubt whether it should have been grown at all.]=],
		},
	},
})

Add({
	kind = "topic",
	id = "holy-light",
	title = "Holy Light",
	category = "force",
	unlock = {
		{ type = "read" },
	},
	sections = {
		{
			title = "Summary",
			text = [=[The Holy Light is the power of faith and virtue that answers the devoted. Its priests heal wounds and mend spirits. Its paladins bear it into battle as a shield and a weapon against the undead and the demonic. Most humans of the {link:eastern-kingdoms}Eastern Kingdoms{/link} have been raised in its faith, and many {link:dwarves}dwarves{/link} now share it.]=],
		},
		{
			title = "Nature",
			text = [=[The faithful do not teach that the Light is a god. They teach that it dwells within all who strive for virtue, and that it grows stronger through compassion, courage and sacrifice. It cannot be stolen or bent to cruelty. Those who try to wield it without faith find that it does not answer them.]=],
		},
		{
			title = "History",
			text = [=[The faith of the Light has deep roots among humankind, reaching back to the days of {link:arathor}Arathor{/link}. In the kingdom of {link:stormwind-city}Stormwind{/link} it was kept at {link:northshire-abbey}Northshire Abbey{/link} and in the {link:cathedral-of-light}Cathedral of Light{/link}. After the {link:first-war}First War{/link}, Archbishop {link:alonsus-faol}Alonsus Faol{/link} saw that faith alone had not saved the south. He joined the clerics of the Light with the finest knights of {link:lordaeron}Lordaeron{/link} and founded the Order of the Silver Hand, the first paladins. {link:uther-the-lightbringer}Uther the Lightbringer{/link} was the first of them. The paladins fought with honor through the {link:second-war}Second War{/link}. In the {link:third-war}Third War{/link}, the order was torn apart. Prince {link:arthas-menethil}Arthas Menethil{/link} had been one of them.]=],
		},
		{
			title = "In the Present Day",
			text = [=[The Light is still the heart of {link:stormwind-city}Stormwind{/link}'s faith, and its priests serve in every town. In {link:lordaeron}Lordaeron{/link}, it has become a battle cry. The {link:scarlet-crusade}Scarlet Crusade{/link} burns all it suspects of the plague in the Light's name. The {link:argent-dawn}Argent Dawn{/link} fights the same dead with a steadier hand.]=],
		},
	},
})

Add({
	kind = "topic",
	id = "arcane-magic",
	title = "Arcane Magic",
	category = "force",
	unlock = {
		{ type = "read" },
	},
	sections = {
		{
			title = "Summary",
			text = [=[Arcane magic is the magic of the mind and of the patterns of the world. Its masters bend space and time, summon fire and frost, and see what others cannot. It is the oldest learned magic of {link:azeroth}Azeroth{/link}, and the most dangerous to those who love it too much.]=],
		},
		{
			title = "Nature",
			text = [=[Arcane power can be learned by those with talent and discipline, but it gives nothing for free. Those who wield it grow to crave it. It also calls to the demons of the {link:burning-legion}Burning Legion{/link}, who hunger for worlds rich in magic. Every great age of arcane power in {link:azeroth}Azeroth{/link} has drawn the Legion's eye.]=],
		},
		{
			title = "History",
			text = [=[The night elves first mastered arcane magic at the {link:well-of-eternity}Well of Eternity{/link}, and their Highborne used it to bring about the {link:war-of-the-ancients}War of the Ancients{/link}. After the {link:great-sundering}Great Sundering{/link}, the night elves outlawed it. The Highborne who would not give it up were exiled. They founded {link:quel-thalas}Quel'Thalas{/link} in the east and became the {link:high-elves}high elves{/link}. In the {link:troll-wars}Troll Wars{/link} they taught magic to one hundred humans of {link:arathor}Arathor{/link}. The art spread through human lands. The mages of Arathor raised the city of {link:dalaran}Dalaran{/link}, and its ruling council, the {link:kirin-tor}Kirin Tor{/link}, watched over the use of magic. When demons began to appear in human lands, the elves and the mages founded the secret Council of {link:tirisfal-glades}Tirisfal{/link}. They chose a Guardian to fight the Legion alone. The last Guardians were {link:aegwynn}Aegwynn{/link} and her son {link:medivh}Medivh{/link}.]=],
		},
		{
			title = "In the Present Day",
			text = [=[{link:dalaran}Dalaran{/link} was destroyed by {link:archimonde}Archimonde{/link} in the {link:third-war}Third War{/link}. Now its mages rebuild it behind a shimmering violet barrier in the {link:alterac-mountains}Alterac{/link} foothills. Magi still train in {link:stormwind-city}Stormwind{/link}, {link:ironforge}Ironforge{/link} and {link:theramore-isle}Theramore{/link}. Among the night elves, the old law against arcane magic stands.]=],
		},
	},
})

Add({
	kind = "topic",
	id = "fel-magic",
	title = "Fel Magic",
	category = "force",
	unlock = {
		{ type = "read" },
	},
	sections = {
		{
			title = "Summary",
			text = [=[Fel magic is the magic of the {link:burning-legion}Burning Legion{/link}. It draws its power from destruction and from the theft of life. It burns with a sickly green fire, and it poisons the land and the souls of those who use it. Warlocks still bargain with it, knowing the price.]=],
		},
		{
			title = "Nature",
			text = [=[Fel power is quick and strong, and it asks for little study. It asks instead for something to be consumed: a life, a soul, the health of the land. Those who use it are slowly changed, in body and in heart. Places where it has been used often wither and rot.]=],
		},
		{
			title = "History",
			text = [=[Fel magic first came to {link:azeroth}Azeroth{/link} with the Legion in the {link:war-of-the-ancients}War of the Ancients{/link}. Many Highborne who served the demons were twisted into {link:satyrs}satyrs{/link}. Ten thousand years later, it came again through the {link:orcs}orcs{/link}. On Draenor, the demon lord {link:kil-jaeden}Kil'jaeden{/link} taught its secrets to {link:gul-dan}Gul'dan{/link} and his warlocks. The orc chieftains drank the blood of the demon {link:mannoroth}Mannoroth{/link}, and it filled them with a terrible rage. The land of Draenor died beneath their magic. The orcs carried the curse through the {link:dark-portal}Dark Portal{/link} into the {link:first-war}First War{/link} and the {link:second-war}Second War{/link}. In the {link:third-war}Third War{/link}, {link:grom-hellscream}Grom Hellscream{/link} slew Mannoroth and freed his people from the demon's blood at the cost of his own life. {link:illidan-stormrage}Illidan Stormrage{/link} consumed the {link:skull-of-gul-dan}Skull of Gul'dan{/link} and took on a demon's power.]=],
		},
		{
			title = "In the Present Day",
			text = [=[The forests of {link:felwood}Felwood{/link} still bear the taint of the Legion. The warlocks of the {link:burning-blade}Burning Blade{/link} serve demons in the shadows of {link:orgrimmar}Orgrimmar{/link} and {link:durotar}Durotar{/link}. The satyrs haunt {link:ashenvale}Ashenvale{/link}. Warlocks of the {link:alliance}Alliance{/link} and the {link:horde}Horde{/link} still study the art. They insist that they are its masters.]=],
		},
	},
})

Add({
	kind = "topic",
	id = "emerald-dream",
	title = "Emerald Dream",
	category = "force",
	unlock = {
		{ type = "read" },
	},
	sections = {
		{
			title = "Summary",
			text = [=[The Emerald Dream is a vast spirit realm that mirrors the world. It shows {link:azeroth}Azeroth{/link} as it might have been, wild and untouched by the hands of mortals. Its guardian is Ysera, the Aspect of the green dragonflight. The druids of the {link:night-elves}night elves{/link} walk it in spirit while their bodies sleep.]=],
		},
		{
			title = "Nature",
			text = [=[The chronicles hold that the titans shaped the Dream as a living image of their design for the world. It is the realm of growth and of dreams. The green dragons guard its gates, and the spirits of the wild dwell within it. Time and distance there do not follow the rules of the waking world.]=],
		},
		{
			title = "History",
			text = [=[The demigod {link:cenarius}Cenarius{/link} taught {link:malfurion-stormrage}Malfurion Stormrage{/link} the ways of druidism, and through them Malfurion learned to enter the Dream. After the {link:war-of-the-ancients}War of the Ancients{/link}, Ysera bound {link:nordrassil}Nordrassil{/link} to the Dream. For thousands of years, the druids of the {link:cenarion-circle}Cenarion Circle{/link} slept in hidden barrows, their spirits wandering the Dream while the {link:sentinels}Sentinels{/link} guarded their bodies. They were woken to fight in the {link:third-war}Third War{/link}. After the victory, the druids returned to their work.]=],
		},
		{
			title = "In the Present Day",
			text = [=[{link:malfurion-stormrage}Malfurion{/link} has gone into the Dream once more, and he has not returned. {link:fandral-staghelm}Fandral Staghelm{/link} leads the druids in his absence. Something is wrong within the Dream. Green dragons are seen in the waking world, and some of them are no longer what they were. The druids of {link:moonglade}Moonglade{/link} speak of a darkness spreading through the Dream, which none can yet name.]=],
		},
	},
})

Add({
	kind = "topic",
	id = "elements",
	title = "Elements",
	category = "force",
	unlock = {
		{ type = "read" },
	},
	sections = {
		{
			title = "Summary",
			text = [=[The elements are the living forces of earth, fire, water and air. In their raw forms they are wild and destructive. In balance they sustain the world. The shamans of the {link:orcs}orcs{/link}, the {link:tauren}tauren{/link} and the {link:trolls}trolls{/link} speak with the spirits of the elements and ask for their aid.]=],
		},
		{
			title = "Nature",
			text = [=[Four great elemental lords rule the elements. Ragnaros is lord of fire. Therazane is mother of stone. {link:al-akir}Al'Akir{/link} is lord of the winds, whose realm is {link:skywall}Skywall{/link}. Neptulon is lord of the tides. Their servants are wild and hostile to mortal life. The lesser spirits, however, can be reasoned with. A shaman does not command them. A shaman asks, and the spirits choose whether to answer.]=],
		},
		{
			title = "History",
			text = [=[In the first age of the world, the elemental lords fought for the Old Gods. The titans defeated them and bound them in a realm apart from the world. On Draenor, the orcs were a people of shamans. When {link:gul-dan}Gul'dan{/link} turned them to demon magic, the spirits abandoned them. Far later, in Khaz Modan, the Dark Iron thane {link:ruins-of-thaurissan}Thaurissan{/link} summoned Ragnaros into the world. The summoning killed the thane and raised {link:blackrock-mountain}Blackrock Mountain{/link}. Ragnaros has dwelled beneath it ever since. After the {link:second-war}Second War{/link}, the old shaman {link:drek-thar}Drek'Thar{/link} taught the ways of the spirits to young {link:thrall}Thrall{/link}. The elements answered the new {link:horde}Horde{/link} as they had not answered the old.]=],
		},
		{
			title = "In the Present Day",
			text = [=[Ragnaros rules the Dark Iron dwarves from the molten depths of {link:blackrock-mountain}Blackrock Mountain{/link}. The {link:twilight-s-hammer}Twilight's Hammer{/link} seeks to wake the elements for its own ends. Shamans of the {link:horde}Horde{/link} keep the old balance, as their ancestors did before the demons came.]=],
		},
	},
})
